### ISSUE TITLE
Worldview/GIBS blog post

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#100]

**Comment by Benjaki2** [comment]
👍

**Comment by minniewong** [comment]
Preview of new year blog post: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=78975356

**Comment by mcechini** [comment]
it looks great! lots of hard work putting that together!

My only nit is that I find the numbered list a little distracting when I'm digging through the new list of layers.

**Comment by minniewong** [comment]
@mcechini  - i changed them to regular bullets - better?

**Comment by mcechini** [comment]
yup.  :)

**Comment by minniewong** [comment]
Blog post posted on the wiki! https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=78977335
