### ISSUE TITLE
Add SEDAC "Batch 1" BEDI Layers

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#1006]
We have added the following layers to GIBS, and are now ready for Worldview:

| Layer Identifier | Title | Subtitle | CMR ID |
| ------------- |-------------|-------------|------|
|Agricultural_Lands_Croplands_2000|Croplands|Global Agricultural Lands, v1 (2000)|C1000000060-SEDAC|
|Anthropogenic_Biomes_of_the_World_2001-2006|Anthropogenic Biomes|Anthropogenic Biomes of the World, v1 (2001-2006)|C179002107-SEDAC|
|NDH_Drought_Hazard_Frequency_Distribution_1980-2000|Drought Hazard|Drought Hazard Frequency and Distribution, v1 (1980-2000)|C179001770-SEDAC|
|Estimated_Net_Migration_1970-1980|Estimated Net Migration by Decade: 1970-1980|Global Estimated Net Migration Grids By Decade, v1 (1970-2000)|C1000000660-SEDAC|
|Estimated_Net_Migration_1980-1990|Estimated Net Migration by Decade: 1980-1990|Global Estimated Net Migration Grids By Decade, v1 (1970-2000)|C1000000660-SEDAC
|Estimated_Net_Migration_1990-2000|Estimated Net Migration by Decade: 1990-2000|Global Estimated Net Migration Grids By Decade, v1 (1970-2000)|C1000000660-SEDAC|
|GPW_Population_Density_2015|Population Density, 2015|GPWv4: UN-Adjusted Population Density, v4 (2000, 2005, 2010, 2015, 2020)|C1399944642-SEDAC|

**Comment by minniewong** [comment]
@apdeluca and @mcechini  - Does the existing Drought Hazard layer get removed from Worldview?

**Comment by mcechini** [comment]
Yeah, it looks like your current ndh-drought-hazard-frequency-distribution layer gets replaced by ours.
