### ISSUE TITLE
Add LPRM A2 Daily STD

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#1007]
We have added the following layers to GIBS, and are now ready for Worldview:

| Layer Identifier | Title | Subtitle | CMR ID |
| ------------- |-------------|-------------|------|
|LPRM_AMSR2_Surface_Soil_Moisture_C1_Band_Night_Daily|Surface Soil Moisture C1-band (Daily)|GCOM-W1 AMSR2 LPRM|C1235316217-GES_DISC|
|LPRM_AMSR2_Surface_Soil_Moisture_C1_Band_Day_Daily|Surface Soil Moisture C1-band (Daily)|GCOM-W1 AMSR2 LPRM|C1235316198-GES_DISC|
|LPRM_AMSR2_Downscaled_Surface_Soil_Moisture_C1_Band_Night_Daily|Surface Soil Moisture C1-band (Daily)|GCOM-W1 AMSR2 LPRM|C1235316199-GES_DISC|
|LPRM_AMSR2_Downscaled_Surface_Soil_Moisture_C1_Band_Day_Daily|Surface Soil Moisture C1-band (Daily)|GCOM-W1 AMSR2 LPRM|C1235316218-GES_DISC|

**Comment by minniewong** [comment]
@apdeluca - I will have to add more information to the titles (adding in Day/Night; Downscaled) as they currently all say the same thing 😄
