### ISSUE TITLE
Catalog Of Worldview Examples

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#101]
Thanks for the feedback @mstuenkel

Comment by @ZachTRice:
Here is a list of potential events to be story-boarded. Adding a check beside the event means the event has been completely story-boarded out. This list will need to be narrowed down to a 9 events initially.

Event Types
---
- Default (No Event Type)
- Wildfire
- Volcano
- Snow
- Sea and Lake Ice
- Iceberg
- Water Color
- Dust and Haze
- Severe Storm
- Man Made

Top 9 Latest Events
---
1. **Hurricane Florence - 2018**
Type: Hurricane
Reason for showcasing (optional):
Features to highlight:
2. **California Wildfires & British Columbia Wildfires - 2018**
Type: Wildfire
Reason for showcasing (optional):
Features to highlight:
3. **Snow in South Africa - August 2018**
Type: Snow
Reason for showcasing (optional):
Features to highlight:
4. **Saharan Dust Storms - 2018**
Type: Dust and Haze
Reason for showcasing (optional):
Features to highlight:
5. **Sinabung Volcano - February 2018**
Type: Volcano
Reason for showcasing (optional):
Features to highlight:
6. **Hurricane Maria - September 2017**
Type: Hurricane
Reason for showcasing (optional):
Features to highlight:
7. **Larsen C Ice Shelf / Iceberg A68A - July 2017**
Type: Iceberg
Reason for showcasing (optional):
Features to highlight:

and 2 more events of different event types

Other Potential Events:
---
10. **Shrinking Aral Sea - 2001-2018**
Type: Man Made (?) 
Reason for showcasing:
Features to highlight:
11. **Eyjafjallajökull Volcano Eruption - 2010**
Type: Volcano
Reason for showcasing:
Features to highlight:

**Comment by rboller** [comment]
A few more thoughts after discussing this idea again today.

We should consider providing a set of use cases for new users of the app since many not be familiar with what's possible. This would be distinct from the tour but related to it - so rather than showing how the app works, it would show how the imagery can be used for science and NRT applications.

We may also want to unobtrusively (i.e., not a modal) provide this kind of guidance to first-time users who arrive via permalink.

**Comment by ZachTRice** [comment]
Updating the first post of this ticket with a checklist of events to be storyboarded

**Comment by ZachTRice** [comment]
Action for 9/13/2018 Meeting:
- Create final list of 9 events for initial tour creation
- Discuss what we want to show the end-user in these 9 tours
