### ISSUE TITLE
Running data bug when page is loaded in Arctic projection

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1017]
### Description

If page is loaded in arctic projection and then switched to geographic you will get an error in the console and running-data will no longer work

### Steps to Reproduce

1. Load page in arctic projection
2. Switch to Geographic projection
3. Add a layer with a palette 
4. hover over data

**Expected behavior:**   
Data legend is displayed on palette

**Actual behavior:**   
Running data doesn't work

### Environment

Version: 2.4.0 on production
Browser: Chrome v66 OSX

**Comment by ZachTRice** [comment]
Verify that this has been fixed

**Comment by mike-mcgann** [comment]
I cannot reproduce this bug at this time. Reopen this ticket if it shows up again.
