### ISSUE TITLE
Top Border of animation-dragger is gone

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1024]
### Description

No longer have a black border on the top of the animation dragger
<img width="109" alt="screen shot 2018-05-29 at 5 09 21 pm" src="https://user-images.githubusercontent.com/3605988/40685936-95b673da-6363-11e8-8aa3-1e1be888b754.png">

### Environment

Version: 2.5.0 UAT
Browser: [Chrome 66 OS X]

**Comment by mike-mcgann** [comment]
That was probably me trying to make the top part draggable.
