### ISSUE TITLE
Add keyword support to layer.json files & layer search

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1025]
### Description

Searching "AMSR-2" in the layer picker search returns no results because AMSR2 layers only have references in their layer.json file to "AMSR2". It would be nice if there was a "keywords" field in the layer.json files to filter by additional words not included in the title / description.

**Expected behavior:**   
Searching "AMSR-2" returns AMSR2 layers (without modifying the title, subtitle or description fields.)

**Actual behavior:**   
Searching "AMSR-2" returns nothing because all references in the layer.json and are labeled "AMSR2".

### Environment

Version: 2.0.0 +
Browser: all

**Comment by mike-mcgann** [comment]
Already implemented. See:

- https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/config/wv.json/layers/viirs/VIIRS_SNPP_Fires_375m_Day.json

Words put in "tags" can be searched. For the above, it works with "Suomi NPP", "snpp" and "s-npp"

**Comment by ZachTRice** [comment]
Ah, right. Thanks, that's what I was looking for.
