### ISSUE TITLE
Animation-GIF style adjusts

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#103]
Add worldview stamp & adjust the date font and format

**Comment by Benjaki2** [comment]
A couple options in consideration: 
![stamp-without-nasa-logo](https://cloud.githubusercontent.com/assets/3605988/21509592/816af1a6-cc58-11e6-8cd9-f30803930d2a.gif)
![stamp-with-nasa-logo](https://cloud.githubusercontent.com/assets/3605988/21509606/9926a998-cc58-11e6-9c7f-57118de52028.gif)

**Comment by Benjaki2** [comment]
Leaning towards this:
![iceberg](https://cloud.githubusercontent.com/assets/3605988/21530033/d5fe09d4-cd0b-11e6-8126-3e8dd8c92c9a.gif)

**Comment by minniewong** [comment]
think that looks pretty good

**Comment by rboller** [comment]
I like the last one you posted the best.  Does the NASA meatball + Worldview label get added even if the "Include Date Stamps" checkbox is unchecked?

**Comment by Benjaki2** [comment]
@rboller As of now the stamp is automatically added unless the selected area is very small.

**Comment by rboller** [comment]
Sounds good - not sure I have a preference but just wanted to see what you decided.
