### ISSUE TITLE
Create E2E-specific test build

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1032]
### Description

Right now we are parsing all layers in the GIBS `getCapabilities` and building a config from that and our options repo **every time** we run our end to end tests on `Travis CI` (Whenever we push to a branch with a PR open). This is time consuming.

It would be good to find a way to shorten that build process.

@mike-mcgann suggested creating a custom options repo with fewer layers.

**Comment by edplato** [comment]
Handle in part with #1180.
