### ISSUE TITLE
Remove build warnings from unused layers 

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1038]
### Description

By default, Worldview will emit a warning if it finds a layer in the GIBS GC that is not used. Example:

```
validateOptions.py:  WARN: [Estimated_Net_Migration_1980-1990] Unexpected layer, not in layer order
validateOptions.py:  WARN: [Anthropogenic_Biomes_of_the_World_2001-2006] Unexpected layer, not in layer order
validateOptions.py:  WARN: [UHI_Urban-Rural_Summer_Night_Min_Land_Surface_Temp_Difference_2013] Unexpected layer, not in layer order
validateOptions.py:  WARN: [AIRS_Carbon_Dioxide_IR_Monthly] Unexpected layer, not in layer order
validateOptions.py:  WARN: [OSM_Land_Mask] Unexpected layer, not in layer order
```

Let Worldview know this is okay.

**Comment by minniewong** [comment]
Some of these layers are just about to be added to Worldview (SEDAC and LPRM layers) in the June release - how does this change affect that?

**Comment by mike-mcgann** [comment]
Once added, they can be removed from the exception list. 

Later on it may be best to change how this works. Before it was usually a problem if a layer was in GIBS that wasn't in Worldview. That is no longer the case so the validation should probably eventually be dropped.
