### ISSUE TITLE
Cannot open KMZ files in Google Earth if it contains orbit tracks

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1046]
### Description

KMZ files with orbit tracks do not load in Google Earth

### Steps to Reproduce

1. Load an orbit track e.g. Terra/Day
2. Take a snapshot of an area with terra corrected reflectance and orbit track; and download as a KMZ
3. Load KMZ into Google Earth web or Pro
4. It doesn't load

**Expected behavior:**   
It should load the KMZ into Google Earth and display the corrected reflectance image and orbit track overlaid

**Actual behavior:**   
It does not load anything into Google Earth

### Environment

Version: 2.5.1   
Browser: [all]

**Comment by mike-mcgann** [comment]
Might be related to WVS-38.

**Comment by edplato** [comment]
Fixed.
