### ISSUE TITLE
Add blurb advertising video tutorial to Tour

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1050]
Add some text to advertise the Worldview video tutorial on the first instance of the Tour, such as: 
Watch our tutorial (https://www.nasa.gov/feature/goddard/2018/explore-earth-your-way-with-worldview) to learn how to visualize global satellite imagery for severe storms, volcanic eruptions, wildfires and more in Worldview!

**Comment by edplato** [comment]
Fixed in Tour Overhaul.
