### ISSUE TITLE
Add 2016-2017 DayMet to WV

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#1051]
GIBS has added 2016/2017 to our daymet collection. They will be available in the GIBS GC on or about June 13th. Stay tuned.

**Comment by jejeking** [comment]
Daymet 2016/17 is now available in GIBS OPS.

**Comment by minniewong** [comment]
Worldview was rebuilt yesterday for v2.5.2 (hotfix) and the Daymet is now up-to-date to 2016/2017.
