### ISSUE TITLE
Scrollbar in data download tab can extend further than expected

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1064]
### Description

<img width="461" alt="screen shot 2018-06-13 at 2 34 29 pm" src="https://user-images.githubusercontent.com/10747923/41370979-10992c78-6f17-11e8-92c2-b207603522f2.png">

### Steps to Reproduce

1. Add a bunch of layers and go to data download tab (like: https://go.nasa.gov/2JAd0w5)
2. Scroll down, and the scroll bar on the right will extend over the timeline

**Expected behavior:**   
The scroll bar should stop at the bottom of the data download section

### Environment

Version: 2.6.0-rc.1 and v2.5.1 
Browser: Chrome Version 67.0.3396.87 (Official Build) (64-bit) | Firefox 52.8.0 (64-bit

**Comment by ZachTRice** [comment]
This is happening in v2.5.0 and lower
