### ISSUE TITLE
Colorbar units on Cloud Effective Radius layers are unreadable in water phase

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1065]
### Description

The colorbar units on the Cloud Effective Radius - Water Phase are unreadable. I think the range is supposed to be 4.0um to 30.0 um. It looks like the first number is on top of another number. The intervening units are readable when you hover over the colorbar.

<img width="290" alt="screen shot 2018-06-13 at 3 09 56 pm" src="https://user-images.githubusercontent.com/10747923/41372652-eb128710-6f1b-11e8-9321-670d2cc6593a.png">

### Environment

Version: 2.5.1 (production)
Browser: Chrome Version 67.0.3396.87 (Official Build) (64-bit) | Firefox 52.8.0 (64-bit

**Comment by ZachTRice** [comment]
I have a fix in place. These dual colorbars should each have labels:
![screenshot_15](https://user-images.githubusercontent.com/17348884/41373393-3f28986a-6f1e-11e8-9213-41aa6b76475a.png)
