### ISSUE TITLE
Legend labels sticky after moving off data point [layer.legend.4]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1076]
### Description

Following steps/links in layer.legend.4, if you hover over sea ice or fires the 'fires' or 'sea ice' labels in the legend remain stuck even after hovering off the relevant data point. The labels disappear after moving mouse off the map (i.e., off window, or over other layers).

### Steps to Reproduce

1. Follow layer.legend.4
2. Hover over sea ice data on map and 'sea ice' appears in legend (expected)
3. Hover off sea ice data on map and note stuck 'sea ice' in legend (not expected)

**Expected behavior:**   
'sea ice' legend label disappears when not hovering over sea ice data

**Actual behavior:**   
'sea ice' legend label remains when not hovering over sea ice data

### Environment

Version: 2.5.0
Browser: [Windows checked on IE11, Edge, Chrome ]

**Comment by ZachTRice** [comment]
I noticed this behavior as well when I was making changes in #1066. Could you test this using the `fix-dual-colorbar-units-1065` branch?

**Comment by edplato** [comment]
Nice, you fixed it! Will close.
