### ISSUE TITLE
Better data collection labeling when downloading data

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1077]
In the "Data Collection Information" section of the data download feature, the provided links often have minimal or no labeling, e.g.:

<img width="648" alt="data-download-example" src="https://user-images.githubusercontent.com/7243823/41471740-7a7ca4e6-7082-11e8-8867-9bbfdd428eb4.png">

Since the time we originally wrote that code, there now appears to be additional metadata available in CMR.  For the above example of MODIS Aerosol, see the subtitles under the "Related URLs" section [here](https://cmr.earthdata.nasa.gov/search/concepts/C1426717545-LANCEMODIS.html):

<img width="394" alt="cmr-example" src="https://user-images.githubusercontent.com/7243823/41472356-2b9ab29e-7084-11e8-9e82-47f8ebb4c023.png">

So instead of the raw links being posted in Worldview, they can now be labeled as:
- "NASA LANCE Near Real Time data set descriptions and access links."
- "Access Collection 6.1 data set from the MODAPS LANCE-MODIS page."
- "Direct access to the directory hosting the MYD04_3K 6.1 NRT data set."
- "MODIS Science Team"

**Comment by rboller** [comment]
Looking into a sample JSON response from CMR in more detail:
https://cmr.earthdata.nasa.gov/search/granules.json?shortName=MOD04_L2&temporal=2018-06-15T21%3A00%3A00.000Z%2C2018-06-17T02%3A59%3A59.000Z&pageSize=1000

the required metadata isn't being provided:
<img width="898" alt="cmr-response" src="https://user-images.githubusercontent.com/7243823/41557657-541146f4-730c-11e8-9b84-74371e6a17e5.png">

After looking at this and speaking with someone who has worked on Earthdata Search/CMR, it appears that they are using the ECHO10 (or other non-JSON) format for the additional labels.  We can file a ticket with them to request these to be made available in JSON or update Worldview to request/parse another metadata format.

**Comment by mike-mcgann** [comment]
The code does look for a "title" attribute and uses that if available. So that was there at some point in the past.

**Comment by edplato** [comment]
Will add to project roadmap for Data Download.
