### ISSUE TITLE
Units overlapping colorbar legend

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1079]
### Description

Units overlapping colorbar legend on the following layers: 
- Lightning Flash Rate (OrbView-1/OTD)
- Calibrated Flash Radiance (OTD/Microlab-1) OrbView-1/OTD
- Flash Radiance (Level 2, Standard) TRMM/LIS
-Lightning Flash Rate (Combined) TRMM/LIS, OrbView-1/OTD

![screen shot 2018-06-15 at 1 04 59 pm](https://user-images.githubusercontent.com/10747923/41480711-4d037aec-709d-11e8-82a4-e923fca40c37.png)

![screen shot 2018-06-15 at 1 05 20 pm](https://user-images.githubusercontent.com/10747923/41480703-445dc820-709d-11e8-9a08-f0b59655d46d.png)

![screen shot 2018-06-15 at 1 12 06 pm](https://user-images.githubusercontent.com/10747923/41480853-ce3a44ec-709d-11e8-81f3-7caeb410736f.png)

### Environment

Version: v2.6.0-rc.2 
Browser: Mac Chrome

**Comment by ZachTRice** [comment]
Does not occur in Windows Chrome or Windows FireFox
Occurs in IE11 & Edge
