### ISSUE TITLE
Sometimes hovering over values on layers do not show the corresponding running data value in the colorbar

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1080]
### Description

Sometimes hovering over values on layers do not show the corresponding running data value in the colorbar.
Example, all Lightning related layers loaded, the bottom 6 don't show the corresponding value when you hover over the map. If you remove some of the layers, some of those bottom ones start providing the detail again.

UAT: ?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden),OLS_DMSP_F10_Digital_Derived_Lightning,OLS_DMSP_F12_Digital_Derived_Lightning,OTD_High_Resolution_Full_Climatology_OTD_Scaled_Flashes(hidden),OTD_High_Resolution_Full_Climatology_OTD_Raw_Flashes(hidden),LIS_High_Resolution_Full_Climatology_Combined_Flash_Rate_Climatology(hidden),OTD_High_Resolution_Full_Climatology_OTD_Flash_Rate_Climatology(hidden),OTD_OrbView1_Flash_Radiance(hidden),LIS_TRMM_Flash_Radiance(hidden),LIS_Very_High_Resolution_Lightning_Seasonal_Climatology_LIS_Mean_Flash_Rate(hidden),LIS_Very_High_Resolution_Lightning_Monthly_Climatology_LIS_Mean_Flash_Rate(hidden),LIS_Very_High_Resolution_Lightning_Full_Climatology_LIS_Mean_Flash_Rate(hidden),LIS_Very_High_Resolution_Lightning_Daily_Climatology_LIS_Mean_Flash_Rate(hidden),LIS_High_Resolution_Full_Climatology_LIS_Flash_Rate_Climatology(hidden),LIS_High_Resolution_Full_Climatology_LIS_Scaled_Flashes(hidden),LIS_High_Resolution_Full_Climatology_LIS_Raw_Flashes,Coastlines&t=2000-03-15-T00%3A00%3A00Z&z=3&v=-12.438692702410995,-17.50857370746168,41.983182297589,13.569551292538321&ab=off&as=2018-05-16T03%3A10%3A00Z&ae=2018-06-15T16%3A36%3A30Z&av=3&al=false

### Environment

Version: 2.6.0-rc.2
Browser: Mac Chrome

**Comment by ZachTRice** [comment]
This issue and #1079 are caused by adding `position: relative` to `.sidebar-panel div.wv-palettes-legend`. This was added to fix overlapping in dual colormaps.

**Comment by ZachTRice** [comment]
Verify that this has been fixed

**Comment by minniewong** [comment]
looks fine now
