### ISSUE TITLE
Add SEDAC Batch 2 layers

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#1093]
Those static layers are ready to be added to WV:

 ID | Colormap 
--- | ---------
|SEDAC_AgPastures_LL|Agricultural_Lands_Pastures_2000
|SEDAC_FloodHazard_LL|NDH_Flood_Hazard_Frequency_Distribution_1985-2003|
|SEDAC_LandslideHazard_LL|NDH_Landslide_Hazard_Distribution_2000|
|SEDAC_GRUMP_1995_LL|GRUMP_Urban_Extents_Grid_1995|
|SEDAC_HumanFootprint_LL|Human_Footprint_1995-2004|
|SEDAC_LastWild_LL|Last_of_the_Wild_1995-2004|
|SEDAC_UrbalRuralExtents_LL|LECZ_Urban_Rural_Extents_Below_10m|
|SEDAC_PM25_2001-2010_LL|Particulate_Matter_Below_2.5micrometers_2001-2010|
|SEDAC_PM25_2010-2012_LL|Particulate_Matter_Below_2.5micrometers_2010-2012|
|SEDAC_Mangrove_LL|Mangrove_Forest_Distribution_2000|
|SEDAC_UrbanExpansion_LL|Probabilities_of_Urban_Expansion_2000-2030|
|SEDAC_LST_SD_LL|Summer_Day_Max_Land_Surface_Temp_2013|
|SEDAC_LST_SN_LL|Summer_Night_Min_Land_Surface_Temp_2013|
|SEDAC_NO2_1996-1998_LL|Ground_Level_Nitrogen_Dioxide_3_Year_Running_Mean_1996-1998|
|SEDAC_NO2_2010-2012_LL|Ground_Level_Nitrogen_Dioxide_3_Year_Running_Mean_2010-2012|
|SEDAC_GPWPD_2000_LL|GPW_Population_Density_2000|
|SEDAC_GPWPD_2005_LL|GPW_Population_Density_2005|
|SEDAC_GPWPD_2010_LL|GPW_Population_Density_2010|
|SEDAC_GPWPD_2020_LL|GPW_Population_Density_2020|
|SEDAC_Amphibian_AS_LL|Amphibian_Richness_All_Species_2013|
|SEDAC_Amphibian_VS_LL|Amphibian_Richness_Vulnerable_Species_2013|
|SEDAC_Amphibian_CES_LL|Amphibian_Richness_Critically_Endangered_Species_2013|
|SEDAC_Amphibian_ES_LL|Amphibian_Richness_Endangered_Species_2013|
|SEDAC_Amphibian_AT_LL|Amphibian_Richness_All_Threats_2013|
|SEDAC_Mammal_AS_LL|Mammal_Richness_Grids_All_Species_2013|
|SEDAC_Mammal_VS_LL|Mammal_Richness_Grids_Vulnerable_Species_2013|
|SEDAC_Mammal_CES_LL|Mammal_Richness_Grids_Critically_Endangered_Species_2013|
|SEDAC_Mammal_ES_LL|Mammal_Richness_Grids_Endangered_Species_2013|
|SEDAC_Mammal_AT_LL|Mammal_Richness_Grids_All_Threats_2013|

**Comment by minniewong** [comment]
@jejeking - could you also add the Title, Subtitle and CMR ID (like https://github.com/nasa-gibs/worldview/issues/1006)? Thanks!

**Comment by jejeking** [comment]
Here is the ICD:
https://docs.google.com/spreadsheets/d/1d1DPN3C4Av1vNMYtV4Mei_53aGJryXr6LwaNEV7R014/edit#gid=0

Let me know if that does not work for you.

**Comment by mcechini** [comment]
With the introduction of those GPW layers, SEDAC would like to remove the grump-v1-population-count_2000 layer from Worldview.  Can we do this at the same time?

**Comment by minniewong** [comment]
I think we'll have to wait until the next release as all the changes have been made and we are doing a release tomorrow.
