### ISSUE TITLE
Add colormap to Landsat WELD Tree Cover

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#1094]
GIBS OPS added a colormap to the WELD Tree Cover layer. I suspect this requires a WV rebuild to allow WV to display the colormap.

**Comment by minniewong** [comment]
We will have to move the WELD tree cover layer from baselayers to overlays for it to display the colormap in Worldview.

**Comment by minniewong** [comment]
![screen shot 2018-06-19 at 12 39 41 pm](https://user-images.githubusercontent.com/10747923/41611458-dff1b206-73bd-11e8-9a26-abb393ea5ce1.png)
- There appears to be an issue when trying to change the color palette for the tree cover layer. Not all the pixel are assigned the correct color although when you zoom way in, the colors are correct. In the example above, the colors should go from dark red to yellow, but the imagery shows some dark red pixels and a lot of green at that zoom level. 
- Should there also be a single box in the legend assigned to black, which shows "No Tree Cover"? That seems to be in the colormap file, but doesn't seem to show up in Worldview. 
@mcechini

**Comment by mcechini** [comment]
The WELD Tree Cover product isn't paletted which means that the base layer will conform to the colormap... but overviews may not because the zoom interpolation will introduce new colors.

**Comment by minniewong** [comment]
How do you suggest we deal with this? If I keep it as a base layer it will not show the colormap/legend. Or do we remove the option to change the color palette (if that is possible?)

**Comment by minniewong** [comment]
Requires #1109 to be fixed in order to have the Tree cover layer show the colorbar in the legend but not give users the option to change the palette (as it causes issues with the display of the layer)
