### ISSUE TITLE
Ability to download data products for MODIS Corrected Reflectance layers

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1111]
Data provider has requested that we allow users to download the four data products which are used to generate MODIS Corrected Reflectance layers.  From the [CR documentation](https://cdn.earthdata.nasa.gov/conduit/upload/946/MODIS_True_Color.pdf):

> The following data products are required for creating MODIS true color images:
Level 1B Radiance at 1000, 500, and 250 meter resolution:
(MOD021KM, MOD02HKM, MOD02QKM for Terra),
(MYD021KM, MYD02HKM, MYD02QKM for Aqua).
AND
Level 1A Geolocation at 1000 meter resolution:
(MOD03 for Terra), (MYD03 for Aqua).

One challenge here will be to allow a mapping to many data products from a single imagery layer.  As it currently stands, the app can map several imagery layers to a single data product ([sample link](https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,OMI_Absorbing_Aerosol_Optical_Depth,OMI_Aerosol_Optical_Depth,MODIS_Aqua_Aerosol,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2018-06-25-T00%3A00%3A00Z&z=3&v=-149.44435096153848,-46.54687499999999,18.66310096153846,53.01562499999999&ab=off&as=2018-06-18T00%3A00%3A00Z&ae=2018-06-25T00%3A00%3A00Z&av=3&al=false&download=MYD04_L2)), e.g.:
<img width="296" alt="data-download" src="https://user-images.githubusercontent.com/7243823/41874143-0048b9c4-7895-11e8-8ac0-2fba50c2d0b6.png">

**Comment by mike-mcgann** [comment]
Does this apply to the Surface Reflectance layers too?

**Comment by minniewong** [comment]
no - there are standard Land Surface Reflectance products. Corrected reflectance is not a standard product.

**Comment by minniewong** [comment]
Check with @rboller if we should do the same for the Suomi-NPP/VIIRS Corrected Reflectance layers
