### ISSUE TITLE
GIBS Metadata Needs Gathering

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#1120]
Were GIBS to provide metadata to Worldview for its layers, what does Worldview need?  This would cover titles, subtitles, abstracts, platforms, instruments, source/target dataset information, granule filters, temporal/spatial resolution, etc...

**Comment by ZachTRice** [comment]
For future dates, it would be nice to have a parameter that signifies the layer is a "future" layer and a parameter to say how many days into the future the layer is available. i.e. 10 days a head of the current date.

Other parameters which would be nice to have would be what we are already putting in manually to our layer config files, see: https://github.com/nasa-gibs/worldview/blob/master/doc/configuration.md#required-properties

**Comment by minniewong** [comment]
Some imagery are "daily" layers but are not updated daily, but rather have a latency of a few days or weeks (or months) - it would be good to have an indicator/tag to specify this latency.
