### ISSUE TITLE
OSCAR/TPJ/AVISO/GRACE/SMAP/GHRSST Layers

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1123]
Add the following layers to Worldview:

- [ ] OSCAR_SSCZ_LL_STD
- [ ] OSCAR_SSCM_LL_STD
- [ ] TPJ_GDRC_SSHA_LL_STD
- [ ] TPJ_GAFECC_SSHA_LL_STD
- [ ] TPJ_GAFECC_SSCZ_LL_STD
- [ ] TPJ_GAFECC_SSCM_LL_STD
- [ ] TPJ_RECON_SSHA_LL_STD
- [ ] AVISO_ADT_LL_STD
- [ ] GRACE_LWET_MC_LL_STD
- [ ] GRACE_LWET_M_LL_STD
- [ ] GRACE_LWET_LG_LL_STD
- [ ] GRACE_LWET_LJ_LL_STD
- [ ] GRACE_LWET_LC_LL_STD
- [ ] GRACE_LWET_OG_LL_STD
- [ ] GRACE_LWET_OJ_LL_STD
- [ ] GRACE_LWET_OC_LL_STD
- [ ] GRACE_LWET_OEG_LL_STD
- [ ] GRACE_LWET_OEJ_LL_STD
- [ ] GRACE_LWET_OEC_LL_STD
- [ ] SMAP_L3SSSRSS_M_LL_STD
- [ ] SMAP_L3SSSRSS_8R_LL_STD
- [ ] SMAP_L3SSSCAP_M_LL_v4_STD
- [ ] SMAP_L3SSSCAP_8R_LL_v4_STD
- [ ] GHRSST_L4AVHRROI_LL_STD

**Comment by minniewong** [comment]
@jejeking or @apdeluca - Could i get some more info on these layers? Link to ICD etc?

**Comment by jejeking** [comment]
Here is the ICD:

https://docs.google.com/spreadsheets/d/1LJeF_9uTxvO_CdLUU9LqKuALeTEPmF0hQrrutdh9dSg/edit#gid=562601153

**Comment by mike-mcgann** [comment]
I'm going to help out by putting the minimum configuration in needed to display in Worldview. Working from the top down.

**Comment by minniewong** [comment]
sure! - I think i did the first two in the branch

**Comment by mike-mcgann** [comment]
I added as much as I could. Let me know if there is more I can help with.
