### ISSUE TITLE
Improve cache policy on static assets

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1127]
**Part of Google Chrome Audit Recommendation.** #1126 

Uses inefficient cache policy on static assets: 31 assets found
A long cache lifetime can speed up repeat visits to your page.

![image](https://user-images.githubusercontent.com/24417194/42243249-b4c30446-7ede-11e8-9190-5e38e6efef99.png)
![image](https://user-images.githubusercontent.com/24417194/42243266-c5ea35aa-7ede-11e8-9791-9939777dc9b9.png)

**Comment by minniewong** [comment]
closing for now
