### ISSUE TITLE
Preload key requests

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1128]
**Part of Google Chrome Audit Recommendation.** #1126 
Preload key requests:
Consider using ```<link rel=preload>``` to prioritize fetching late-discovered resources sooner:

**URL - Potential Savings**
…fonts/fontawesome-webfont.woff2?v=4.7.0 - **470 ms**
…Italic/OpenSans-Italic.woff - **430 ms**
…Bold/OpenSans-Bold.woff - **430 ms**
…Regular/RobotoMono-Regular.woff2 - **150 ms**

**Comment by TuLondonIT** [comment]
Hi, How To Fix Preload key requests fontawesome-webfont.woff2?v=4.7.0 I have this website https://www.niwtech.com and I can’t fix the Preload key requests fontawesome-webfont.woff2?v=4.7.0 is there is any ideas Please Thank You
