### ISSUE TITLE
Notification spacing is off

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1149]
**Describe the bug**
Alert text has too much spacing

**Expected behavior**
Both alert and outage should have same padding

**Screenshots**
<img width="645" alt="screen shot 2018-07-17 at 3 34 58 pm" src="https://user-images.githubusercontent.com/3605988/42841144-21a76518-89d7-11e8-9667-b8d64369971c.png">

**Desktop (please complete the following information):**
 - OSX
 - Chrome

**Additional context**
This is a problem related to adding bootstrap. There is a conflicting `alert` class

**Comment by ZachTRice** [comment]
I'll fix this along with #904
