### ISSUE TITLE
Add OMI SSA STD

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#1159]
GIBS now offer OMI SSA STD. It's a GESDISC product. 

ICD:
https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=81795237

Let me know if you need more information.
Thanks.

**Comment by minniewong** [comment]
@jejeking - Am I adding this layer: OMI_SSA_LL_NRT or something else? this one is not STD but i don't see another SSA in the ICD.

**Comment by minniewong** [comment]
Worldview is already picking up the imagery/ new start date, 1 October 2004.
