### ISSUE TITLE
Month in timeline obscured by line

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1169]
1. Open app
2. Grab the timeline and move it to the right
3. the Month labels now appear right under the month line and the year disappears (this happens in production too) - Fix by moving month label to the right of the line and add year.
![Screen Shot 2018-07-31 at 11.33.08 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5838ab2138f438130034ed03/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246457f26b7191a379ee0c2852415f46bc30254d58eeb9cb74fce36f34985619e8d96e5725943e42a9bfd41fbb57b8238b4f85e7bedb1f91fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e24d50a5173263ef763e6e0a.png)

**Comment by Benjaki2** [comment]
Looks like this bug is on Production too.

**Comment by edplato** [comment]
Addressing in Timeline Overhaul.
