### ISSUE TITLE
Add GHRC AMSRU2 Sea Ice Concentration/Brightness Temperature

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#1178]
| Layer Identifier | Title | Subtitle | CMR ID | Projections |
| ------------- |-------------|-------------|------|------|
|AMSRU2_Sea_Ice_Concentration_12km | Sea Ice Concentration (12 km) | GCOM-W1 / AMSR2 | C1000000560-NSIDC_ECS | 4326,3031,3413 |
|AMSRU2_Sea_Ice_Concentration_25km | Sea   Ice Concentration (25 km) | GCOM-W1   / AMSR2 | C1000000580-NSIDC_ECS | 4326,3031,3413 |
|AMSRU2_Sea_Ice_Brightness_Temp_89H | Brightness Temperature for Sea Ice (89H Ghz) | GCOM-W1 / AMSR2 | C1000000561-NSIDC_ECS | 4326,3031,3413 |
|AMSRU2_Sea_Ice_Brightness_Temp_89V | Brightness   Temperature for Sea Ice (89V Ghz) | GCOM-W1   / AMSR2 | C1000000561-NSIDC_ECS | 4326,3031,3413 |

**Comment by minniewong** [comment]
Needs this to be fixed before it can go into Worldview: GIBS-3126
