### ISSUE TITLE
Starting tour causes page jump

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1184]
**Describe the bug**
Clicking 'Start Tour' causes the page to jump and DOM elements to shift up. If you get to the last step of the tour, the page actually shifts back down making the site look normal. If you exit the tour prior to that, the page is stuck in a shifted state for the remainder of your session.

**To Reproduce**
1. Go to page
2. Click on 'Start Tour'
3. Notice timeline is shifted up, along with the sidebar and top right toolbar buttons.

**Expected behavior**
No page jump on tour.

**Screenshots**
shifted up (no room at top of page now)
![image](https://user-images.githubusercontent.com/24417194/44095595-3a7a98f4-9fa7-11e8-82d3-559faf2f927c.png)

normal
![image](https://user-images.githubusercontent.com/24417194/44095641-57d955ac-9fa7-11e8-9527-126e2fca2a25.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, IE11 tested
 - Version 2.7.1

**Comment by mike-mcgann** [comment]
This has happened before. I cannot remember the reason though.

**Comment by mike-mcgann** [comment]
See also WV-1206
