### ISSUE TITLE
Now parameter not being used in time range check [perm.in.date.3]

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1188]
**Describe the bug**

In this test case, 16 Mar is shown instead of 15 Mar. 

**To Reproduce**

Use these parameters:

?now=2013-03-15T12&t=2020-01-01

and today is selected.

**Expected behavior**

15 March is selected.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [IE11]
 - Version [11]

**Also**
- date.pick.20
- date.mob.nav.5

**Comment by minniewong** [comment]
Same issue in Chrome OSX

**Comment by minniewong** [comment]
[date.mob.range.1-5] This seems to be related to the now parameter
