### ISSUE TITLE
Tokens not substituted in tour components [tour.walk.5]

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1190]
**Describe the bug**

Text in the tour says NAME instead of Worldview

**To Reproduce**

- Start tour.
- Go to step "Toolbar"
- NAME is found in the text

**Expected behavior**
"Worldview" should be in place of NAME

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [IE11]
 - Version [11]

**Comment by minniewong** [comment]
Same issue in Chrome OSX. It also appears on the last "Finished!" screen.
