### ISSUE TITLE
Box zoom selects all text in layer list [map.zoom.7]

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1192]
**Describe the bug**
When using shift drag to draw a zoom box, all text in the layer list gets selected

**To Reproduce**

- Hold down the shift key, left click and drag a box around Australia, and release.
- Look at the layer list. All text should be selected.

**Expected behavior**
Text in the layer list should not be selected

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [IE11]
 - Version [11]

**Comment by minniewong** [comment]
I don't see this issue in Chrome OSX

**Comment by ZachTRice** [comment]
I am able to reproduce this on IE11. I also occasionally have the browser crash when zooming using shift-drag in IE11. All other non-IE browsers seem to work fine.
