### ISSUE TITLE
Measure Tool

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1193]
Add a tool for measuring distances between two points.

**Comment by jasontk19** [comment]
Based on our conversation during sprint planning the plan will be to: 

* Implementation similar to [State of the Ocean](https://podaac-tools.jpl.nasa.gov/soto/)
* Add “measure” button above scale with the following options
	* “Measure distance” - initiates point-to-point measure tool
	* “Measure area” - initiates area measurement tool
	* “Clear Measurements” - removes all existing measurements that have been made
* In tooltip that follows mouse show:
	* Instructions on how to close the line
	* running total of distance/area (in both miles and km?)
* After completed line show
	* area or distance total in both miles/km in tooltip
