### ISSUE TITLE
Add perceptually uniform colormaps for visualization

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1195]
"Use perceptually uniform colormaps for visualization"

Need to decide on what these colormaps are. https://matplotlib.org/users/colormaps.html

**Comment by minniewong** [comment]
https://earthobservatory.nasa.gov/blogs/elegantfigures/2013/08/05/subtleties-of-color-part-1-of-6/

**Comment by rboller** [comment]
http://sciviscolor.org/home/colormaps/

**Comment by minniewong** [comment]
@rboller - add a prioritized list of colormaps
