### ISSUE TITLE
Firefox Zoom +/- button stays white after clicking until next click 

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1199]
**Describe the bug**
Zoom +/- button stays white after clicking until next click 

![image](https://user-images.githubusercontent.com/24417194/44280067-a4f5e900-a221-11e8-9810-a8920eda02c3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 2.8.0 SIT

**Comment by edplato** [comment]
This behavior is also happening for the polar rotate buttons and rotate reset button.

**Comment by mike-mcgann** [comment]
Appears to be a JQuery-UI thing
