### ISSUE TITLE
Temporal coverage for active layers no longer states that it goes up to "present" 

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1204]
**Describe the bug**
The temporal coverage stated in the layer description for layers that are active should say that they are going up to "present" e.g. Temporal coverage: 15 December 2017 - Present *View Dates

In SIT, the same layer now says "Temporal coverage: 26 January 2012 - 17 August 2018 *View Dates" (which is today). 

**To Reproduce**
1. Go to Worldview SIT
2. Go "Add Layers", type in OMPS, add the SO2 Planetary Boundary Layer, Add it to the layer list
3. Click on the "i" button in the layer, the layer description says "Temporal coverage: 26 January 2012 - 17 August 2018 *View Dates"

**Expected behavior**
The layer description should say "Temporal coverage: 15 December 2017 - Present *View Dates"

**Screenshots**
![screen shot 2018-08-17 at 2 19 02 pm](https://user-images.githubusercontent.com/10747923/44282274-89daa780-a228-11e8-8bdc-415bd848328f.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version: 68.0.3440.106 (Official Build) (64-bit)

**Comment by ZachTRice** [comment]
I'll take a look at this one

**Comment by ZachTRice** [comment]
After re-releasing SIT, this appears to be a non-issue. We can re-open this ticket if we find any other dates appear incorrect.
