### ISSUE TITLE
Make overpass times easier to find

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1207]
A lot of users ask what time the satellite acquired the image. This information can be found in the orbit track layers but it isn't obvious.

**Comment by minniewong** [comment]
We can add some text to the layer title or subtitle e.g. "Overpass time"

**Comment by minniewong** [comment]
"Terra Orbital Track/Overpass Time (Ascending/Night)"; "Terra Orbital Track Time (Ascending/Night)"
