### ISSUE TITLE
Add all new GIBS layers to Worldview

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#121]
Add new GIBS layers listed here: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=78977335

**Comment by minniewong** [comment]
Add layers listed here: https://wiki.earthdata.nasa.gov/pages/viewrecentblogposts.action?key=GIBS

**Comment by minniewong** [comment]
Waiting on feedback from Matt on Sea Ice Concentration layers and MISR Cloud Stereo Height image download doesn't work.

**Comment by minniewong** [comment]
Contacted NSIDC regarding Sea Ice Concentration layer; OnEarth is fixing issue with MISR Cloud Stereo Height

**Comment by minniewong** [comment]
MISR Cloud Stereo Height should be fixed in the OE 1.1.3 release; need to designate Sea Ice Concentration as having dual products; Also need to add RSS layers: RSS_Total_Precipitable_Water_Climatology_Monthly, RSS_Merged_Wind_Climatology_Monthly

**Comment by mcechini** [comment]
1.1.3 is in production (though with maintenance today, we'll be in B13 which doesn't have 1.1.3 yet).
