### ISSUE TITLE
Animated GIF is not displaying the last 3 days of imagery [id.gif.4]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1210]
**Describe the bug**
on SIT, previewing/downloading an animated GIF for the last 7 days (13-20 Aug) only shows Terra CR imagery from 13-17, when there clearly is imagery for 18 - 20. The imagery is downloadable via image download, but does not show in the animated GIF. 

**To Reproduce**
1. Click on the Animation icon
2. Click on the create animated GIF 
3. Using the default dates (13-20 Aug) and default bounding box, click on Create GIF
4. Watching the preview, the imagery animates 13 - 17 Aug, but is blank for 18 - 20. The coastlines are still apparent.

**Expected behavior**
The Terra CR imagery should show for 18, 19 and 20 Aug.

**Screenshots**
![nasa-worldview-2018-08-13t00_00_00z-to-2018-08-20t00_00_00z 2](https://user-images.githubusercontent.com/10747923/44360645-70846600-a489-11e8-9767-c7da7840eab5.gif)

**Desktop (please complete the following information):**
 - OS: OSX Mac
 - Browser Chrome
 - Version: Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by mike-mcgann** [comment]
I'm still seeing this issue with:

p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2018-08-20-T00:00:00Z&z=3&v=-75.28274341045889,-44.24619440178962,84.06073366377692,55.31630559821038&ab=on&as=2018-08-10T00:00:00Z&ae=2018-08-25T00:00:00Z&av=3&al=true
