### ISSUE TITLE
Layer-search mobile bug when text is cleared with backspace

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1213]
**Describe the bug**
When you clear text from the search bar the layer-picker widget shows display/css bug

**To Reproduce**
1. Click Add Layers
2. Add `aod` to search bar
3. Delete text

**Expected behavior**
Modal should revert back to category selection

**Screenshots**
![image from ios](https://user-images.githubusercontent.com/3605988/44364650-8f88f500-a495-11e8-8eb5-b983be742f7c.jpg)

**Smartphone :**
 - Device: iphone6s
 - OS: iOS11.3
 - Browser: Chrome & Safari
 - Version 2.8.0

**Comment by mike-mcgann** [comment]
This can be reproduced on a desktop when resizing the browser to mobile size.
