### ISSUE TITLE
Check to see if Using Free Download Manager for Windows works with https [dd.wget.5]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1214]
**Is your feature request related to a problem? Please describe.**
When you have selected a few datasets to download in Worldview, you are given the following instructions "Using Free Download Manager for Windows". Check to see if these instructions are still correct since most datasets are now accessed via HTTPS and not FTP. 

**Describe the solution you'd like**
Update instructions if needed.

**Comment by mike-mcgann** [comment]
Instructions do need an update. It looks like the application has changed enough that the directions don't even make sense any more.

**Comment by edplato** [comment]
Can confirm 'Free Download Manager for Windows' works with HTTPS. I can make PR for updated instructions.
