### ISSUE TITLE
Events may not be visible notification does not appear [events.notify.3]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1215]
**Describe the bug**
The "Events may not be visible at all times" notification does not appear when clicking on an event.

**To Reproduce**
1. Go to the main page
2. Click on Events
3. Expect to see a notification in the top right should be visible that says "Events may not be visible at all times"

**Expected behavior**
Expect to see a notification in the top right should be visible that says "Events may not be visible at all times"

**Desktop (please complete the following information):**
 - OS: OSX Mac
 - Browser Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by mike-mcgann** [comment]
I was able to get it to work after clearing browser history. I updated the test plan to put that in the first step. Let me know if you still have issues.
