### ISSUE TITLE
Provide higher resolution options for animation GIFs

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#123]
- [x] Initial implementation started by Ben
- [x] Style Image Download button
- [x] Rescale / relocate text when image dimensions change
- [x] Style checkbox
- [x] Replace html tables used for image download in worldview components
- [x] Fix timestamp - It is not reliable with current implementation
- [x] Disable red icon when it should be disabled
- [x] Correctly style Deactivated button
- [x] Style red box around request size when too big
- [x] Add propTypes to worldview-components
- [x] Disable stamp and date when gif is too small
- [x] Add new stamp SVG to Options repo

**Comment by minniewong** [comment]
Consolidate the image download and animation widgets into reusable components

**Comment by localjo** [comment]
While you're working on this, I noticed that the revert rotation dialog for downloading GIFs pops up sometimes on the polar projection when the map isn't rotated. If you rotate the map, try to download, revert, then try to download again, you see the revert dialog a second time even though the rotation is already reset. It might be easy to update this if you're touching that code.

**Comment by ZachTRice** [comment]
On going work on this issue can be found in the following branches:
https://github.com/nasa-gibs/worldview/tree/gif-resolutions
https://github.com/nasa-gibs/worldview-components/tree/res-selection
