### ISSUE TITLE
Timeline last date doesn't correspond to date-selector's last date [date.init.20]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1231]
**Describe the bug**
When using the `now` flag the last date selectable in the date selector does not correspond to the last date selectable in the timeline

**Reproduce**
https://worldview.earthdata.nasa.gov/?now=2013-03-15T0

**Expected behavior**
Should be able to select 3/15 in date selector and in timeline but can only select date 3/15 in date selector.

**Screenshots**
<img width="1229" alt="screen shot 2018-08-30 at 12 59 00 pm" src="https://user-images.githubusercontent.com/3605988/44867063-de344d00-ac54-11e8-8114-ee088d26933d.png">

**Desktop (please complete the following information):**
 - OSX
 - Browser [Firefox]
 - Version 61

**Additional context**
Probably related to 3:00 UTC logic

**Comment by edplato** [comment]
Fixed
