### ISSUE TITLE
Deprecate worldview-components repository

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1238]
Worldview v2.9.0 will contain the components from worldview-components. We should update the worldview-componetns about page and npm to reflect this.
- [x] Update worldview-components readme to state the package is deprecated and part of the main repo
- [x] Lock down ability to add new issues to GitHub repo
- [x] Add a deprecated flag to the npmjs.org package and point them to the main worldview repo

~~We could start publishing worldview proper to npm starting with v2.9.0, thoughts?~~ @Benjaki2, @mike-mcgann

**Comment by mike-mcgann** [comment]
I don't think there is need to publish to npm. As an application that needs to be built with a lot of configuration, it doesn't have utility right out of the box.

**Comment by Benjaki2** [comment]
Yep, I agree with @mike-mcgann  ⬆️

**Comment by ZachTRice** [comment]
👍 Alright, that sounds fine to me as well. Thanks

**Comment by ZachTRice** [comment]
This has been completed.
