### ISSUE TITLE
Data download links are not removed when trying to remove from dialog

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1257]
**Describe the bug**
When swathes are added in data download and the Download Selected Data dialog is open, clicking 'X' to remove a selected data removes the selected swath from the map, but not from the dialog list [dd.link.1].

**To Reproduce**
1. Go to [dd.link.1]
2. Click on three random swaths
3. Click 'Download Selected Data'
4. Click 'X' under 'Selected Data' to try and remove the selected data

**Expected behavior**
Selected data should be removed from dialog on clicking its respective 'X'.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge, Chrome
 - Version 2.9.0

**Comment by edplato** [comment]
It looks like another aspect of this issue is that after removal of the data download links (fixed in #1260 ), the dialog doesn't change to 'Selection Empty' like in production, but keeps the data layer information. Also, I am unable to add/remove swaths on the map itself while the dialog is open.

**Comment by Benjaki2** [comment]
I think that clue did it.
