### ISSUE TITLE
Unable to open GIFs in Photoshop

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1263]
**Describe the bug**
When trying to open a GIF created in Worldview in Photoshop, the following error occurs: "Could not complete your request because the file-format module cannot parse the file."

**To Reproduce**
1. Create an animated GIF in worldview
2. Attempt to open the file using Photoshop

**Expected behavior**
Photoshop can open the file and edit each animation step.

**Comment by edplato** [comment]
I am able to open a GIF in GIMP on Windows. This issue may be related to the inability to upload Worldview GIFs to Twitter. Investigating the metadata (using [https://www.get-metadata.com](https://www.get-metadata.com)) for a Worldview GIF against a known working GIF able to upload to Twitter, there are a few notable differences unique to the Worldview GIF:
1) bits per pixel
2) color resolution depth
3) color map

**Confirmed Uploadable/Working GIF:**
![image](https://user-images.githubusercontent.com/24417194/47230910-77e8c280-d399-11e8-801b-e8c30162eb1a.png)

**Worldview GIF:**
![image](https://user-images.githubusercontent.com/24417194/47230868-5f78a800-d399-11e8-850a-9279dbba6dfe.png)

Following this comparison, when the above Worldview GIF is ran through an optimizer ([https://ezgif.com/](https://ezgif.com/)), the **bits per pixel** and **color resolution depth** are set to **8**, the GIF has a **color map**, and the GIF can then be uploaded to Twitter. Also, the GIF is rendered with a different **background color**, which I don't think is too related.

**Optimized Worldview GIF**
![image](https://user-images.githubusercontent.com/24417194/47231261-6c49cb80-d39a-11e8-8655-0d87696c1dc4.png)

**Comment by edplato** [comment]
Using this excellent GIF data spec overview found here [http://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp](http://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp), I was able to get 8 bits per pixel and color resolution depth, but this didn't fix my issue uploading to Twitter. At this point, it appears that not having a Color Map in our GIFs may be the problem.
