### ISSUE TITLE
Image download selection box coordinates slightly offset

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1265]
![Screen Shot 2018-09-06 at 4.26.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5838ab2138f438130034ed03/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f56b7191a37cf1102d4f5a585ecc3c4a4356bcbbd671f3e57862804e0ee5d2650e26c56e14abee821be903b9208b4fd4b4edd91dd2f42f67b6d5db1063474f4dcbed5727a19041c95df54de34b50a214306be5712431.png)
The image download coordinates are overlapping the selection box at the bottom, and too far away at the top

**Comment by Benjaki2** [comment]
Seeing this bug in `Firefox`, and not in `chrome` (OSX)

**Comment by minniewong** [comment]
In UAT, the offset is now the other way.
![Screen Shot 2018-09-18 at 12.39.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5838ab2138f438130034ed03/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455fb6b7191a379ed0c2858415e46bc21254d58eeb9cb74fce36f34985619e8d96e5725943e42a9bfd41fbb57b8238b4f85e7bedb1f91fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e64f5dac143e66e7713e6e0a.png)
