### ISSUE TITLE
Sidebar tabs Layers, Events, Data hover styling different

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1278]
**Describe the bug**
The sidebar tabs hover styling is different from previous versions. The tabs previously changed background color and icon/font color on hover:
![image](https://user-images.githubusercontent.com/24417194/45302768-30d9f880-b4e2-11e8-9473-ac08dfa0a120.png)

The tabs now have a white outline on hover:
![image](https://user-images.githubusercontent.com/24417194/45302829-549d3e80-b4e2-11e8-94d7-d742183aaafa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 2.9.0

**Comment by Benjaki2** [comment]
@edplato @ZachTRice @mike-mcgann These are differences in default styling between jQuery-ui tabs and bootstrap tabs. I updated the sidebar tabs using `reactstrap` to move in the bootstrap-4 direction but we can obviously revert the styles easily. What do you guys prefer?

**Comment by mike-mcgann** [comment]
I think both look fine.

**Comment by ZachTRice** [comment]
I sightly prefer the previous style but I don't think it is a big deal/difference one way or the other.

**Comment by edplato** [comment]
I like them both. The new white border style has a slightly cleaner look in my opinion.

If we go with the new white border style, I would tighten up the bottom border since it overflows slightly into the blue. Maybe even thicken up the border width to 1.5px as well to make it stand out more.
