### ISSUE TITLE
Hovering over discrete palette value sometimes highlights wrong color

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1282]
**Describe the bug**
Hovering over discrete palette value sometimes highlights wrong color.

**To Reproduce**
1. Add the layer "Last of the Wild" 
2. Hover over the rightmost green box 
3. Its labeled as "Temperate Coniferous Forests" and highlights the wrong box. 

**Expected behavior**
It is labeled as "Montane Grasslands and Shrublands" and highlights the correct box. 

**Desktop (please complete the following information):**
- OS: macOS 
- Browser: Chrome
- Version: 69

**Comment by minniewong** [comment]
I have hover issues on a few other ones - mislabeled and hovers over the wrong box: light grey box should be labeled "Tundra" but is labeled "Montane Grasslands and Shrublands"; light pink should be "Desert and Xeric Shrublands" but is labeled as "Tundra"; blue should be labeled "Lakes" but is labeled as "Flooded Grassland and Savannas"
