### ISSUE TITLE
If you move "A" dragger on the timeline, sometimes you can see the guitar pick off set behind it

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1283]
1. Move the 'A' dragger before the 'B' dragger when in comparison mode
2. Move 'A' dragger back and forth on the timeline and sometimes the 'today' guitar pick will be offset behind the 'A' dragger
![Screen Shot 2018-09-10 at 2.45.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5838ab2138f438130034ed03/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f36b7191a37af1162e4f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d2650e26c56e14abee821be903b9208b4fd4b4edd91dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df54de74d50a5173065e5702431.png)
Browser: Chrome OSX
version: 2.9.0

**Comment by Benjaki2** [comment]
Unable to replicate. Closing for now

**Comment by edplato** [comment]
I was able to reproduce in Windows Chrome. It seems to happen only after closing/opening timeline via hamburger while already in A|B mode. The guitar pick lags behind/follows whatever you're dragging.

Mid drag:
![drag](https://user-images.githubusercontent.com/24417194/45626703-27aad780-ba5e-11e8-8662-cdd736a7a454.png)

Post drag:
![image](https://user-images.githubusercontent.com/24417194/45626507-c125b980-ba5d-11e8-91af-bff1fa926206.png)
