### ISSUE TITLE
Add AMSR2 Land layers

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#131]

**Comment by rboller** [comment]
AMSR2_Soil_Moisture_NPD_Day_v0_NRT	Soil Moisture (Normalized Polarization Difference, Day, AMSR2, GCOM-W1)
AMSR2_Soil_Moisture_NPD_Night_v0_NRT	Soil Moisture (Normalized Polarization Difference, Night, AMSR2, GCOM-W1)
AMSR2_Soil_Moisture_SCA_Day_v0_NRT	Soil Moisture (Single Channel Algorithm, Day, AMSR2, GCOM-W1)
AMSR2_Soil_Moisture_SCA_Night_v0_NRT	Soil Moisture (Single Channel Algorithm, Night, AMSR2, GCOM-W1)
