### ISSUE TITLE
Layer list not expanding in mobile [layer.mob.init.1]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1332]
**Describe the bug**
Layer list is not fully expanding in mobile.

**To Reproduce**
1. Go to Mobile sized page and click to open Layer List

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome (mobile simulated)
 - Version 2.9.0

**Comment by minniewong** [comment]
Same issue in OSX, Firefox and iPhone.
