### ISSUE TITLE
Prevent empty layers GIF create

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1351]
**Describe the bug**
Can create GIF with no active layers. This causes a console error related to a rejected Promise and displays the 'Your GIF' dialog with a broken image. Conditionally disabling the create GIF button should address this issue.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 69.0.3497.100

**Comment by minniewong** [comment]
This is an edge case - closing ticket.
