### ISSUE TITLE
Implement startup tour modal & steps 

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1354]
Implement the tour and stories, (outlined in ticket #101 and internal excel sheet), using bootstrap/reactstrap modals with css transitions.

Add any relevant comments regarding the tour functionality in this ticket.

To Do:
- [x] Split stories.json out into separate files and compile into 1 file on build.
- [x] Add: When an old tour is being accessed via a permalink, display a modal saying Sorry, this tour is no longer supported"
- [x] Limit tours to 9
- [x] Add documentation
- [x] Allow pasting the full link into the steps description parameter
- [x] When an old tour is being accessed via a permalink, display a modal saying `"Sorry, this tour is no longer supported".`
- [x] Add GTM tags & test on UAT
- [x] Add/test unit tests
- [ ] Add/test end to end tests
- [x] Add manual test plan pages

======================================================
Major Bugs:
- [x] Comparison feature breaks when two layers of the same type are loaded in A and B states
- [x] Tour permalink parameter is not saving
- [x] If a step has a custom palette and the next step has no custom palette info, the palette does not revert back to default palette

======================================================
Additional Suggestions / Fixes (1/8/2019)
- [x] Make the move from one part of the world to another smoother (like events)
- [x] Change color of links within the dark blue in-progress modal steps (default category)
- [x] Adjust number of start up stories based on vertical window height
- [x] Ensure in-progress modal does not block +/- window when vertical window height is decreased
- [x] Change extra step of in-progress modal to not account for last window (When there is 8 steps it says 9)
- [x] When you have a tour step and scroll down, the next step will be scrolled down to the bottom instead of starting at the top of the text.
- [x] "Read more" links on final dialog should open in new window
- [x] Create a Worldview features category

======================================================
Additional Suggestions / Fixes (1/10/2019)
- [x] Destroy animation widget when starting a new tour (and any other transitional-type elements)
- [x] Destroy comparison mode when a new story has been selected
- [x] Change link text to regular and not bold
- [x] Squashed, min/max, and palettes are not being applied to layers

======================================================
Additional Suggestions / Fixes (1/24/2019)
- [x] Comparison mode persists once opened and then you go back a step

======================================================
Additional Tour Enhancements: https://github.com/nasa-gibs/worldview/issues/1613

**Comment by ZachTRice** [comment]
Ensure there is a way to handle deprecated features / old, unsupported stories. i.e. when an old tour is being accessed via a permalink, display a modal saying `Sorry, this tour is no longer supported`".

**Comment by minniewong** [comment]
I added a step where the last step was where the palette was [squashed](https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor,MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,Reference_Features,GHRSST_L4_MUR_Sea_Surface_Temperature(opacity=0.72,min=16.05,16.2,squash),Reference_Labels(hidden),Coastlines&t=2018-09-09-T00%3A00%3A00Z&z=3&t1=2018-09-19-T00%3A00%3A00Z&v=-92.74094509032383,14.257746126582298,-48.8950826682391,46.52867126722967&ab=on&as=2018-09-09T00%3A00%3A00Z&ae=2018-09-14T00%3A00%3A00Z&av=1.5&al=false) - but the squashed palette was not preserved when i reached that step.

**Comment by minniewong** [comment]
If I go from a story that ends on an animation, and start a new story that does not start with an animation, the animation modal is still open.

**Comment by minniewong** [comment]
If you go through a tour that ends on the comparison mode, click on "Exit Tutorial" and then go to the `i` and click on "Start Tour" and click on a different story, the comparison mode is still active in that new tour story.

**Comment by minniewong** [comment]
![Screen Shot 2019-01-16 at 1.45.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5838ab2138f438130034ed03/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226455f56b7191a379f1162e4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ee5d2650e26c56e14abee821be903b9208b4fd4b4edd91dd2f42f67b6d5db1063474f4dcbed5727a19041c95df24ce74b51a7143266e6742431.png)

Can the link text be regular font, not bold?

**Comment by minniewong** [comment]
The comparison mode persists if you are in a story (e.g. Camp Fire) where the comparison mode is invoked on the 3rd step and you go back a step.
