### ISSUE TITLE
AMSRU Sea Ice version change

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#1366]
Change from R00 to R01

Sea Ice Concentration 25km:
https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/AMSRU2_Sea_Ice_Concentration_25km/default/2018-09-27/2km/0/0/0.png

Sea_Ice_Concentration_12km:
https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/AMSRU2_Sea_Ice_Concentration_12km/default/2018-09-27/2km/0/0/0.png

Sea Ice Brightness Temp 6km 89H:
https://gibs.earthdata.nasa.gov/wmts/epsg4326/nrt/AMSR2_Sea_Ice_Brightness_Temp_6km_89H_v1_NRT/default/2018-09-27/2km/0/0/0.png

Sea Ice Brightness Temp 6km 89V:
https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/AMSR2_Sea_Ice_Brightness_Temp_6km_89V/default/2018-09-25/2km/0/0/0.png

**Comment by minniewong** [comment]
These layers look fine in Worldview now - no change required on our end.

**Comment by minniewong** [comment]
Imagery for the past month looks fine, though I am unable to see older imagery (2012 - 2016) for the 4 layers in Geographic; and no imagery in Arctic and Antarctic for 2012 - April 2018.

**Comment by jejeking** [comment]
Glad all works. The purpose of the ticket is to double check all is working as it si supposed to. But also, if you need to update some metadata somewhere to alert of version changed, that's what this ticket is for.
