### ISSUE TITLE
Add dateline config to relevant layers

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#138]
wrap=true
datewrap

**Comment by minniewong** [comment]
All MODIS and VIIRS daytime products

**Comment by Benjaki2** [comment]
<img width="527" alt="screen shot 2017-01-25 at 6 06 24 pm" src="https://cloud.githubusercontent.com/assets/3605988/22832747/43b85496-ef7d-11e6-8e5a-3dee9dfb681a.png">

**Comment by minniewong** [comment]
"wraps", "datewraps", "wrapdates"?

**Comment by Benjaki2** [comment]
No preference here.

**Comment by rboller** [comment]
I like "datewraps" or "wrapdates" since "wraps" may not make it entirely clear what's being wrapped.

**Comment by minniewong** [comment]
"datewraps"

**Comment by minniewong** [comment]
Added to relevant layers and added to relevant day time orbit tracks for certain satellites
