### ISSUE TITLE
JPEG Baselayer with Colorbar

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#1380]
The Landsat_WELD_NDVI_Global_Annual and Landsat_WELD_NDVI_Global_Monthly products are JPEG base layers, but now have a colormap associated with them, per provider request.  This configuration is not currently supported by Worldview, but we are requesting that it now be.

**Comment by mike-mcgann** [comment]
I appears we already did this work and the updated colormap can go out with the next release.
