### ISSUE TITLE
"TypeError: _jquery2.default.get(...).success is not a function"

### ISSUE THREAD

**Issue by dattilo** [nasa-gibs/worldview#1386]
**Describe the bug**
I have downloaded the latest version of worldview via git and have built it via NPM without error. When I try to select any layer though, the following error is thrown and I cannot select the layer:

error { target: Window, isTrusted: true, message: "TypeError: _jquery2.default.get(...).success is not a function", filename: "https://worldview.acom.ucar.edu/build/wv.js?v=@BUILD_NONCE@", lineno: 248517, colno: 15, error: TypeError, srcElement: Window, currentTarget: Window, eventPhase: 2, … }
react-beautiful-dnd.esm.js:3803

It would seem that _jquery2.default.get(...).success has been deprecated in favor of:

"As replacements, use the Deferred standard methods of done,  fail, and always, or use the new then and catch methods for Promises/A+ compliance."

Note that I can change the code to: "_jquery2.default.get(...).always" and everything works as expected (not sure that is ideal though).

**To Reproduce**
Basic install from git, npm build, etc.
Attempt to add a layer, nothing happens... Look in browser log and see error above.

**Expected behavior**
Should be able to add a layer...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Both Firefox and chrome
 - Version: latest of each

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mike-mcgann** [comment]
I rebuilt Worldview off the develop branch and I'm unable to reproduce this error. Here are the steps I followed:

```bash
git clone https://github.com/nasa-gibs/worldview.git
cd worldview
git checkout develop
npm install
npm run getcapabilities
npm run build:config 
npm run watch 
```

In Worldview:
* Click on "Add Layers"
* Type "AOD" in search box
* Select "Aerosol Optical Depth, Terra/MODIS"
* Click on the "X" button 

We did just switch to jQuery 3 so errors like you reported are expected. If you are able to pinpoint the location in the source code, feel free to submit a pull request. Otherwise some additional information would be helpful to debug. I searched the code for .success and I couldn't find any more references.

**Comment by dattilo** [comment]
Thanks... If it is fixed in the development version then this is a non-issue... For completeness, the issue shows up in the current release in /web/build/wv.js in two places:
  247745    _jquery2.default.get('config/metadata/' + layer.description + '.html').success(function (data) 
  248517    _jquery2.default.get('config/metadata/' + source.description + '.html').success(function (data)
This looks to be dynamically built as it only shows up in /web/build... 
-Garth

**Comment by mike-mcgann** [comment]
Thanks for the info. If you do happen to find other errors like this in the development version, please let us know.
