### ISSUE TITLE
Auto timeline expansion for “future-capable” layers 

### ISSUE THREAD

**Issue by dattilo** [nasa-gibs/worldview#1387]
We are using worldview for our forward looking air quality models which reach out 10 days into the future. Currently, we have to use the "now=DATE" option to "see" the future but that is not realistic for remote users who have never used worldview. 

 I know when I worked with you before, there was some mention that the ICESat-2 mission would require implementation of this feature but I cannot find any documentation that indicates how that might work. It would be great if a future-capable layer still started with today's date but had the option of moving the slider into the future.

**Comment by dattilo** [comment]
I see this is on the "Projects" page... I would certainly help test out this feature if need be...

**Comment by mike-mcgann** [comment]
I can ask about this. Ping us again Monday afternoon if you don't hear back by then.

**Comment by mike-mcgann** [comment]
Scheduled for the November release.
