### ISSUE TITLE
Update share icon

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#139]
Update the share icon to a more standard "box with arrow" or "3-dot-connected" icon.

**Comment by rboller** [comment]
To this old timer, the "more standard" icon _is_ the "link" icon.  :)   But I suppose we could consider one of the other share icons [here](http://fontawesome.io/icons/).

**Comment by CodeMacabre** [comment]
My personal preference (partly inspired by [this article](https://www.fastcodesign.com/3031872/why-isnt-there-a-standard-share-button)) is the 'box with arrow', as I think it conveys the sharing meaning most clearly. FontAwesome's `share-square-o` is great, but depending on how it looks alongside the others, `share` could also work:

![share-square](https://cloud.githubusercontent.com/assets/19981049/24306986/6619bb98-10ba-11e7-8948-55ce101d8404.PNG)

**Comment by Benjaki2** [comment]
Thoughts @minniewong @rboller ?

My initial instinct was to go with the `fa-share-alt` but agree with the above article's comment on it's lack of intuitiveness.

**Comment by rboller** [comment]
If I had to choose between `fa-share` and `fa-share-square-o`, I like the latter better.

That said, is the subtext to this discussion that the "link" icon is dead?  I may be the curmudgeon on this one, but I'll also point out that Google Maps still uses a link-like icon.

**Comment by minniewong** [comment]
which one is fa-share-alt? I also like fa-share-square-o if we had to choose between the two.

**Comment by Benjaki2** [comment]
@minniewong [share-alt](http://fontawesome.io/icon/share-alt/) . I am in support of `fa-share-square-o` if we do decide to make a change

**Comment by ZachTRice** [comment]
In the past I have used the the 3-dots (`fa-share-alt`), because this was the icon that the ShareThis uses and often that service was being dropped in to my projects to provide analytics. I imagine `fa-share-square-o` is going to be more easily recognized by people who use Apple products. Both have a huge user base and I feel both icons convey the intended action. I support using either icon. I'll add `fa-share-square-o` to my share-feature branch.

**Comment by ZachTRice** [comment]
The icon needs to be updated in the start-up tour window.
