### ISSUE TITLE
Provide user guidance for layer selection

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1394]
Certain products have many variations (e.g., Sea Surface Temperature has around 50 of them) which can make it very difficult for users to decide which one(s) to use.  

This ticket is to investigate how to make this process more intuitive; e.g., providing filters to only show layers available for the currently selected date (#962), prioritizing layers known to be more widely used, adding more facets, etc.

**Comment by jasontk19** [comment]
Will be addressed with #2645 and #2778
