### ISSUE TITLE
Improve layer search by adding more layer aliases

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1396]
Per user report of not being able to find relevant layers when searching for "Atmospheric Temperature", we may want to add more layer aliases to catch what some users may be accustomed to using.

GCMD keywords may be able to help with this.  E.g., adding an "Atmospheric Temperature" alias to all relevant layers listed in their database:
https://gcmd.nasa.gov/KeywordSearch/Keywords.do?Portal=GCMD&KeywordPath=Parameters%7CATMOSPHERE%7CATMOSPHERIC+TEMPERATURE&MetadataType=0&Columns=0&lbnode=mdlb2#maincontent

**Comment by minniewong** [comment]
Harness CMR records for keywords at build time
