### ISSUE TITLE
Improve discoverability of orbit tracks

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1405]
As we continue to see, many users find the orbit tracks to be highly valuable but often aren't aware of their existence.  

This ticket is to identify ways to improve the discoverability of orbit tracks. 

Known uses: 
- determining what time of day imagery from a given spacecraft was acquired
- looking for coincident observations between two spacecraft (and to illustrate "scientific dangers" of comparing imagery acquired at different times of day)
- determining which granule to download if they're given a list of timestamps

**Comment by rboller** [comment]
One possible option is to automatically show granule footprints when hovering over the map (when available) which show the extent and time range of each granule.

**Comment by jasontk19** [comment]
I've mocked up a number of options for interactions to toggle showing orbit tracks associated with a given layer:

[Option 1 - Add checkbox(es) to the layer options to show/hide tracks](https://sketch.cloud/s/a8RqA/a/D1meAW/play)
[Option 2 - Checkboxes in layer options show/hide a sub-layer for tracks](https://sketch.cloud/s/a8RqA/a/3zmdad/play)

At last week's dev meeting I presented these and we talked about the pros/cons.  A third option evolved out of this discussion which was to show the sub-layers for an orbit track along aside a given layer at all times.  This option likely provides the most visibility for orbit tracks:

[Option 3 - Sub-layer for tracks always visible](https://sketch.cloud/s/a8RqA/a/ZQ8GrZ/play)

**Comment by jasontk19** [comment]
New mockup based on additional discussions:

[Option 4 - Show sub-layer after adding track via layer options](https://sketch.cloud/s/a8RqA/a/omkkvx/play)

**Comment by jasontk19** [comment]
Remaining work:

- [ ] fix display of track titles without a `daynight` value
- [ ] fix styling of sub-layer section to match the parent layer when enabled/disabled
