### ISSUE TITLE
transparent tiles "zoomed in" views...

### ISSUE THREAD

**Issue by dattilo** [nasa-gibs/worldview#1407]
I have installed the DEV branch via git and all looks to be working well. I am experiencing one oddity that I have not seen before. On certain days, on a new layer I have created I start to see transparent tiles along the bottom and top of the image but only when I zoom in (the 5000km view never has them). Depending on the day, the transparent tile may show up in the 2000km view and for other days, at the 1000km, 500km, etc.  view. The more I zoom in, the more transparent tiles I start to see along the top and bottom. There is nothing too special about this imagery and I have created it in the exact same fashion as our other layers which do not have this issue. I see no errors on the logs nor do I see any in the web dev tools. You can zoom in at the following URL too see what I mean. Have you experienced this before?

https://worldview.acom.ucar.edu/?p=geographic&l=MODIS_Terra_CorrectedReflectance_TrueColor(hidden),BlueMarble_NextGeneration,Reference_Labels(hidden),Reference_Features,Coastlines,NCAR_WACCM_CO_FIRES_1000hPa(hidden),NCAR_WACCM_PM25_1000hPa,NCAR_WACCM_O3_500hPa(hidden),NCAR_WACCM_O3_1000hPa&t=2018-10-10-T00%3A00%3A00Z&z=3&v=-343.41472899840625,-114.83218376399815,312.17902100159375,137.16781623600184

Thanks as always,
Garth

**Comment by mcechini** [comment]
Are you load balancing requests to https://worldview.acom.ucar.edu?

It's odd that [this](https://worldview.acom.ucar.edu/onearth/wmts/epsg4326/wmts.cgi?TIME=2018-10-10T00:00:00Z&layer=NCAR_WACCM_PM25_1000hPa&style=default&tilematrixset=EPSG4326_2km&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=3&TileCol=4&TileRow=1) works, but [this](https://worldview.acom.ucar.edu/onearth/wmts/epsg4326/wmts.cgi?TIME=2018-10-10T00:00:00Z&layer=NCAR_WACCM_PM25_1000hPa&style=default&tilematrixset=EPSG4326_2km&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=3&TileCol=3&TileRow=0) doesn't when the only difference is row/col.

**Comment by dattilo** [comment]
Thanks! We are not load balancing requests... Is it more likely that this
is a mrfgen/onearth issue? I do not see any errors in that process though
so I thought I would start here...
The worldview teams' responsiveness is amazing by the way... :-)
-Garth
--
ACOM Systems Administrator
(dattilo@ucar.edu)
(Office: FL0-2110 Ph: 303-497-1471)

**Comment by mcechini** [comment]
Garth, this doesn't appear to be a Worldview issue, as the issue is demonstrable through the direct tiles requests that I included above.  Worldview is just making it easier to find them. 

Do you see any errors in the apache httpd error.log or access.log files?  Something is definitely causing OnEarth to return an invalid empty tile, but I can't tell why.
