### ISSUE TITLE
When in AEST, timeline date differs from the left entry and the guitar pick

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1410]
**Describe the bug**
When in timezones beyond GMT, the timeline date entry on the left does not match the guitar pick location and label.

**To Reproduce**
1. Change the timezone to AEST
2. When you enter the date on the left side of the timeline, the pick is off a day (but the DOY label is now correct per PR #1402)

**Expected behavior**
The dates should be the same

**Screenshots**
![](https://user-images.githubusercontent.com/10747923/46688466-6bab7b00-cbcb-11e8-80d3-301c9f436a16.png)

**Comment by ZachTRice** [comment]
Upgrading D3 to the latest version might make this fix easier since there are more options to control the time in the decoupled d3-time library, see: https://github.com/d3/d3-time
Initial work on upgrading D3 has started here: https://github.com/nasa-gibs/worldview/pull/1404
