### ISSUE TITLE
Page crashes on load and shows An unexpected error has occurred

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1415]
**Describe the bug**
Page crashes on load with below url in Chrome and displays a dialog with 'An unexpected error has occurred'. The url loads fine in Firefox. The sidebar and map are not populated with the permalink layers.  Page function (buttons, sidebar, timeline) is broken. Appears to be related to react-beautiful-dnd.

**To Reproduce**
1. **IN DEVELOPMENT (error not fully displayed in production)** Go to [http://localhost:3000/?p=arctic&l=MODIS_Aqua_CorrectedReflectance_Bands721(hidden),MODIS_Terra_CorrectedReflectance_Bands721(hidden),MODIS_Terra_CorrectedReflectance_Bands367(hidden),VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1(hidden),VIIRS_SNPP_CorrectedReflectance_BandsM3-I3-M11(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,Graticule(hidden),Reference_Labels(hidden),Reference_Features(hidden),Coastlines(hidden)&t=2018-10-06-T00:00:00Z&z=3&v=-3222333.6038680756,-670670.5729959705,-65539.11419169256,854577.8217811072&ab=off&as=2018-10-02T00:00:00Z&ae=2018-10-06T00:00:00Z&av=5&al=false](http://localhost:3000/?p=arctic&l=MODIS_Aqua_CorrectedReflectance_Bands721(hidden),MODIS_Terra_CorrectedReflectance_Bands721(hidden),MODIS_Terra_CorrectedReflectance_Bands367(hidden),VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1(hidden),VIIRS_SNPP_CorrectedReflectance_BandsM3-I3-M11(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,Graticule(hidden),Reference_Labels(hidden),Reference_Features(hidden),Coastlines(hidden)&t=2018-10-06-T00:00:00Z&z=3&v=-3222333.6038680756,-670670.5729959705,-65539.11419169256,854577.8217811072&ab=off&as=2018-10-02T00:00:00Z&ae=2018-10-06T00:00:00Z&av=5&al=false)
2. See error:

![image](https://user-images.githubusercontent.com/24417194/47234914-51c91f80-d3a5-11e8-9bec-7acc17423755.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 70

**Comment by minniewong** [comment]
Another user had issues on Google Chrome/Windows with the following link: https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden),VIIRS_Black_Marble,Reference_Labels(hidden),Reference_Features(hidden),Coastlines(hidden),VIIRS_SNPP_DayNightBand_ENCC(hidden),VIIRS_Night_Lights(hidden)&t=2016-12-08&z=3&v=-46.95418870015831,12.383070584015819,50.99112379984169,65.39869558401583
