### ISSUE TITLE
Data Download for remote instance and for non-CMR data

### ISSUE THREAD

**Issue by dattilo** [nasa-gibs/worldview#1416]
Hi Team,
   Currently, when we try to download any data using our Worldview instance we get the following message:
     "Unable to search at this time."
     Please try again later.
My browser console shows:
```
Unable to search error 
ui.js:141
onQueryError ui.js:141
events/self.trigger/<	events.js:46
arrayEach	`_arrayEach.js:15`
forEach	forEach.js:38
events/self.trigger	events.js:45
query/<	model.js:345
events/self.trigger/<	events.js:46
arrayEach	_arrayEach.js:15
forEach	forEach.js:38
events/self.trigger	events.js:45
dataHandlerBase/self.submit/<	handler.js:122
fire	jquery.js:3268
fireWith	jquery.js:3398
Deferred/</deferred[tuple[0]]	jquery.js:3736
dataCmrClient/self.submit/<	cmr.js:77
fire	jquery.js:3268
fireWith	jquery.js:3398
done  	jquery.js:9307
callback/<	jquery.js:9540
```

It would be great to download the CMR indexed data from our worldview instance. Even better would be for us to be able to download our own forecast data which would most likely not be considered for CMR inclusion. 

We are using custom URL's to load specific combinations of layers so we can add in a link to a data 
repository, subsetter, giovanni, etc. but it would be nice to be able to do that from within worldview. 

Having an option to link to an specific URL from the data tab would be ideal...

**Comment by mike-mcgann** [comment]
An error at that location indicates that the request failed but it appears that the actual error message isn't informative. In the browser's development tools check the network tab to see what the response is from the server which will probably give a better clue as to what is going on. 

Data download is very CMR specific and also has a lot of features that are very dataset specific. There have been some discussions about providing hooks or handoffs to other systems but that isn't on the schedule right now. 

If it would be useful, static links to repositories, subsetters, Giovanni can be provided in the information/metadata panel for each layer. 

Features in Worldview can also be enabled and disabled as needed in this configuration file:

https://github.com/nasa-gibs/worldview/blob/develop/config/default/common/features.json
