### ISSUE TITLE
URL for squashed palettes does not maintain max value

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#142]
I've been using EOSDIS to highlight arctic temperatures between water/ice. A typical URL is below. Note that the rainbow palette is used with a max of 280.6, squash. However, on loading the URL the max level is not being read correctly. The min is set from the URL but the max has to be set manually every time.

https://worldview.earthdata.nasa.gov/?p=arctic&l=MODIS_Terra_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),Land_Mask,MODIS_Aqua_Brightness_Temp_Band31_Night(palette=rainbow_1,min=232.5,max=280.6,squash),Coastlines(hidden),Reference_Labels(hidden),Reference_Features(hidden)&t=2017-02-08&z=3&v=-1846071.8060576292,-1712535.0571888522,120008.19394237094,-703895.0571888522&ab=off&as=2016-12-15&ae=2016-12-22&av=3&al=true

**Comment by tgunnoe** [comment]
Fixed
