### ISSUE TITLE
Layers extend beyond edge of layer list when adding from product picker

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1439]
**Describe the bug**
When you add a few layers to the layer list from the Product picker, the layers extend beyond the edge of the layer list. 

**To Reproduce**
1. Go to Add layers
2. Search for Snow Water Equivalent; add each layer
3. The layers extend beyond the edge of the layer list.
4. Once you close the product picker, the layers now fit properly in the layer list.

**Expected behavior**
The layers should not extend beyond the edge of the layer list when you're adding from the product picker. 

**Screenshots**
![screen shot 2018-10-30 at 2 04 33 pm](https://user-images.githubusercontent.com/10747923/47740093-53200500-dc4d-11e8-9345-ebdff646781b.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Firefox 
 - Version: 60.2.2esr (64 bit)

SIT 2.10.0

**Comment by edplato** [comment]
Seeing this in chrome as well. Additional screenshot of sidebar text moving and 'remove layer' X's being cutoff:

![image](https://user-images.githubusercontent.com/24417194/47807902-993f9c00-dd13-11e8-9eb9-634073061671.png)
