### ISSUE TITLE
Create image extent initially undefined and coordinates sticky to mouse movement

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1449]
**Describe the bug**
In SIT, when creating an image the 1) initial raw file size and dimensions are undefined, 2) this causes a ```setExtent``` console error to throw, and 3) the coordinates to "stick" to the mouse movements.

**To Reproduce**
1. Go to SIT
2. Click 'Take a Snapshot' to make image (see initial raw size, image dimensions, and console error)
3. Define an area for an image
3. Move mouse over to sidebar and see trailing coordinates

**Screenshots**
-Init snapshot raw size and image dimensions undefined
![image](https://user-images.githubusercontent.com/24417194/47805577-0fd99b00-dd0e-11e8-87d9-425f05ccd61f.png)

-console error
![image](https://user-images.githubusercontent.com/24417194/47805591-16681280-dd0e-11e8-9f0c-7c27a9ab5b5c.png)

-sticky coordinates to mouse
![image](https://user-images.githubusercontent.com/24417194/47805583-12d48b80-dd0e-11e8-94cb-8785b6d0e83b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome (Also seen in Edge)
 - Version 70.0.3538.77

**Comment by minniewong** [comment]
I saw this in Firefox too but couldn't replicate it

**Comment by Benjaki2** [comment]
I've also seen this, in chrome, but could not replicate

**Comment by edplato** [comment]
I think ```setExtent``` is also affecting creating a GIF. Intermittently in SIT, when clicking on 'Created Animated GIF', a ```setExtent``` error is thrown and the dialog to drag a focus area to create a GIF does not open.

Here is the error:
![image](https://user-images.githubusercontent.com/24417194/47814550-62be4d00-dd24-11e8-898d-bcd1ab1df6b3.png)

**Comment by edplato** [comment]
Follow up, here is the local development version error for the original creating an image bug:
![image](https://user-images.githubusercontent.com/24417194/47815922-05c49600-dd28-11e8-828d-dced98118025.png)

**Comment by ZachTRice** [comment]
I am seeing something similar happening in IE11, test plan: [date.animation.gif.2]. I am not able to create a GIF. The error I see is `Unable to get property 'setExtent' of undefined or null reference`

**Comment by minniewong** [comment]
I'm also seeing the same issue as above with the regular image snapshot and the animated GIF creation in Firefox
