### ISSUE TITLE
change 'wraps' flag to 'datewraps'

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#145]
https://github.com/nasa-gibs/worldview/issues/138

**Comment by minniewong** [comment]
in discussion with @rboller, we might need to discuss this some more with the larger group - it would be cool to wrap Monthly (average) layers, but in this case, wrapping the same month as opposed to the month before and after. If so, we should change the name of the flag.

**Comment by minniewong** [comment]
wrapself?
wrapadjacentday?
