### ISSUE TITLE
Adding layers causes sidebar to expand and cutoff

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1451]
**Describe the bug**
In SIT, when clicking '+ Add Layers' the sidebar expands horizontally slightly causing layer text to move and the 'remove layer' X's to be cutoff.

**To Reproduce**
1. Add Layers and see sidebar expands (text moves and 'remove layer' X's are cutoff)

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/47807902-993f9c00-dd13-11e8-9eb9-634073061671.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome (screenshot) and Edge

**Comment by Benjaki2** [comment]
relates to #1439
