### ISSUE TITLE
"x" within search box in IE11

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1455]
**Describe the bug**
In IE11, there is an additional "x" in the search box on focus. This may be confusing to some users.

**Screenshots**
![screenshot_35](https://user-images.githubusercontent.com/17348884/47813939-c8a9d500-dd22-11e8-8566-a55c1d3a376d.png)

**Desktop (please complete the following information):**
- Internet Explorer 11

**Comment by Benjaki2** [comment]
Won't fix.
