### ISSUE TITLE
Product picker categories have no background images in Edge

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1456]
**Describe the bug**
Layer category background images in the product picker are not showing up in Edge. Looks fine when checked in Chrome.

**To Reproduce**
1. In Edge, click '+Add Layers' button and see no background layer category images.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 15.15063

**Comment by ZachTRice** [comment]
Also seeing this in Windows 10 - Internet Explorer 10

Looks like an inline (background-image) style is not being set on `.category-background-cover` 

![screenshot_31](https://user-images.githubusercontent.com/17348884/47858158-c5195b00-ddc1-11e8-869b-ba7b8a52de95.png)
