### ISSUE TITLE
URL Fails to load in IE11 (react infinite loop) [date.pick.7]

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1457]
**Describe the bug**
The following link from [date.pick.7] fails to load in IE11 but appears to work in all other browsers:
`/?p=geographic&l=MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,MEaSUREs_Daily_Landscape_Freeze_Thaw_AMSRE,MEaSUREs_Daily_Landscape_Freeze_Thaw_SSMI,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2013-12-31&v=-118.546875,-53.3671875,40.078125,59.8359375`

The error I receive is `Minified React error #185; visit https://reactjs.org/docs/error-decoder.html/?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings`

Going to the link above shows that the error is related to `componentWillUpdate or componentDidUpdate` here is the full error message:

`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer 11

** Other Notes**
Also seeing this in the following test plan links:
[date.field.6]

**Comment by mike-mcgann** [comment]
I'm unable to reproduce this problem on my version of IE. Both date.pick.7 and date.field.6 work here. Can you poke around more and see if these links always produce this error? Size of browser window might be related.

**Comment by ZachTRice** [comment]
I have tested this on 2 Windows 10 machines. The issue is only appearing on 1 of them. When it does happen, it seems to happen when the height of the viewport is large enough to not trigger a scrollbar in the layer list. When the window is loaded with the height reduced and the layer list has a scrollbar, the error does not occur.

The issue happens on this specific IE version 11.1387.15063.0. I am locked to this specific version on this machine so I can't do much testing with upgrading from this. It is working on the PC with the IE11 version 11.345.17134.0

**Comment by ZachTRice** [comment]
Adjusting this value seems to have no effect

**Comment by mike-mcgann** [comment]
Thanks for checking

**Comment by edplato** [comment]
I couldn't reproduce the issue when I tried on my home PC.
