### ISSUE TITLE
Data download MODIS grid H/V numbers are not displayed at zoomed out resolutions [dd.modis.grid.1]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1462]
**Describe the bug**
Data download MODIS grid H/V numbers are not displayed at zoomed out resolutions when comparing SIT to production [dd.modis.grid.1].

**To Reproduce**
1. Go to dd.modis.grid.1 in SIT
2. Hover over data download granule and note H and V numbers are not displayed at same zoomed out resolution as production

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Edge
 - Version: 70.0.3538.77 and 15

**Comment by edplato** [comment]
I am also seeing this in [dd.dbound.1] where SIT needs to zoom in more for the text to show up.

**Comment by mike-mcgann** [comment]
This appears to be with all labels in general.
