### ISSUE TITLE
Search mobile version input is too tight

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1480]
**Describe the bug**
Search mobile version input is too tight when using the input to type a search query. May need a mobile specific version omitting the breadcrumbs, but just an idea.

**Screenshots**
*photo from chrome mobile mode, but tested in android with same view
![image](https://user-images.githubusercontent.com/24417194/48072773-4cdcdc00-e1ab-11e8-9628-fc5e5bbc712e.png)

**Comment by Benjaki2** [comment]
Sounds like a good solution  👍 

**suggestion:** Removing the categories all together in mobile view might be a good future implementation.
