### ISSUE TITLE
Number of layers doesn't update on Projection change (Mobile) [proj.nav.5]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1488]
**Describe the bug**
When you are in mobile and you click to change the projection, the number of layers does not update
**To Reproduce**
1. Go to main page
2. Switch to antarctic projeciton
3. Layer-list now only has 4 layers (was 6 before) but 'bubble' still shows 6 layers

**Screenshots**
<img width="419" alt="screen shot 2018-11-08 at 9 20 59 am" src="https://user-images.githubusercontent.com/3605988/48204371-a83bd500-e337-11e8-8e05-774f22947ab7.png">

**Smartphone (please complete the following information):**
 - Device: iphone 6SE
 - OS: IOS 11.3
 - Chrome

**Comment by minniewong** [comment]
same on my desktop chrome too
