### ISSUE TITLE
Optimize tile requests for multi-day and sub-daily products

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#149]
Subtasks:
- [x] Create build step in processTemporalLayer.py to detect "monthly" and "yearly" temporal type from GC doc
Pending Fix in: #750 
- [x] Create build step in processTemporalLayer.py to output array of all date ranges from GC doc
Pending Fix in: #750 
- [x] Create branch based on `develop` for optimizing monthly/yearly layer requests
- [x] Create build step to determine timeInterval. (i.e. `P8D`, would be `8`)
- [x] Monthly: Request tiles only for active layers when timeline date matches a date within the dateRanges object and perform request only at what is specified in the dateInterval object.
- [x] Yearly: Request tiles only for active layers when timeline date matches a date within the dateRanges object and perform request only at what is specified in the dateInterval object.
- [x] Daily: Check for odd intervals and only request daily layers when the specified interval has passed (should tie in with the subdaily work below)
- [x] Fix issues with precached events (animations and image download)
- [x] Investigating enabling persistent cache via LocalStorage
- [x] Rebase `subdaily-timeline` on `optimize-requests` branch
- [x] Subdaily: Ensure that daily layers are only requested when needed, based on initial "Daily" work above
- [x] Bug fixes

Overview:
For our new multi-day products (e.g., monthly and annual), Worldview currently requests imagery for every day within a given period even though it only needs to retrieve it once.  This can be optimized by deeper parsing of the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string from the [GIBS GetCapabilities document](https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml) to better handle these non-daily products.

As also described in #610, we'll need to optimize for sub-daily products (e.g., hourly) so that time slider movements which don't cross a day/month/year boundary won't trigger continuous tile requests for daily/monthly/annual layers.

**Comment by minniewong** [comment]
weekly and seasonal too

**Comment by rboller** [comment]
Relates to #150

**Comment by rboller** [comment]
Something to note when we start work on this ticket: there will be new products (e.g., GRACE and OSCAR) which have "ugly" time availabilities.  

More specifically, a given layer will have irregular time intervals for adjacent time steps.  E.g., one time step will be 28 days, the next will be 31 days, etc.  These intervals will be documented in the GIBS GetCapabilities documents, but we should be aware of them when implementing and testing this optimization.
