### ISSUE TITLE
Timeline forward right arrow missing [date.init.20]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1494]
**Describe the bug**
The timeline forward right arrow is missing [date.init.20] where the ```now``` query string is set to 2013/Mar/15. The right arrow is visible in production when comparing with the UAT version. The arrow is actually still clickable and will move the date from the 14th the 15th when clicked.

**To Reproduce**
1. Go to date.init.20
2. See timeline right arrow missing, but still clickable 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 60

**Comment by mike-mcgann** [comment]
I'm seeing this too. SIT version is also correct.
