### ISSUE TITLE
Enhanced Timeline Redesign 

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1496]
**The improved timeline should:**
* Not cover up too much of the imagery
* Clearly visualize when/which products are available
* Work with sub-daily imagery
* Show events (**Maybe**) 

**Suggested implementations**

1. Keep main timeline minimal and have `data-bars` visualized in the layer-list #1772 
2. Start with a minimal timeline (just shows time without extras) that can be expanded to show `data-bars` and/or `historical events`
         - Expanded 'availability dialog' could provide additional details (full coverage range, etc.)
 

@edplato Please add/edit to this if I'm missing anything

**Comment by tgunnoe** [comment]
Are there any current designs that I can review? I am really proud of having created the timeline in Worldview and can offer reasoning or guidance for its future

**Comment by Benjaki2** [comment]
It's good to hear from you @tgunnoe! Thanks for reaching out. That list above is a bit outdated. https://github.com/nasa-gibs/worldview/projects/21 might give a little more insight into our direction. For now, the main focus is on accommodating sub-daily layers and custom intervals (allowing the user to create a custom time interval on-the-fly).

@edplato has some designs he has been working on. I will talk to him and the team about getting you those to look over on Monday. :v:

**Comment by edplato** [comment]
Hi @tgunnoe. Here are some draft designs for the timeline that may shift depending on any unforeseen limitations or usability issues.

**Screenshot 1:**
This is the timeline with the date picker component remaining the same, with the exception of the data-layer panel button added (see Screenshot 4). The actual scale part of the timeline will have a smoother drag (no locking on ticks), no ticks, and no bottom date region. There is also a Today button on the right portion of the timeline next to the toggle arrow (specific icons/sizing may change).
![timeline-preivew-withopacity-backgrounda-newac-alt-thickerrevision](https://user-images.githubusercontent.com/24417194/51271264-15ea2a00-1995-11e9-8949-735856e41d0f.png)

**Screenshot 2:**
Hovering (and most likely dragging the triangle) will display a date label above the triangle pick - we may want the day number to be added within this tooltip.
![image](https://user-images.githubusercontent.com/24417194/51271606-fdc6da80-1995-11e9-834e-25fef384f188.png)

**Screenshot 3:**
Here is the Custom Interval Selector which will be functionally connected to the left/right arrows (example: 7 min selected, click right arrow and the triangle pick jumps 7 min based on initial set time). The triangle dragger itself will drag freely and not be locked to this custom interval. The selected interval will also be displayed on the timeline, but there are a few options to work out for the exact marker (see blue rectangles in Screenshot 1).
![customintervalselector-github](https://user-images.githubusercontent.com/24417194/51271213-e89d7c00-1994-11e9-8881-c557c12faa5f.png)

**Screenshot 4:**
Data coverage is planned to be handled after the release of the initial Timeline overhaul, but this is the design that takes the individual data bars out of the timeline and into its own panel above with the option to select multiple layers and show a single bar on the timeline that represents matching coverage of the selected layers.
![daily-black-coastlines-notimeline-ticks-months-withpick-coveragecolorshown2-matching-postv2](https://user-images.githubusercontent.com/24417194/51271375-619cd380-1995-11e9-96e8-42c906f6e624.png)

**Comment by tgunnoe** [comment]
There's a lot of new ideas here and i can see that obviously requirements have outgrown what's capable with the current one.

I'm glad to see that data coverage has been thought about more. Custom intervals is a new idea to me. The amount of buttons and text that are being added invalidates the clean lines that the current design was shooting for originally (the addition of the animation icon started this). e.g. the collapsed timeline was supposed to be as wide as the side layer menu.

The less than day intervals was not been planned with the current design either, so i would toss that date picker part in favor of a new one. The amount of arrows will be overwhelming, I didn't even like the current faded up and down arrows!

I'm assuming in Screenshot 4 that the layers in the data coverage should match whats added in the layer list. Its preferable to not repeat bunches of text, otherwise it'll become more of a text document than a map.. hard task to accomplish. The combined coverage bar of what you see is interesting though. 

Thanks for sharing these! Sorry I dont have more to offer at the moment.

**Comment by rboller** [comment]
@tgunnoe thanks for sharing your thoughts - agreed that there are lots of new challenges and ideas here and I think we're moving in a good direction.

To add one more idea to this ticket, we discussed today what we should do with the default "availability bar" visible from within the timeline.  While not slated for the first release of the new design, something for us to consider is what that bar should show.

One idea is that it can show a single "unified availability bar" which shows the bar as "active" for dates where any currently-enabled layer has imagery.  It could then be "inactive" wherever no imagery is available for all enabled layers.  The goal is for the user to know at a glance when they should be seeing something on the map.

This is potentially complementary to the "show matching coverage on timeline" checkbox and would need to be designed to work together.
