### ISSUE TITLE
Unable to create a gif after clicking on certain events

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1503]
**Describe the bug**
Can't create GIF after selecting certain events. Uncaught error reads `Uncaught Error: no such layer in cache: Reference_Labels:geographic:2018-11-10T00:00:00Z::active`

**To Reproduce**
1. Go to fresh UAT page
2. Click on events tab and select Woolsey Fire
3. Try to create/download a GIF
4. See error.

**Screenshots**
Development localhost error shown:
![image](https://user-images.githubusercontent.com/24417194/48516376-37ae2000-e831-11e8-9cbe-90fa1c17d310.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 70.0.3538.77

**Comment by ZachTRice** [comment]
Reverting the changes in https://github.com/nasa-gibs/worldview/commit/6acd896b9adedf76374818b825a3ec2cad7b798b seems to fix the issue. Looks like this commit is also the cause of #1449 

@mike-mcgann can you take a look at this one?

**Comment by mike-mcgann** [comment]
I didn't see any issue with #1449. Is that still a problem?

**Comment by ZachTRice** [comment]
Yeah, I hadn't seen it again until I was looking at #1503. I can make it happen by doing the following:
1. Go to fresh UAT page
2. Click on events tab and select Woolsey Fire
3. Click Snapshot tool -> (For me a 0 x 0 px shows for the selection window)
4. Expand the snapshot selection window out
5. Click off the selection window.
Selection window disappears and only the coordinates are left. You cannot reinitiate the selection window. Console shows `Cannot read property 'setExtent' of null` error

**Comment by mike-mcgann** [comment]
Does it work with the submitted fix?

**Comment by ZachTRice** [comment]
Yes, just finished checking #1504 and the issue is now resolved there. The snapshot window appears at 200px x 200px and no errors when clicking off.
