### ISSUE TITLE
Map disappears when navigating with tablet pen in Firefox

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1517]
User support ticket #90397: 
Map position and zoom uncontrollable in Firefox 63.0.3 (64-bit) especially with Wacom Intuos tablet pen and / or mouse. World view shrinks to small patch, then moves off-screen so that it cannot be seen. No amount of mouse movement, left right clicking or mouse wheel scrolling seems able to bring it back on-screen.

****
Follow up: 
Windows 10 Pro (64-bit) Version 10.0.17134 Build 17134;  HP z840 workstation, NVIDIA Quadro M4000 GPU display board.

The world map shrunk leaving a black background with the layers  selection pane on the left and nav /zoom controls on the left. The  layers control seemed to work in that I could add layers to the stack - just couldn't see them because the map shrunk and moved off screen.  Any motion of the mouse pointer when a button was not pressed caused the map to move, expand and or contract, but I could not "fix" the size or position with any UI or mouse button action.  The zoom (mouse wheel) indicated it was working somewhat as the scale would run between 100-500 km, but then it also would as I moved the pointer around the screen (as this would cause both zooming and panning of the map in an uncontrollable manner).

NOTE: It worked fine on the same set-up with the latest version of Chrome browser.

**Comment by edplato** [comment]
I can't reproduce this particular issue where the map gets lost. However, there are multiple Firefox browser specific issues with the Wacom Intuos tablet that I tested on. For example, dragging the guitarpick with a pen works with Chrome but not Firefox. When comparing the Chrome pen `pointerdown` event to Firefox for the guitarpick, Chrome registers the pen as a `e.pointerType === 'pen'` while Firefox registers it as a `e.pointerType === 'touch'`. This causes nonworking UI elements for Firefox tablet pen in a few areas like guitarpick(s), image download area (also Chrome - maybe jcrop related), compare slider, and possibly others.
