### ISSUE TITLE
Vector layer ordering is incorrect in image snapshot

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1546]
When taking a snapshot of the fires and labels here:
https://go.nasa.gov/2KBKoiY

the resulting layer order is incorrect.  I.e., the fires are on top of the labels even though they're underneath in the app.

**Comment by rboller** [comment]
![image](https://user-images.githubusercontent.com/7243823/50188437-afb7ac00-02ef-11e9-8284-9d5ab30f3133.png)

[Sample image snapshot link](https://gibs.earthdata.nasa.gov/image-download?TIME=2018313&extent=-119.4987869129039,33.72756863367253,-118.5595626163545,34.43259047067106&epsg=4326&layers=MODIS_Terra_CorrectedReflectance_TrueColor,Coastlines,Reference_Features,MODIS_Fires_Aqua,Reference_Labels&opacities=1,1,1,1,1&worldfile=false&format=image/jpeg&width=855&height=642)

**Comment by mike-mcgann** [comment]
I'm in this code already, I'll take a look.

**Comment by mike-mcgann** [comment]
Check the SIT version with WVS SIT. Looks like it works with the replacement.
