### ISSUE TITLE
Coordinate labels in image download box should be unselectable

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#1547]
The coordinate labels in the image download box can be selected with the mouse. This can cause problems as it is then possible to select all the text in the timeline which is then difficult to remove. 

![selection](https://user-images.githubusercontent.com/3263862/50222055-0c08e300-0365-11e9-8755-01fc36114607.png)

**Comment by minniewong** [comment]
I also have this problem in the layer list - I can select the text and it's hard to get rid of it.

**Comment by minniewong** [comment]
@mike-mcgann - look at noselect class that was recently added
