### ISSUE TITLE
normalize range inputs

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1548]
- [ ] Normalize the `range inputs` to all use `nouislider`  get rid of `react-input-range`
- [ ] Update style of `nouislider` to look better

**Comment by Benjaki2** [comment]
Some options for styling in order of personal preference: 

1. <img width="280" alt="screen shot 2018-12-19 at 8 45 11 pm" src="https://user-images.githubusercontent.com/3605988/50258755-08aa4180-03cf-11e9-98fd-3570786e9b61.png">
2. <img width="283" alt="screen shot 2018-12-19 at 8 34 58 pm" src="https://user-images.githubusercontent.com/3605988/50258747-01833380-03cf-11e9-954c-fd1d2bc2bcd5.png">
3. <img width="293" alt="screen shot 2018-12-19 at 8 42 05 pm" src="https://user-images.githubusercontent.com/3605988/50258763-0ea02280-03cf-11e9-8edd-9490a045c073.png">
4. <img width="291" alt="screen shot 2018-12-19 at 8 39 56 pm" src="https://user-images.githubusercontent.com/3605988/50258758-0b0c9b80-03cf-11e9-935f-b19b0b558747.png">

**Comment by ZachTRice** [comment]
I like #1 and #3. Though, #1 is probably most consistent with other elements (i.e. swipe dragger) so that one wins out for me.

**Comment by mike-mcgann** [comment]
1️⃣

**Comment by Benjaki2** [comment]
`#1` wins 💪

**Comment by Benjaki2** [comment]
Update: 
Decided to use another library that is a react library that is react out-of-the-box and works well.

New default styles:
<img width="277" alt="screen shot 2019-01-08 at 11 39 15 am" src="https://user-images.githubusercontent.com/3605988/50845242-65e44380-133a-11e9-87fd-c2956759cba1.png">

**Comment by mike-mcgann** [comment]
👍
