### ISSUE TITLE
Error adding layers - cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1559]
**Describe the bug**
Breaking error trying to add a layer in develop.

**To Reproduce**
1. Go to develop branch
2. Click on Add Layers
3. Add Aerosol Index

**Screenshots**
Initial console error on trying to add layer:
![image](https://user-images.githubusercontent.com/24417194/50519969-86cfad80-0a8b-11e9-9a38-19778080b0ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 71

**Comment by minniewong** [comment]
I also just noticed this too in develop.
