### ISSUE TITLE
Events that cross the dateline cross the entire map, from east to west

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1568]
**Describe the bug**
Tropical Cyclone Mona currently crosses the dateline on 2019-01-06. Instead of wrapping around, the event track crosses the entire map, from east to west.

**To Reproduce**
1. Go to 'Events'
2. Click on 'Tropical Cyclone Mona 2019-01-06'
3. See the event track from 2019-01-05 to 2019-01-06 cross the entire map from east to west.

**Expected behavior**
Would be nice if the event track wrapped around the other way. 

**Screenshots**
<img width="1434" alt="screen shot 2019-01-07 at 5 03 02 pm" src="https://user-images.githubusercontent.com/10747923/50796084-71822c80-129e-11e9-8368-595f6b7b465c.png">
<img width="1421" alt="screen shot 2019-01-07 at 5 08 48 pm" src="https://user-images.githubusercontent.com/10747923/50796245-f1a89200-129e-11e9-8941-dbab61c98d50.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by Benjaki2** [comment]
Proposed solution:
<img width="313" alt="screen shot 2019-01-30 at 12 49 18 pm" src="https://user-images.githubusercontent.com/3605988/52001496-8f057900-248d-11e9-8f00-06b4f0bfa65a.png">

Selected date's point will always be between -180 and 180 degrees.
