### ISSUE TITLE
Hover state on timeline's ticks has two separate highlight zones that often arent in sync

### ISSUE THREAD

**Issue by tgunnoe** [nasa-gibs/worldview#1575]
**Describe the bug**
The timeline's hover states for each of the ticks is funky. On the day level, there seems to be two different vertical hover areas for each tick area. You can hover over the top 1/3 of the tick and the hover remains if you move your cursor to the bottom 2/3 of the tick area. On the Month and Year zoom levels, the top area isnt hoverable at all, and no hover indication appears.

**To Reproduce**
1. Start Worldview
2. Hover over the timeline, vary between the top and bottom tick areas over different zoom levels

**Expected behavior**
Hover state should be consistent

**Screenshots**
![screenshot-787c7392](https://user-images.githubusercontent.com/7254833/51070167-af6ab200-160a-11e9-8512-19ec2e87ebff.png)

**Desktop:**
 - OS: Manjaro Linux
 - Browser Firefox Developer Edition
 - Version 65.0b7

**Additional context**
I am a former developer of Worldview =)

**Comment by edplato** [comment]
Can confirm issue in Firefox 64 and Firefox Developer Edition 65. On first look, this issue goes back quite a few Worldview releases, so it must be something recently introduced in Firefox as the issue appears limited to Firefox browsers and 64+ versions. Will try and find underlying problem.

**Comment by tgunnoe** [comment]
Cool, glad it wasn't just me
