### ISSUE TITLE
Unable to create GIF [date.animation.gif.3]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1578]
**Describe the bug**
Unable to create GIF in SIT.

**To Reproduce**
1. Create GIF to dialog where you preview/can download and see error

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/51195814-d0a5f980-18bb-11e9-87b3-dac4625ee24f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 71

**Comment by minniewong** [comment]
Same issue with OSX Chrome

**Comment by Benjaki2** [comment]
➕Firefox OSX
