### ISSUE TITLE
Make layer information and layer settings boxes consistent in font, font size and design

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1585]
Make the two consistent in design:
<img width="1216" alt="screen shot 2019-01-16 at 2 28 11 pm" src="https://user-images.githubusercontent.com/10747923/51273613-27cecb80-199b-11e9-878c-7f5ecd1492bc.png">

Also, when you open layer settings, it fades in from the top; when you open layer description, it fades in from the left/layer list.

**Comment by edplato** [comment]
Handled in Redux enhancements.
