### ISSUE TITLE
MODIS Granule data download boxes are unselectable on ipad [dd.sel.6]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1590]
**Describe the bug**
Unable to select a "+" on the map when displaying a MODIS layer with granule footprint data download on ipad. 

**To Reproduce**
1. Add MODIS Aerosol Optical Depth, Terra
2. Click on the data download tab
3. Try to click on a "+", nothing happens.

**Expected behavior**
You should be able to select a "+" and get a granule footprint outline and selection. 

**Tablet (please complete the following information):**
 - Device: iPad mini 2
 - OS: 12.1.1
 - Browser: Safari

**Comment by edplato** [comment]
Updating test plan to remove test case.

**Comment by minniewong** [comment]
Added a note to test suite to not test this section on tablets.
