### ISSUE TITLE
Issues with swipe and opacity comparison interactions on ipad

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1592]
**Describe the bug**
1. If you have the "You're in comparison mode" notification box on the screen and swipe back and forth on the ipad - the notification box sometimes moves up and down (because you fingers is not swiping back and forth totally horizontally). 
2. The "You're in comparison mode" description box is too wide for portrait view on my ipad, so the edges get cut off. 
3. The opacity slider seems to be less sensitive than the old one and it's harder to be able to "grab" it and slide back and forth.

Tablet (please complete the following information):

Device: iPad mini 2
OS: 12.1.1
Browser: Safari

**Comment by Benjaki2** [comment]
@minniewong 
* What do you think about leaving the notification out with tablets?
* I will work on making the handlers larger
