### ISSUE TITLE
Text is easily selectable when using the threshold and opacity sliders

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1598]
**Describe the bug**
On UAT, in Firefox, it's really easy to select the text of the layer settings box, layer list etc when sliding the threshold and opacity sliders back and forth. 

**To Reproduce**
1. Go to UAT
2. Add Cloud Water Path
3. Slide threshold sliders back and forth
4. See error - surrounding text is selected very easily. 

**Expected behavior**
I'd expect it not to select any of the text. (I don't see this issue in Chrome)

**Screenshots**
<img width="737" alt="screen shot 2019-01-22 at 1 46 24 pm" src="https://user-images.githubusercontent.com/10747923/51557907-25adb680-1e4c-11e9-8f5f-f1e3c7f1838c.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version 60.3.0esr (64-bit)

**Comment by Benjaki2** [comment]
Fix reported here: https://github.com/react-component/slider/issues/491#issuecomment-438673627
