### ISSUE TITLE
Animation playback in annual mode skips dates

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#160]
While trying to do a looping annual animation from 2008 Dec 1 through 2010 Dec 1, the playback skips around unevenly:

http://go.nasa.gov/2lfKJLR

It also changes the default date to be Dec 27 rather than the initial Dec 1.

**Comment by rboller** [comment]
Just tested in the latest v1.4.0 build but still looks to be uneven.

**Comment by minniewong** [comment]
@Benjaki2 - Create a test instance

**Comment by minniewong** [comment]
@Benjaki2  - seems to work as intended!
