### ISSUE TITLE
Selecting custom colormap should stop animation

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1600]
**Describe the bug**
If you are animating through a set of dates and select a new custom colormap for one of the active layers, the animation should stop.

**To Reproduce**
1. Go to https://go.nasa.gov/2FHaH86
2. Change AOD colormap
3. See error (animation continues but imagery is not preloaded)

**Expected behavior**
Animation should stop when new custom colormap is selected.

**Comment by minniewong** [comment]
Closing as it's not so much of a problem in v3.0.0
