### ISSUE TITLE
'daily' flag being added to every layer's config

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#163]
Every wtms layer is being flagged as daily in the config. This needs to be adjusted to give correct period value to each layer.

https://github.com/nasa-gibs/worldview/blob/master/bin/wv-options-wmts#L95-L99

**Comment by rboller** [comment]
Note that the documentation says the available flags for 'period' are 'daily' and 'static':
https://github.com/nasa-gibs/worldview/blob/master/doc/config.md#required-properties

If appropriate, we'll want to update the documentation accordingly.

**Comment by Benjaki2** [comment]
@ryan I am imagining this was published before WV had to worry about monthly and yearly products. Do we want to update these flags?

**Comment by rboller** [comment]
@Benjaki2 I believe we do - I'm assuming that we're talking about the same 'period' flag in both the JSON configs and the WMTS parsing script that you referenced above.  If they are referring to the same thing, then we should update the documentation and configurations, as appropriate.

**Comment by polluxll** [comment]
I want to add my own data on worldview,but the time step is hourly.dose the timeline support the hourly data?

**Comment by Benjaki2** [comment]
@polluxll see issue #108
