### ISSUE TITLE
IE11 and Chrome intermittent loader error

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1633]
**Describe the bug**
On occasion, an error is thrown from the loader being undefined and not appearing. I have only seen this in IE11 and it is not a breaking issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/52724506-7319d100-2f7d-11e9-97af-318b1283cfc9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE11

**Comment by Benjaki2** [comment]
I have seen this happen using` OSX chrome` as well

**Comment by minniewong** [comment]
Fixed!
