### ISSUE TITLE
Consider storing/serving WDPA layer as vector tiles

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1639]
Currently we're using a rasterized version of the WDPA layer which doesn't allow us to change its style. This can be problematic if the WDPA layer is similarly colored as the underlying satellite imagery.

If we stored and served it as vector tiles, it could allow the user to adjust the style as needed.

**Comment by olsinao** [comment]
I understand you guys have a lot on your plate, but if you already have some processes that generate vector tiles, I would be happy to use that code, tweak it to process WDPA and check it back to your system. Either FIRMS or you could host the final tile imagery.

**Comment by rboller** [comment]
Hey @olsinao, that all sounds great here.  I'll start a new thread for us to discuss options.

**Comment by minniewong** [comment]
working this offline with @olsinao
