### ISSUE TITLE
New and Updated SMAP Products

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#164]
The following SMAP products have been added to GIBS.  They are "Enhanced" versions of the ones that we have and point to the same CMR data product.  The title has "Passive Enhanced" instead of just "Passive".  Additionally, if there is an AM/PM designation, that comes after "Passive Enhanced" in the comma-delimited parenthetical. 

SMAP_L1_Passive_Enhanced_Brightness_Temp_Fore_H
SMAP_L1_Passive_Enhanced_Brightness_Temp_Aft_H
SMAP_L1_Passive_Enhanced_Brightness_Temp_Fore_V
SMAP_L1_Passive_Enhanced_Brightness_Temp_Aft_V
SMAP_L1_Passive_Enhanced_Brightness_Temp_Fore_H_RFI
SMAP_L1_Passive_Enhanced_Brightness_Temp_Aft_H_RFI
SMAP_L1_Passive_Enhanced_Brightness_Temp_Fore_V_RFI
SMAP_L1_Passive_Enhanced_Brightness_Temp_Aft_V_RFI
SMAP_L1_Passive_Enhanced_Brightness_Temp_Fore_H_QA
SMAP_L1_Passive_Enhanced_Brightness_Temp_Aft_H_QA
SMAP_L1_Passive_Enhanced_Brightness_Temp_Fore_V_QA
SMAP_L1_Passive_Enhanced_Brightness_Temp_Aft_V_QA
SMAP_L2_Passive_Enhanced_AM_Soil_Moisture_Option1
SMAP_L2_Passive_Enhanced_AM_Soil_Moisture_Option2
SMAP_L2_Passive_Enhanced_AM_Soil_Moisture_Option3
SMAP_L2_Passive_Enhanced_PM_Soil_Moisture_Option1
SMAP_L2_Passive_Enhanced_PM_Soil_Moisture_Option2
SMAP_L2_Passive_Enhanced_PM_Soil_Moisture_Option3
SMAP_L3_Passive_Enhanced_AM_Soil_Moisture
SMAP_L3_Passive_Enhanced_PM_Soil_Moisture

Note that you currently have SMAP_L2_Passive_Soil_Moisture_Option[1-3] and SMAP_L3_Passive_Soil_Moisture layers. Those go away in lieu of the following layers that have the AM/PM designation.  Same thing goes for putting AM/PM in the title.

SMAP_L3_Passive_AM_Soil_Moisture
SMAP_L3_Passive_PM_Soil_Moisture
SMAP_L2_Passive_AM_Soil_Moisture_Option1
SMAP_L2_Passive_AM_Soil_Moisture_Option2
SMAP_L2_Passive_AM_Soil_Moisture_Option3
SMAP_L2_Passive_PM_Soil_Moisture_Option1
SMAP_L2_Passive_PM_Soil_Moisture_Option2
SMAP_L2_Passive_PM_Soil_Moisture_Option3

**Comment by Benjaki2** [comment]
Waiting for Freeze/Thaw

**Comment by minniewong** [comment]
Contact NSIDC and ask whether we can change AM/PM to Day/Night

**Comment by rboller** [comment]
NSIDC is supportive of the rename to Day/Night.  This ticket is now blocked by the rename in GIBS-2088.
