### ISSUE TITLE
Optimize tour thumbnail image file sizes

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1646]
**Is your feature request related to a problem? Please describe.**
Some tour thumbnail images are large in file size. Optimizing those images would help save total file request size on page load. After finding a decent file size/resolution compromise, it may be worth documenting a maximum allowable file size for future tour thumbnails made by the team/external partners.

**Comment by ZachTRice** [comment]
Good catch! The standard size should be 392px x 392px. I'll add documentation and optimize.
