### ISSUE TITLE
Consider separating MODIS fires out into 3 layers: Day, Night and Combined

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1650]
As we now have the MODIS Fires layers available as Day, Night and Combined (All), we should consider whether to split it out into 3 layers (knowing that we should probably maintain the All layer for users who have bookmarked the All layer)

**Comment by minniewong** [comment]
Get rid of combined (all); have day and night layers; redirect from combined adds the two layers, day and night.

**Comment by mcechini** [comment]
Will your approach to this change when the fire layers change to vectors?

**Comment by minniewong** [comment]
we will wait for vectors

**Comment by minniewong** [comment]
I think we should re-open this issue if fire vectors might take more time. We have a user would would like to be able to turn on the day and night fires for MODIS separately.
