### ISSUE TITLE
Send Feedback on mobile does not bring up email

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1673]
**Describe the bug**
When you are on a mobile phone or resize the browser window to mobile size, the "Send Feedback" button no longer opens the email client.

**To Reproduce**
1. Using a mobile phone or resize the browser window to mobile size and go to Worldview.
2. Click on "Send Feedback" under the "i"
3. See error/nothing happens - It should open your email client and start an email to support@earthdata.nasa.gov with a subject "Feedback for EOSDIS Worldview tool"

**Expected behavior**
When you click on "Send Feedback" in the mobile mode, it should open your email client and start an email that is addressed to support@earthdata.nasa.gov with a subject "Feedback for EOSDIS Worldview tool"

**Comment by ZachTRice** [comment]
Fixed in v2.14.1
