### ISSUE TITLE
New Daymet Layers

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#168]
We've added the following layers to GIBS, now ready for Worldview:

Layer Identifier | Title | Subtitle | CMR Product
------------ | ------------- | ------------- | -------------
Daymet_Maximum_Air_Temp_Daily | Maximum Air Temperature (Daily) | (Daymet) | C1286838487-ORNL_DAAC
Daymet_Minimum_Air_Temp_Daily | Minimum Air Temperature (Daily) | (Daymet) | C1286838487-ORNL_DAAC

**Comment by mcechini** [comment]
Yeah, waiting on Alex to deploy and rebuild the GCs

**Comment by rboller** [comment]
In production as of now

**Comment by minniewong** [comment]
will release when other layers (e.g. SMAP) are ready to go
