### ISSUE TITLE
Update build to use Python3

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1682]
**Is your feature request related to a problem? Please describe.**
python2 support drops Jan 2020; let's upgrade to python3 before that time.

**Describe the solution you'd like**
Replace python2 with python3

**Describe alternatives you've considered**
Don't upgrade it?

**Additional context**
We don't have a lot of python so this should be doable if someone can find time to do it.

**Comment by Benjaki2** [comment]
Notes on dependenices:
`wsgiref` is included as python 3 core.
All others have python 3 support
(`isodate, six, urllib3, xmltodict `)
