### ISSUE TITLE
Add data download handler for Daymet layers

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#169]
The product short name for the Daymet layers is: doi:10.3334/ORNLDAAC/1328

The relevant imagery layers are: Daymet_Minimum_Air_Temp_Daily and Daymet_Maximum_Air_Temp_Daily

The product metadata/CMR record  includes all the available parameters and for different geographical regions (North America, Hawaii and Puerto Rico) and are grouped by year even though the data are daily - this cannot be currently displayed in Worldview Data download with existing handlers. Need to come up with a new handler to display the information, by parameter and perhaps by geographical region too.

**Comment by rboller** [comment]
Added to [roadmap](https://github.com/nasa-gibs/worldview/projects/7) if we decide to overhaul data download.
