### ISSUE TITLE
Taking image snapshot that includes a layer with no coverage shows service exception text

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1706]
**Describe the bug**
Taking image snapshot that includes a layer with no coverage shows service exception text

**To Reproduce**
1. Go to [https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,OrbitTracks_OCO-2_Ascending,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2019-03-20-T00%3A00%3A00Z&z=3&v=-84.31421641147047,-59.57648844452113,75.24650439144925,52.919559315810744&ab=off&as=2019-02-28T00%3A00%3A00Z&ae=2019-04-01T00%3A00%3A00Z&av=3&al=true](https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,OrbitTracks_OCO-2_Ascending,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2019-03-20-T00%3A00%3A00Z&z=3&v=-84.31421641147047,-59.57648844452113,75.24650439144925,52.919559315810744&ab=off&as=2019-02-28T00%3A00%3A00Z&ae=2019-04-01T00%3A00%3A00Z&av=3&al=true)
2. Take snapshot image and note text included

**Expected behavior**
Layer with no coverage should be transparent.

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/57239425-ddc92e80-6ff9-11e9-8393-61a9ecf94b5b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Related to #1707

**Comment by minniewong** [comment]
Looks like this ticket is fixed, but related ticket #1707 still throws an error.
