### ISSUE TITLE
Optimize client for vector capabilities

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1711]
**Description**
Using OL6 + 10k+ vector points, slows the application to an unacceptable level. Optimization to the client (via mainly Openlayers 6 features) needs to occur before some of these larger data sets can be accomodated.

**Suggestions**
- [x] Investigate decimating on server-side
  - We have optimized the server-side to an acceptable level of decimation where we aren't loosing visual value.
- [x] Investigate client-side decimation
  - Result: Not a viable option for most/all visualization products.
- [x] Investigate using supercluster mapbox package for clustering at higher zoom levels
  - This can be a viable option but only at higher zoom level
  - Initial tests showed a conflict between inspecting metadata and using supercluster
- [x] Investigate incorporating webGL rendering instead of canvas
  - Issue thus far is there is not good documentation on using webGL with vectorTile/TileGrid & MVT w/ URL + mapbox Styles.
- [x] Evaluate performance of multiple layers added to the map in ol 6
- [x] Evaluate using rasters at low zoom levels and vectors at higher zoom levels using FIRMS data.

**Comment by ZachTRice** [comment]
@mcechini @rboller - webGL does not support selecting vector features; i.e. we wouldn't be able to click and inspect the data.. See this issue (it's not documented): https://github.com/openlayers/openlayers/issues/9501

**Comment by ZachTRice** [comment]
Also related to this ticket (performance): "Ol 6 beta performance problem with multiple layers" https://github.com/openlayers/openlayers/issues/9457 

I mentioned this in our brown bag. Layers are now rendered on separate canvases and this could reduce performance. I have added a task in this ticket to evaluate multiple layer performance.

**Comment by rboller** [comment]
@ZachTRice that's good to know... we'll need to be able to select vector features so perhaps WebGL isn't the approach we should take unless it gets addressed in OL.

**Comment by mcechini** [comment]
Hmmm, ok.  Sounds like WebGL may not be the silver bullet we were hoping for.  But then again OL6 doesn't sound like it's all that great either.

**Comment by ahocevar** [comment]
The performance issue with multiple vector layers will be fixed with openlayers/openlayers#9584.

**Comment by ZachTRice** [comment]
Great, thanks for the update @ahocevar

**Comment by jahow** [comment]
Hi! dropping by to let you know webgl layers in OL now support hit detection, with the limitation that only the topmost features can be detected for now. See: https://github.com/openlayers/openlayers/pull/9655
