### ISSUE TITLE
Improve default animation range for sub-daily layers

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#1735]
When the animation panel is first loaded and sub-daily layers are present, the default animation range could be more helpfully defined to show the most recent ~three hours... e.g., if the current time is 0950z, set the start time to 0650z and end time to 0950z. 

For sub-daily/geostationary layers, this would be more helpful than the current default behavior of selecting the most recent 7 days.

**Comment by jasontk19** [comment]
Related to #1941
