### ISSUE TITLE
Transition AIRS L3 layer identifiers

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#1738]
Transition the existing AIRS L3 layers to new identifiers:

Current Identifier | New Identifier
-- | --
AIRS_All_Sky_Outgoing_Longwave_Radiation_Daily_Day | AIRS_L3_All_Sky_Outgoing_Longwave_Radiation_Daily_Day
AIRS_All_Sky_Outgoing_Longwave_Radiation_Daily_Night | AIRS_L3_All_Sky_Outgoing_Longwave_Radiation_Daily_Night
AIRS_All_Sky_Outgoing_Longwave_Radiation_Monthly_Day | AIRS_L3_All_Sky_Outgoing_Longwave_Radiation_Monthly_Day
AIRS_All_Sky_Outgoing_Longwave_Radiation_Monthly_Night | AIRS_L3_All_Sky_Outgoing_Longwave_Radiation_Monthly_Night
AIRS_Methane_Volume_Mixing_Ratio_Daily_Day | AIRS_L3_Methane_400hPa_Volume_Mixing_Ratio_Daily_Day
AIRS_Methane_Volume_Mixing_Ratio_Daily_Night | AIRS_L3_Methane_400hPa_Volume_Mixing_Ratio_Daily_Night
AIRS_Methane_Volume_Mixing_Ratio_Monthly_Day | AIRS_L3_Methane_400hPa_Volume_Mixing_Ratio_Monthly_Day
AIRS_Methane_Volume_Mixing_Ratio_Monthly_Night | AIRS_L3_Methane_400hPa_Volume_Mixing_Ratio_Monthly_Night
AIRS_Carbon_Monoxide_Volume_Mixing_Ratio_Daily_Day | AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Daily_Day
AIRS_Carbon_Monoxide_Volume_Mixing_Ratio_Daily_Night | AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Daily_Night
AIRS_Carbon_Monoxide_Volume_Mixing_Ratio_Monthly_Day | AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Monthly_Day
AIRS_Carbon_Monoxide_Volume_Mixing_Ratio_Monthly_Night | AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Monthly_Night
AIRS_Surface_Relative_Humidity_Daily_Day | AIRS_L3_Surface_Relative_Humidity_Daily_Day
AIRS_Surface_Relative_Humidity_Daily_Night | AIRS_L3_Surface_Relative_Humidity_Daily_Night
AIRS_Surface_Relative_Humidity_Monthly_Day | AIRS_L3_Surface_Relative_Humidity_Monthly_Day
AIRS_Surface_Relative_Humidity_Monthly_Night | AIRS_L3_Surface_Relative_Humidity_Monthly_Night
AIRS_Surface_Air_Temperature_Daily_Day | AIRS_L3_Surface_Air_Temperature_Daily_Day
AIRS_Surface_Air_Temperature_Daily_Night | AIRS_L3_Surface_Air_Temperature_Daily_Night
AIRS_Surface_Air_Temperature_Monthly_Day | AIRS_L3_Surface_Air_Temperature_Monthly_Day
AIRS_Surface_Air_Temperature_Monthly_Night | AIRS_L3_Surface_Air_Temperature_Monthly_Night
AIRS_Surface_Skin_Temperature_Daily_Day | AIRS_L3_Surface_Skin_Temperature_Daily_Day
AIRS_Surface_Skin_Temperature_Daily_Night | AIRS_L3_Surface_Skin_Temperature_Daily_Night
AIRS_Surface_Skin_Temperature_Monthly_Day | AIRS_L3_Surface_Skin_Temperature_Monthly_Day
AIRS_Surface_Skin_Temperature_Monthly_Night | AIRS_L3_Surface_Skin_Temperature_Monthly_Night
AIRS_Clear_Sky_Outgoing_Longwave_Radiation_Daily_Day | AIRS_L3_Clear_Sky_Outgoing_Longwave_Radiation_Daily_Day
AIRS_Clear_Sky_Outgoing_Longwave_Radiation_Daily_Night | AIRS_L3_Clear_Sky_Outgoing_Longwave_Radiation_Daily_Night
AIRS_Clear_Sky_Outgoing_Longwave_Radiation_Monthly_Day | AIRS_L3_Clear_Sky_Outgoing_Longwave_Radiation_Monthly_Day
AIRS_Clear_Sky_Outgoing_Longwave_Radiation_Monthly_Night | AIRS_L3_Clear_Sky_Outgoing_Longwave_Radiation_Monthly_Night
AIRS_Carbon_Dioxide_AIRS_AMSU_Monthly | AIRS_L3_Carbon_Dioxide_AIRS_AMSU_Monthly
AIRS_Carbon_Dioxide_IR_Monthly | AIRS_L3_Carbon_Dioxide_IR_Monthly

**Comment by minniewong** [comment]
30 changes; 1 addition (AIRS_L3_Carbon_Dioxide_IR_Monthly)
