### ISSUE TITLE
Add AIRS L2 NRT (26 layers)

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#1741]
ICD for AIRS L2 NRT: [Lines 33-38;43-62](https://docs.google.com/spreadsheets/d/115meLuA976ASmcGHKROJKNQJGeQS_oqPlF9fwfBisbM/edit#gid=0)

**Comment by minniewong** [comment]
@jejeking Do these replace any of the existing layers?

**Comment by jejeking** [comment]
No. All of those are new.

**Comment by mcechini** [comment]
Note that we will need to make sure the STD imagery (at least going back as far as the existing NRT) is processed and available in the Best endpoint before making the switch. Otherwise you'll lose the history.  Or you can move forward if ok with losing the history.

**Comment by minniewong** [comment]
@mcechini - let us know what the timeline is for that work, and we can make sure to switch after the STD imagery is processed and available in the BEST endpoint.

**Comment by mcechini** [comment]
I'll be sending out STD imagery for review in UAT to JPL/GESDISC today.  I'm optimistic that I'll get the geographic STD historical in place before your June release... so that this is a moot point.  Stay tuned...

**Comment by mcechini** [comment]
New Layer | Replaced Layer
------------ | -------------
AIRS_L2_Methane_400hPa_Volume_Mixing_Ratio_Day | N/A
AIRS_L2_Methane_400hPa_Volume_Mixing_Ratio_Night | N/A
AIRS_L2_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Day | N/A
AIRS_L2_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Night | N/A
AIRS_L2_Cloud_Top_Height_Day | N/A
AIRS_L2_Cloud_Top_Height_Night | N/A
AIRS_L2_Dust_Score_Day | AIRS_Dust_Score_Ocean_Day
AIRS_L2_Dust_Score_Night | AIRS_Dust_Score_Ocean_Night
AIRS_L2_RelativeHumidity_500hPa_Day | AIRS_RelativeHumidity_500hPa_Day
AIRS_L2_RelativeHumidity_500hPa_Night | AIRS_RelativeHumidity_500hPa_Night
AIRS_L2_RelativeHumidity_700hPa_Day | AIRS_RelativeHumidity_700hPa_Day
AIRS_L2_RelativeHumidity_700hPa_Night | AIRS_RelativeHumidity_700hPa_Night
AIRS_L2_RelativeHumidity_850hPa_Day | AIRS_RelativeHumidity_850hPa_Day
AIRS_L2_RelativeHumidity_850hPa_Night | AIRS_RelativeHumidity_850hPa_Night
AIRS_L2_Surface_Relative_Humidity_Day | N/A
AIRS_L2_Surface_Relative_Humidity_Night | N/A
AIRS_L2_Surface_Air_Temperature_Day | N/A
AIRS_L2_Surface_Air_Temperature_Night | N/A
AIRS_L2_Sulfur_Dioxide_Brightness_Temperature_Difference_Day | N/A
AIRS_L2_Sulfur_Dioxide_Brightness_Temperature_Difference_Night | N/A
AIRS_L2_Surface_Skin_Temperature_Day | N/A
AIRS_L2_Surface_Skin_Temperature_Night | N/A
AIRS_L2_Temperature_500hPa_Day | AIRS_Temperature_500hPa_Day
AIRS_L2_Temperature_500hPa_Night | AIRS_Temperature_500hPa_Night
AIRS_L2_Temperature_700hPa_Day | AIRS_Temperature_700hPa_Day
AIRS_L2_Temperature_700hPa_Night | AIRS_Temperature_700hPa_Night
AIRS_L2_Temperature_850hPa_Day | AIRS_Temperature_850hPa_Day
AIRS_L2_Temperature_850hPa_Night | AIRS_Temperature_850hPa_Night
AIRS_L2_Total_Cloud_Fraction_Day | 
AIRS_L2_Total_Cloud_Fraction_Night |

**Comment by minniewong** [comment]
awaiting descriptions
