### ISSUE TITLE
v3.0.0 Bugs To Fix / Task To Complete

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1755]
**Pre-Develop Bugs / Tasks To Do**
- [x] Cursor does not default to search input when opening Add Layers modal @Benjaki2 
- [x] Palettes / Opacity breaks in layer settings @Benjaki2 
- [x] Layers sometimes do not get updated in the URL (changing opacity forces update) @Benjaki2 
- [x] Timeline breaks when `custom` is selected from animation widget tooltip @edplato 
- [x] Modals do not get destroyed when in mobile
  Possible solution: Pass prop to Modal container to make modal show on desktop only (and an option for showing on mobile only?) @Benjaki2 
- [x] Gesture two finger horizontal touch pad scroll on timeline axis @edplato 
- [x] Timeline axis bounds jumpy on certain position updates @edplato 
- [x] Left/right arrows don't update date on hold keypress/mousedown @edplato 
- [x] Animation widget randomly keeps playing on press pause and/or close modal @Benjaki2 
- [x] Need global `pageLoadTime` and `now` params based on page load time and frequent (10 minutes?) updates to address to re-rendering issues with using Date.now() for comparisons @edplato 
- [x] Start Comparison button is still visible on mobile @Benjaki2 
- [x] Measurement row breaks when selecting orbit tracks @ZachTRice
- [x] If a layer has a palette applied, and then you open comparison, mode, the l1 state does not get updated (see comment below) @Benjaki2 
- [x] Animation retained in permalink when not open @Benjaki2 
- [x] Animation start and end dates are always initiated at start date @Benjaki2 
- [x] When you mouse-zoom on the timeline it does not zoom the location of the mouse @edplato 
- [x] Prevent animation, compare, and data download in mobile @Benjaki2 
- [x] Compare alert not showing up @Benjaki2 
- [x] Event track is not showing up @Benjaki2 
- [x] Event date list is not showing up in sidebar @Benjaki2 
- [x] Event and data-download map rendering does not update on proj change
- [x] v1.0.5 of `run-script-os` does not properly detect Windows machines. This leads to `npm install python` running the linux command on Windows. -- Fix is upgrading to v1.0.7 / creating new package-lock.json @ZachTRice
- [x] Update dependencies that depend on autoprefixer to try to curtail browserlist build warnings (i.e. autoprefixer removed, stylefmt removed, stylint updated, postcss-preset-env updated) @ZachTRice
- [x] Add browserlist key to package.json and change webpack browsers key to browserlist to curtail build warnings @ZachTRice
- [x] Bump minimum node version from `8.8.1` to `8.15.1` due to `stylelint` upgrade @ZachTRice
- [x] `babel-preset-es2015": "^6.24.1",` and `babel-preset-stage-0` was introduced even though we are current;y using `babel-preset-env` - Remove these dependencies @ZachTRice 
- [x] Update critical dependencies for v3.0.0 @ZachTRice
- [x] Update Windows test using `run-script-os` to circumvent TZ issues on Windows machines @ZachTRice 
- [x] Remove `stylefmt`, `stylelint`'s --fix command in v7.1.1+ replaces it's functionality (see: https://github.com/morishitter/stylefmt#notice-consider-other-tools-before-adopting-stylefmt) @ZachTRice
- [x] Upgrade to babel 7 @ZachTRice
- [x] Upgrade babel dependencies and configurations @ZachTRice
- [x] Upgrade jest to latest (which uses babel 7+) @ZachTRice
- [x] Change `.babelrc` to `babel.config.js` @ZachTRice
- [x] Remove unused devDependencies @ZachTRice

Remaining:
Critical Bugs:
- [x] GIF and Image download rotation and custom colormap modal not implemented @Benjaki2 
- [x] A|B Timeline tabs do not show in Comparison mode @edplato 
- [x] When loading the app with the B Sidebar Tab selected, applying B-side layer modifications, applies those modifications to the A-side layers   
(see: http://localhost:3000/?v=-1.7407784151547503,-72.8038111575179,202.27202841515475,79.2725611575179&t=2019-06-24-T06%3A02%3A03Z&t1=2019-06-19-T06%3A02%3A03Z&l=MODIS_Combined_Value_Added_AOD(palette=blue_5),Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&l1=MODIS_Combined_Value_Added_AOD(palette=blue_5),Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&ca=false)   
Change color or remove layers in b-side, flip to a-side to see the changes applied there.
@Benjaki2 

Minor Bugs / Cleanup:
- [x] Fix timeline webpack warnings (seen in node console & browser console when running `npm run watch`) @Benjaki2 
- [x] Cleanup  **overdefined** `propTypes` in files. (Some files are defining propTypes for variables that are not in the file. @ZachTRice  , @edplato 
- [x] Version / release custom dependencies (i.e. gifStream) @Benjaki2 
- [x] Remove custom configs / layers from timeline work @edplato 
- [x] Remove custom configs / layers from vector work @ZachTRice

Bonus tasks
- Update (or removed unused) dependencies / devDependencies
- Investigate snapshots not downloading monthly layers (WVS-303, make a ticket if WV issues found)

Minor bugs for v3.1 followup
- Adding `GOES-West_ABI_Band13_Clean_Infrared_v0_NRT` causes an issue where it is not updating on time change - this subdaily layer uses `wrapX` so may be related

**Comment by ZachTRice** [comment]
@Benjaki2, @edplato 

Lets edit the above comment with new bugs / tasks.
We will mark our name beside any bugs we are working on / want to fix.

**Comment by Benjaki2** [comment]
I like the modal prop (eg: `desktopOnly: true`) idea. 👍

**Comment by ZachTRice** [comment]
For the issue: "If a layer has a palette applied, and then you open comparison, mode, the l1 state does not get updated"

Here is an example:
https://uat.gibs.earthdata.nasa.gov/worldview-dev/redux-timeline-6_20-11-15am/worldview/?v=-98.6261506136606,-48.77826507470651,52.25832110458913,50.78423492529349&l=MODIS_Water_Mask(palette=red),MODIS_Terra_CorrectedReflectance_TrueColor

Open console and Click 'Start Comparision'
Observe error and URL not updating
