### ISSUE TITLE
Running data issue for Orbit Tracks

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#180]
The hover over text only seems to appear for the orbit track layer on top if you have both Day and Night displayed in the layer picker. The hover text appears for that top layer even if your mouse is over the bottom orbit track layer. 
https://uat.gibs.earthdata.nasa.gov/worldview-dev/v1.4.0/release/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,Aqua_Orbit_Dsc(hidden),Aqua_Orbit_Asc(hidden),Terra_Orbit_Asc,Terra_Orbit_Dsc,MODIS_Fires_Aqua,MODIS_Fires_Terra,MODIS_Fires_All,VIIRS_SNPP_Fires_375m_Night,VIIRS_SNPP_Fires_375m_Day,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2017-03-03&z=3&v=-138.6858143071329,-3.210989377631689,-78.74440805713289,26.21479187236831

**Comment by minniewong** [comment]
Might be due to palette ID being the same for Ascending and Descending tracks. @rboller - should we give each orbit track their unique ID?

**Comment by rboller** [comment]
I'm having a tough time getting the hover-over to work at all for the orbit tracks... or fires for that matter.  

If it fixes the problem to make the orbit track palette IDs unique, please do go ahead and make the change.

**Comment by Benjaki2** [comment]
@rboller I don't know what was going on with the orbit-track hover. I redeployed and it appears to be working. (Note: the issue with unique ID's is still a problem and should be fixed by supplying unique palette IDs.)

**Comment by minniewong** [comment]
created pull request #50
