### ISSUE TITLE
Disable sidebar settings / descriptions on mobile

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1807]
**Describe the bug**
When clicking the layer settings, the modal is offset and not clickable on mobile. 
*Note, the layer description modal works as expected,

**To Reproduce**
1. Go to sidebar layer
2. Click on layer settings
3. Observe offset modal

**Expected behavior**
Full-width. The same as the layer description modal

**Screenshots**
![Screenshot_4](https://user-images.githubusercontent.com/17348884/60906062-4cb64400-a244-11e9-8355-c1a9acd8749f.png)

**Comment by Benjaki2** [comment]
Should `settings` and `info` be disabled in mobile? Looks like they are disabled on Prod.

**Comment by ZachTRice** [comment]
We will revert for now but I'll create another ticket for us to investigate adding this functionality in the future.
