### ISSUE TITLE
Animation seems to hang when you change the end date to yesterday

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1811]
**Describe the bug**
Animation seems to hang (with a "preloading imagery" message) when you open the animation panel, change the end date to yesterday then press play. It starts the animation but stops on July 7 and hangs there with a "preloading imagery' message. It should animate to July 8. This still seems to occur even if you scroll through the days using the timeline to preload/cache the imagery in Worldview. If you cancel out of the "preloading imagery" message, and try to download the animated GIF, while it states that it's producing an animated GIF for 
Start Date: 2019-07-02T17:02:34.364Z
End Date: 2019-07-08T17:02:34.000Z
It only produces an animated GIF that ends on 2019-07-07.

**To Reproduce**
1. Go to SIT
2. Click on the video camera icon
3. Change the end date to yesterday (i.e. July 8)
4. Press play, animation begins
4. See error - animation hangs on July 7 showing a "preloading imagery" message with a spinning wheel. 

**Expected behavior**
The animation should run through without stopping. 

**Screenshots**
![Screen Shot 2019-07-09 at 1 03 05 PM](https://user-images.githubusercontent.com/10747923/60908750-a28dea80-a24a-11e9-8a6c-48ca6df1fadd.png)

**Desktop (please complete the following information):**
 - OS:OSX
 - Browser Firefox
 SIT V3.0

**Comment by edplato** [comment]
I'm not certain on why the animation is hanging, but the image stopping on 2019-07-07 is by the current design since the start date is slightly later in the day than the end date. We handle this in the production version by flooring the times of start and end dates so they're zeroed out the same. I can work on doing this date flooring in the new version #1813 .

**Comment by minniewong** [comment]
it only stops on the 7th if I change the date to the 8th, but if i leave it as "current" day, and play the animation - it doesn't hang and doesn't stop a day early.
