### ISSUE TITLE
Compare mode alert text has non-breaking space (SIT v3.0)

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1826]
**Describe the bug**
Compare mode alert text has non-breaking space (&nbsp).

**To Reproduce**
1. Go to compare mode
2. Note compare mode alert text (may have to clear localStorage to see alert)

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/61059656-5d42f780-a3c7-11e9-8e15-9e74f674010e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome/IE11

**Comment by minniewong** [comment]
Also happens in Firefox in OSX and with the Events mode alert.
