### ISSUE TITLE
Adding three layers then refreshing the page does not reload with the same layers [perm.out.2, perm.out.4, perm.out.5, perm.out.7]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1830]
**Describe the bug**
Using the URL in the test plan, adding three layers and reloading the page does not have the three layers loaded anymore. 

**To Reproduce**
1. Go to SIT /?t=2016-06-15
2. Click on Add Layers, Dust Storms, Add three layers from that category
3. Zoom to an area and refresh page
4. See error - the 3 layers are not reloaded.

**Expected behavior**
The three layers should reload. 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 SIT V3.0

**Comment by ZachTRice** [comment]
I also experienced issues with the layers permalinks while testing mobile via browserstack. In my case, adding layers did not save the layers to the permalink. I checked again on a real device and found the permalink worked there. I had no issues with any other parameter types saving to the URL.
