### ISSUE TITLE
URL parameter time is ignored (SIT v3.0)

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1834]
**Describe the bug**
This may not be necessary if we don't feel the need to support it, but the `time` url parameter is not recognized and ignored. We use `t` for time, however I encountered a test link that uses `time`, so we may want to make sure both work (as in production) for older links that still use `time` instead of `t`.

**Comment by minniewong** [comment]
I also noticed we use `TIME` in Worldview Snapshots but `t` in Worldview - it was confusing one of our users who was trying to hack the URL

**Comment by edplato** [comment]
Related to the `time` parameter, and looking at analytics, here is a query string that works in production but not SIT with some parameters I'm not familiar with:

`/?switch=geographic&products=baselayers,!MODIS_Aqua_CorrectedReflectance_TrueColor,MODIS_Terra_CorrectedReflectance_TrueColor~overlays,sedac_bound&time=2014-04-19&map=-82.889404,44.088867,-78.670654,46.116943`

It appears that changing `time` to `t` makes this query string work in SIT and production. `switch` may need testing to confirm it can handle polar projections.

**Comment by mike-mcgann** [comment]
This is the old permalink format which still needs to be supported
