### ISSUE TITLE
TypeError on clicking event track supercluster and/or points (not consistent) (SIT v3.0)

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1838]
**Describe the bug**
A `TypeError` was thrown in the console when clicking on the super cluster (group of points marked as a number) or certain points on the event track line. Not all points throw this error and this error didn't appear to affect functionality.

**To Reproduce**
1. Go to an iceberg event with a lot of points (enough for a super cluster)
2. Click on super cluster number and a few points until you see console error (shown below)

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/61230421-0192aa00-a6f8-11e9-8b04-4d14d9c46b63.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by minniewong** [comment]
I have noticed this: if you click on a supercluster, then try to click on the individual dots, it doesn't change the date/imagery. (try Iceberg B39 in Antarctic)
