### ISSUE TITLE
Changing color palette sometimes turns off the layer and can't be turned back on again

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#184]
Steps to reproduce (in Chrome):
1. Add AOD
2. Change the threshold, squash palette.
3. Refresh page
4. Repeat (2), this will often disable the layer in the map and sometimes in the layer picker, trying to turn it back on doesn't do anything. 

Is it a caching issue?

**Comment by minniewong** [comment]
In Firefox, clicking on the settings button turns everything off in the map and can't be turned back on again.

**Comment by Benjaki2** [comment]
Related to #154
