### ISSUE TITLE
No Breadcrumb or back button when mobile category is selected [layer.add.9]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1843]
**Describe the bug**
There is no way to return to main 'add layers' selection when a category is selected in mobile

**To Reproduce**
1. Go to home
2. Open layer list  and click add layers
3. Select `Floods` from the category list 

**Expected behavior**
There should be some way to get back to initial add layers selection

**Smartphone (please complete the following information):**
 - Device: iPhoneSE
 - OS: 12
 - Browser: safari

**Additional context**
This issue exists on PRODUCTION

**Comment by jasontk19** [comment]
Fixed.
