### ISSUE TITLE
Emphasize satellite for the orbit track layers in the product picker

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#185]
A user suggested that we add the satellite to the orbit track layer titles, instead of the subtitle, so it's more obvious which satellite the orbit track belongs to.

**Comment by minniewong** [comment]
Consider in new layer picker design

**Comment by localjo** [comment]
Here's an example of the issue: https://go.nasa.gov/2Gj8rkn

<img width="270" alt="screen shot 2018-01-26 at 8 32 50 am" src="https://user-images.githubusercontent.com/516388/35449750-e3644636-028b-11e8-9fb2-f7387a5626b6.png">

<img width="406" alt="screen shot 2018-01-26 at 11 27 53 am" src="https://user-images.githubusercontent.com/516388/35449783-fd831ae2-028b-11e8-974f-de0f000396dc.png">

I think the suggested change is from something like;
```
title: "Orbital Track (Descending/Night)"
subtitle: "Space-Track.org/GOSAT"
```

to something like;

```
title: "GOSAT Orbital Track (Desc./Night)"
subtitle: "Space-Track.org"
```

**Comment by SantiagoGasso** [comment]
I the suggested solution looks good. But still it can be improved  ....

I think the words "Orbital Track" can be omitted (unless are needed in the search). The reason is that it forces the frame to stretch to the right, which takes a lot of real state , particularly when using a laptop. Further , I would eliminate( or include inside the i icon) Night/Day and/or shorten Ascending/Descending for the same reasons. 

Same with the information about Space-track.org , it could go into the information icon.

Santiago

**Comment by minniewong** [comment]
I'd suggest going with:
title: Terra (Descending/Day)
subtitle: Space-Track.org / Orbital Track

I'd prefer not seeing Ascending and Descending shortened as we have it listed like that for other layers, and not removing them entirely from the title because many of the satellites have ascending and descending orbits and it would be hard to distinguish between the two if that information was not in the title.

**Comment by SantiagoGasso** [comment]
title: Terra (Descending/Day)
subtitle: Space-Track.org / Orbital Track

I think this is better than before definitely. 

Regarding shortening the words, I am OK to leave it as it if you think so. But personally, I think the additional value of having it there is minimal. 

Regarding the Day/Night information, I think it is useful for certain satellites but not all. For example, the International Space Station does no have a constant orbit sometime it has sees day time in Descending or Ascending mode, sometimes in both. so, unless you guys have something that will change dynamically depending on the orbit, the information of day/night can be misleading for certain satellites.

**Comment by SantiagoGasso** [comment]
Hey

thanks a bunch , it looks much better and easier to navigate.

S

Santiago Gassó,  Ph: (301)614-6244
Code 613, NASA/GSFC,
Greenbelt, MD 20771
________________________________
