### ISSUE TITLE
Upgrade Facebook (Share) API to v3.2+

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1855]
**Description**
Our current Facebook share link uses API v3.1.
There is an upgrade compatibility checker tool which indicated that v3.2+ has changes to the Share Dialog which would likely affect us. Our current version is v3.1 which is supported until July 28, 2020.

**Comment by Benjaki2** [comment]
Our implementation appears to still be supported without any warnings of being replaced: https://developers.facebook.com/docs/sharing/reference/share-dialog/ 

Closing this for now.
