### ISSUE TITLE
Test instance is slow sometimes in Firefox

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#186]

**Comment by Benjaki2** [comment]
@minniewong In which situations does is it acting slow?

**Comment by minniewong** [comment]
tester says: not sure if you should bring up the issue of speed. It might be the tools I use. I used FF with very restrictive script blockers. Although I enable them to let WV to operate freely, it might be they still interfere with its operation... or that my computers are just slow . So my suggestion is not to make it a big issue unless somebody else has a similar problem.

**Comment by Benjaki2** [comment]
Got it. Should we close this out?

**Comment by minniewong** [comment]
guess so
