### ISSUE TITLE
Feedback module does not open in mobile (UAT V3.0)

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1867]
**Describe the bug**
Feedback module does not open in mobile.

**To Reproduce**
1. From a mobile device, click 'Send Feedback' in info drop down menu
2. Note no feedback modal/email triggered and no error shown

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS: Android
 - Browser: Chrome

**Comment by minniewong** [comment]
I think it's supposed to only open your phone's mail client, not the feedback module itself.
