### ISSUE TITLE
Animation dates should update with timeline dates in tour story (UAT v3.0)

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1868]
**Describe the bug**
Animation dates should update with timeline dates in tour story - more specifically, if you are on a tour that does not have the animation widget invoked, such as Earth At Night, and you open the animation widget on the last step, the dates in the animation widget should change to the dates that are showing in the timeline. 

**To Reproduce**
1. Go to UAT
2. Click on Earth at Night tour story
3. Go through all the steps and stop on step 8, open animation widget
4. See error - animation widget dates should update to 2017 Sept 8 as the start date, and 2017 Sept 15 as the end date.

**Expected behavior**
Animation widget dates should update to 2017 Sept 8 as the start date, and 2017 Sept 15 as the end date.

**Screenshots**
![Screen Shot 2019-07-18 at 11 38 29 AM](https://user-images.githubusercontent.com/10747923/61471334-9859a380-a950-11e9-9e0c-256de50b086f.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
UAT v3.0

**Comment by Benjaki2** [comment]
Looks like this issue is on PROD as well.

**Comment by minniewong** [comment]
I didn't notice this issue in PROD. But I feel like I noticed these issues in SIT and sometimes it would happen and sometimes it wouldn't. so i'm not sure what that means.

**Comment by Benjaki2** [comment]
Sorry. I had some sort of false positive when I first tested it. 

I believe that with the current (UAT) implementation once the animation widget has been opened or is in a tour permalink that it would retain that state until it is manually adjusted or finds itself in another tour permalink. But we should probably clean the animation state every time a tour state changes, right?

**Comment by ZachTRice** [comment]
Can this possibly be 'fixed' by adding the animation start and animation end parameters to the tour step URL?

**Comment by minniewong** [comment]
That sounds right - I notice a similar issue when opening the comparison tool on step 8 of Earth at night - where the tab A is 2017 SEP 8 but side tab b is 2019 JUL 11. I think it should adhere to the same principle where it shows 7 days before i.e. 2017 SEP 1

**Comment by minniewong** [comment]
@ZachTRice - I think the issue is that we are removing the existing functionality. If a permalink was sent to someone and they activated the animation widget, the widget would default to the end date to be today?

**Comment by ZachTRice** [comment]
Not sure but you are probably right
