### ISSUE TITLE
Event track dates do not change consistently after clicking supercluster

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1871]
**Describe the bug**
When focused on an event with a track that includes multiple previous dates (e.g., Iceberg B30), event track dates do not change consistently on clicking points revealed after clicking a supercluster.

**To Reproduce**
1. Go to `/?v=-145.79,-72.006953125,-118.78999999999999,-58.753046874999995&t=2019-06-14-T00%3A00%3A00Z&e=EONET_2733&l=MODIS_Terra_Sea_Ice(hidden),MODIS_Aqua_Sea_Ice(hidden),MODIS_Aqua_Brightness_Temp_Band31_Night(hidden),MODIS_Aqua_Brightness_Temp_Band31_Day(hidden),MODIS_Terra_Brightness_Temp_Band31_Night(hidden),MODIS_Terra_Brightness_Temp_Band31_Day(hidden),VIIRS_SNPP_DayNightBand_ENCC(hidden),Reference_Labels,Reference_Features,Coastlines(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor`
2. Click on a previous point along the track (that is not a supercluster)
3. Click a supercluster and click one of the points revealed from the supercluster zoom in
4. Note date is not changing to selected point date - it appears to be focusing on the currently selected date

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by edplato** [comment]
_Originally posted by @minniewong in https://github.com/nasa-gibs/worldview/issues/1838#issuecomment-511469080_

**Comment by jasontk19** [comment]
This issue also happens when you switch away from the "Events" tab and back again.  When you return to the events tab, clicking on a point no longer properly sets the date to that point's date.
