### ISSUE TITLE
Supercluster points not always removed after clicking to zoom in

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#1885]
**Describe the bug**
Sometimes when clicking a supercluster point on an event track, the map will zoom in and show additional points/clusters that were represented by the originally targeted cluster but, the original is not properly removed from the map.

**To Reproduce**
1. Go to `?v=-91.21319211065571,-106.63320385434251,-6.5569421106557115,-14.805078854342511&t=2019-06-07-T00%3A00%3A00Z&e=EONET_4120,2019-05-03&l=MODIS_Terra_Sea_Ice(hidden),MODIS_Aqua_Sea_Ice(hidden),MODIS_Aqua_Brightness_Temp_Band31_Night(hidden),MODIS_Aqua_Brightness_Temp_Band31_Day(hidden),MODIS_Terra_Brightness_Temp_Band31_Night(hidden),MODIS_Terra_Brightness_Temp_Band31_Day(hidden),VIIRS_SNPP_DayNightBand_ENCC(hidden),Reference_Labels,Reference_Features,Coastlines(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor`
2. Click on the "5" cluster
3. The map will zoom in to now show a "2" and a "3" cluster, which made up the "5"
4. The "5" cluster remains on the map even though we've zoomed in to show the component clusters it was made of.

**Expected behavior**
When clicking a supercluster, the target cluster should be removed from the map and replaced with the points or sub-clusters it was representing.

**Screenshots**
*Before:*
![Screen Shot 2019-07-22 at 1 40 55 PM](https://user-images.githubusercontent.com/1480000/61652618-6022cf80-ac86-11e9-85ff-cc88469dbc8d.png)

*After:*
![Screen Shot 2019-07-22 at 1 41 01 PM](https://user-images.githubusercontent.com/1480000/61652646-6e70eb80-ac86-11e9-97f6-75418659b5d2.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.5
 - Browser: Chrome 75.0.3770.100 
 - Version: 3.0

**Additional context**
Discovered while working on #1871.  Does not appear related to #1838 (fixed this error locally and can still reproduce the issue in this ticket.

**Comment by Benjaki2** [comment]
Looks like this bug exists on `Production` as well.

**Comment by jasontk19** [comment]
I was able to track down what's causing this but haven't come up with a good solution yet.  Should we defer til later if this exists in prod?

**Comment by jasontk19** [comment]
Found a really simple solution so went ahead with the fix for this.

**Comment by Benjaki2** [comment]
Sounds good!  Generally I would defer (depends on the bug), but if it is an easy fix... why not?!
