### ISSUE TITLE
Fires custom colormap does not work

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#189]
http://go.nasa.gov/2n7u9BG

**Comment by Benjaki2** [comment]
@rboller @minniewong Should this layer have a custom colormap option?

**Comment by minniewong** [comment]
i guess it's OK to allow users to change the color. Is this the error you are getting? https://bugs.earthdata.nasa.gov/browse/WV-1772

**Comment by Benjaki2** [comment]
No, it's the imagery that I am referring to

**Comment by Benjaki2** [comment]
No longer have the option to add custom colormaps to wms layers. Closed
