### ISSUE TITLE
Comparison mode opacity values are not saved in url

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1891]
**Describe the bug**
Comparison mode opacity values are not saved in url and revert to 50% on page refresh.

**To Reproduce**
1. Go to comparison mode opacity mode
2. Set opacity to value that is not 50% and reload page
3. Note comparison opacity mode is 50%

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jasontk19** [comment]
This looks like another existing issue in prod.  I'll still take a look though

**Comment by jasontk19** [comment]
Going to unassign this one for now up to take a look at #1898
