### ISSUE TITLE
Event tracks are not retained when switching projections (UAT v3.0)

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1893]
**Describe the bug**
Event tracks are not retained when switching projections. The track is missing after selecting a multi-point event (e.g., iceberg) in geographic and switching to antarctic. 

**To Reproduce**
1. Go to `?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,MODIS_Terra_Sea_Ice(hidden),MODIS_Aqua_Sea_Ice(hidden),MODIS_Aqua_Brightness_Temp_Band31_Night(hidden),MODIS_Aqua_Brightness_Temp_Band31_Day(hidden),MODIS_Terra_Brightness_Temp_Band31_Night(hidden),MODIS_Terra_Brightness_Temp_Band31_Day(hidden),VIIRS_SNPP_DayNightBand_ENCC(hidden),Reference_Labels,Reference_Features,Coastlines(hidden)&t=2018-09-21-T00%3A00%3A00Z&z=3&v=-72.19,-72.366953125,-45.19,-59.113046874999995&e=EONET_2934,2018-09-21`
2. Note event track for Iceberg A68A
3. Switch to antarctic projection
4. Note event track is missing

**Expected behavior**
The event track should remain visible/selectable upon switching back and forth between projections that include the same selected event.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jasontk19** [comment]
I can take a look at this!  I've spent most of my time so far looking at event track stuff
