### ISSUE TITLE
Add IMERG Precipitation Rate

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#1895]
| Layer Identifier | Title | Subtitle | Dataset | Projection |Time Period|
| ------------- |-------------|-------------|------|------|--------|
|IMERG_Precipitation_Rate|Precipitation Rate |IMERG|GPM_3IMERGDF v06|4326|2000-06-01 -to Ongoing |

**Comment by minniewong** [comment]
Keep current IMERG Rain and Snow Rates layers for the time being
