### ISSUE TITLE
build

### ISSUE THREAD

**Issue by oladitan** [nasa-gibs/worldview#190]
how do i build this project? Thanks.

**Comment by Benjaki2** [comment]
Thank you for exploring Worldview. The basic install has been problematic for a while now. The problem usually is a response to a dependency releasing a new version. We are trying to simplify the process using a minimalistic node server as opposed to the VM setup we currently have in place. Development can be monitored here #249 . 

In the meantime, look into our [manual setup documentation](https://github.com/nasa-gibs/worldview/blob/master/doc/manual_setup.md)

**Comment by oladitan** [comment]
I'm at the last step and I cant get past thist error

> `usr@DESKTOP-#######MINGW64 ~/worldview (master)
$ grunt
Running "exec:python_packages" (exec) task
>> 'virtualenv' is not recognized as an internal or external command,
>> operable program or batch file.
>> Exited with code: 1.
Warning: Task "exec:python_packages" failed. Use --force to continue.

Aborted due to warnings.
`

**Comment by Benjaki2** [comment]
Looks like `virtualenv` wasn't successfully installed. Did you run `sudo easy_install virtualenv==1.10.1` and have everything go smoothly?

**Comment by oladitan** [comment]
Thnks. I have installed virtualenve 1.10.1 now I get the following 

i have python 2.7 installed for all users.

> usr@DESKTOP-#######MINGW64 ~/worldview (master)
$ grunt
Running "exec:python_packages" (exec) task
>> Traceback (most recent call last):
>>   File "C:\Users\usr\worldview\python\lib\site.py", line 67, in <module>
>>     import os
>>   File "C:\Users\usr\worldview\python\lib\os.py", line 409
>>     yield from walk(new_path, topdown, onerror, followlinks)
>>              ^
>> SyntaxError: invalid syntax
Overwriting python\lib\orig-prefix.txt with new content
New python executable in python\Scripts\python.exe
ERROR: The executable python\Scripts\python.exe is not functioning
ERROR: It thinks sys.prefix is u'c:\\users\\usr\\worldview' (should be u'c:\\                                                                                                                                  users\\usr\\worldview\\python')
ERROR: virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for                                                                                                                                   "Only this user" or have multiple versions of Python installed. Copying the app                                                                                                                                  ropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.
>> Exited with code: 100.
Warning: Task "exec:python_packages" failed. Use --force to continue.

Aborted due to warnings.

**Comment by Benjaki2** [comment]
This issue looks pretty similar: https://github.com/pypa/virtualenv/issues/817

Retracing the steps here might help.
