### ISSUE TITLE
Clicking on event in sidebar does not select event and throws errors (UAT v3.0)

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1905]
**Describe the bug**
Clicking on event in sidebar does not select event and throws errors.

**To Reproduce**
1. Click on an event from the sidebar
2. See normal zoom/date change function not happen and console error (screenshot below)

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/61819469-1f12f280-ae21-11e9-9966-bbbce5a0fb7b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jasontk19** [comment]
I've got a fix for this!
