### ISSUE TITLE
Data download not handling VIIRS layers

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1939]
**Describe the bug**
There are two distinct/related issues concerning VIIRS and data download:

**1. App crashes with VIIRS fires on selecting Data tab**
**To Reproduce**
1. Go to `https://worldview.earthdata.nasa.gov/?t=2019-07-30-T21%3A29%3A06Z&l=VIIRS_SNPP_Thermal_Anomalies_375m_Night,VIIRS_SNPP_Thermal_Anomalies_375m_Day,MODIS_Terra_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden)`
2. Click on Data tab
3. See console error screenshot

**2. Unable to select VIIRS layers (in sidebar with Data tab selected)**
**To Reproduce**
1. Go to `https://worldview.earthdata.nasa.gov/?v=-165.55529498987173,-100.63612760107533,165.89818869652092,133.23992864493073&t=2019-07-30-T21%3A29%3A06Z&l=VIIRS_SNPP_Thermal_Anomalies_375m_Night,VIIRS_SNPP_Thermal_Anomalies_375m_Day,MODIS_Terra_SurfaceReflectance_Bands143,MODIS_Terra_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden)&download=MOD09GA`
2. Click on a VIIRS layer in the data download sidebar
3. See MODIS/TERRA still selected in sidebar

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/62330733-89faa400-b487-11e9-9cb8-e31ce05914f8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 75.0.3770.142

**Comment by minniewong** [comment]
I thought it was because VNP14IMG_NRT_DAY and VNP14IMG_NRT_NIGHT were not searchable in CMR but changing the filename to VNP14IMG_NRT still showed an error. Second thought was that it's trying to give the user two download options: '"product": ["VNP14IMG_NRT_DAY", "VNP14IMGTDL_NRT"],' (as you can see in the number 2 link above) and that was possibly an issue?

**Comment by minniewong** [comment]
Pretty sure it's because this layer has two data download options: `"product": ["VNP14IMG_NRT_DAY", "VNP14IMGTDL_NRT"]` (vector data file and regular data file)

**Comment by minniewong** [comment]
Works now
