### ISSUE TITLE
Clicking on an event on the map does not move that listing in the Event list

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1948]
**Describe the bug**
If I click on an event on the map, I expect to be able to see the event listing in the event list. But if this event is not near the top of the list, you have to manually scroll to that highlighted listing to find it. 

**To Reproduce**
1. Click on Events tab
2. Click on an event on the map that is not at the top of the event list
3. See that you are zoomed to the event, but don't know what the event is called because the event list does not scroll to that event, unless you manually scroll down the list to find the highlighted event. 

**Expected behavior**
You would expect to be able to easily see the event listing when you click on an event on the map. Either the event listing should appear at the top of the list, or the list should scroll to that spot where the event is listed. 

**Screenshots**
Clicked on random event on map. The event listing does not show up on the event list on the left. You have to manually scroll to the highlighted event to find it.

<img width="957" alt="Screen Shot 2019-08-02 at 10 24 48 AM" src="https://user-images.githubusercontent.com/10747923/62377185-51eb7380-b510-11e9-94a5-20a686b85fe5.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by minniewong** [comment]
I suppose that's the reason for the "Only show events in current view" but that's an extra step?

**Comment by edplato** [comment]
I think showing the focused event in the sidebar would be a good user experience.
