### ISSUE TITLE
WIndows platform manual installation issues

### ISSUE THREAD

**Issue by christosvl** [nasa-gibs/worldview#197]
An error is poped up when executing the instructions for manual installation on windows 10 64bit operational system. Providing a screenshot of the error.
![worldview](https://cloud.githubusercontent.com/assets/26527759/24136092/d3230f66-0e15-11e7-82f0-791b5c2c03ab.jpg)

**Comment by Benjaki2** [comment]
@christosvl Could you share what errors you are getting in your console?

**Comment by Benjaki2** [comment]
I am closing the issue for the time being. If you are still having this problem, please share the errors you are seeing in your console or those you may be receiving during build. Thanks!
