### ISSUE TITLE
Worldview stops working when layer name has periods

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1976]
**Describe the bug**
It appears that Worldview stops working with certain layers that have periods in their filename. 
"MISR_Cloud_Stereo_Height_Histogram_Bin_0.5km_Monthly", "MISR_Cloud_Stereo_Height_Histogram_Bin_1.5-2.0km_Monthly",
"Particulate_Matter_Below_2.5micrometers_2001-2010", "Particulate_Matter_Below_2.5micrometers_2010-2012",

**To Reproduce**
1. Go to Worldview
2. Click on Add layers and search for "particulate matter"
3. Try to select the layers
4. See error - Worldview stops responding

**Expected behavior**
Worldview should work with layers with periods in their layer name.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by mike-mcgann** [comment]
This was a issue before where the layer identifier was being used in an HTML element and then the selector was failing because of the period.

**Comment by edplato** [comment]
Disabling the palettes in `sidebar\layer.js` allows the map layer building to function.
