### ISSUE TITLE
MODIS data download swaths have incorrect coverage and dates/times

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1980]
**Describe the bug**
Data download swath selection for MODIS products appears not to be working correctly. 
The swath lines don't cover the whole earth, and the times appear to be incorrect. I think it's an issue with the time parameter. If the time parameter goes into the afternoon hours it seems to cause the MODIS swath granule buttons to display incorrectly and with the incorrect times. 

**To Reproduce**
Download Swath granules are wrong: 
https://worldview.earthdata.nasa.gov/?v=-260.296875,-137.390625,255.796875,130.640625&t=2012-10-07-T14%3A00%3A00Z&l=MODIS_Aqua_Aerosol_Optical_Depth_3km,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor,MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&download=MYD04_3K

Download swath granules are correct: 
https://worldview.earthdata.nasa.gov/?v=-267.30289239099983,-165.90141232097193,248.79085760900017,102.12983767902807&t=2012-10-07-T00%3A00%3A00Z&l=MODIS_Aqua_Aerosol_Optical_Depth_3km,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor,MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&download=MYD04_3K

**Expected behavior**
The MODIS download swaths should span the map like it does for 00:00:00Z

**Screenshots**
![Screen Shot 2019-08-06 at 4 36 17 PM](https://user-images.githubusercontent.com/10747923/62575248-598c7e80-b868-11e9-9c6c-c1fae1a35f2f.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by edplato** [comment]
It does look to be a wrong time or offset somewhere in the processing/filtering chain. Looking into the granule query results, the `TimeFilter` in `dataResultsTimeFilter` is currently filtering these points.
