### ISSUE TITLE
New layers PoDAAC BEDI Batch II

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#199]
We've added the following layers to GIBS, now ready for Worldview:

Layer Identifier | Title | Subtitle | CMR product  
--------------- | ---- | -------- | --------------
Aquarius_Sea_Surface_Salinity_L3_7Day_Snapshot | Sea Surface Salinity (L3, 7-Day Snapshot) | Aquarius / SAC-D | C1293230934-PODAAC
Aquarius_Sea_Surface_Salinity_L3_7Day_RunningMean | Sea Surface Salinity (L3, 7-Day Running Mean) | Aquarius / SAC-D | C1293229315-PODAAC
Aquarius_Sea_Surface_Salinity_L3_Daily | Sea Surface Salinity (L3, Daily) | Aquarius / SAC-D | C1293231186-PODAAC
Aquarius_Sea_Surface_Salinity_L3_Monthly | Sea Surface Salinity (L3, Monthly) | Aquarius / SAC-D | C1293232698-PODAAC
Aquarius_Sea_Surface_Salinity_L3_3Month | Sea Surface Salinity (L3, 3-Month) | Aquarius / SAC-D | C1293232765-PODAAC
Aquarius_Wind_Speed_L3_7Day_Snapshot | Wind Speed (L3, 7-Day Snapshot) | Aquarius / SAC-D | C1293242270-PODAAC
Aquarius_Wind_Speed_L3_Daily | Wind Speed (L3, Daily) | Aquarius / SAC-D | C1293242548-PODAAC
MODIS_Aqua_L3_SST_MidIR_4km_Night_8Day | Sea Surface Temperature (L3, Night, 8 Day) | Aqua / MODIS | C1293276420-PODAAC
MODIS_Aqua_L3_SST_MidIR_9km_Night_8Day | Sea Surface Temperature (L3, Night, 8 Day) | Aqua / MODIS | C1293277885-PODAAC
MODIS_Aqua_L3_SST_MidIR_4km_Night_Annual | Sea Surface Temperature (L3, Night, Annual) | Aqua / MODIS | C1293278588-PODAAC
MODIS_Aqua_L3_SST_MidIR_9km_Night_Annual | Sea Surface Temperature (L3, Night, Annual) | Aqua / MODIS | C1293278533-PODAAC
MODIS_Aqua_L3_SST_MidIR_4km_Night_Daily | Sea Surface Temperature (L3, Night, Daily)	| Aqua / MODIS | C1293278618-PODAAC
MODIS_Aqua_L3_SST_MidIR_9km_Night_Daily | Sea Surface Temperature (L3, Night, Daily)	| Aqua / MODIS | C1293289256-PODAAC
MODIS_Aqua_L3_SST_MidIR_4km_Night_Monthly | Sea Surface Temperature (L3, Night, Monthly) | Aqua / MODIS | C1293298839-PODAAC
MODIS_Aqua_L3_SST_MidIR_9km_Night_Monthly | Sea Surface Temperature (L3, Night, Monthly) | Aqua / MODIS | C1293299333-PODAAC
MODIS_Aqua_L3_SST_Thermal_4km_Day_8Day | Sea Surface Temperature (L3, Day, 8 Day) | Aqua / MODIS | C1293300264-PODAAC
MODIS_Aqua_L3_SST_Thermal_4km_Night_8Day | Sea Surface Temperature (L3, Night, 8 Day) | Aqua / MODIS | C1293301591-PODAAC
MODIS_Aqua_L3_SST_Thermal_9km_Day_8Day | Sea Surface Temperature (L3, Day, 8 Day) | Aqua / MODIS | C1293303723-PODAAC
MODIS_Aqua_L3_SST_Thermal_9km_Night_8Day | Sea Surface Temperature (L3, Night, 8 Day) | Aqua / MODIS | C1293305387-PODAAC
MODIS_Aqua_L3_SST_Thermal_4km_Day_Annual | Sea Surface Temperature (L3, Day, Annual)	 | Aqua / MODIS | C1293306067-PODAAC
MODIS_Aqua_L3_SST_Thermal_4km_Night_Annual | Sea Surface Temperature (L3, Night, Annual) | Aqua / MODIS | C1293306075-PODAAC
MODIS_Aqua_L3_SST_Thermal_9km_Day_Annual | Sea Surface Temperature (L3, Day, Annual)	 | Aqua / MODIS | C1293306150-PODAAC
MODIS_Aqua_L3_SST_Thermal_9km_Night_Annual | Sea Surface Temperature (L3, Night, Annual) | Aqua / MODIS | C1293306180-PODAAC
MODIS_Aqua_L3_SST_Thermal_4km_Day_Daily | Sea Surface Temperature (L3, Day, Daily) | Aqua / MODIS | C1293312706-PODAAC
MODIS_Aqua_L3_SST_Thermal_4km_Night_Daily | Sea Surface Temperature (L3, Night, Daily)	 | Aqua / MODIS | C1293324400-PODAAC
MODIS_Aqua_L3_SST_Thermal_9km_Day_Daily | Sea Surface Temperature (L3, Day, Daily) | Aqua / MODIS | C1293338818-PODAAC
MODIS_Aqua_L3_SST_Thermal_9km_Night_Daily | Sea Surface Temperature (L3, Night, Daily) | Aqua / MODIS | C1293348875-PODAAC
MODIS_Aqua_L3_SST_Thermal_4km_Day_Monthly | Sea Surface Temperature (L3, Day, Monthly) | Aqua / MODIS | C1293354696-PODAAC
MODIS_Aqua_L3_SST_Thermal_4km_Night_Monthly | Sea Surface Temperature (L3, Night, Monthly) | Aqua / MODIS | C1293355023-PODAAC
MODIS_Aqua_L3_SST_Thermal_9km_Day_Monthly | Sea Surface Temperature (L3, Day, Monthly) | Aqua / MODIS | C1293355353-PODAAC
MODIS_Aqua_L3_SST_Thermal_9km_Night_Monthly | Sea Surface Temperature (L3, Night, Monthly) | Aqua / MODIS | C1293355722-PODAAC
MODIS_Terra_L3_SST_MidIR_4km_Night_8Day | Sea Surface Temperature (L3, Night, 8 Day) | Terra / MODIS | C1293356591-PODAAC
MODIS_Terra_L3_SST_MidIR_9km_Night_8Day | Sea Surface Temperature (L3, Night, 8 Day) | Terra / MODIS | C1293358062-PODAAC
MODIS_Terra_L3_SST_MidIR_4km_Night_Annual | Sea Surface Temperature (L3, Night, Annual) | Terra / MODIS | C1293359756-PODAAC
MODIS_Terra_L3_SST_MidIR_9km_Night_Annual | Sea Surface Temperature (L3, Night, Annual) | Terra / MODIS | C1293359796-PODAAC
MODIS_Terra_L3_SST_MidIR_4km_Night_Daily | Sea Surface Temperature (L3, Night, Daily)	 | Terra / MODIS | C1293365714-PODAAC
MODIS_Terra_L3_SST_MidIR_9km_Night_Daily | Sea Surface Temperature (L3, Night, Daily)	 | Terra / MODIS | C1293371959-PODAAC
MODIS_Terra_L3_SST_MidIR_4km_Night_Monthly | Sea Surface Temperature (L3, Night, Monthly) | Terra / MODIS | C1293379206-PODAAC
MODIS_Terra_L3_SST_MidIR_9km_Night_Monthly | Sea Surface Temperature (L3, Night, Monthly) | Terra / MODIS | C1293379591-PODAAC
MODIS_Terra_L3_SST_Thermal_4km_Day_8Day | Sea Surface Temperature (L3, Day, 8 Day) | Terra / MODIS | C1293381343-PODAAC
MODIS_Terra_L3_SST_Thermal_4km_Night_8Day | Sea Surface Temperature (L3, Night, 8 Day) | Terra / MODIS | C1293382854-PODAAC
MODIS_Terra_L3_SST_Thermal_9km_Day_8Day | Sea Surface Temperature (L3, Day, 8 Day) | Terra / MODIS | C1293384369-PODAAC
MODIS_Terra_L3_SST_Thermal_9km_Night_8Day | Sea Surface Temperature (L3, Night, 8 Day) | Terra / MODIS | C1293385956-PODAAC
MODIS_Terra_L3_SST_Thermal_4km_Day_Annual | Sea Surface Temperature (L3, Day, Annual)	 | Terra / MODIS | C1293386715-PODAAC
MODIS_Terra_L3_SST_Thermal_4km_Night_Annual | Sea Surface Temperature (L3, Night, Annual) | Terra / MODIS | C1293386808-PODAAC
MODIS_Terra_L3_SST_Thermal_9km_Day_Annual | Sea Surface Temperature (L3, Day, Annual)	 | Terra / MODIS | C1293386830-PODAAC
MODIS_Terra_L3_SST_Thermal_9km_Night_Annual | Sea Surface Temperature (L3, Night, Annual) | Terra / MODIS | C1293386857-PODAAC
MODIS_Terra_L3_SST_Thermal_4km_Day_Daily | Sea Surface Temperature (L3, Day, Daily) | Terra / MODIS | C1293493714-PODAAC
MODIS_Terra_L3_SST_Thermal_4km_Night_Daily | Sea Surface Temperature (L3, Night, Daily) | Terra / MODIS | C1293505403-PODAAC
MODIS_Terra_L3_SST_Thermal_9km_Day_Daily | Sea Surface Temperature (L3, Day, Daily) | Terra / MODIS | C1293517154-PODAAC
MODIS_Terra_L3_SST_Thermal_9km_Night_Daily | Sea Surface Temperature (L3, Night, Daily) | Terra / MODIS | C1293528849-PODAAC
MODIS_Terra_L3_SST_Thermal_4km_Day_Monthly | Sea Surface Temperature (L3, Day, Monthly) | Terra / MODIS | C1293535460-PODAAC
MODIS_Terra_L3_SST_Thermal_4km_Night_Monthly | Sea Surface Temperature (L3, Night, Monthly) | Terra / MODIS | C1293535845-PODAAC
MODIS_Terra_L3_SST_Thermal_9km_Day_Monthly | Sea Surface Temperature (L3, Day, Monthly) | Terra / MODIS | C1293536203-PODAAC
MODIS_Terra_L3_SST_Thermal_9km_Night_Monthly | Sea Surface Temperature (L3, Night, Monthly) | Terra / MODIS | C1293536579-PODAAC
CCMP_REMSS_Zonal_Wind_Speed_Monthly | Wind Speed (Zonal, REMSS, Monthly) | CCMP | C1293249063-PODAAC
CCMP_REMSS_Meridional_Wind_Speed_Monthly | Wind Speed (Meridional, REMSS, Monthly) | CCMP | C1293249063-PODAAC
CCMP_REMSS_Scalar_Wind_Speed_Monthly | Wind Speed (Scalar, REMSS, Monthly) | CCMP | C1293249063-PODAAC

**Comment by mcechini** [comment]
They'll need to know the CMR Concept ID for each of these as well.

**Comment by jejeking** [comment]
Done

**Comment by jejeking** [comment]
fixed external layer name

**Comment by minniewong** [comment]
@mcechini and @jejeking 
Imagery is missing for the following Aquarius Sea Surface Salinity layers: Monthly -  Aug 25 2011, 2012, 2012, 2014 and Jan - May 2015; 3 Month - Aug 25 2011, July - Dec 2012, 2013, 2014

**Comment by jejeking** [comment]
Yup. I am aware. You can follow activity on GIBS-2168.
Thanks,
Jerome

**Comment by minniewong** [comment]
@mcechini and @jejeking - The WV titles for the MODIS layers are not descriptive and don't differentiate between the Mid IR and Thermal and the 4 km and 9 km resolutions. I'm going to add that information into the titles, but do we need to work with the data provider to update the ICD?

**Comment by mcechini** [comment]
I'll email Jeff Hall and see what he thinks.

**Comment by mcechini** [comment]
Updated Worldview titles are in the ICD (https://docs.google.com/spreadsheets/d/1LJeF_9uTxvO_CdLUU9LqKuALeTEPmF0hQrrutdh9dSg/edit#gid=562601153)

**Comment by mcechini** [comment]
New titles are here:

Sea Surface Temperature (L3, Night, 8 Day, Mid Infrared, 4km)
Sea Surface Temperature (L3, Night, 8 Day, Mid Infrared, 9km)
Sea Surface Temperature (L3, Night, Annual, Mid Infrared, 4km)
Sea Surface Temperature (L3, Night, Annual, Mid Infrared, 9km)
Sea Surface Temperature (L3, Night, Daily, Mid Infrared, 4km)
Sea Surface Temperature (L3, Night, Daily, Mid Infrared, 9km)
Sea Surface Temperature (L3, Night, Monthly, Mid Infrared, 4km)
Sea Surface Temperature (L3, Night, Monthly, Mid Infrared, 9km)
Sea Surface Temperature (L3, Day, 8 Day, Thermal, 4km)
Sea Surface Temperature (L3, Night, 8 Day, Thermal, 4km)
Sea Surface Temperature (L3, Day, 8 Day, Thermal, 9km)
Sea Surface Temperature (L3, Night, 8 Day, Thermal, 9km)
Sea Surface Temperature (L3, Day, Annual, Thermal, 4km)
Sea Surface Temperature (L3, Night, Annual, Thermal, 4km)
Sea Surface Temperature (L3, Day, Annual, Thermal, 9km)
Sea Surface Temperature (L3, Night, Annual, Thermal, 9km)
Sea Surface Temperature (L3, Day, Daily, Thermal, 4km)
Sea Surface Temperature (L3, Night, Daily, Thermal, 4km)
Sea Surface Temperature (L3, Day, Daily, Thermal, 9km)
Sea Surface Temperature (L3, Night, Daily, Thermal, 9km)
Sea Surface Temperature (L3, Day, Monthly, Thermal, 4km)
Sea Surface Temperature (L3, Night, Monthly, Thermal, 4km)
Sea Surface Temperature (L3, Day, Monthly, Thermal, 9km)
Sea Surface Temperature (L3, Night, Monthly, Thermal, 9km)
Sea Surface Temperature (L3, Night, 8 Day, Mid Infrared, 4km)
Sea Surface Temperature (L3, Night, 8 Day, Mid Infrared, 9km)
Sea Surface Temperature (L3, Night, Annual, Mid Infrared, 4km)
Sea Surface Temperature (L3, Night, Annual, Mid Infrared, 9km)
Sea Surface Temperature (L3, Night, Daily, Mid Infrared, 4km)
Sea Surface Temperature (L3, Night, Daily, Mid Infrared, 9km)
Sea Surface Temperature (L3, Night, Monthly, Mid Infrared, 4km)
Sea Surface Temperature (L3, Night, Monthly, Mid Infrared, 9km)
Sea Surface Temperature (L3, Day, 8 Day, Thermal, 4km)
Sea Surface Temperature (L3, Night, 8 Day, Thermal, 4km)
Sea Surface Temperature (L3, Day, 8 Day, Thermal, 9km)
Sea Surface Temperature (L3, Night, 8 Day, Thermal, 9km)
Sea Surface Temperature (L3, Day, Annual, Thermal, 4km)
Sea Surface Temperature (L3, Night, Annual, Thermal, 4km)
Sea Surface Temperature (L3, Day, Annual, Thermal, 9km)
Sea Surface Temperature (L3, Night, Annual, Thermal, 9km)
Sea Surface Temperature (L3, Day, Daily, Thermal, 4km)
Sea Surface Temperature (L3, Night, Daily, Thermal, 4km)
Sea Surface Temperature (L3, Day, Daily, Thermal, 9km)
Sea Surface Temperature (L3, Night, Daily, Thermal, 9km)
Sea Surface Temperature (L3, Day, Monthly, Thermal, 4km)
Sea Surface Temperature (L3, Night, Monthly, Thermal, 4km)
Sea Surface Temperature (L3, Day, Monthly, Thermal, 9km)
Sea Surface Temperature (L3, Night, Monthly, Thermal, 9km)

**Comment by minniewong** [comment]
Waiting on GIBS-2168

**Comment by minniewong** [comment]
layers are 99% ready on the GIBS side - I think we should release these layers this week in Worldview
