### ISSUE TITLE
Provide a place to access older tour stories

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#1991]
**Is your feature request related to a problem? Please describe.**
We can only have 9 tour stories showing at a time - as we create new tour stories, it would be good for users to be able to see old tour stories that have cycled off. 

**Describe the solution you'd like**
Provide a place where users can access older tour stories. Might be good to display them in their categories, rather than just by date or provide different sort options.

**Comment by ZachTRice** [comment]
Also described in this ticket: https://github.com/nasa-gibs/worldview/issues/1613#issuecomment-515087389
