### ISSUE TITLE
perm.in.map.3 opens zoomed out too far in Chrome, IE

### ISSUE THREAD

**Issue by marseillebunk** [nasa-gibs/worldview#2043]
While running perm.in.map.3, world map appears as a small rectangle on a large field of black--much too small to be useful.  Clicking on zoom + or - zooms it to correct size.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, IE
 - Version: Chrome Version 76.0.3809.100, IE 11.1182.16299.0

Also appears in production on Chrome
https://worldview.earthdata.nasa.gov/?v=-1931.8181818181818,-1000,1931.8181818181818,1000&now=2013-07-01T12%3A00%3A00Z

**Comment by jasontk19** [comment]
Removing milestone since this is minor and already in production
