### ISSUE TITLE
Image dimensions are incorrect for resolution and black image returned on valid request

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2045]
**Describe the bug**
It appears that the 10km resolution is behaving like a higher resolution based on the dimensions/raw sizes that are being displayed. For example, if you draw an extent for image download using 10km resolution, it now quickly exceeds the maximum dimensions of 8200px x 8200px, but that shouldn't be possible with 10km resolution.

Beyond the above issue, this request returned an all black image where from a valid/visible area.

Here is an image request that went through that returns a black image:
https://wvs.earthdata.nasa.gov/api/v1/snapshot?REQUEST=GetSnapshot&TIME=2019-08-16&BBOX=-522.080859375,1399.31982421875,-235.3201171875,2119.3330078125&CRS=EPSG:4326&LAYERS=MODIS_Terra_CorrectedReflectance_TrueColor,Coastlines&WRAP=day,x&FORMAT=image/jpeg&WIDTH=8192&HEIGHT=3263&ts=1565987604049

**To Reproduce**
1. Go to image download
2. Draw an extent over South America and note the raw size/image dimensions 

**Screenshots**
Note: raw size / dimensions while in 10km resolution
![image](https://user-images.githubusercontent.com/24417194/63196943-83059100-c044-11e9-931b-224aa65cd137.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome/ IE11

**Comment by edplato** [comment]
This may have been fixed in #2033 . Can confirm fix and close - WVS ticket opened for all black image.

**Comment by jasontk19** [comment]
This appears to be fixed.  Closing!
