### ISSUE TITLE
Iceberg events use sea and lake ice icon

### ISSUE THREAD

**Issue by CodeMacabre** [nasa-gibs/worldview#205]
Icebergs have a new icon separate from sea ice (see #68). Iceberg event classes need to be changed from `sea-and-lake-ice` to `icebergs`.

![iceberg-sea-lake-ice-icon](https://cloud.githubusercontent.com/assets/19981049/24307727/2beb0b90-10bd-11e7-8033-d6f81b6b89a8.PNG)

![iceberg-sea-lake-ice-css](https://cloud.githubusercontent.com/assets/19981049/24307788/663927fa-10bd-11e7-857c-19f03f096d96.PNG)

**Comment by Benjaki2** [comment]
@CodeMacabre As of now we only have iceberg events coming from [eonet](https://eonet.sci.gsfc.nasa.gov/), so I switched the icon [6efb70c](https://github.com/nasa-gibs/worldview/commit/6efb70c4b79617062649147274ae135869dc6a62). 

In the future when we get 'sea-and-lake-ice' events we will work on distinguishing them on the client side as they share a category in the API.
