### ISSUE TITLE
Consider using svg for WV logo and icons

### ISSUE THREAD

**Issue by CodeMacabre** [nasa-gibs/worldview#206]
Currently, the WorldView logo and icons in the main widget panel are png, which makes them fairly blurry, especially at higher resolutions.

![wv-widget-icons](https://cloud.githubusercontent.com/assets/19981049/24309260/13883752-10c3-11e7-9c1a-1388c141456d.PNG)

Where possible, can they be updated to either:
1) Vector (svg) icons (possibly larger filesizes?)
2) Use Font Awesome equivalent icons (faster as FA fonts are already used?)?

Font Awesome replacement suggestions:
+ Layers - [`fa-clone`](http://fontawesome.io/icon/clone/)
+ Events - [`fa-calendar`](http://fontawesome.io/icon/calendar/)
+ Data - [`fa-download`](http://fontawesome.io/icon/download/)
+ Show - [`fa-angle-double-down`](http://fontawesome.io/icon/angle-double-down/)
+ Hide - [`fa-angle-double-up`](http://fontawesome.io/icon/angle-double-up/)
+ Show Layer - [`fa-eye`](http://fontawesome.io/icon/eye/)
+ Hide Layer - [`fa-eye-slash`](http://fontawesome.io/icon/eye-slash/)
+ Layer Options - [`fa-sliders`](http://fontawesome.io/icon/sliders/)
+ Remove Layer - [`fa-times`](http://fontawesome.io/icon/times/)

It would potentially be a little more tricky for the latter four layer icons, as they are all currently part of the same png spritesheet (`./web/images/wv.layers/show-hide.png`). I believe svgs can be used in the same way, but using Font Awesome might be faster than loading and calculating the spritesheet coordinates (may need testing to verify).

**Comment by CodeMacabre** [comment]
For the WorldView logo, if you don't have the source artwork at higher resolution in vector format, I volunteer to copy it into an svg. 🙂

**Comment by Benjaki2** [comment]
@CodeMacabre It would be great if you can copy the logo to svg! I also agree with using FA for the others icons, I can work on that.

Thanks!

**Comment by CodeMacabre** [comment]
Done! I couldn't find an equivalent font (without paying), so I just redrew the text (with slight modifications and improved kerning). I used the official NASA logo from [nasa.gov](https://www.nasa.gov/) so that's why there are minor color and shape differences. See below for comparison (svg at the top, png at the bottom):

![wv-logo comparison](https://cloud.githubusercontent.com/assets/19981049/24452295/70d68be2-147a-11e7-9325-2ba1fb3713bc.png)

The `wv-logo.png` doesn't seem to be in the `web/brand/images/` folder on any branch, but that's where it appears in the url, so I'll make a PR with the new logo there. If it needs to be moved, please do so (or let me know).

Are there any of the pngs in the `web/images/` folder that you're not going to replace with fonts? I'm happy to redraw any of them into svg too.

**Comment by Benjaki2** [comment]
closing. was released in 1.4.0
