### ISSUE TITLE
Large GIFs are hanging in requesting imagery stage

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2063]
**Describe the bug**
Large GIFs are hanging in the requesting imagery stage. I noticed this on creating large GIFs with custom intervals and large GIFs with single day intervals (example link). We used to have a maximum GIF frame limit of 40 frames, so maybe this logic has been removed.

**To Reproduce**
1. Go to https://worldview.earthdata.nasa.gov/?as=2019-05-16-T00%3A00%3A00Z&ae=2019-08-22-T00%3A00%3A00Z&ab=on
2. Create Animated GIF
3. See "Requesting Imagery" dialog with spinner remain with no resolution

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by minniewong** [comment]
A user also reported this issue yesterday
