### ISSUE TITLE
Clean up CSS dependencies

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2064]
Currently we are relying on a number of different third party CSS libraries throughout the app, some of which are quite old and are no longer updated.  In some cases, we bring in small one-off libraries for specific components (`rc-slider` for example).  Right now we rely on Bootstrap, jQuery UI, and a handful of small individual component libraries.

Ideally, we should move to something modern like Material-UI which is built for use in React projects, which should allow us to replace all other major libraries, and minor components, we are bringing in individually. Relying on only a single, modern and well-supported library throughout the app will provide more consistency and maintainability moving forward.  Also, this library only brings in the CSS needed for each component that is used, which will help prevent bloating our `wv.css` with a bunch of unused styles.

Currently the biggest offender for CSS file size bloat is FontAwesome which adds about 373kb to the gzipped file size of `wv.css`.  This is more than our base css and all other third-party CSS combined.  Material-UI provides a set of icons that can be imported individually.

**Comment by minniewong** [comment]
Investigate importing individual fontawesome icons
