### ISSUE TITLE
Epic - Product Picker

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2069]
Combined notes from all linked tickets/meetings:
https://docs.google.com/document/d/1BPW8mUzFU8jkcs4V-Xh2DV5HqVM3ajOoJzF8ZDu45wY/edit#

**Comment by edplato** [comment]
Create facets for level, day/night, and time interval filtering.

**Comment by jasontk19** [comment]
Dev meeting 10/18 notes:

* Discussed that the general problem is that finding things is hard, and finding _good_ things is harder.
* Identified the need for an ability to prioritize "better" products over others either via a score, relevance to search, or some other means.
* Discussed the possible use of facets to limit results 
** by availability 
** by attributes (day/night, update frequency, spectrum, resolution, etc)
* In absence of faceted search, discussed grouping search results by attributes to allow a more limited list initially, then provide a means to drill down to individual layers 
* Agreed that a layer preview image showing example of global coverage (like State of the Ocean) would be nice to have
