### ISSUE TITLE
Provide ability to export a legend with the image snapshot feature

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#207]
If a legend was available for download with the imagery, it would provide a self-contained package which would more fully describe what the user is seeing.  To be included: product names, color bars, and scale bars.

As an additional twist, the legends could also be embedded into KMZs as Screen Overlays:
https://www.google.com/earth/outreach/tutorials/screenoverlays.html

**Comment by mcechini** [comment]
Is this an implicit acceptance of Image Download functionality under the Worldview umbrella?  :)

**Comment by rboller** [comment]
Nothing implicit going on here, just a ticket to keep track of several user's requests!  :)

**Comment by minniewong** [comment]
scale bar?

**Comment by edplato** [comment]
From the NRT Global Flood Mapping. I think there is a lot of valuable styling and legend representations here that may be useful as a reference for development of this feature:
https://floodmap.modaps.eosdis.nasa.gov/Products/080W050N/2020/MFM_2020252_080W050N_3D3OT.png
![image](https://user-images.githubusercontent.com/24417194/92628729-45048c00-f29b-11ea-8413-ed1281d8f7be.png)

**Comment by minniewong** [comment]
Waiting on update to Snapshots

**Comment by minniewong** [comment]
Moved to WV-1994
