### ISSUE TITLE
Automate release notes

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#2075]
**Is your feature request related to a problem? Please describe.**
Creating the release notes is tedious / time consuming. Let's investigate packages (or commit-hooks?), that we can use to compile notes based on merged PRs automatically.

**Describe the solution you'd like**
Automatically create a list of merged PRs (title and PR number) that were tagged to a specific release milestone.

**Describe alternatives you've considered**
Continue creating the release notes manually.

**Comment by edplato** [comment]
https://github.com/github-changelog-generator/github-changelog-generator seems like a great solution as a master `CHANGELOG.MD` can be created along with release specific notes. I think adding some new labels for `story` (new story) and `layer`(layer changes) will allow a very similar format to our current release notes.

**Comment by ZachTRice** [comment]
Looks like a good solution. Since it is written in Ruby, I would opt towards using the docker implementation vs the cmd line.
