### ISSUE TITLE
Change api ECHO urls to use CMR

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2077]
**Describe the bug**
Per CMR migration from UTC meeting, ingest traffic being sent to `api.echo.nasa.gov` will need to be sent instead to `cmr.earthdata.nasa.gov` due to future plans to stop supporting redirects.

I see that we use `api.echo.nasa.gov` in a few places for mock data. These should be replaced.

**Comment by jasontk19** [comment]
Are we actually making requests to those URLs in this mock data?  If not, this can probably slip for v3.2.0

**Comment by edplato** [comment]
Investigate how mock data is being used.
