### ISSUE TITLE
Minimize the animation widget

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2081]
**What existing feature could be improved?**
The animation widget covers up valuable map real estate.

**Describe the improvement you'd like**
Be able to minimize the animation widget for a cleaner interface. Minimizing the controls to have only two buttons that play/pause and maximize (return to normal size) would be a clean interface that retains necessary functionality. There is also the option to allow clicking `X` to close the widget and continue playing, but that seems less intuitive as the range draggers need to be removed.

**Comment by jasontk19** [comment]
I like this idea.  I've always thought being able to move this dialog around would be desirable.

**Comment by jasontk19** [comment]
The icons I really want to use for this are not included in the  font-awesome free plan: https://fontawesome.com/icons/compress-alt?style=solid
https://fontawesome.com/icons/expand-alt?style=solid

**Comment by jasontk19** [comment]
![Screen Shot 2019-10-22 at 4 00 43 PM](https://user-images.githubusercontent.com/1480000/67327829-8d318900-f4e6-11e9-8e5c-d3d2509ac07e.png)

**Comment by jasontk19** [comment]
Possible locations for the minimized widget:
![Screen Shot 2019-10-23 at 9 41 19 AM](https://user-images.githubusercontent.com/1480000/67398875-59537380-f579-11e9-8791-7c971126bc9c.png)
![Screen Shot 2019-10-23 at 9 41 41 AM](https://user-images.githubusercontent.com/1480000/67398876-59537380-f579-11e9-849d-d0e5e93c3077.png)
