### ISSUE TITLE
New Layers NSIDC - NISE

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#209]
We've added the following layers to GIBS, now ready for Worldview:

Layer Identifier | Title | Subtitle | CMR product  
--------------- | ---- | -------- | --------------
SSMIS_Sea_Ice_Concentration_Snow_Extent | Sea Ice Concentration and Snow Extent | DMSP 5D-3 F17 / SSMIS | C184437554-NSIDC_ECS

**Comment by mcechini** [comment]
You've got the product id (our internal id) listed instead of the public layer identifier (GC).  That'll condense this down to one row

**Comment by jejeking** [comment]
fixed
