### ISSUE TITLE
KMZ files no longer load in Global Mapper

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2104]
**Describe the bug**
For the past 5 years I have been downloading .kmz format files from https://worldview.earthdata.nasa.gov/?v=-118.10934495208099,29.755569837637477,-111.07809495208099,33.26194319290063&t=2019-08-25-T02%3A00%3A00Z&l=MODIS_Aqua_CorrectedReflectance_Bands721(hidden),MODIS_Terra_CorrectedReflectance_Bands721

I have then opened the file in Global Mapper and converted the file to .ecw format.

Sometime in the past two weeks the files started showing up with long file names and may be compiled differently, anyway since that time I have not been able to open the files in Global Mapper. They do still open in Google Earth. I have submitted a technical request to Global Mapper but since the change did not happen with a change in software, I am thinking the problem may be with the file structure.

The file name format changed recently. Formerly, the file generated by a snapshot form the site would have been named "snapshot.2019-09-03.kmz". The "T00_00_00z" addition seems to have coincided with the .kmz files not opening properly in Global Mapper."

**Expected behavior**
THE KMZ file should load in the Global Mapper GIS software.

**Additional context**
Go to Kayako ticket #97256 for more information. You can download the Global Mapper software for evaluation (windows only).

**Comment by minniewong** [comment]
There is additional information from that user today in the kayako ticket #97256

**Comment by edplato** [comment]
This issue is related to file naming on the server side. The old format used the date `2019-08-25` in the naming, but with the incoming geostationary times the new format uses `2019-08-25T00:00:00Z` and Windows considers `:` invalid for file names.

**Comment by mike-mcgann** [comment]
This will be in Worldview Snapshots v1.4

**Comment by minniewong** [comment]
Another user has reported this issue today kayako #97682
