### ISSUE TITLE
Frames count for animated gif disabling isn't always accurate

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2108]
**Describe the bug**
When creating an animated GIF you are able to work around the 40 frame limit and create a GIF with over 40 frames, previously this was not permitted.  

**To Reproduce**
1. Go to Worldview
2. Click on Animation icon
3. Change the month to August, see message "Too many frames were selected. Please request less than 40 frames if you would like to generate a GIF." and the create GIF icon is greyed out. 
4. Change the month back to September and create GIF icon is no longer greyed out. Press Play, then press Pause.
5. Change the month to August. This time, the message does not appear and the create GIF icon is not greyed out. Now you are able to create a GIF with over 40 frames.

**Expected behavior**
User should not be able work around the 40 frame limit.

**Screenshots**
Able to create a GIF with over 40 frames: 
![Screen Shot 2019-09-10 at 9 46 52 AM](https://user-images.githubusercontent.com/10747923/64619349-f08caf00-d3af-11e9-8520-53cf6b8651ba.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by jasontk19** [comment]
There is definitely _some_ bug here but, it doesn't look like you are able to actually work around the limit, from what I can tell.  The number of days between 8/3/2019 - 9/10/2019 is only 38.

**Comment by minniewong** [comment]
ooh - so that means the bug is that when I change it to Aug, it think it's more than 40 frames when it's only 38, but if i go back and change it to September, and back to August again, it realises it's less than 40 frames...??

**Comment by jasontk19** [comment]
Yeah, at a glance I noticed the `startDate` it's looking at to calculate the number of frames isn't always right.  I will probably hold off on this one until I finish up other v3.2.0 tasks

**Comment by jasontk19** [comment]
Looking at this again more closely, I think this is fine.  I haven't been able to get the button to enable when the frame count is 40 or greater. @minniewong are you able to reproduce an issue here?

**Comment by minniewong** [comment]
@jasontk19 can't reproduce it anymore, so i'd say we can close this ticket.
