### ISSUE TITLE
Add a new tab for featured layers

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2125]
**What existing feature could be improved?**
Layer Picker

**Describe the improvement you'd like**
In the Layer Picker, add a new tab to show off new/featured imagery.

**Comment by jasontk19** [comment]
What if we showed the "measurements" view like this?
![Screen Shot 2019-09-25 at 4 18 09 PM](https://user-images.githubusercontent.com/1480000/65636370-246ef380-dfb0-11e9-83c6-9922ac1771a9.png)

**Comment by jasontk19** [comment]
Here's an example with multiple measurements:
![Screen Shot 2019-09-26 at 9 48 37 AM](https://user-images.githubusercontent.com/1480000/65693832-e7a00c80-e042-11e9-8d06-c1440412e062.png)

**Comment by jasontk19** [comment]
And here's what the list of individual layers would look like with just Geostationary:
![Screen Shot 2019-09-26 at 10 06 07 AM](https://user-images.githubusercontent.com/1480000/65695300-46ff1c00-e045-11e9-9e5c-70c8315c330a.png)

**Comment by minniewong** [comment]
Featured tab measurements:
- Geostationary
- Corrected Reflectance
- Fires
- Precipitation (new measurement - include IMERG, GPM, AMSR2)
- Population Density
- Earth At Night
- SST (new measurement - only includes GHRSST layers)
- Land Surface Temperature
- Orbit Tracks

**Comment by jasontk19** [comment]
![Screen Shot 2019-09-27 at 8 14 59 AM](https://user-images.githubusercontent.com/1480000/65768462-0237bb80-e0ff-11e9-9e5f-bbfce690064a.png)
