### ISSUE TITLE
Add alert notification for geostationary imagery

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2126]
Add an alert notification for the new geostationary imagery (like the alert in Events and Comparison). It will contain a link/a way to load the geostationary imagery and update the state of the app.

**Comment by jasontk19** [comment]
I could use some input on the exact wording we want to use for this notification  @rboller @minniewong.

**Comment by jasontk19** [comment]
Here's a sample:
![Screen Shot 2019-09-26 at 12 51 12 PM](https://user-images.githubusercontent.com/1480000/65708354-63f31980-e05c-11e9-92fe-6c8f7a0e829c.png)

**Comment by minniewong** [comment]
"Read more..." will open a window like the Comparison tool alert. It will contain information telling users to change the time increment to 10 min...etc and include a link to product picker featured tab, and do a hacky tour to pre-load imagery and show animation.

**Comment by jasontk19** [comment]
I've pushed demo instances up to GIBS UAT for both discussed approaches:

[Tutorial approach](https://uat.gibs.earthdata.nasa.gov/worldview-dev/tutorial-toast/)

[Modal approach](https://uat.gibs.earthdata.nasa.gov/worldview-dev/geostationary-notice/)
(images don't load)

Let me know what you think @rboller @minniewong
