### ISSUE TITLE
Scrolling in About page should maintain the header/title

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2127]
Scrolling in the Tour modal and About page should behave more like the Layer picker where the header/title and close button are still viewable.

**Comment by Benjaki2** [comment]
fixed by #2198

**Comment by edplato** [comment]
Tour modal appears to be fixed, but About page header/title is not sticky to the top.

**Comment by minniewong** [comment]
Still need to fix the About page
