### ISSUE TITLE
Fix time snapping based on layer intervals

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2129]
**Describe the bug**
Currently, we don't properly snap date/times to actual available times based on intervals for the following layer periods:
* Yearly - Incrementing month/day/minute will issue additional requests
* Monthly - Incrementing day/minute will issue additional requests

I haven't checked some of our more unusual intervals (8 day, etc) but these and others should be investigated. The `datesinDateRanges` and `prevDateInDateRange` functions should be updated to properly handle this snapping.  As of #2041 snapping should be working appropriately for sub-daily products.

**To Reproduce**
1. Load Black Marble layer
2. Set date to 2016-01-01
3. Increment to 2016-02-01 - note that tile requests are made

**Expected behavior**
We should not make requests for tiles at date/times at smaller steps than the defined interval.

**Screenshots**
![Screen Shot 2019-09-13 at 2 24 29 PM](https://user-images.githubusercontent.com/1480000/64885475-45d7f300-d632-11e9-90a0-5a3b9f145de8.png)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Comment by minniewong** [comment]
We had fixed it here: https://github.com/nasa-gibs/worldview/issues/149
