### ISSUE TITLE
Can't tab through time selector to subdaily hour and minutes

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2131]
**Describe the bug**
Can't `TAB` through time selector to subdaily HOUR and MINUTES from DAY.

**To Reproduce**
1. With a subdaily layer loaded, press `TAB` in date selector to cycle through time options
2. Note DAY skips HOUR and cycles back to YEAR

**Expected behavior**
`TAB` cycles from DAY to HOUR when subdaily is active.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jasontk19** [comment]
A couple notes related to this we may want to consider changing/fixing while working this ticket:
* manually entering a value into any time field requires pressing enter to keep changes (this feels unintuitive to me)
* after hitting enter in any of these fields, focus is always shifted back to the year (this also feels unintuitive, if anything I'd expect focus to shift to the next field to the right)
* ideally, when hitting the character limit for a field, the most intuitive behavior is probably to automatically shift focus to the next field to the right

**Comment by edplato** [comment]
Good points. This may be a Windows only thing, but for the first note, `TAB` also works for me to set the field and move to the next one - some keypress might always be necessary for validation/partial dates (want 15, type in 1 and it changes too soon). Though I see if I enter text then click outside onto the map, it doesn't save and should. For the second point, my focus goes to the field to the right like pressing `TAB` and cycles back to YEAR only when originally focused on DAY.

The third point can probably be wrapped into working on  #1662 which is related to revamping the way dates are validated to be a little more forgiving while inputting time parameters.
