### ISSUE TITLE
dd.urs.3 - 6: Download swath map doesn't update right away

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#214]
Sometimes you have to go past the previous year to get the map to update - Firefox OS X

**Comment by mike-mcgann** [comment]
I'm unable to reproduce this issue. Can you check to see if is still a bug?

**Comment by minniewong** [comment]
May have been associated with timeline bug where the map wouldn't update when you changed the year. Might have been fixed by #761
