### ISSUE TITLE
Vector style enhancements for initial release

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2144]
Style enhancements to vector products

**Sidebar**
- [x] bring legend out of setting dialog and into sidebar

**Map**
- [x] Show list of data instead of metadata for only top item clicked
- [x] if selected item in layer list is removed, remove selection
- [x] remove selected on proj change
~- [x] Hover interaction - add border or enlarge point~
- [x] Maybe add cursor change instead of actual map style change on hover
- [x] Emphasize selected point by adding a border 
- [x] add gradient to selected border
~wrap imagery~
- [x] Prevent click after map drag

**Dialog**
- [x] tabs for multi-layers, vertical
- [x] Make it so dialog doesn't reset location if already open. 
- [x] make it so you can click out of dialog
- [x] show valuemap value for relevant attributes
- [x] maybe format numbers
- [x] fix tooltip's hover flashing bug
- [x] change `bg` color to `white`
- [x] bigger modal (resize?)
- [x] start dialog in position that does not cover selected point
- [x] Make selected points stand out more
- [x] replace attribute title with intended title in json
- [x] possibly(Definitely) show units
- [x] ordering (either GIBS or in wv-config)
- [x] cell is th: replace with body cells
- [x] fix drag lag
- [x] set max number of tabs (or see if stacking works)
- [x] move `(i)` component to start of row
- [x] add simplebar scrolling
- [x] prevent uppercasing units
- [x] scrollbar not showing up in some cases

**Comment by mcechini** [comment]
We also need to discuss what to do with https://bugs.earthdata.nasa.gov/browse/GIBS-3654 in order to support the SEDAC layers specifically.
