### ISSUE TITLE
URL crashes Worldview - may be related to too many layers or a specific set of layers

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2145]
**Describe the bug**
Randomly testing adding layers, I added a few Landsat layers and the app crashed: https://worldview.earthdata.nasa.gov/?l=Reference_Labels(hidden),Reference_Features(hidden),Coastlines,Landsat_WELD_CorrectedReflectance_TrueColor_CONUS_Annual,Landsat_WELD_CorrectedReflectance_TrueColor_CONUS_Seasonal,Landsat_WELD_CorrectedReflectance_TrueColor_CONUS_Monthly,Landsat_WELD_CorrectedReflectance_TrueColor_Alaska_Annual,Landsat_WELD_CorrectedReflectance_TrueColor_Alaska_Seasonal,Landsat_WELD_CorrectedReflectance_TrueColor_Alaska_Monthly,Landsat_WELD_NDVI_Global_Annual,Landsat_WELD_NDVI_Global_Monthly,Landsat_WELD_CorrectedReflectance_TrueColor_Global_Annual,Landsat_WELD_CorrectedReflectance_TrueColor_Global_Monthly,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor

I tried to reproduce locally and it didn't crash until I added one more layer and then it did.

**To Reproduce**
1. Go to [above link](https://worldview.earthdata.nasa.gov/?l=Reference_Labels(hidden),Reference_Features(hidden),Coastlines,Landsat_WELD_CorrectedReflectance_TrueColor_CONUS_Annual,Landsat_WELD_CorrectedReflectance_TrueColor_CONUS_Seasonal,Landsat_WELD_CorrectedReflectance_TrueColor_CONUS_Monthly,Landsat_WELD_CorrectedReflectance_TrueColor_Alaska_Annual,Landsat_WELD_CorrectedReflectance_TrueColor_Alaska_Seasonal,Landsat_WELD_CorrectedReflectance_TrueColor_Alaska_Monthly,Landsat_WELD_NDVI_Global_Annual,Landsat_WELD_NDVI_Global_Monthly,Landsat_WELD_CorrectedReflectance_TrueColor_Global_Annual,Landsat_WELD_CorrectedReflectance_TrueColor_Global_Monthly,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor)
2. If crashed, see error, if not add a layer and see crash/error

**Screenshots**
Development console error:
![image](https://user-images.githubusercontent.com/24417194/65169752-34695f00-da15-11e9-80f7-f98a9ff32100.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jasontk19** [comment]
Hmmmm... I opened the app with those params and was able to add about 30 more layers without issue.  Not sure what caused this but I don't think it's related to number of layers necessarily.

**Comment by edplato** [comment]
Maybe I had a few dozen tabs open or something. I can't reproduce this issue now either - tested on two different machines. Closing.
