### ISSUE TITLE
Add SPoRT Imagery

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#2147]
The following (subdaily!!!) layers can be added to the next release of Worldview.

- GOES-East_ABI_Band2_Red_Visible : Red Visible (0.64 µm, Band 2, ABI, GOES-East)
- GOES-West_ABI_Band2_Red_Visible : Red Visible (0.64 µm, Band 2, ABI, GOES-West)
- Himawari_AHI_Band3_Red_Visible : Red Visible (0.64 µm, Band 3, AHI, Himawari)
- GOES-East_ABI_Band13_Clean_Infrared : Clean Infrared (10.3 µm, Band 13, ABI, GOES-East)
- GOES-West_ABI_Band13_Clean_Infrared : Clean Infrared (10.3 µm, Band 13, ABI, GOES-West)
- Himawari_AHI_Band13_Clean_Infrared : Clean Infrared (10.3 µm, Band 13, AHI, Himawari)
- GOES-East_ABI_Air_Mass : Air Mass (ABI, GOES-East)
- GOES-West_ABI_Air_Mass : Air Mass (ABI, GOES-West)
- Himawari_AHI_Air_Mass : Air Mass (AHI, Himawari)

Info on Band 2/3 [here](https://www.star.nesdis.noaa.gov/GOES/conus_band.php?sat=G16&band=02&length=24#targetText=About%20Band%202,clouds%20throughout%20the%20daylight%20hours.)
Info on Band 13 [here](https://www.star.nesdis.noaa.gov/GOES/conus_band.php?sat=G16&band=13&length=24#targetText=About%20Band%2013,retrievals%20of%20cloud%20top%20height.)
Info on airmass [here](https://nasasporttraining.files.wordpress.com/2015/12/quickguide_airmassrgb_nasa_sport.pdf)

**Comment by minniewong** [comment]
Need to deploy snapshots to get image download working

**Comment by minniewong** [comment]
Change endpoint before going to production
