### ISSUE TITLE
Unable to click and use the scroll bar in Layers list (windows/edge)

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2170]
**Describe the bug**
The scroll bar for the layers box on the left side of Worldview does not work (Right click, hold, drag the scroll bar does not work; mouse wheel scroll works fine) with Windows 10, Microsoft Edge browser.

**To Reproduce**
1. Go to Layers; add lots of layers
2. Click and drag scroll bar on the right
3. See error

**Expected behavior**
Should be able to use the scroll bar when clicking and dragging up and down as well as the mouse scroll.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Comment by edplato** [comment]
This might be fixed in an update to `simplebar` #1956 .
