### ISSUE TITLE
Render vector conditional styling in settings dialog

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2180]
**Describe the bug**
Conditional vector legends are rendered correctly in settlings dialog

**Screenshots**
<img width="633" alt="Screen Shot 2019-10-01 at 2 22 54 PM" src="https://user-images.githubusercontent.com/3605988/65989958-ae0f3d00-e458-11e9-9116-128b398904c6.png">
<img width="215" alt="Screen Shot 2019-10-01 at 2 32 27 PM" src="https://user-images.githubusercontent.com/3605988/65989968-b0719700-e458-11e9-9f72-2565b920c1db.png">

**Comment by ZachTRice** [comment]
Probably should have it loop through each circle-color condition and output each color in the settings panel? Each set of styles (based on IDs) would be a different selectable set of colors.

**Comment by Benjaki2** [comment]
That's what I was thinking but I think for this first release we are just going to show the corresponding colors without the option to toggle.

**Comment by Benjaki2** [comment]
<img width="642" alt="Screen Shot 2019-10-01 at 5 51 54 PM" src="https://user-images.githubusercontent.com/3605988/66003510-49fa7200-e474-11e9-86a0-d139d29ca8ca.png">
@mcechini

**Comment by mcechini** [comment]
Looks good to me
