### ISSUE TITLE
Projection button does not appear in IE 11

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2200]
**Describe the bug**
The projection button does not appear in IE 11, Windows 10 Enterprise. User was able to see the button in Firefox. 

**Expected behavior**
The projection "globe" button should appear in the top right corner. 

**Desktop (please complete the following information):**
 - OS: Windows 10 enterprise
 - Browser: IE 11

**Comment by edplato** [comment]
I am able to see and interact with it in production and develop with IE11 v11.2046.15063.0.

**Comment by jasontk19** [comment]
I wasn't able to reproduce this on IE11 or IE10
