### ISSUE TITLE
Be able to see and interact with multiple notification alerts at once

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2209]
**What existing feature could be improved?**
In the event of multiple notification alerts, they should all be visible. Currently, the alerts are occupying the same space and covering each other up. I think stacking them would be more useful to prevent mis-clicks/accidental dismissals . We may also want to investigate mobile notification alerts due to limited space available.

**Additional context**
![image](https://user-images.githubusercontent.com/24417194/66224118-1c474000-e6a3-11e9-87de-f10d9a166b95.png)

**Comment by jasontk19** [comment]
Looks like there is enough space to fit two alerts comfortably if we move the zoom in/out down a little bit.
<img width="802" alt="Screen Shot 2019-10-18 at 3 39 50 PM" src="https://user-images.githubusercontent.com/1480000/67123174-8ab8f180-f1bd-11e9-9495-5125135f5ad7.png">
