### ISSUE TITLE
Unnecessary legend tick marks for certain layer(s)

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2216]
**Describe the bug**
`MODIS_Terra_Cloud_Top_Pressure_Day` shows layer legend tick marks. May need to investigate other similar layers to check for tick marks.

**To Reproduce**
1. Add `MODIS_Terra_Cloud_Top_Pressure_Day` and see legend in layer list

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/66234727-6c7ecc00-e6bc-11e9-8e09-e0687641e1ba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome/IE11

**Comment by minniewong** [comment]
Also affected: Cloud Fraction, Cloud Top Height, Cloud Top Temperature
