### ISSUE TITLE
IE11 measure tool modal positioned in upper right

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2218]
**Describe the bug**
The measure tool modal is positioned in the upper right for IE11.

**To Reproduce**
1. Open measure tool modal in IE11

**Expected behavior**
Modal opens above measure tool button (like Chrome).

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/66316260-5bfd6a00-e8e5-11e9-8cba-0f1faf2cc383.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE11

**Comment by jasontk19** [comment]
I used browserstack to try to reproduce this on Windows 10/IE11 and Windows 7/IE11 but was not able to reproduce. 🤔

**Comment by jasontk19** [comment]
Disregard previous message... I see it now.
