### ISSUE TITLE
Running data style bug (firefox)

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2224]
**Describe the bug**
Running data bar not aligned with triangle

**Screenshots**
<img width="286" alt="Screen Shot 2019-10-07 at 9 57 37 AM" src="https://user-images.githubusercontent.com/3605988/66323300-37a38c80-e8e9-11e9-9ccc-284f822aa492.png">

**Desktop (please complete the following information):**
 - OSX
 - Browser: Firefox
 - 3.2 SIT

**Comment by jasontk19** [comment]
Maybe also worth including here, I've seen an issue where when you hover over a pixel that has a very low value, the indicator goes outside the bar:
![Screen Shot 2019-10-07 at 11 03 20 AM](https://user-images.githubusercontent.com/1480000/66323727-39258280-e8f2-11e9-9594-3cc3b390f4d1.png)

**Comment by Benjaki2** [comment]
Good call

**Comment by Benjaki2** [comment]
@jasontk19 in what browser are you seeing that happen?

**Comment by jasontk19** [comment]
Was seeing this in Chrome

**Comment by jasontk19** [comment]
I'm wondering if you just weren't hovering over a pixel with a low enough value?

I was able to see this on SIT in both Chrome and FF just now.  Here's a wayyy zoomed view of a low value that should trigger this issue: https://worldview.sit.earthdata.nasa.gov/?v=-102.5059000489823,33.012093155273426,-102.1543375489823,33.19583949316405&t=2019-10-06-T19%3A33%3A02Z&l=MODIS_Terra_Aerosol,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor

**Comment by Benjaki2** [comment]
I was able to replicate it now by zooming the browser out. It looks like this exists on production.
