### ISSUE TITLE
Improve event icon colours

### ISSUE THREAD

**Issue by CodeMacabre** [nasa-gibs/worldview#223]
The event icons colours don't match particularly well (brightness and saturation is inconsistent). Two possible solutions:

## General palette adjustments
Amend saturation make icons match better:
![Adjusted colours](https://cloud.githubusercontent.com/assets/19981049/24460514/6c888e5c-1496-11e7-8c63-e0cd44f7d9a9.jpg)
The main problem with this is that there are 9 different blues!

## Categorise events
Put icons into categories and assign a colour to each category rather than individual icons (ice, weather, misc., water, earth and fire respectively):
![Category colours](https://cloud.githubusercontent.com/assets/19981049/24460515/6c8c2882-1496-11e7-9800-07e481daf8e1.jpg)
The categories do look nice, but have potential issues:
+ Less readable
+ Some events cross categories (should sea-ice be classified as water or ice? / should volcano be classified as fire or earth?)

Which do you prefer?

**Comment by rboller** [comment]
Hi @CodeMacabre, we've discussed it and think the approach listed as "General palette adjustments" would be most appropriate since these categories will be viewed independently in the events list.  Thanks for the idea!

**Comment by CodeMacabre** [comment]
@rboller Agreed, I think they're better too. Should I PR into the `master` branch?

**Comment by rboller** [comment]
Will defer to @Benjaki2 on this one - what do you think, Ben?

**Comment by Benjaki2** [comment]
Yep, a PR into `master` would be great. Thanks @CodeMacabre
