### ISSUE TITLE
[dd.mob.1] Data download tab shows on tablets 

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2241]
**Describe the bug**
Data download tab shows on mobile

**To Reproduce**
1. Open app on iPad

**Expected behavior**
Data download tab not shown on mobile

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari

**Comment by jasontk19** [comment]
This is working fine on actual mobile devices (when screen width is narrow enough to be considered "mobile").  However, the data download tab shows when on larger touch devices like an iPad.  Should we disable this tab in those cases?  Is there a use case for data download on tablets?  I'm guessing not but would like to confirm. @ZachTRice @rboller

**Comment by ZachTRice** [comment]
Deferring to @rboller
