### ISSUE TITLE
Strange display of tick marks for cloud top pressure layer [layer.active.15]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2242]
**Describe the bug**
Strange display of tick marks for cloud top pressure layer

**To Reproduce**
1. Go to `/?t=2013-05-15-T00%3A00%3A00Z&l=MODIS_Terra_Cloud_Top_Pressure_Day,MODIS_Terra_Brightness_Temp_Band31_Day`

**Expected behavior**
There should be no ticks for layers that have less than 100 bins

**Screenshots**
<img width="317" alt="Screen Shot 2019-10-08 at 11 45 11 AM" src="https://user-images.githubusercontent.com/3605988/66415642-ad7b2700-e9c1-11e9-8f91-e1d849651563.png">

**Desktop (please complete the following information):**
 - OSX
 - Browser: Firefox
 - Version: v3.2.0-rc.3

**Comment by jasontk19** [comment]
Looks like the same as #2216

**Comment by Benjaki2** [comment]
It is. closing.
