### ISSUE TITLE
Geostationary alert is shown over active layers in mobile [layer.mob.init.2]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2248]
**Describe the bug**
* Geostationary alert is shown over active layers in mobile 
* Alert prevents user from being able to click layers button in smaller mobile views 

**Screenshots**
**browserstack iphone 8 (12)**
<img width="450" alt="Screen Shot 2019-10-08 at 3 19 55 PM" src="https://user-images.githubusercontent.com/3605988/66430429-bda1ff00-e9df-11e9-91e9-37e2d489f156.png">
**OSX Firefox resized**
<img width="579" alt="Screen Shot 2019-10-08 at 3 17 56 PM" src="https://user-images.githubusercontent.com/3605988/66430441-c4c90d00-e9df-11e9-9582-e7bd67371f5a.png">

**Comment by jasontk19** [comment]
I just figured users would dismiss the alert to get it out of the way.  I guess a more conventional approach to alerts/notices on mobile would be to have it show above everything else and push the rest of the app down but that seemed like more trouble than it was worth for this one alert.

Any thoughts on how best to address this for the v3.2.0 release @Benjaki2 @edplato @ZachTRice ?

**Comment by ZachTRice** [comment]
For v3.2, I'm of the opinion that the user can just dismiss the alert if it is in the way.

I'm on the fence about whether or not moving it to the top is the best long-term solution. We can look at addressing the change after the v3.2 release. The current position is not a blocker since it is a dismiss-able alert.

**Comment by edplato** [comment]
I'd be for a more in your face mobile modal alert that overlays the whole app and includes a 0.5 opacity overlay (or something similar) so the user can't avoid addressing the alert to start interacting with the app. This could also allow positioning that is right up against the top of the viewport making things (hopefully) easier for different mobile devices.

Example, but positioned differently: https://getbootstrap.com/docs/4.0/components/modal/#live-demo

**Comment by edplato** [comment]
Extra clicks would add some friction to getting started. Another option is for all mobile notifications (maybe even for desktop as well for previously dismissed alerts?) to share the same space as the notifications info. That way, the user can see the little yellow badge and if they want to go deeper and get to notifications then they can.
