### ISSUE TITLE
Relative Humidity layers no longer exist [dd.multi.1]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2249]
**Describe the bug**
These layers are in the test plan [dd.multi.1] but have been removed from the config. 

**To Reproduce**
1. Go to `?v=-183.22738486842104,-53.3906245,20.368009868421055,59.8125005&t=2013-09-29-T00%3A00%3A00Z&l=AIRS_RelativeHumidity_700hPa_Night,MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,AIRS_RelativeHumidity_700hPa_Day,Coastlines`
4. See error: AIRS_RelativeHumidity_700hPa_Day is not there

**Additional context**
Do we want to add something to the config so old permalinks will show the new layers or do we just update the test plan?

**Comment by minniewong** [comment]
@Benjaki2 - We should just update the test plan. This release has the new RH layers

**Comment by minniewong** [comment]
Test plan updated for dd.multi.1 and dd.multi.2
