### ISSUE TITLE
Share-Link Cursor

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#227]
After share-link is shortened the cursor stays a pointer when selecting text.

**Comment by CodeMacabre** [comment]
@Benjaki2 I believe I've figured out why this is happening, but I'm unable to test as I keep getting an 'unable to shorten' error. Is this a temporary issue with the CGI script or have I found a new bug?

**Comment by Benjaki2** [comment]
It's a script limitation. The shortening of the link is a service that can only be done on specific domains. Feel free to create a pull request, I will review and try to test it out on one of our test instances.

Thanks @CodeMacabre !

**Comment by CodeMacabre** [comment]
@Benjaki2 This is fairly tricky without being able to test, so rather than figure out *why* the bug occurs and fix in that direction, I've just added a `cursor: text` to the share link `input` element. That should do it, but let me know if not.

**Comment by Benjaki2** [comment]
Works!
