### ISSUE TITLE
Fix/disable palette adjustments for Clean Infrared layers

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2274]
Adjusting the palette for our upcoming geostationary Clean Infrared layers doesn't behave as expected.  Only the grayscale areas of the original palette are updated while the rainbow portion remains unchanged. In this example, I changed to the `Orange 1` palette but the layer isn't completed updated:

<img width="857" alt="CleanIR-palette" src="https://user-images.githubusercontent.com/7243823/66849607-2ab81600-ef45-11e9-89b8-41ec2650dd4f.png">

Given our near-term release, this ticket is to at least disable palette adjustments for this set of layers but to also keep the original colorbars visible.  And if it's easy enough to fully fix, then let's of course go ahead and do that.

Note that there are three Clean Infrared layers which need to be addressed: GOES-East, GOES-West, and Himawari-8.

**Comment by jasontk19** [comment]
This appears to be zoom level dependent. If you zoom in far enough, the results look correct.

![Screen Shot 2019-10-15 at 2 33 22 PM](https://user-images.githubusercontent.com/1480000/66861745-8db5a700-ef5d-11e9-85b6-79d67c82bda0.png)
![Screen Shot 2019-10-15 at 2 33 30 PM](https://user-images.githubusercontent.com/1480000/66861746-8db5a700-ef5d-11e9-90e2-e71c17eec316.png)

**Comment by jasontk19** [comment]
I believe this is happening because the color map has repeating colors.  Note that a gradient from grey and black represents the 19ºC to 57C range but, also represents the -80ºC to -67ºC range. 

![Screen Shot 2019-10-17 at 10.02.33 AM.png](https://images.zenhubusercontent.com/5d41d84f1325bafe06ddabb7/be5ee03f-1888-45a3-83dc-0a6129116e72)
