### ISSUE TITLE
Update GOES and Himawari "Red Visible" layer identifiers

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2280]
GIBS will be updating their layer identifiers for the GOES and Himawari `Red Visible` products from

1. GOES-East_ABI_Band2_Red_Visible
2. GOES-West_ABI_Band2_Red_Visible
3. Himawari_AHI_Band3_Red_Visible

to:

1. GOES-East_ABI_Band2_Red_Visible_1km
2. GOES-West_ABI_Band2_Red_Visible_1km
3. Himawari_AHI_Band3_Red_Visible_1km

since we're planning to have a 500km version of these layers in the future and these 1km products will eventually be deprecated.  See GIBS-3849 for more info and coordination.

**Comment by minniewong** [comment]
Rebuild Snapshots after this is updated too

**Comment by rboller** [comment]
Snapshots has been updated and confirmed working.
