### ISSUE TITLE
Available imagery date/time is too long

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2285]
**What existing feature could be improved?**
When there is no imagery available for a layer, a no entry sign appears and when you hover over the sign it shows the date/time where the imagery is available. It's currently showing too much information.

![Screen Shot 2019-10-16 at 1.08.42 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/eb135055-0ea0-4f6d-b21c-72ddfe0c37ef)

**Describe the improvement you'd like**
Make the information more concise - report the time as HH:MM Z or HH:MM UTC.

**Comment by StephanJW** [comment]
In the example layer posted in your screen capture @minniewong , Red Visible (0.64um...), it's layer period is marked as sub-daily, hence it ignores the if block and we get the long timestamp.

Code here:
![image](https://user-images.githubusercontent.com/583793/73307743-d29fd980-41ec-11ea-9333-e2089982cd27.png)

 Is there any reason for displaying the date in a different format depending on the layer period when that period does not equal **sub-daily**?

For dailys, we have: 28 August 2019
For sub-dailys, we have: Sat Aug 28 2019 10:00:00 GMT -0400 (Eastern Daylight Time)

Would it be better to consistently match the date time with the date time picker below:
![image](https://user-images.githubusercontent.com/583793/73307393-22ca6c00-41ec-11ea-980d-8e102bda2b2b.png)

Such that, regardless of the period type, we just output the following:
**2019 Aug 28 00:00 Z** (dailys)
**2019 Aug 28 10:00 Z** (sub-dailys)

**Comment by minniewong** [comment]
@StephanJW: I think it would be preferable to have it reported as "HH:MM Z or HH:MM UTC" for sub-daily layers, but to not report a time for daily (or other temporal periods). In some cases I don't think we don't actually know the start time/it's not reported in the GetCapabilities doc.

**Comment by StephanJW** [comment]
#2616 resolves the above issue.
