### ISSUE TITLE
Remove seconds from the animated GIF

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2287]
**What existing feature could be improved?**
The timestamp in the animated GIF shows "YYY-MM-DDTHH:MM:SSZ." 

**Describe the improvement you'd like**
I think we could remove the "T" and instead leave it as a space; also remove seconds - "YYYY-MM-DD HH:MMZ" 

**Describe alternatives you've considered**
You could also keep the "T" in, and just remove the seconds. 

![nasa-worldview-2019-10-16T00_00Z-to-2019-10-16T00_02Z.gif](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/f1235745-0ca5-4790-8fbe-5b03569ab448)

**Comment by Benjaki2** [comment]
@minniewong should we take out minutes and hours when we incrementing by day/month/year?

**Comment by minniewong** [comment]
Seems like that would make sense - we could discuss with the team today?
