### ISSUE TITLE
Add more whitespace around the GIF results

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2288]
**What existing feature could be improved?**
The GIF results box needs some extra whitespace/padding around the text if the image is short, as the text appears to be almost cut off. 

![Screen Shot 2019-10-16 at 1.53.38 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/74532cb7-9e82-42dd-8a62-642ccd28f2be)

**Describe the improvement you'd like**
Add some spacing around the box if the image is short.

**Comment by edplato** [comment]
Download button appears to have lost top padding/margin on certain browsers.
