### ISSUE TITLE
Create static wrap flag

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#229]
related to #163 and #361

**Comment by minniewong** [comment]
related to #163

**Comment by rboller** [comment]
Once static wrap flag is in place, @jschmaltz suggested the following layers as a starting point:

Blue Marble*
Land/Water Map
Land Mask
Global 250m Water Map
MODIS Areas of No Data
SEDAC layers
Latitude-Longitude Lines
Reference Layers*
GDEM*

(his message didn't indicate what the asterisks meant)

**Comment by minniewong** [comment]
I think the asterisks denote that there are multiple versions of this layer

**Comment by minniewong** [comment]
It is possible to instead use `wrapadjacentdays` but would be better if it was a different flag specifically for static layers
