### ISSUE TITLE
Style sidebar event item to allow for longer titles and prevent wrapping below icon

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2299]
**Describe the bug**
Minor style issue where longer event titles wrap into the left icon area. Allow longer titles without text wrapping below event icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/67045466-58938b00-f0fc-11e9-84f5-baf394a5e167.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by evlnyng** [comment]
Hi! Is it alright if I give this one a shot?

**Comment by jasontk19** [comment]
@evlnyng we'd be glad to have you tackle this one!
