### ISSUE TITLE
Create worldview notification component

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#230]
Pull from EarthData Notification API. The API has three default types of notifications: alerts, outages, and messages that we can use.

**Comment by Benjaki2** [comment]
![screen shot 2017-04-05 at 4 57 03 pm](https://cloud.githubusercontent.com/assets/3605988/25023098/96ccaae6-2066-11e7-82e2-9f4d702874fd.png)

**Comment by Benjaki2** [comment]
# Design Ideas

When there is a notification present that hasn't yet been viewed, the most important notification's (outage > alert > message) icon will become visible in place of the 'i' logo.


![screen shot 2017-04-05 at 4 57 03 pm](https://cloud.githubusercontent.com/assets/3605988/25050788/6a357376-2117-11e7-8758-0471d28fcd74.png)
<img width="262" alt="screen shot 2017-04-14 at 1 18 00 pm" src="https://cloud.githubusercontent.com/assets/3605988/25050808/80deb902-2117-11e7-8f23-a2622cc73246.png">
<img width="278" alt="screen shot 2017-04-14 at 10 35 57 am" src="https://cloud.githubusercontent.com/assets/3605988/25050832/98b5d06a-2117-11e7-8bcb-0690a3372fbf.png">

(red == outages ; blue == messages; yellow == alerts)

## Information Dropdown
### Before user sees notifications -- Idea 1
<img width="276" alt="screen shot 2017-04-14 at 11 28 41 am" src="https://cloud.githubusercontent.com/assets/3605988/25050915/017c7702-2118-11e7-8f49-1f859a8e3586.png">

The Notification that takes precedent will be visible in the dropdown

### Before user sees notifications -- Idea 2

<img width="273" alt="screen shot 2017-04-14 at 1 17 28 pm" src="https://cloud.githubusercontent.com/assets/3605988/25050995/76f71e7e-2118-11e7-9600-00f61addb9c1.png">

The dropdown always has the same text ('notifications' or whatever we decide) and the icon/bg-color adjust based on the present notification-type.

### After user sees notifications
<img width="286" alt="screen shot 2017-04-14 at 1 33 34 pm" src="https://cloud.githubusercontent.com/assets/3605988/25051106/fea10e7a-2118-11e7-9d56-9584e39301d0.png">

## Notification box
![notifications](https://cloud.githubusercontent.com/assets/3605988/25051134/227befcc-2119-11e7-8c10-c13fc8e86c31.jpg)

Dropdown item links to this pop-up. The notifications will be ordered by importance and by time of publication amongst notifications of similar types.

Thoughts??? @minniewong @rboller  @CodeMacabre @jschmaltz

**Comment by minniewong** [comment]
i quite like it!

**Comment by Benjaki2** [comment]
:) @minniewong 

After talking the designs over with @rboller . The plan is to isolate the 'messages' type from the other two notification types. 'What's new' will now link to a pop-up that shows the most recent release and shares a link to the list of past releases.

**Comment by CodeMacabre** [comment]
@Benjaki2 Very nice, so it'll become two types of notifications now: messages and outages/alerts? The coloured notification icon is great, certainly grabs attention.

**Comment by Benjaki2** [comment]
@CodeMacabre The messages type will now take over 'What's new' slot (I would like to replace the flag with the fa-gift icon). Currently the 'what's new' is populated [here](https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/brand/pages/new.md).


<img width="264" alt="screen shot 2017-04-17 at 10 40 56 am" src="https://cloud.githubusercontent.com/assets/3605988/25092160/6f4a4ce8-235a-11e7-8bb1-870cb1acd616.png">
(example of what the user will see after a new release)
