### ISSUE TITLE
Exiting comparison mode after moving B dragger doesn't load correct date on timeline

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2303]
**Describe the bug**
Exiting comparison mode after selecting and moving the B dragger results in the previous date being used instead of the currently selected date.

**To Reproduce**
1. Go to comparison mode
2. Click on B dragger and move it a few days
3. Exit while on B dragger and note timeline date change

**Expected behavior**
Exiting comparison mode stays on whatever dragger date the user has selected.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 77.0.3865.120

**Comment by jasontk19** [comment]
I'm not seeing this happen in Firefox/OSX.  When I exit comparison the timeline dragger is always where the A dragger was in comparison mode.

**Comment by edplato** [comment]
It looks like it only affects the B dragger. You also have to change dates on the B dragger and then exit while still in B dragger mode for it to cause bug. I think the issue has something to do with `bStatesInitiated`.
