### ISSUE TITLE
Toggle-able classification color palettes feature

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2306]
**Is your feature request related to a problem? Please describe.**
For our "classification" products (e.g., [Land Cover Type](https://worldview.earthdata.nasa.gov/?v=-157.14074582245814,-38.752295066979784,2.1873791775418425,79.09951095660911&t=2018-10-18-T15%3A52%3A14Z&l=Last_of_the_Wild_1995-2004(hidden),GRUMP_Urban_Extents_Grid_1995(hidden),MODIS_Combined_L3_IGBP_Land_Cover_Type_Annual,Coastlines(hidden),Land_Water_Map)), it would be helpful to be able to toggle individual classification values (e.g., "Open Shrublands") on/off to allow the user to focus on the specific values of interest.  

This should be particularly relevant for our upcoming flood extent layer which will include a "cloud mask" value which could be distracting if a user just wants to see the observed flood areas.

**Describe the solution you'd like**
One idea is to make each "classification box" in the legend directly toggle-able.  Another would be to open the layer's setting panel and toggle it there.

**Additional context**
Eventually we'll also want the ability to toggle transparent flags for certain layers (#115).  This ticket is also remarkably similar to #232 and we'll want to talk through any differences and possibly combine them or close one as a duplicate.

**Comment by Benjaki2** [comment]
First look:
<img width="575" alt="Screen Shot 2020-01-04 at 8 27 18 PM" src="https://user-images.githubusercontent.com/3605988/71774004-28a69780-2f35-11ea-8522-ec7d17bd7e7b.png">

![toggle_classes](https://user-images.githubusercontent.com/3605988/71774011-3eb45800-2f35-11ea-936c-9cc5d32c39bd.jpg)
