### ISSUE TITLE
The previous UTC date should be displayed when before 3:00 UTC

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2311]
**Describe the bug**
The previous UTC date should be displayed when before 3:00 UTC so that imagery is visible to the user on load
**To Reproduce**
1. Go to homepage before 3:00 UTC

**Screenshots**
<img width="1268" alt="Screen Shot 2019-10-18 at 9 20 09 PM" src="https://user-images.githubusercontent.com/3605988/67136531-201faa00-f1ed-11e9-89eb-73df52f0d65f.png">

**Additional context**
Looks like it was probably introduced in `v3.0.0`

**Comment by StephanJW** [comment]
@Benjaki2. Can you take another look at this with the msot recent changes pulled down on develop and also look at production: https://worldview.earthdata.nasa.gov/?now=2020-02-13T02:00:00Z

This all seems to be working as expected...

**Comment by Benjaki2** [comment]
It does look like it's working. So, either the test flag is broken, it wasn't an error, or it fixed itself. I will check this one out during the wee hours to verify.

**Comment by StephanJW** [comment]
Copy that.

**Comment by Benjaki2** [comment]
Issue verified. Screenshot taken at 1:10 UTC FEB 9th.
<img width="1231" alt="Screen Shot 2020-02-18 at 7 11 10 PM" src="https://user-images.githubusercontent.com/3605988/74792264-8b07ed00-5282-11ea-81c2-34cd97d6af94.png">


This means there is something wrong with the `now` flag we use for testing in addition to initial problem @StephanJW
