### ISSUE TITLE
Date selector disappears when accessing Worldview via saved iPhone home screen icon/shortcut

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2318]
**Describe the bug**
"Hey I’ve been using this tool for a long time. All of a sudden my link on home screen doesn’t allow me to change the dates. It’s not even there. When I copy link into safari on phone date change thing is there but when I choose add to home screen on iPhone and it does add icon it disappears. Any suggestion. Here’s screen shots."

**To Reproduce**
1. On an iPhone/safari: Go to https://worldview.earthdata.nasa.gov/?v=-88.2459683699929,30.02512558064909,-87.82136065842614,30.89895594358355&t=2017-01-12-T00%3A00%3A00Z&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,Reference_Labels(hidden),Reference_Features(hidden),Coastlines
2. Click on the share button at the bottom of the browser, click on "Add to Home Screen"
3. Go to your home screen, and click on the new icon on the home screen
4. See error - the date selector has disappeared

**Expected behavior**
The date selector should not disappear when viewing the website via the home screen icon (which is a more full screen mode)

**Screenshots**
![image1](https://user-images.githubusercontent.com/10747923/67326469-96215b00-f4e4-11e9-92f2-cb0a2a153b60.png)
![image0](https://user-images.githubusercontent.com/10747923/67326481-9cafd280-f4e4-11e9-894d-f83652e6eb63.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max 
 - Browser: Safari
 - Version: Latest update from other day (probably 13.1.3)

**Comment by minniewong** [comment]
Can't replicate this problem on iPhone 6 12.4.2

**Comment by jasontk19** [comment]
I see this issue on my iPhone 6S.  I think the iOS or Safari mechanism that supports this functionality is to blame.  The elements at the bottom of the page are absolutely positioned, meaning if the bottom of the viewport really was the bottom of the screen (as it should be) that they would be positioned in relation to this and be visible.  I think the header is pushing the viewport beyond the edge of the screen which causes the date selector not to be visible.  On my device, the top of the measure button is just barely visible.

**Comment by jasontk19** [comment]
I wonder if this is related: 
https://github.com/nasa-gibs/worldview/blob/48eca7aac872b88211ec997945acb62dc80212d5/web/js/polyfill.js#L57-L71

**Comment by jasontk19** [comment]
![IMG_6096](https://user-images.githubusercontent.com/1480000/74039199-7462bb80-498f-11ea-84b6-8418bb9a8ef7.PNG)

**Comment by minniewong** [comment]
Closing as this appears to be fixed now with the updates made to the mobile date picker.
