### ISSUE TITLE
Turn opaque classification values to transparent

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#232]
In addition to ticket #115, which wants the ability to make opaque existing transparent pixels... I think there may be more immediate interest in the ability to make transparent existing opaque pixels associated with ColorMap entries in a 'classification' legend. For example, our new GMI imagery will have a grey background to the swath as a classification value, and it might be nice to turn that off.  

https://worldview.earthdata.nasa.gov/?p=geographic&l=BlueMarble_NextGeneration,GMI_Rain_Rate_Dsc,GMI_Rain_Rate_Asc&t=2017-01-01&z=3&v=-156.21697809278353,-25.334246134020635,9.948614690721627,74.22825386597937

**Comment by rboller** [comment]
@mcechini agreed.  The "zero value" for GMI layers are currently included as part of the main palette but we can make it a classification value in the future which would be easily toggle-able similar to #115.
