### ISSUE TITLE
Zots cause colorbar to shift to the right

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2321]
**Describe the bug**
If you zoom in too far with layers like IMERG Rain Rate and IMERG Precipitation rate and Aura AOD (https://go.nasa.gov/2BDk709) the zots cause the colorbars to shift to the right and become flush with the right side of the layer list. 

**To Reproduce**
1. Go to https://go.nasa.gov/2BDk709
2. See error - when zoomed in and the zots appear, the colorbars shift to the right and become flush with the layer list edge.

**Expected behavior**
A border should be maintained around the colorbar even when the zots come on. 

**Screenshots**
![Screen Shot 2019-10-23 at 3.38.53 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/9f6dcafb-d3a8-4a41-9474-8a9d59c8deeb)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser:Chrome
 - Version: [e.g. 22]

**Comment by jasontk19** [comment]
Somewhat related to this, I am seeing a blank space between the border and the actual colorbar for several layers, regardless of whether or not the zot is showing (can be seen in IMERG - Rain Rate above)
![Screen Shot 2019-12-13 at 2 23 49 PM](https://user-images.githubusercontent.com/1480000/71000451-57a1ba00-20a9-11ea-8bc5-fc5bb9462bd1.png)

**Comment by jasontk19** [comment]
Disregard... just realized that's actually part of the color palette for these layers!
