### ISSUE TITLE
Animted GIF creation with hour interval hangs

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2335]
**Describe the bug**
When trying to create an animated GIF with an hour interval, the process hangs at requesting imagery and no GIF is created.  It looks like the `current` date in `modules/animation/selectors.js:63` is not being updated on each iteration of the while loop. 🤔 

**To Reproduce**
1. Add a geostationary layer
2. Open animation
3. Set interval to hourly
4. Try to create GIF

**Screenshots**
![Screen Shot 2019-10-25 at 1 12 38 PM](https://user-images.githubusercontent.com/1480000/67590506-3bc50c00-f729-11e9-8ca3-6689b9e71ef2.png)

**Comment by edplato** [comment]
I am unable to reproduce in prod/dev. Can you provide any other details on browser/version for debugging?

**Comment by jasontk19** [comment]
Hmmmm... I'm not seeing it now either.

**Comment by edplato** [comment]
Maybe since it seems to be working in prod/dev that this issue was related to your #2361 fix and that fixed this one too.

**Comment by jasontk19** [comment]
That's what I'm thinking... closing this!
