### ISSUE TITLE
Replace date-fns with moment

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2336]
It might make sense to remove this dependency now and use moment.js. Originally, date-fns was used before we introduced moment.js in an effort to use a lighter-weight date library. But, if we are using moment now, there is no point in using both libraries

_Originally posted by @ZachTRice in https://github.com/nasa-gibs/worldview/pull/2317#issuecomment-546428751_

**Comment by edplato** [comment]
Removed in #2572
