### ISSUE TITLE
Production build not able to start locally

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2348]
**Describe the bug**
The app crashes after running `npm run build:prod` and starting the instance locally. Something was introduced/removed in between the latest release and the current develop branch that is causing this crash and console error. Current `master` and `48eca7aac872b88211ec997945acb62dc80212d5` work fine for reference.

1. pull down latest in develop, `npm install`, `npm run build:prod`
2. `npm start` to see app crash and console error

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/67702104-880d8780-f987-11e9-9bbb-e24277cceebe.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 77.0.3865.120

**Comment by jasontk19** [comment]
We should probably modify the Travis jobs that run e2e to use the production build instead of the dev build.  That way we are testing both on each CI/CD build.

**Comment by jasontk19** [comment]
I tracked this down to the following commit which is the first where I'm seeing this error: https://github.com/nasa-gibs/worldview/commit/1f99009c336004e1b20d101a75d47fd5001c1085

When pointing to the previous commit, this issue does not happen:
https://github.com/nasa-gibs/worldview/commit/4de1d06c2491030b0de42a1b6ae0f4be2989c333

I find it hard to believe updating our Chromedriver version would cause this but will keep investigating.
