### ISSUE TITLE
Map crashes when selecting Hurricane Dorian tour story from arctic projection

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2356]
**Describe the bug**
Map crashes when selecting Hurricane Dorian tour story from arctic projection. Does not occur on a couple other tested tour stories that also switch to geographic projection.

**To Reproduce**
1. Select `arctic` projection
2. Click on `Explore Worldview` from the info toolbar menu and select the Hurricane Dorian (September 2019) story
3. See map is black
4. Upon moving the mouse, see console error (screenshot below)

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/67780187-180d0900-fa3c-11e9-8da9-b24b8e5503a3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 77.0.3865.120

**Comment by minniewong** [comment]
Confirmed - this also happens in Chrome OSX
