### ISSUE TITLE
Product picker list position scrolls to top on item select

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2358]
**Describe the bug**
If you open product picker, select all, scroll down, open a measurement tab, the scrollbar jumps back to the top. This is not currently occurring on production.

**To Reproduce**
1. Open Product picker
2. Click "All"
3. Scroll down near the bottom
4. Click any measurement (e.g. Temperature)
5. List scrolls back to the top

**Expected behavior**
List scroll position should not change when an item is clicked.

**Comment by minniewong** [comment]
I'm not seeing this?

**Comment by jasontk19** [comment]
This is happening on `develop`
