### ISSUE TITLE
Typing a value into the date field required a TAB or Enter to save the value

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2359]
**Describe the bug**
When you type in a value into the date/time field, a TAB or Enter is required to save the value. If you type in a value, click on the next value with your mouse, the previous value is not saved. This occurs in the timeline and in the animation widget.

**To Reproduce**
1. Go to the date/time entry field
2. Click on OCT and change it to 07
3. Click on the Day field and see that it did not save the previous value to "07"

**Expected behavior**
Typing/manually entering in a value in the time/date fields and clicking on the next field should save the previous value. 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Additional context**
This was discussed in the comments of #2131 but was not addressed.

**Comment by edplato** [comment]
Related to #1662 as additional input validation considerations arise working on a fix for this issue.
