### ISSUE TITLE
Adding MAIAC layers (4)

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#2373]
[MAIAC ICD](https://docs.google.com/spreadsheets/d/1ewYzXqcd-HtWYMVmaRvnNy2d8_bH-JtOeJQHINXD1BQ/edit#gid=953925495)

[MODIS_Combined_MAIAC_L2G_BidirectionalReflectance_Bands143](https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Combined_MAIAC_L2G_BidirectionalReflectance_Bands143/default/2019-10-31/1km/0/0/0.jpeg)
[MODIS_Combined_MAIAC_L2G_AerosolOpticalDepth](https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Combined_MAIAC_L2G_AerosolOpticalDepth/default/2019-10-31/1km/0/0/0.png)
[MODIS_Combined_MAIAC_L2G_ColumnWaterVapor](https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Combined_MAIAC_L2G_ColumnWaterVapor/default/2019-10-31/1km/0/0/0.png)
[MODIS_Combined_MAIAC_L3_IsotropicKernelParameters_8Day](https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Combined_MAIAC_L3_IsotropicKernelParameters_8Day/default/2019-10-24/1km/0/0/0.jpeg)

**Comment by minniewong** [comment]
@jejeking - the 8-day product only appears every 8 days. Can you fix it so that it appears every day (and only changing images every 8 days).

**Comment by minniewong** [comment]
@jejeking - Clarified issue with the 8-day product and we will fix it on the WV side #2129
