### ISSUE TITLE
New WELD geographic and polar layers

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#2411]
The following layers are now available in GIBS.  Bands157 are meant to be equivalent to the MODIS snow/ice CR product.  Bands 743 equivalent to the MODIS burn scar CR product. More info [here](https://wiki.earthdata.nasa.gov/display/GIBS/WELD+False+Color+Combinations).  Updated ICD is [here](https://docs.google.com/spreadsheets/d/1XN-UXTTmC8Uj9etIsv-wMO2Ni90eZnaGeQYN7ltoUvs/)

## Geographic
Landsat_WELD_CorrectedReflectance_Bands157_Global_Annual
Landsat_WELD_CorrectedReflectance_Bands157_Global_Monthly
Landsat_WELD_CorrectedReflectance_Bands743_Global_Annual
Landsat_WELD_CorrectedReflectance_Bands743_Global_Monthly

## Polar
Landsat_WELD_CorrectedReflectance_Bands157_Global_Annual
Landsat_WELD_CorrectedReflectance_Bands157_Global_Monthly
Landsat_WELD_CorrectedReflectance_TrueColor_Global_Annual
Landsat_WELD_CorrectedReflectance_TrueColor_Global_Monthly

**Comment by minniewong** [comment]
@mcechini - the 157 and True color layers are not in the Antarctic GetCapabilities doc

**Comment by mcechini** [comment]
True.  They are north polar only.

**Comment by mcechini** [comment]
We should also update the version to 3.1 and the informational links.  I sent an email to LPDAAC to see if they can give us that info.

**Comment by mcechini** [comment]
Minnie has the link/abstract information updates in her inbox from LPDAAC.  If you need them in here too, let me know.
