### ISSUE TITLE
Shorten date range when creating dateArray in datesinDateRanges

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2433]
**What existing feature could be improved?**
Optimize the process of creating ranges of available dates when layer building.

- [x]  Shorten date range when creating `dateArray` in `datesinDateRanges` to a smaller, interval appropriate array range of available dates. This currently can be costly CPU for slower machines with long 7000+ day interval arrays being created, for example.
- [x]  While we're here, determine the use case for `def.startDate` and `def.endDate` and check if these ever conflict with the dates found in `def.dateRanges`, and if there are conflicts does any date take precedence.

**Additional context**
Related to the layer request in #2432

**Comment by minniewong** [comment]
Also related to #2540

**Comment by edplato** [comment]
Here are the findings of my investigation of the layer config `def.startDate` and `def.endDate` in each parent layer object (`def`) vs the layer property array `def.dateRanges` which contains its own `startDate` and `endDate` for each included date range. Here are some findings to note:

**Of 928 layers checked:**

**856** layers have`def.startDate`
**244** layers have `def.endDate`
**788** layers have `def.dateRanges`

- Not every layer has a `def.startDate` and `def.endDate`
- Layers that have a `def.startDate` **do not always** have a `def.endDate`
- Layers that have a `def.endDate` **always** have a `def.startDate`
- Layers that have a `def.endDate` **always** have `def.inactive` equal to `true`
- The `def.startDate`, when present, is **always** the same as the earliest `def.dateRanges` date range  `startDate`
- The `def.endDate`, when present, is **sometimes different** than the latest `def.dateRanges` date range `endDate` (128 layers match and 116 are different) . The difference is because the `def.endDate` is the latest date range `endDate` plus the range `dateInterval` added. It should be noted that where the `def.endDate` and date range `endDate` are the same, the layer `period` is `daily` and the `def.dateRanges` length was typically 1, excluding `AMSUA_NOAA16_Brightness_Temp_Channel_1` (and related channels) which contains a larger `def.dateRanges` length of 25 at the time of investigation.

I see value in having consistent `def.startDate` and `def.endDate` added during the building of the layer config. However, a standard should be implemented so functions throughout the app that rely on either of these layer properties are being handled correctly and not repeating layer property lookups and/or date range array traversals.
