### ISSUE TITLE
No way to tell when hovering over a value for single classification palette

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2437]
**Describe the bug**
If a layer has a single color classification palette, we are currently always showing the label next to the colorbox.  With this behavior, there is no way to tell if you are hovering the mouse over a point on the map that matches this value for this layer.

**To Reproduce**
1. Go to https://worldview.sit.earthdata.nasa.gov/?v=46.94546382826535,-17.16228931699522,51.69595210951535,-11.282406504495222&l=MODIS_Combined_Thermal_Anomalies_All,Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor

**Expected behavior**
Label should only show on hover so user can tell if they are hovering over a pixel that matches.

**Screenshots**
![Screen Shot 2019-11-21 at 3 22 55 PM](https://user-images.githubusercontent.com/1480000/69373877-d0f8e900-0c72-11ea-8fb7-e6dda467117f.png)

**Comment by edplato** [comment]
Related, the "Sea Ice" label is now showing up as "Classifications".
![image](https://user-images.githubusercontent.com/24417194/69550019-495bf480-0f68-11ea-8abe-477ea6db51a0.png)

**Comment by jasontk19** [comment]
@ed That should be addressed in the #2443 PR.
