### ISSUE TITLE
Dragging layers in the sidebar doesn't maintain correct drag position

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2445]
**Describe the bug**
Can not consistently reorder layers in sidebar. Dragging layers in the sidebar doesn't maintain correct drag position.

**To Reproduce**
1. Go to main page
2. Drag Aqua CR below Terra CR, and attempt to now drag layers back to original order
3. See Terra CR snap back and not be able to drag under Aqua CR - this can also cause the bottom most layer to not be able to drag.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 78.0.3904.108

**Comment by jasontk19** [comment]
This should already be fixed by #2436
