### ISSUE TITLE
Base default vector metadata modal width on device width for mobile

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2449]
**What existing feature could be improved?**
The existing version of the vector metadata modal is very usable on mobile, but I think there can be a way the modal can be more responsive for mobile devices so that it's easier to close, primarily. Currently, for the devices that I've tested it sometimes requires the user to drag the modal into view to see the `X` close button and be able to close it.

**Describe the improvement you'd like**
For mobile devices, base the initial modal width on the device screen width/orientation. 

**Describe alternatives you've considered**
Another option would be a modal that covers a majority or the entirety of the screen similar to the mobile layer picker.

**Comment by Benjaki2** [comment]
Might also be worth while to prevent the vector point styling when in mobile since it is computationally intensive and you can't see the style changes behind the modal.
