### ISSUE TITLE
Imagery not showing when animating geostationary at an off-10 min mark

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2466]
**Describe the bug**
If you try to set up an animation at an off-10 minute mark such as 13:04 - 15:24, no imagery is shown on the map. If you instead use the advance/forward and back arrows in the timeline, imagery is shown on the map.

**To Reproduce**
1. Go to UAT
2. Click on Add Layers and add GOES East Red Visible
3. Change the time in the timeline to 13:04, change the custom interval to 10 minutes, open the animation panel and click play.
4. See error - no imagery is animated. 
5. Click on the forward/back arrow and see imagery load. Try clicking play again, an no imagery is animated on the map.

**Expected behavior**
Imagery should animate on the map even if you're not on the 10 minute mark. 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by edplato** [comment]
#2462  appears to have addressed this.
