### ISSUE TITLE
Basic install fails: npm

### ISSUE THREAD

**Issue by davidbernat** [nasa-gibs/worldview#248]
[User cmd line]:worldview astrorobotic$ vagrant up --provision
/opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/platform.rb:24: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bkyoung/centos7' is up to date...
==> default: Running provisioner: shell...
    default: Running: /var/folders/m2/g7d083kj5qx0gwfb18vt7stw0000gn/T/vagrant-shell20170408-4336-2scaou.bootstrap
==> default: epel-release-7-9.noarch
==> default: Loaded plugins: fastestmirror
==> default: Loading mirror speeds from cached hostfile
==> default:  * base: mirrors.kernel.org
==> default:  * epel: mirror.sjc02.svwh.net
==> default:  * extras: mirror.lax.hugeserver.com
==> default:  * updates: mirror.pac-12.org
==> default: Package httpd-2.4.6-45.el7.centos.x86_64 already installed and latest version
==> default: Package git-1.8.3.1-6.el7_2.1.x86_64 already installed and latest version
==> default: Package 1:nodejs-6.10.1-2.el7.x86_64 already installed and latest version
==> default: Package 1:npm-3.10.10-1.6.10.1.2.el7.x86_64 already installed and latest version
==> default: Package python-virtualenv-1.10.1-3.el7.noarch already installed and latest version
==> default: Nothing to do
==> default: /usr/bin/grunt -> /usr/lib/node_modules/grunt-cli/bin/grunt
==> default: /usr/lib
==> default: └── grunt-cli@1.2.0 
==> default: Searching for xmltodict
==> default: Best match: xmltodict 0.10.2
==> default: Processing xmltodict-0.10.2-py2.7.egg
==> default: xmltodict 0.10.2 is already the active version in easy-install.pth
==> default: 
==> default: Using /usr/lib/python2.7/site-packages/xmltodict-0.10.2-py2.7.egg
==> default: Processing dependencies for xmltodict
==> default: Finished processing dependencies for xmltodict
==> default: npm WARN @1.4.1 No license field.
==> default: /vagrant/node_modules/coffee-script/lib/coffee-script/lexer.js:55
==> default:       forcedIdentifier = colon || (prev = last(this.tokens)) && (((_ref2 = prev[0]) === '.' || _ref2 === '?.' || _ref2 === '::')
==> default:                                                                                                                                 
==> default: SyntaxError: Invalid or unexpected token
==> default:     at createScript (vm.js:56:10)
==> default:     at Object.runInThisContext (vm.js:97:10)
==> default:     at Module._compile (module.js:542:28)
==> default:     at Object.Module._extensions..js (module.js:579:10)
==> default:     at Module.load (module.js:487:32)
==> default:     at tryModuleLoad (module.js:446:12)
==> default:     at Function.Module._load (module.js:438:3)
==> default:     at Module.require (module.js:497:17)
==> default:     at require (internal/module.js:20:19)
==> default:     at Object.<anonymous> (/vagrant/node_modules/coffee-script/lib/coffee-script/coffee-script.js:10:10)
==> default: /vagrant/node_modules/coffee-script/lib/coffee-script/lexer.js:55
==> default:       forcedIdentifier = colon || (prev = last(this.tokens)) && (((_ref2 = prev[0]) === '.' || _ref2 === '?.' || _ref2 === '::')
==> default:                                                                                                                                 
==> default: SyntaxError: Invalid or unexpected token
==> default:     at createScript (vm.js:56:10)
==> default:     at Object.runInThisContext (vm.js:97:10)
==> default:     at Module._compile (module.js:542:28)
==> default:     at Object.Module._extensions..js (module.js:579:10)
==> default:     at Module.load (module.js:487:32)
==> default:     at tryModuleLoad (module.js:446:12)
==> default:     at Function.Module._load (module.js:438:3)
==> default:     at Module.require (module.js:497:17)
==> default:     at require (internal/module.js:20:19)
==> default:     at Object.<anonymous> (/vagrant/node_modules/coffee-script/lib/coffee-script/coffee-script.js:10:10)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by Benjaki2** [comment]
Thank you for exploring Worldview. The basic install has been problematic for a while now. The problem usually is a response to a dependency releasing a new version. We are trying to simplify the process using a minimalistic node server as opposed to the multi-dependant VM setup we currently have in place. Development can be monitored here #249 .
