### ISSUE TITLE
Concurrency build changes breaks windows build

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2508]
**Describe the bug**
Build changes in #2502 breaks Windows build. I am getting the errors as can be seen starting at the line linked in this [Travis Job #9150.7](https://travis-ci.org/nasa-gibs/worldview/jobs/624204863#L452)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by edplato** [comment]
Looks like this is a known error that needs some additional wrapping for Windows multiprocessing: https://pytorch.org/docs/stable/notes/windows.html#usage-multiprocessing

**Comment by jasontk19** [comment]
Oh nooo
