### ISSUE TITLE
When changing tour step, give option to close a popup box or to keep it open

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2539]
**What existing feature could be improved?**
While creating a vector tour story, I noticed that if have a vector layer loaded and I open the attribute table pop up box in one step, it remains open in the next step. I would like to have the option to either say that I want that box to be closed for the next tour step, or remain open for the next tour step. e.g. i would like the attribute table box I opened in step 4 to be closed in step 5.  Maybe it can be defined as an 'action' in the json file? wv.json/stories/default/vectors_intro.json on vector-tour-story branch.

**Comment by Benjaki2** [comment]
@minniewong It's easy to force modals to close when clicking through a tour but keeping some open and closing others is harder to implement. For example, in this vector case we aren't going to know if the user opened that modal or kept it open before going to the next step. 

Possible options:
1.  There could be an `acceptable_modals` param containing modal `IDs` that could persist. 
2. We could potentially pass a vector feature ID in the parameters and have the modal open completely independent of the previous tour step.

**Comment by minniewong** [comment]
The fix going into v3.4.0 will force the modals to close. We can revisit this if we want other functionality.
