### ISSUE TITLE
Add warning message to indicate snapshot area of interest has crossed the dateline

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2549]
**What existing feature could be improved?**
Add warning to users to indicate the snapshot area of interest has crossed the dateline so that they are aware the date they have currently selected on the timeline may not coincide with the date of the image they are about to download. An example of the problem is taking a snapshot of Australia on the very west of the map, beyond the standard map extent, and over the dateline; the actual image returned will be 1 day in the future from the day selected on the timeline.

**Describe the improvement you'd like**

Discussed options include:
- Conditional message that shows in the image panel when the snapshot area of interest is over the dateline. This message can potentially include text that warns users of the +/- 1 day discrepancy that crossing the dateline causes.

**Comment by jasontk19** [comment]
Snapshot download filename should show correct date/time as well for all file types.   Currently only shows for GeoTIFF
