### ISSUE TITLE
[technique question] What is the structure of this red dot.

### ISSUE THREAD

**Issue by Malgus1995** [nasa-gibs/worldview#2578]
![image](https://user-images.githubusercontent.com/43834887/72774949-ec22ad80-3c4f-11ea-8874-957ae71f8a19.png)

It seems like using open layer's clustering library.. 
But i really want to know the source section when i added some layers in the map of world view.

the source is too enormous to me.. So if you fine to teach me, then.. i want to know the directory, and source code which use add layer and lay the cluster on map.

**Comment by jasontk19** [comment]
The red dots seen here are actually just a transparent tile layer which is being placed on top of a standard imagery layer.  We request map tiles via WMTS from GIBS (NASA's Global Imagery Browse Service)  If you check out your browser's network tab in the developer tools, you'll see a bunch of requests being made for individual map tiles as you pan/zoom around the map.  

![Screen Shot 2020-01-22 at 2 28 08 PM](https://user-images.githubusercontent.com/1480000/72927019-6ff99a00-3d23-11ea-8dbd-11080e856ab7.png)

For example, a request which returns a single map tile with red dots on it would be:
 [https://gibs-b.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?TIME=2020-01-22T00:00:00Z&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=VIIRS_SNPP_Thermal_Anomalies_375m_Day&WIDTH=256&HEIGHT=256&SRS=EPSG%3A4326&STYLES=&BBOX=36%2C18%2C72%2C54](https://gibs-b.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?TIME=2020-01-22T00:00:00Z&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=VIIRS_SNPP_Thermal_Anomalies_375m_Day&WIDTH=256&HEIGHT=256&SRS=EPSG%3A4326&STYLES=&BBOX=36%2C18%2C72%2C54)

For a simplified example of a map using WMTS with OpenLayers, check out this example: https://openlayers.org/en/latest/examples/wmts.html

**Comment by Malgus1995** [comment]
Oh thanks for detail describe!  Then Can i add one more question?
