### ISSUE TITLE
Can't drag luxor past what is visible on timeline [date.pick.13]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2579]
**Describe the bug**
If the desired date you want to change to is not in current timeline view you need to use date selector to change date because you can not drag Luxor outside of viewport. 

**To Reproduce**
1. Go to `?v=-155.96913206155142,-53.3671875,77.50038206155143,59.8359375&t=2004-07-08-T18%3A00%3A00Z&z=2&l=MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,MEaSUREs_Daily_Landscape_Freeze_Thaw_AMSRE,MEaSUREs_Daily_Landscape_Freeze_Thaw_SSMI,Reference_Labels(hidden),Reference_Features(hidden),Coastlines`
2. Drag luxor to `1960`
3. See error

**Expected behavior**
Be able to continuously drag luxor until timeline ends. Timeline should auto-pan when you get close to timeline borders.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 3.3.0 PROD

**Additional context**

**Comment by minniewong** [comment]
As a first step, we could also have the luxor be limited to the visible timeline extent range.
