### ISSUE TITLE
Clicking out of unacceptable date does not revert to previously selected date [date.input.6]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2580]
**Describe the bug**
Clicking out of the input of an unacceptable date does not revert to previously selected date

**To Reproduce**
1. Go to '?t=2019-12-23-T12%3A00%3A00Z'
2. Enter `2020` in date year input
3. Press tab
4. Click anywhere else on the map
5. See error

**Expected behavior**
Should be able to click out of input to revert back to previous date

**Screenshots**
<img width="488" alt="Screen Shot 2020-01-21 at 8 48 11 AM" src="https://user-images.githubusercontent.com/3605988/72810229-22016b00-3c2b-11ea-933b-295514e3cc39.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 3.4.0 UAT

**Comment by edplato** [comment]
This is the intended behavior for "potential temporarily invalid dates", so invalid inputs like "ASD" entered in the month input would reset on click out, but potential temporarily invalid dates are retained in case the user wants to change the year to 2019, in this case for example.

**Comment by Benjaki2** [comment]
Ahh cool ⚡️Will close
