### ISSUE TITLE
Add DAP to Worldview

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#259]
https://itcd.gsfc.nasa.gov/content/nasa-instructions-googleuniversal-analytics-code#.WQn5q7zys5h

**Comment by rboller** [comment]
and
https://github.com/digital-analytics-program/gov-wide-code

**Comment by minniewong** [comment]
https://www.digitalgov.gov/services/dap/common-questions-about-dap-faq/ - it should work alongside the GA we've already implemented

**Comment by minniewong** [comment]
@Benjaki2 - Add code in first link to Worldview; then I will email hq-webteam@lists.nasa.gov to get our account set up with DAP

**Comment by minniewong** [comment]
Double check implementation strategy
