### ISSUE TITLE
VIIRS Corrected Reflectance (True Color) layer imagery missing since Jan 1st 2020...

### ISSUE THREAD

**Issue by dattilo** [nasa-gibs/worldview#2614]
**Describe the bug**
VIIRS Corrected Reflectance (True Color) layer imagery missing since Jan 1st 2020...

**To Reproduce**
Navigate here:
https://worldview.earthdata.nasa.gov/?v=-382.22428116781873,-347.4772550046511,306.24100282144786,236.9602449953489&t=2020-01-01-T22%3A49%3A45Z&l=VIIRS_SNPP_CorrectedReflectance_TrueColor

**Expected behavior**
Should see VIIRS data...

**Desktop (please complete the following information):**
Happens from all os's and browsers...

One our of scientists found it and indicates that the data is available elsewhere... No real rush on fixing as other products provide almost the same image. 

Thanks,
Garth

**Comment by jasontk19** [comment]
Thanks for the heads up Garth!  I will let the GIBS team know (they are the ones who handle serving the imagery from various providers)

**Comment by jasontk19** [comment]
The GIBS team has addressed the issue with these missing days.  Closing this ticket.
