### ISSUE TITLE
Provide method in layer config to override GC ISO8601 durations

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#2617]
**What existing feature could be improved?**
Currently, the layer interprets the date / time interval from the GC doc using the ISO8601 duration. (i.e. daily: 2018-01-08/2018-01-10/**P1D** or 10-min subdaily: 2017-08-16T00:00:00Z/2017-08-16T02:30:00Z/**PT10M**). There is currently no way to override this behavior using the layer config.

**Describe the improvement you'd like**
Add an additional "duration" field to the layer config (which also requires the period field), to override the duration extracted from the GC.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by minniewong** [comment]
@ZachTRice can you elaborate on this ticket?

**Comment by ZachTRice** [comment]
If a layer is defined as P1D in the GC, but I wanted to override that duration, via the app, there is no way to do so. @mike-mcgann ran into a situation where the GC doc was incorrectly defining a layer as P1D but the layer was actually a 10-min later. Since the GC doc was constantly being refreshed, he had no way to override that duration within Worldview. In an ideal world, you could set `duration` in the layer config to override any duration parsed from the GC doc.

**Comment by minniewong** [comment]
@ZachTRice Is this still relevant?

**Comment by ZachTRice** [comment]
Yes

**Comment by edplato** [comment]
Hey @ZachTRice , I think I found a fix for this seen in action as the `temporal` option in `tasks\python3\validateOptions.py`.  If added to the specific layer config like below, then it will overwrite the GC time during build:

`"temporal": "1984-03-01/2019-11-01/P1M",`
