### ISSUE TITLE
Added VIIRS NOAA20 Thermal Anomalies 375m Layers

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#2619]
| Layer Identifier | Title | Subtitle | Projection |Time Period|
| --------------- |-------------|-------------|------|--------|
|VIIRS_NOAA20_Thermal_Anomalies_375m_All|Fires and Thermal Anomalies (Day and Night, 375m)|NOAA20/VIIRS|4326, 3413|2020-01-29 -to Ongoing |
|VIIRS_NOAA20_Thermal_Anomalies_375m_Day|Fires and Thermal Anomalies (Day, 375m)|NOAA20/VIIRS|4326, 3413|2020-01-29 -to Ongoing |
|VIIRS_NOAA20_Thermal_Anomalies_375m_Night|Fires and Thermal Anomalies (Night, 375m)|NOAA20/VIIRS|4326, 3413|2020-01-29 -to Ongoing |

**Comment by minniewong** [comment]
Awaiting fix to WMS GC
