### ISSUE TITLE
Migrate to EONET V3

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2634]
**What existing feature could be improved?**
Currently use `v2.1` of the EONET API

**Describe the improvement you'd like**
Migrate to the newly released `v3.0`

**Additional context**
v2.1 is going to continue to be reachable... v3.0 gives access to a new `magnitude` field, it would be nice to visualize the magnitude.

**Comment by rboller** [comment]
An update from EONET today:

> Version 3 has included GeoJSON formatting, event magnitudes, and the ability to search for events spatially or by date range.
>
> We are excited to announce that Version 3 will be going from Beta to official release on March 31, 2020.  We welcome any and all of your comments leading up to that date, but we will be changing over the URLs at that time (v3-beta in the URL will simply change to v3 – we will send a message as a reminder on launch day).
> 
> As far as the other versions of EONET: Version 2.1 will stay available, but may not receive all future updates.  Version 2.0 reach end of life and will be removed on 12/31/2020.
>

**Comment by minniewong** [comment]
Update from EONET:
EONET Users – EONET V3 will go live on March 31, 2020.  To aid in your transition to the new API, the URLs are now active.

For example - 
https://eonet.sci.gsfc.nasa.gov/api/v3/events/geojson
 
In most cases, you will simply update your existing “v3-beta” path to just “v3.”  On March 31, 2020, the “v3-beta” URLs will no longer be available.
Version 2.1 will stay available, but may not receive all future updates.  Version 2.0 reach end of life and will be removed on 12/31/2020.

**Comment by jasontk19** [comment]
I'd be interested in taking a look at this one but, @Benjaki2 I think you once mentioned you have some work in progress for this?  Would you be interested in sharing that and passing it off?

**Comment by Benjaki2** [comment]
@jasontk19 I will dig up that branch and send a diff your way.
