### ISSUE TITLE
Stories misaligned when browser is zoomed out

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2639]
**Describe the bug**
The stories are misaligned when browser is zoomed out (see screenshot below). This issue appears at every zoom below 90%.

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/73965145-9c93e100-48e1-11ea-9bf1-a5452bac16fb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by minniewong** [comment]
I checked in Mac Chrome, Windows and Mac Firefox - closing this ticket as the issue appears to be fixed.
