### ISSUE TITLE
Mobile datepicker should show forward/backward buttons

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2642]
**What existing feature could be improved?**
Currently, it is tedious to advance one day forward or backwards on a mobile device.  You have to open the mobile date picker and scroll the date up/down, then click ok.  There is plenty of room to add simple `<` and `>` arrows next to the datepicker button on mobile to simplify this action.

**Comment by ragnarokatz** [comment]
@jasontk19 Hello, I would like to take on this issue please.

**Comment by ragnarokatz** [comment]
@jasontk19 Hello, I have created a PR for this issue. Please review it when you have time, thanks.
