### ISSUE TITLE
Newly-added base layers can get inserted into middle of existing layers

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2660]
Under certain circumstances, newly-added base layers can get inserted into the middle of the existing set of base layers.

1. Start here: [https://go.nasa.gov/39pQtuk](https://go.nasa.gov/39pQtuk)
2. Add a base layer
3. Observe where that base layer is in the layer list

**Comment by jasontk19** [comment]
Likely related to this, I noticed a case where an overlay layer was being obscured by a baselayer:

1. Start here: `?v=-4488543.2519886065,-5578613.025073164,4727456.7480113935,4382858.974926836&p=arctic&t=2013-03-15-T00%3A00%3A00Z&l=MODIS_Terra_Brightness_Temp_Band31_Day,MODIS_Terra_L3_Land_Surface_Temp_Monthly_Night,Land_Water_Map,MODIS_Terra_Aerosol`
2. Add a corrected reflectance layer

![Screen Shot 2020-02-18 at 2 47 40 PM](https://user-images.githubusercontent.com/1480000/74772317-bd532380-525d-11ea-8a47-46ae8943a71f.png)
