### ISSUE TITLE
Tour step footer arrow buttons overflow container

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2661]
**Describe the bug**
Tour step footer arrow buttons overflow container in Edge. The footer arrow buttons positioning appears to be changing depending on length of step text content. 

**To Reproduce**
1. Go to `Bushfires in Australia` tour and click through a few steps
2. See footer arrow buttons overflowing

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/74556541-456abd80-4f2c-11ea-8083-8e9319aaf143.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge 
 - Version: 18

**Comment by jasontk19** [comment]
Looks like this isn't just in Edge;  seeing it in Chrome as well.
