### ISSUE TITLE
Extra map tiles loading as solid colors in Edge

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2662]
**Describe the bug**
Extra map tiles loading as solid colors in Edge consistent with color in `palette` query string param. The position of these solid tiles changes depending on map zoom level. This was observed in the `Bushfires in Australia` tour story on Step 9 for the `GPW_Population_Density_2015` layer.

**To Reproduce**
See screenshots and links below:

**Screenshots**
`/?v=142.87725733402257,-39.248622498527695,155.67953191354158,-32.989177049817556&t=2020-01-04-T00%3A00%3A00Z&l=VIIRS_SNPP_Thermal_Anomalies_375m_Day,Reference_Labels,Reference_Features,Coastlines,VIIRS_SNPP_Thermal_Anomalies_375m_Night(hidden),GPW_Population_Density_2015(palette=blue_9),VIIRS_SNPP_CorrectedReflectance_TrueColor,MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&tr=australia_fires_2019_2020`
![image](https://user-images.githubusercontent.com/24417194/74557247-bd85b300-4f2d-11ea-8279-133e772b9c7d.png)

`/?v=80.62139083595292,-65.47238925932493,188.62139083595292,-12.667701759324927&t=2020-01-04-T00%3A00%3A00Z&l=VIIRS_SNPP_Thermal_Anomalies_375m_Day,Reference_Labels,Reference_Features,Coastlines,VIIRS_SNPP_Thermal_Anomalies_375m_Night(hidden),GPW_Population_Density_2015(palette=blue_9),VIIRS_SNPP_CorrectedReflectance_TrueColor,MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&tr=australia_fires_2019_2020`
![image](https://user-images.githubusercontent.com/24417194/74557286-d1c9b000-4f2d-11ea-89c4-acb1171ea643.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 18

**Comment by minniewong** [comment]
No longer an issue.
