### ISSUE TITLE
Add test for removed layers

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#267]
If something is removed from the layerorder.json and not removed from one of the json files in the measurements folder it causes the product picker to not work for the category the measurement is in.

**Comment by ZachTRice** [comment]
I may have addressed this in my polar-picker branch when rewriting the layer modal functionality. I was seeing this happening when I was testing with the gibs-specific-options repo. I can do some testing and look into this more.

**Comment by ZachTRice** [comment]
The polar-picker branch addresses this issue. If a layer is removed from the layerOrder file, it will be removed from the measurement & layer views. If all layers within a measurement are removed, i.e. all 3 Blue Marble layers are removed, then that (empty) measurement won't be output in the categories view or the measurements view.
