### ISSUE TITLE
Consider removing duplicate layer entries across measurement files

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#2678]
Looking at the measurement json files, I find the following layers showing up across multiple measurements.  Out of 870 layers, ignoring orbit tracks, these are the exception by far.

AMSRE_Brightness_Temp_89H_Day:
    Brightness Temperature.json
    Sea Ice Brightness Temperature.json

AMSRE_Brightness_Temp_89H_Night:
    Brightness Temperature.json
    Sea Ice Brightness Temperature.json

AMSRE_Brightness_Temp_89V_Day:
    Brightness Temperature.json
    Sea Ice Brightness Temperature.json

AMSRE_Brightness_Temp_89V_Night:
    Brightness Temperature.json
    Sea Ice Brightness Temperature.json

AMSRE_Sea_Ice_Brightness_Temp_89H:
    Brightness Temperature.json
    Sea Ice Brightness Temperature.json

AMSRE_Sea_Ice_Brightness_Temp_89V:
    Brightness Temperature.json
    Sea Ice Brightness Temperature.json

AMSRU2_Sea_Ice_Brightness_Temp_89H:
    Brightness Temperature.json
    Sea Ice Brightness Temperature.json

AMSRU2_Sea_Ice_Brightness_Temp_89V:
    Brightness Temperature.json
    Sea Ice Brightness Temperature.json

GRanD_Reservoirs:
    Reservoirs.json
    Water Bodies.json

MODIS_Terra_L3_Land_Water_Mask:
    Land Cover.json
    Water Bodies.json

**Comment by minniewong** [comment]
Considered, but won't fix.
