### ISSUE TITLE
IE11 Tour step dialog positioned off screen

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2691]
**Describe the bug**
IE11 Tour step dialog positioned off screen.

**To Reproduce**
1. Go to tour and see step dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/75046475-25d71600-5493-11ea-9c5b-81b2d7262842.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE11

**Comment by jasontk19** [comment]
I guarantee this is because I set the `margin` on this to `0 auto`:
https://stackoverflow.com/questions/7810326/margin-auto-not-working-in-ie
