### ISSUE TITLE
Update layer picker measurement styles to match search

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2695]
Use light background styles for selected measurement rows and details, per request from @rboller

**Comment by jasontk19** [comment]
There are a few possible variations of this, here's one where the details have a light background along with the selected instrument:
![Screen Shot 2020-02-24 at 9 28 13 AM](https://user-images.githubusercontent.com/1480000/75160499-18ff3000-56e8-11ea-8ed1-26f3853b6edb.png)

**Comment by jasontk19** [comment]
Here's another where the entire measurement list item shares the light background:
![Screen Shot 2020-02-24 at 9 36 46 AM](https://user-images.githubusercontent.com/1480000/75161149-4ef0e400-56e9-11ea-9204-a94f95adf6f4.png)

**Comment by jasontk19** [comment]
And yet another where the selected instrument, individual layers for that instrument, and full detail text to the right, all share the same light background.  This might tie all the related things together with a common color scheme the best but it might also look odd:
![Screen Shot 2020-02-24 at 9 42 14 AM](https://user-images.githubusercontent.com/1480000/75161627-1bfb2000-56ea-11ea-88bb-641bf0df9474.png)

**Comment by jasontk19** [comment]
Here are some more variants:

## Closed Border ⛔️ 
![Screen Shot 2020-02-25 at 10 23 33 AM](https://user-images.githubusercontent.com/1480000/75261403-fb4dcb80-57b8-11ea-8708-99a0226c1295.png)

## Open Border 📂 
![Screen Shot 2020-02-25 at 10 23 12 AM](https://user-images.githubusercontent.com/1480000/75261404-fb4dcb80-57b8-11ea-8bac-3b1ab4456207.png)

## Less Border 🌤 
![Screen Shot 2020-02-25 at 10 27 02 AM](https://user-images.githubusercontent.com/1480000/75261712-74e5b980-57b9-11ea-8120-df9a86cc7110.png)

## Mixed Border 🥄 
![Screen Shot 2020-02-25 at 10 27 19 AM](https://user-images.githubusercontent.com/1480000/75261713-757e5000-57b9-11ea-9dd4-ee77a00d266f.png)

**Comment by jasontk19** [comment]
I'm not sure I like any of these more than what we currently have in UAT. 🤷‍♂

**Comment by edplato** [comment]
I like the color menu connection of the light color throughout. I like ⛔️or 📂. Although, after playing with query results of varying sizes, I think my final vote would depend on if the scroll bar looks weirder on either version since it's not really separated from the right half of the picker. Maybe a minimal change in Choice 3 (from above) addresses any/all  of my visual scroll bar hangups:
![image](https://user-images.githubusercontent.com/24417194/75264811-f6d7e180-57bd-11ea-9162-fb872b137082.png)

**Comment by Benjaki2** [comment]
I like 📂or what Ed has above. I do think the color connection is valuable.

**Comment by rboller** [comment]
I like `open border` or `less border` best though hadn't considered the scrolling issues that Ed mentioned and am supportive of what he suggested, too.  

So I'm flexible on the final call but do think the color connection really helps and should be there in one form or another.  Thanks for working this in, @jasontk19!

**Comment by ZachTRice** [comment]
I like open border + the changes @edplato suggested to give some divide to the scroll bar
