### ISSUE TITLE
Zoom level not retained on tour permalink reload

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2704]
**Describe the bug**
If you reload the page on a tour, the zoom level that loads will not necessarily be the desired zoom

**To Reproduce**
1. Go to tour
2. Click on dust storm
3. Click next tour step (>)
4. reload page
5. See error: Zoom level of initial tour step is not the same as when you originally clicked through it

**Expected behavior**
Zoom level for step 1 will be the same as when you first clicked through

**Screenshots**
Initial click through:
<img width="1184" alt="Screen Shot 2020-02-25 at 10 17 46 AM" src="https://user-images.githubusercontent.com/3605988/75260884-40bdc900-57b8-11ea-9063-f9d4e33e8541.png">
Zoom after page reload:
<img width="1199" alt="Screen Shot 2020-02-25 at 10 17 57 AM" src="https://user-images.githubusercontent.com/3605988/75260935-53d09900-57b8-11ea-8420-9d3095060070.png">

**Desktop (please complete the following information):**
 - OSX
 - Browser: firefox
 - Version: 3.4.1 prod

**Comment by edplato** [comment]
May be related to #2670
