### ISSUE TITLE
Consider displaying a "recently used layers" panel 

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2719]
Per user suggestion, it could be helpful if we provided something like a "recently used layers" or "frequently used" panel when the user is adding new layers.

**Comment by jasontk19** [comment]
One possibility would be adding a fourth tab to the product picker "browse" view for recent layers:

![Screen Shot 2020-06-16 at 1 49 40 PM](https://user-images.githubusercontent.com/1480000/84809748-61fd2c00-afd8-11ea-8058-b26aca223ba1.png)

**Comment by jasontk19** [comment]
Another possibility would be to introduce a new facet for "recently viewed" layers.
![Screen Shot 2020-06-16 at 1 55 00 PM](https://user-images.githubusercontent.com/1480000/84810228-0b442200-afd9-11ea-9425-757d3cb20af0.png)

**Comment by jasontk19** [comment]
_As a user I want to:_ 

- See a list of recently added layers
- See layers I use more often shown at the top of the list
- Not have layers I've only viewed once replace those I frequently use 
-- (e.g. if list is capped at 10 and top used layer has been viewed 20+ times, it shouldn't be replaced by a newly added layer that user only viewed once)
- Clear the list of recently added layers
- Remove a single layer from the list of recently added
