### ISSUE TITLE
Support classification toggling for raster colormaps with one classification legend entry

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#2727]
The new classification toggling works for colormaps that have more than one non-transparent legend entry in the classification legend. However, if there is only a single legend entry, the user can't toggle, but _can_ change the color. At a minimum, we should also support toggling for single non-transparent legend entries. 

BUT, perhaps we could also support changing the color. Instead of the scrolling list of colors, you could just have drop down menu next to the toggle.

**Comment by minniewong** [comment]
Provide a transparent option in the "color palette"

**Comment by mcechini** [comment]
Having issues with the GPM layer in sit... https://sit.gibs.earthdata.nasa.gov/worldview-dev/mattc-sit/?v=-183.0841905626926,-112.01240383010528,176.86894861578148,88.96143221120943&l=GMI_Rain_Rate_Dsc_v5_NRT,Coastlines(hidden),OSM_Land_Water_Map

**Comment by mcechini** [comment]
Having issues with the GPM layer

**Comment by Benjaki2** [comment]
GMP issue was related to an external GIBS config that was behind Worldview's master banch. Closing for now.
