### ISSUE TITLE
Adding AMSRU2 Rain products

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#2791]
GHRC ICD [Lines 44-47](https://docs.google.com/spreadsheets/d/1Y33ggDjGlpSJfCvuA1arxcCp1A1NPbcA-S5EntaFwFg/edit#gid=70067320)

**Comment by mcechini** [comment]
Well... we should discuss when we actually want these to go into WV production.  They will replace existing products... and until we have a) completed STD historical b) are forward processing STD, and c) are forward processing NRT... we may not want to do the switch in WV.

**Comment by jejeking** [comment]
After discussing with GHRC, it will be best to wait until both the standard and NRT imagery are forward processing in production, as well as completing the historical standard processing for both Rain and Ocean. Then these will replace the current A2RnOcn layers. So put this on the back burner for now. It will take months to complete historical processing.
