### ISSUE TITLE
Remove "day" and "night" distinction from ICESat-2 and Metop-A orbit tracks

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#2808]
The [ICESat-2](http://database.eohandbook.com/database/missionsummary.aspx?missionID=613) and [Metop-A](http://database.eohandbook.com/database/missionsummary.aspx?missionID=261) satellites are not sun-synchronous, so we should remove the "day" and "night" designations from their orbit tracks.  They're just "ascending" and "descending".

**Comment by minniewong** [comment]
appears Metop-A should be sun-synchronous since Metop-B and Metop-C are too: https://www.wmo-sat.info/oscar/satellites/view/306
