### ISSUE TITLE
Blank screen for tour.link.12

### ISSUE THREAD

**Issue by npressley** [nasa-gibs/worldview#2813]
Blank screen in SIT for tour.link.12, using this [link](https://worldview.sit.earthdata.nasa.gov/?tr=testing)

Expected result:
    An alert should appear below the toolbar stating "Sorry, this tour is no longer supported."
    The alert should close itself in 10 seconds.

Using Firefox on Mac

**Comment by jasontk19** [comment]
Possibly related:
https://github.com/nasa-gibs/worldview/pull/2802#discussion_r400862729 😅

**Comment by minniewong** [comment]
I also see this issue.

**Comment by StephanJW** [comment]
> Possibly related:
> [#2802 (comment)](https://github.com/nasa-gibs/worldview/pull/2802#discussion_r400862729) 😅

Yup - I'll correct it.
