### ISSUE TITLE
S-04[map] map.init.13 Reset button indicates 0

### ISSUE THREAD

**Issue by npressley** [nasa-gibs/worldview#2817]
MacBook Pro/Firefox:

map.init.13 SIT [link](https://worldview.sit.earthdata.nasa.gov/?p=arctic&r=60) Map view should be rotated 60 degrees clockwise. 
Expected result:  Reset button should indicate 60 degree rotation

However, the url has r=60 but it appears to reload w/o it and the reset button is 0

**Comment by minniewong** [comment]
The URL in the test plan is https://worldview.sit.earthdata.nasa.gov/?p=arctic&r=60 but it gets updated to: https://worldview.sit.earthdata.nasa.gov/?v=-5898240,-2781184,5898240,2781184&p=arctic after you click on the test plan URL. The rotation parameter is not being kept.

**Comment by minniewong** [comment]
I see this issue also on Chrome Mac and Safari iPad
