### ISSUE TITLE
S-14 Data Download: dd.size.4, Download Data does show total granule size 

### ISSUE THREAD

**Issue by npressley** [nasa-gibs/worldview#2820]
MacBook/Firefox

[S-14 in Test Plan](https://wiki.earthdata.nasa.gov/display/WOR/S-14+%5Bdd%5D%3A+Data+Download), Granule Sizes, 

I'm on this [SIT link](https://wiki.earthdata.nasa.gov/display/WOR/S-14+%5Bdd%5D%3A+Data+Download)

dd.size.4 Instructions say:
    Select "MODIS/Aqua Aerosol" in the "Data Download" tab
    Select a granule

Expected Results:
The button now just shows "Download Data" without a total granule size.

dd.size.5 instructions say:
Unselect the granule.
Expected Results:
The button in the "Data Download" tab shows "Download Data (X MB)"

However, when I select a granule, the Download Data increases to 5.21 MB if I deselect, it goes back to 0.59 MB.

**Comment by minniewong** [comment]
Closing and will be addressed with data download overhaul
