### ISSUE TITLE
compare.swipe.8: Freezes when typing into search bar

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2822]
**Describe the bug**
After going to this [link](https://worldview.sit.earthdata.nasa.gov/?ca=true&cm=swipe&cv=50&p=geographic&l=MODIS_Terra_CorrectedReflectance_TrueColor&l1=MODIS_Terra_Aerosol&t=2018-08-17-T00%3A00%3A00Z&z=3&t1=2018-08-16-T00%3A00%3A00Z&v=-127.6171875,-46.5556640625,31.7109375,53.0244140625/?ca=true&cm=swipe&cv=50&p=geographic&l=MODIS_Terra_CorrectedReflectance_TrueColor&l1=MODIS_Terra_Aerosol&t=2018-08-17-T00%3A00%3A00Z&z=3&t1=2018-08-16-T00%3A00%3A00Z&v=-127.6171875,-46.5556640625,31.7109375,53.0244140625) and removing the layers, then clicking on Add Layers and trying to type in AOD, the app freezes for about a minute.

ipad/safari

**Comment by jasontk19** [comment]
This appears to be mobile/tablet specific.  I'm guessing this is also somewhat related to your older iPad?  The code to search for layers (which would normally be handled by a server in larger apps) may be too much for older devices to handle in a timely fashion.  I have been trying to make improvements in this area with the product picker work but, I'm not sure how much we'll be able to do for older devices.

**Comment by minniewong** [comment]
likely! it is rather old :)
