### ISSUE TITLE
Illustrate the movement of multi-day events

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#283]
Some of our events - hurricanes and icebergs, currently - have multiple date entries for single event.  For those events, we can "connect the dots" to show the paths that these events have taken.  Here is one approach taken to show hurricane tracks:

https://coast.noaa.gov/hurricanes/#/search/name/ALBERTO%202012

**Comment by localjo** [comment]
Is there a precedent in the UI for representing data for multiple days at the same time?

**Comment by rboller** [comment]
That's a great point... and no, we don't currently have a way to show multiple days at the same time.  There have been requests to show several days of our vector layers (e.g., [fire points](https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,VIIRS_SNPP_Fires_375m_Night(hidden),VIIRS_SNPP_Fires_375m_Day(hidden),MODIS_Fires_Aqua(hidden),MODIS_Fires_Terra,Reference_Labels,Reference_Features,Coastlines(hidden)&t=2017-07-31&z=3&v=-126.97675312807831,48.8459623388261,-117.92178123188768,54.27148770970766&e=t), [orbit tracks](https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,Terra_Orbit_Dsc,Reference_Labels,Reference_Features,Coastlines(hidden)&t=2017-07-31&z=3&v=-206.71124731495132,-68.19460252543107,71.88721728965697,98.73501971192175)) simultaneously which we plan to address in the future.  Initial ideas for that are to support date ranges in the timeline directly or to do it on a per-layer basis in the layer settings.

On a somewhat related note, we also have monthly and annual products (e.g., [monthly vegetation indices](https://worldview.earthdata.nasa.gov/?p=geographic&l=Landsat_WELD_NDVI_Global_Monthly,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden),Terra_Orbit_Dsc(hidden),Reference_Labels,Reference_Features,Coastlines(hidden)&t=2011-07-31&z=2&v=-146.24204260142506,1.7615027878214562,-43.79673010142507,63.144315287821456)) which aren't currently treated differently than daily layers, though at some point it would be good to differentiate them in the timeline.

**Comment by localjo** [comment]
Ok. I'll need to get more familiar with how different types of data are displayed before I can make recommendations for a good UI approach, so I'll tackle some other issues first, and come back around to this.
