### ISSUE TITLE
ruler/timeline cover rotation buttons in arctic and antarctic projections on Android tablet

### ISSUE THREAD

**Issue by bvpeters713** [nasa-gibs/worldview#2832]
After switching to Arctic or Antarctic projections, the lower rotation button is covered by the timeline and the upper rotation button is covered by the ruler.  Geographic projection is fine (since it does not use the rotation buttons).

 **To Reproduce**
Pics attached to demonstrate

**Expected behavior**
The buttons must be accessible or polar projections are severely hampered. 
**Screenshots**
See attached pics.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
  - OS: Android 8 - 8" tablet
 - Browser: Chrome 
 - Version: 84

**Additional context**

**Comment by bvpeters713** [comment]
![Screenshot_2020-04-13-12-32-15](https://user-images.githubusercontent.com/63357274/79161855-34aeba80-7daa-11ea-85cb-a3f7063e08cb.png)

**Comment by edplato** [comment]
Note a different variant of rotation button off-positioning using Samsung Galaxy Tab S6 Chrome:
![image](https://user-images.githubusercontent.com/24417194/79241506-23fd5380-7e41-11ea-89a6-8477d5d269fb.png)

**Comment by edplato** [comment]
Galaxy S5 via Chrome device toolbar:
![image](https://user-images.githubusercontent.com/24417194/79249654-97a45e00-7e4b-11ea-9b11-810437df6759.png)

**Comment by jasontk19** [comment]
Discussed at tech dev meeting.  Consider:
* Removing zoom/rotation buttons on mobile since those interactions can be done directly with touch gestures.
* Zoom and rotate can be moved upward, measure button and coordinates over on desktop
* Consider enforcing min-width/min-height to transition to mobile mode rather than supporting edge cases in desktop

**Comment by edplato** [comment]
Addressed in mobile changes in #3193
