### ISSUE TITLE
Measure tool - conversion from kilometers to miles not performed

### ISSUE THREAD

**Issue by bvpeters713** [nasa-gibs/worldview#2837]
**Describe the bug**
In the measure tool, in the distance selection, one ends up with a number in  miles or kilometers. By switching the selection, there should be a conversion to the other standard. 

**To Reproduce**
1. Select the ruler icon.
2. Select distance
3. Tap on the starting location and move to the next location  and tap (repeat as desired)
4. Double tap on the finishing location.
5. The distance is computed as expected.
6. Switch to the other standard and the conversion is supposed to be made automatically. However, on the Android tablet, the number  does not change.
7. Redoing the scenario in the other standard also does not work.

Note - on the Android tablet, the area computation DOES work and the conversion DOES work.

**Expected behavior**
After the measurement is completed,  and the switch changed, the conversion from miles to kilometers should be made (or alternatively from kilometers to miles.

**Screenshots**
Not required.

**Smartphone (please complete the following information):**
 - Device: Generic 8" Android tablet
 - OS: Android 8.0
 - Browser: Chrome
 - Version:  84

**Additional context**
None.

**Comment by jasontk19** [comment]
Thanks for filing this one @bvpeters713!

Since we think a relatively low number users will encounter this issue, and the conversion does happen once you've completed the measurement, we've decided to close this one out for now.
