### ISSUE TITLE
Don't include preview images when feature is disabled

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2876]
**What existing feature could be improved?**
Currently we include a feature flag for `previewSnapshots` that turns on/off the fetching of preview images from WVS during build and whether or not those images are shown in the product picker.  However, since the images themselves are committed to the repo they get included in a `dist` build whether you want them or not which can greatly increase the file size of the deployed tgz file.

**Describe the improvement you'd like**
Streamline this process so that files aren't included when you don't want to use this feature.

**Describe alternatives you've considered**
* Could remove preview image directory from a `dist` build  if `previewSnapshots` is disabled
* Could move the images outside of the code repo

**Comment by ZachTRice** [comment]
Can we move the preview-images to another repo?

When I am on a slow connection or vpn, running a `git clone` of the worldview repo takes a very long time now. If those images were in another repo, you could have that repo pulled at build time via a script; something like add-images.sh which, if the previewImages feature is enabled would git clone the preview-images into the web/images/layers/preview directory.

**Comment by ZachTRice** [comment]
I guess I am voting for the second alternatives you've considered option

**Comment by jasontk19** [comment]
I had previously decided not to go with moving the images to another repo for a couple of reasons:

1.  The current approach of having the images live in the same repo helps streamline the process for when new layers are added: just build WV with new layer configs and the new images are fetched automatically.  The new configs and corresponding images can be included in the same PR, in the same repo.

2. I was worried moving the images to a separate repo would add unnecessary complexity to the dev/build/deployment process but that could be because I don't have a clear picture of exactly what this would involve at each step without looking into it a bit more.  The process of cloning the image repo at build time you described seems straightforward enough but what do you think the process for adding new images looks like with this approach?  

I can look into it some more but I may be reaching out to you with questions if I get stuck 😉 

If we can come up with an approach that keeps the simplicity of adding new images when new layers are added that is offered by the current approach, I can get behind this.
