### ISSUE TITLE
Console warning on layer add

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2921]
**Describe the bug**
Console issue on layer add.
reference: https://github.com/nasa-gibs/worldview/pull/2915#pullrequestreview-421160658

**To Reproduce**
1. Go to worldview
2. Add settlements layer
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/3605988/83431151-e199d100-a404-11ea-84d9-4d7a02d7a02d.png)

**Desktop (please complete the following information):**
 - macOS
 - Browser: chrome
 - Version: 83.0

**Additional context**
Probably the result of an updated dependency

**Comment by jasontk19** [comment]
I'm not seeing this anymore so I'm guessing it's no longer an issue.  Please re-open if you're noticing it.
