### ISSUE TITLE
Simplify process of adding layers

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#2922]
**Is your feature request related to a problem? Please describe.**
Right now there are a number of hurdles one must leap in order to add a new layer.
* You need to add the layer in multiple places (layerOrder, config file,defaults, etc )
* You may misspell an ID somewhere and need to debug where.
* you may just not know the right place to put things 

**Describe the solution you'd like**
* Run a script (`npm run addlayer new_layer_id`)
* have the script prompt multiple questions that piece together the layer's config
    * what type of layer is this? (wms/wmts/vector, default:wmts)
    * Is this an overlay or base layer(default: overlay)
    * Should this layer be added to the default layer list?(add option for where to place item in array)
* Add information at end of process that points to documentation of more custom settings (measurements, descriptions, featured tab) 

**Describe alternatives you've considered**
Have one script that accepts multiple parameters
`npm run addlayer id=layer_id type=vector group=base `

**Comment by edplato** [comment]
An option is to rely on a singular template that is edited in one place to add a new layer. Upon running the necessary `add-layer` script, this template is parsed to create/append the separate necessary files (`layerOrder.json`, layer metadata, instrument layer json, etc.). These files created from the scripts are based on individual templates.

**For example (working out feature ideas):**
`/tasks/layer-config-builder/` contains main template `new-layer.json` to edit with new layer data prior to running `add-layer.js`

`/tasks/layer-config-builder/layer-templates/` contains necessary templates for new files created (layer metadata markdown, instrument layer json) that will be populated with data from above `new-layer.json`

`/tasks/add-layer.js` script to add layer to config
- Uses `new-layer.json` to create/append related layer files and provides verbose feedback/errors for each step ✅ ❌ 
- Upon successful completion of adding a layer, copy newly added layer template to localized/gitignored `/tasks/layer-config-builder/added-layers` directory and replace template with default/unedited copy.
- Note: A new layer should be able to be added with minimal metadata information for low friction layer testing, which may require an additional parameter to pass when running the script for work in progress (ex: `npm run addlayer new_layer_id --wip`)
- Note: Any script should be created with the awareness of likely breaking config directory changes in the future and make directory paths easy to modify if needed.

**Comment by minniewong** [comment]
Wait for vis metadata; consider simplifying the build and configs
