### ISSUE TITLE
Buttons not working in animation modal on iPad

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2928]
**Describe the bug**
When the buttons are pressed in the animation modal on an iPad, nothing happens. This happens to all buttons - play, loop, export to animated gif, dates, animate in x increments. the FPS slider works fine.

**To Reproduce**
1. Go to SIT on an iPad 
2. Click on Video camera icon
3. Try to click on any of the buttons

**Expected behavior**
The buttons should work. 

**Smartphone (please complete the following information):**
 - Device: iPad mini 2
 - OS: 12.4.6
 - Browser: stock browser

**Additional context**
Works fine in production.

**Comment by jasontk19** [comment]
This also appears to be fixed by #2932

**Comment by jasontk19** [comment]
Fixed by #2932
