### ISSUE TITLE
PODAAC Feb 2020 Updates

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#2934]
| Layer Identifier | Title | Subtitle | CMR ID | Projection |Time Period|
| ------------- |-------------|-------------|------|------|--------|
|GHRSST_L4_GAMSSA_GDS2_Sea_Surface_Temperature|Sea Surface Temperature (L4, GAMSSA GDS2)|Multi-Mission / GHRSST|C1653205971-PODAAC|4326|2008-07-23 to Present|
|GHRSST_L4_MUR25_Sea_Surface_Temperature|Sea Surface Temperature (L4, MUR25)|Multi-Mission / GHRSST|C1646568487-PODAAC|4326|2002-09-01 to Present|
|GHRSST_L4_MUR25_Sea_Surface_Temperature_Anomalies|Sea Surface Temperature Anomalies (L4, MUR25)|Multi-Mission / GHRSST|C1646568487-PODAAC|4326|2002-09-01 to Present|
|GHRSST_L4_MUR_Sea_Surface_Temperature_Anomalies|Sea Surface Temperature Anomalies (L4, MUR)|Multi-Mission / GHRSST|C1664741463-PODAAC|4326|2002-06-01 to Present|
|JPL_MEaSUREs_L4_Sea_Surface_Height_Anomalies|Sea Surface Height Anomalies (L4)|TOPEX/POSEIDON, JASON-1, OSTM/Jason-2, and Jason-3|C1646328472-PODAAC|4326|1992-10-01/P5D|
|GHRSST_L4_MUR_Sea_Ice_Concentration|Sea Ice Concentration (L4, MUR)|Multi-Mission / GHRSST|C1664741463-PODAAC|4326|2002-06-01 to Present|
|GHRSST_L4_MUR25_Sea_Ice_Concentration|Sea Ice Concentration (L4, MUR25)|Multi-Mission / GHRSST|C1646568487-PODAAC|4326|2002-09-01 to Present|
|GHRSST_L4_GAMSSA_GDS2_Sea_Ice_Concentration|Sea Ice Concentration (L4, GAMSSA GDS2)|Multi-Mission / GHRSST|C1653205971-PODAAC|4326|2008-07-23 to Present|

**Comment by minniewong** [comment]
1. `GHRSST_L4_GMSSA_GDS2_Sea_Ice_Concentration` is likely missing an `A` in the filename - it doesn't match the layer name.
2. `JPL_MEaSURES_L4_Sea_Surface_Height_Anomalies` the second `s` in MEaSUREs should be lower case.

**Comment by apdeluca** [comment]
The `A` has been added to `GHRSST_L4_GMSSA_GDS2_Sea_Ice_Concentration` in GIBS, along with the second `s` being lowered `JPL_MEaSURES_L4_Sea_Surface_Height_Anomalies`
