### ISSUE TITLE
When "view dates" panel is opened for a layer, it remains open when switching to another layer description

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2956]
**Describe the bug**
When you have a layer that has "view dates" open in the temporal coverage section of the layer description, and you switch to another description, the "view dates" panel remains open even if that layer doesn't have any dates to show in the panel. 

**To Reproduce**
1. Open the Layer Picker
2. Type in SST, click on "Sea Surface Temperature (L3, Night, Daily, Mid Infrared, 4 km)" (third in list)
3. In the layer description, click on "View dates" and you will see a list of dates.
4. Switch to "Sea Surface Temperature (L4, MUR)" and see that the View dates panel is still open and says "Date Ranges:" though there are no date ranges to show.

**Expected behavior**
When the "view dates" panel is open for a layer that doesn't have date ranges, it looks odd to have a title that says "Date Ranges:" and not show any date ranges. It should not show "Date Ranges" if the layer doesn't have Date Ranges.

**Screenshots**
![Screen Shot 2020-06-15 at 2.52.12 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/58a48e1a-faf0-4365-9b63-b167fd852097)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

In production

**Comment by jasontk19** [comment]
@minniewong What about if the the layer you switched to _did_ have date ranges?  Would it be preferable to leave the dates showing when switching between layers to more easily compare date ranges?  If so I can have it only hide when no date ranges exist.

**Comment by minniewong** [comment]
@jasontk19 agree with your comment above - I should have been more specific in the ticket.
