### ISSUE TITLE
Added AMSRU2 Sea Ice vR04 NRT

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#2984]
Updated NRT version from v2 to vR04 for all Sea Ice products for AMSRU2.
[ICD](https://docs.google.com/spreadsheets/d/1Y33ggDjGlpSJfCvuA1arxcCp1A1NPbcA-S5EntaFwFg/edit#gid=70067320)
Lines 82-93 replace Lines 95-106

**Comment by minniewong** [comment]
No updates needed to be made to the file as they are pointing to the same BEST identifier. No updates available for the information/metadata - metadata not yet in CMR.
