### ISSUE TITLE
Measure distance tool: start point "wandering."

### ISSUE THREAD

**Issue by kbasye00** [nasa-gibs/worldview#2991]
**Describe the bug**
Once set, the start point for the distance measuring tool wanders slowly away from the original location.

**To Reproduce**
1. Choose either Arctic or Antarctic projection (!)
2. Click on 'Measure Distance'
3. Click on map
4. Move mouse away, causing distance measurement line to appear with tooltip showing length of line.
5. Without clicking a second time, take hand off mouse.
6. Watch start point of measuring line slowly move while distance updates.

**Expected behavior**
Start point of measuring line doesn't move by itself.

**Screenshots**
If you can't reproduce, please update here and I'll try to get something to show this.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: firefox, chrome, safari (same for all of them)
 - Version: FF 78.0.1 (64-bit),  Chrome  83.0.4103.116 (Official Build) (64-bit), Safari Version 13.1.1 (14609.2.9.1.3)

**Additional context**
Generally the start point seems to wander toward the current end of the line, but not always (!).  It does eventually stop someplace, but I can't predict where.

**Comment by jasontk19** [comment]
@kbasye00 thanks for filing this issue!  We'll have a fix for this go out in the next release.

**Comment by kbasye00** [comment]
thanks - def. one of the more amusing bugs I've run across :-)

**Comment by kbasye00** [comment]
FWIW, this is still an issue as of today.  Not sure if the fix just isn't in yet or what?

**Comment by jasontk19** [comment]
@kbasye00 we are wrapping up the next release right now!  Should be in production early next week.
