### ISSUE TITLE
Represent MODIS and VIIRS fires as appropriately-sized polygons

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#2992]
**What existing feature could be improved?**
The representation of MODIS and VIIRS fire points.

**Describe the improvement you'd like**
We can accurately represent the extent of a MODIS/VIIRS fire detection using an appropriately-sized polygon.  MODIS fire detections cover a 1km diameter area and VIIRS fire detections cover a 375m diameter area.  We'll have to determine if a circle or square (or other shape) is most appropriate.

**Describe alternatives you've considered**
As of now, our current (raster-based) and upcoming (vector-based) fire visualizations don't represent the exact size of the fire detection.

**Additional context**
The [FIRMS Fire Map](https://firms.modaps.eosdis.nasa.gov/map/#d:2020-07-16..2020-07-17;@-82.1,28.3,12z) does accurately represent the size of MODIS (orange) and VIIRS (red) fires:
![image](https://user-images.githubusercontent.com/7243823/87834075-76db1280-c857-11ea-82e0-bd23999d010e.png)

**Comment by Benjaki2** [comment]
Todo: Create spread sheet with `| zoom-level | resolutions |` in order to organize correct pixel at zoom.

**Comment by minniewong** [comment]
Moved to WV-1936
