### ISSUE TITLE
Measurement labels are removed in distraction free mode

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#2999]
**Describe the bug**
Measurement labels are removed when distraction free mode is active.

**Expected behavior**
Measurement labels remain.

**Comment by jasontk19** [comment]
Fixed here: https://github.com/nasa-gibs/worldview/pull/3000/commits/4f6493c20c77c01e01e026911e6f2ec4b13c98b8
This fix is included with PR #3000
