### ISSUE TITLE
Should not be able to select Worldfile for KMZ in image download

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#301]
On the image download pane, when Format is KMZ, Worldfile can be "Yes" but when you download the KMZ does not contain the worldfile (which is as it should be).

In a perfect World(view), only "No" should be selectable for Worldfile when Format is KMZ.

**Comment by mcechini** [comment]
Should ImageDL throw an error/warning if a user tries to request this?

**Comment by minniewong** [comment]
I believe you also shouldn't be able to select worldview for GeoTIFFs - since the referencing information should be in the tif. Is this true?
