### ISSUE TITLE
Copy coordinates to clipboard

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3032]
**What existing feature could be improved?**
Coordinates display - provide a way to easily copy the coordinates of a specific location.

**Describe the improvement you'd like**
Provide a way to easily copy coordinates of a specific location to the clipboard - e.g. right click, or click a button.

(Kayako ticket 106709)

**Comment by jasontk19** [comment]
I'm interested in this one

**Comment by minniewong** [comment]
Wait for geosearch implementation
