### ISSUE TITLE
Hovering over a fire at outer zoom levels no longer highlights the legend entry [layer.legend.5]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3033]
**Describe the bug**
Hovering over a fire at outer zoom levels no longer highlights the Fire legend entry.

**To Reproduce**
1. Go to SIT
2. Add a fire layer
3. Hover over fires on the map
4. See error - Fire legend is not highlighted, if you zoom into vector tile, it will highlight.

**Expected behavior**
When hovering over a fire on the map at outer zoom levels, the fire legend should have a label that appears with "Fire" in the label

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox and Chrome

**Comment by Benjaki2** [comment]
I think the change to opaque WMS circles will fix this. 🤞

**Comment by jasontk19** [comment]
Looks like the change to opaque circles did fix this.  Working fine in SIT now!
