### ISSUE TITLE
Style bug -- A | B opacity compare

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#3035]
**Describe the bug**
Percent sign `%` is shown outside of tooltip. (Style bug)

**To Reproduce**
1. Go to https://go.nasa.gov/31FACVZ
2. Drag slider left and right
3. See error

**Screenshots**
<img width="247" alt="Screen Shot 2020-08-10 at 10 42 31 AM" src="https://user-images.githubusercontent.com/3605988/89795623-997ae700-daf6-11ea-892a-6f0cd4bc5105.png">
**Desktop (please complete the following information):**
 - OSmac
 - Browser: chrome
 - Version: 10.15.6

**Comment by KoushikSahu** [comment]
@Benjaki2 Please close this issue

**Comment by KoushikSahu** [comment]
@jasontk19 Oh that makes sense. I was looking for hacktoberfest issues and I saw this merged PR so thought of making a minor contribution by asking to close the issue.
