### ISSUE TITLE
Unable to play animation in step 2 of Australia fire story

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3037]
When trying to play the animation in Step 2 of the Australia fire tour story, the "Preloading imagery" spins, and there is this error message in the console.
 ![Screen Shot 2020-08-10 at 5.15.03 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/32112a28-d183-4cfd-a26b-d3fd50c3daca)

**Comment by jasontk19** [comment]
I am not seeing this when running locally 🤔

**Comment by minniewong** [comment]
> I am not seeing this when running locally 🤔

I see it when I run develop locally in Chrome and Firefox

**Comment by edplato** [comment]
I'm not seeing this issue running locally on latest `develop`. However, it looks like fire layer styling is still in progress since I'm not seeing fires at higher zoom levels.

**Comment by minniewong** [comment]
Working fine now in SIT!
