### ISSUE TITLE
Get Social media ids for sharing

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#305]
Facebook, Twiiter?

**Comment by ZachTRice** [comment]
- Facebook: We need an App ID; this requires a Facebook **Developer** account. Here are the steps to [Register and Configure an App](https://developers.facebook.com/docs/apps/register)
- Twitter: We **do not** need to authorize an App on Twitter for the sharing features, [see documentation](https://dev.twitter.com/web/intents).
- Google Plus: We **do not** need to authorize an App on Google Plus, [see documentation](https://developers.google.com/+/web/share/#sharelink)

- Instagram: As mentioned in issue #140, **does not allow sharing media**.

**Comment by minniewong** [comment]
@ZachTRice - I will check with Jennifer to see if we can just use the Earthdata Developer account
