### ISSUE TITLE
Step 2 of Australia tour story loads slowly

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3059]
When you press play for Step 2 for the Australia tour story, it seems to 1) take longer than it used to (as it when I created the story) to pre load the imagery; and 2) the fires take longer to load and it takes 2 or 3 loops before all of the fires appear in the animation. This happens on the initial load, but also if you change steps and go back to step 2 again, it has to load everything again.

**Comment by edplato** [comment]
I see this in Windows Chrome UAT as well. I am also getting an unrequested debugger pause when devtools panel is open with the message `paused before potential out-of-memory crash`. May be related to #3039 changes.

**Comment by minniewong** [comment]
interim fix - zoom out one level.
