### ISSUE TITLE
Social links are not displaying correct urls on hover / twitter not opening correct url

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3067]
**Describe the bug**
Social links are not displaying correct urls on hover / twitter not opening correct url.

**To Reproduce**
1. Go to Social buttons - hover over - note `/#`
2. Click on Twitter button and see broken link?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Benjaki2** [comment]
Email redirect seems to be broken as well. (macOS chrome)
