### ISSUE TITLE
ghost measurement labels

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3072]
1. Start an area or distance measurement
2. While measuring, click on the Ruler icon/button
3. Click on "measure area" or "Measure distance"
4. See a "ghost" measurement label (of the distance/area from where you started to when you clicked on the ruler icon) that remains on the map and cannot be removed. 

![Screen Shot 2020-08-28 at 10.57.45 AM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/93c198ca-d9cd-4ca3-b012-b14dc95ac024)

Chrome and Firefox

**Comment by jasontk19** [comment]
Hmmm, this didn't happen for me when I tried to reproduce.  Is this happening every time?  Maybe I'm missing some step 🤔

**Comment by minniewong** [comment]
Happening every time in Chrome and Firefox. Natalie had also noticed it earlier in SIT but couldn't reproduce it.
