### ISSUE TITLE
Custom palette revert to original intermittently breaks for snapshots

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3098]
**Describe the bug**
Custom palette revert to original intermittently breaks for snapshots and possibly only for certain layers (e.g., `VIIRS_SNPP_DayNightBand_ENCC`). 

**To Reproduce**
This bug is inconsistent in triggering and I'm not certain of the exact steps to reproduce it. However, this is a series of steps that I've encountered to cause the error:
1. Have a custom palette selected for `VIIRS_SNPP_DayNightBand_ENCC`
2. Change projection from `geographic` to `arctic`
3. Try to take a snapshot
4. Click `OK` on dialog indicating the palette will revert to original (the desired action to revert the custom palette to the original never completes and gets stuck here with the error)
5. See error

This is one instance of the copied url after the error occurred:
`https://worldview.earthdata.nasa.gov/?v=-2881165.258872362,-623426.8153981147,-538253.2588723621,920765.1846018853&p=arctic&t=2019-02-01-T00%3A00%3A00Z&l=VIIRS_NOAA20_Thermal_Anomalies_375m_Day,VIIRS_SNPP_DayNightBand_ENCC(palette=red_2),Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor`

**Screenshots**

**Error case 1: First click on `OK`**
![image](https://user-images.githubusercontent.com/24417194/92610426-afaacd00-f285-11ea-8802-ae901cc9080f.png)

**Error case 2: Second click on `OK`**
![image](https://user-images.githubusercontent.com/24417194/92610491-bf2a1600-f285-11ea-8bdc-7fcf4baf1599.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Benjaki2** [comment]
@edplato Not able to reproduce this issue on `OSX` chrome or Firefox, develop or Prod. Maybe a windows-specific error?

**Comment by edplato** [comment]
It was very intermittent and I couldn't provide clear steps to reproduce. I'm not sure if it's OS related. Based on the error it looks like an `undefined` is making it to a reducer somewhere. I can't reproduce it now either. Close it and can reopen if encountered again.
