### ISSUE TITLE
Colormap Legend units aren't at the end of the colorbar on mobile

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3125]
![Screen Shot 2020-09-21 at 4.12.40 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/b7f6ec08-9a31-4420-941d-f259102e530a)

On mobile, the units of the color bar aren't at the end of the colorbar, but at the far right of the layer picker window. Seems like it should display at the end of the colorbar

**Comment by jasontk19** [comment]
Looks like this was still lined up properly in version 3.3.0 as seen on GIBS UAT Worldview-Dev archive

**Comment by ibamibrhm** [comment]
I create PR for this issue, #3151
