### ISSUE TITLE
Remove map zoom buttons in mobile

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3156]
**What existing feature could be improved?**
Perhaps a good place to start for improving the mobile UI is removing the map zoom buttons when the app is in mobile. I notice major mapping platforms interfaces like Google Map and Bing Maps do not have zoom buttons in mobile, so I expect users to be familiar with the zoom pinch interaction necessary to zoom in/out of the Worldview map.

**Additional context**
I think we can remove the rotate buttons in the mobile UI at the same time; however, I could see keeping them since the use case of these buttons may be rare enough for users when compared to other mapping applications they're familiar with.

**Comment by jasontk19** [comment]
I think dropping the rotate buttons would be OK as well

**Comment by edplato** [comment]
Based on design meeting, we're good to remove the zoom buttons. It was decided there is still some value in the rotate buttons and to keep them for now since rotating the map is not as intuitive as mobile zooming and also resetting rotation without the buttons might be confusing for some users. However, with the zoom buttons removed, now the rotate buttons can be slightly repositioned and resized to help minimize the UI footprint.
