### ISSUE TITLE
Break up configuration.md file into smaller files

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3166]
**What existing feature could be improved?**
Break up [configuration.md](https://github.com/nasa-gibs/worldview/blob/master/doc/configuration.md) into smaller, more digestible files. Possibly add a barebones **Get Started** kind of section with brief explanations for a user to get up and running quickly. Then if the users wants to explore deeper configuration options, we can retain our current detailed documentation with those topics.

**Comment by jasontk19** [comment]
I will grab this and add the additional Joyride related tour configuration options in this ticket.
