### ISSUE TITLE
Take advantage of EONET magnitude fields.

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#3174]
**Describe the improvement you'd like**
The EONET API provides magnitude information for several event types.  The magnitude units can be requested via [this API call](https://eonet.sci.gsfc.nasa.gov/api/v3/magnitudes) and the values are included in the API call for events we are already making.  We should display this information meaningfully for storms and icebergs which are the only event types we show which would include this information.  An example event with magnitude information would be [this Typhoon Molave event](https://eonet.sci.gsfc.nasa.gov/api/v3/events/EONET_5134)

Magnitude is provided for each date listed for an event like so:

```
{
"magnitudeValue": 35,
"magnitudeUnit": "kts",
"date": "2020-10-24T12:00:00Z",
"type": "Point",
"coordinates": [
128.9,
13.4
]
},
{
"magnitudeValue": 40,
"magnitudeUnit": "kts",
"date": "2020-10-24T18:00:00Z",
"type": "Point",
"coordinates": [
127.7,
13.4
]
},
...
```

A simple approach would be to include a small tooltip or some other element above the icon on the map that shows this information.

**Comment by jasontk19** [comment]
* Put magnitude values next to dates in the list
* Change circle sizes based on magnitude values
* Show tooltips for points on track, either on hover or at all times?

**Comment by jasontk19** [comment]
Sea/lake ice magnitude is represented in `nm^2`.  Looking at the response from [https://eonet.sci.gsfc.nasa.gov/api/v3/events](https://eonet.sci.gsfc.nasa.gov/api/v3/events) the values range from `~25 - 2132` for events that are being returned at this time.  Sometimes the values vary slightly across days for a single event, but in most cases either:
* a number of days will have the same value while the rest are just `null` (e.g. https://eonet.sci.gsfc.nasa.gov/api/v3/events/EONET_2934).
* all days have the same value

For this reason, I'm not sure there's much value in trying to style the event point size based on the magnitude value for sea/lake ice.

**Comment by jasontk19** [comment]
Next steps:  re-assess available magnitude data now that historical event browsing is in place and a larger sample of events can be analyzed.

**Comment by minniewong** [comment]
This ticket has been moved to: WV-1944
