### ISSUE TITLE
Orbit tracks aren't showing on the left wing when zoomed out

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3177]
When zoomed out, the orbit tracks aren't showing on the left "wing": https://go.nasa.gov/3jJjCp0. They then appear when you zoom in further. 

![Screen Shot 2020-10-30 at 5 00 14 PM](https://user-images.githubusercontent.com/10747923/97756521-66326d80-1ad1-11eb-86e0-b7667351d64f.png)

**Comment by edplato** [comment]
This WMS `GRUMP_Settlements` layer offset looks to be related to the orbit tracks. When zooming in to reveal the orbit track, this offset of GRUMP points disappears at the same zoom/breakpoint point. First thought is the extent wrap changes in `createLayerWMS`.

**Comment by Benjaki2** [comment]
It looks like the change from 256 -> 512px tiles caused this bug. It looks like it might be an actual bug in OL. One workaround I see that works is requesting 256 tiles at zoom 0 and 512 for the rest (for WMS layers). Does that sounds like a reasonable hack @rboller ? I can also open a ticket on OL to see if they have any advice.

**Comment by rboller** [comment]
@Benjaki2 that sounds like a reasonable plan to me - I'd suggest starting with OL to see if a fix can be done on that level.  If not, I'm good with changing the tile size to 256 for the affected layers.
