### ISSUE TITLE
Snapshot doesn't work right with SEDAC's layers

### ISSUE THREAD

**Issue by pombero** [nasa-gibs/worldview#318]
Conditions, layers:
- Fires and Thermal Anomalies (Day and Night) Terra/MODIS
- Reservoirs SEDAC Global Reservoir and Dam Database (GRanD), v 1.1
- Coastlines OpenStreetMap

The image generated doesn't contains, or is incomplete, SEDAC's data.

WorldView:
![worldview](https://cloud.githubusercontent.com/assets/158188/26742494/42ae0cc8-47b4-11e7-8bfd-d61b5fe4c58a.jpg)
Snapshot 1:
![snapshot1](https://cloud.githubusercontent.com/assets/158188/26742487/3c03f18a-47b4-11e7-937f-424244996e70.jpeg)
Snapshot 2:
![snapshot2](https://cloud.githubusercontent.com/assets/158188/26742486/3bff6926-47b4-11e7-9a0e-c096f3275f40.jpeg)

**Comment by pombero** [comment]
It seems that snapshot cuts SEDAC's layer at specific longitudes.

Snapshot 3:
![snapshot3](https://cloud.githubusercontent.com/assets/158188/26742847/cc7c31c2-47b5-11e7-8683-5948e6e086c5.jpeg)

**Comment by rboller** [comment]
Thanks for the report, @pombero!  I can reproduce the problem and we'll take a look into it on the server side.

**Comment by minniewong** [comment]
@pombero - This issue has been fixed.
