### ISSUE TITLE
Allow comparison mode to work on mobile

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3188]
Comparison mode partially works on mobile, if you go to a comparison link like: https://go.nasa.gov/3ldGVsu, swipe appears and you can compare between the images. When you open the layer list, it shows the "B" side layer list, and when you close the layer list, you are no longer in compare mode, and will be viewing the "B" date. 

We should allow Comparison mode to work on mobile and to display the two layer lists.

**Comment by edplato** [comment]
Consider limiting to swipe mode and possibly also opacity mode. I could see spyglass causing some usability issues in mobile.

**Comment by minniewong** [comment]
Agreed - Spy currently doesn't work well on tablets either.

**Comment by edplato** [comment]
Smaller viewport comparison mode UI changes related to embedding Worldview with comparison mode #964 : 

- How to display if A/B is selected for date change arrows
- How to view A/B sidebar layers
- How to add layers to A/B
