### ISSUE TITLE
Adding VIIRS Fusion v1.0 STD products

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#3196]
[ICD](https://docs.google.com/spreadsheets/d/1i-pt2bNH_RYtGnhPhVBSXIhPyxOk3-6VyJ9qjBwogcA/edit#gid=953925495). Line 14-17.
Time range is for the whole mission but historical has not been completed yet.

**Comment by minniewong** [comment]
Data download info: 
NOAA20 VIIRS+CrIS Fusion 6-Min L2 Swath 750m 
Short Name:FSNRAD_L2_VIIRS_CRIS_NOAA20
Concept ID: C1645246591-LAADS.html

SNPP VIIRS+CrIS Fusion 6-Min L2 Swath 750m
Short Name:FSNRAD_L2_VIIRS_CRIS_SNPP
Concept ID: C1645249781-LAADS

**Comment by minniewong** [comment]
@jejeking ICD says the start dates are Suomi NPP should be 2012-04-17/P1D and NOAA-20 should be 2018-02-17/P1D, but currently the GC says it's 2012-03-01 for both. Could you update the GC?

**Comment by jejeking** [comment]
Let me know if this is still an issue. Thx

**Comment by minniewong** [comment]
@jejeking Looks good now, thanks!
