### ISSUE TITLE
Add Sea Ice Concentration descriptions

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#323]
nsidc-0051 & nsidc-0081, NISE

**Comment by minniewong** [comment]
Rewrote the descriptions to merge nsidc-0051 and nsidc-0081. Sent to Donna for review.

**Comment by minniewong** [comment]
These layers only work in polar projections - need to test it wil the polar product picker enhancement

**Comment by minniewong** [comment]
Adding descriptions for polar only layers breaks the product picker in geographic mode. I think since the product picker is based on measurements, which only work in Geographic, the two polar only sea ice layers will display in the Geographic product picker but you cannot activate them and it will throw an error in the console. We'll have to consider this issue in #361.

**Comment by minniewong** [comment]
Try the settings we use for coastlines

**Comment by rboller** [comment]
Sounds good
