### ISSUE TITLE
Horizontal rule not visible in layer description

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3230]
Some descriptions have a horizontal rule that is not visible when you click on the "i" in the Layer List. The Horizontal rule is visible as a grey line when you read the description in the Layer Picker. 
Example below is where the horizontal rule is under the 29 June 2020 Notice for the ENCC Night lights imagery. 

Layer List
![Screen Shot 2020-12-17 at 9.59.54 AM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/a8b212e2-1934-410a-be9c-4a93315cb1c5)

Layer Picker
![Screen Shot 2020-12-17 at 9.59.31 AM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/e83edb0c-82b8-4685-8981-768281c4c4f2)

**Comment by jasontk19** [comment]
It's there... just very very dark 😄  We'll need to update the styles

**Comment by jasontk19** [comment]
Addressed in #3606
