### ISSUE TITLE
Fix broken SSMI sea ice data download

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#324]
Data download for SSMI sea ice is currently [broken](https://worldview.earthdata.nasa.gov/?p=arctic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,SSMIS_Sea_Ice_Concentration,VIIRS_SNPP_Fires_375m_Night(hidden),VIIRS_SNPP_Fires_375m_Day(hidden),Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2017-03-06&z=3&v=-6389760,-3869884.54315269,6586368,1741635.45684731&ab=off&as=2017-05-30&ae=2017-06-06&av=3&al=true&download=NSIDC-0051-0081) in v.1.4.5.  It did work in v1.4.4.

**Comment by minniewong** [comment]
@rboller - When I do a search for "NSIDC-0051" and "NSIDC-0081" in Earthdata Search no results are returned (or even a search for "Sea Ice Concentration", the two collections are not returned in the search results). When I do the same search in Reverb, I get the correct search results. Could this actually be a bug with the newly released Earthdata Search (last wednesday) - something that was changed on their end that we are not properly querying?

**Comment by minniewong** [comment]
Upon further inspection, I noticed I had to check a box in Earthdata Search that said "Include collections without granules", then NSIDC-0051 and NSIDC-0081 showed up. This might be something that we have to account for in Worldview data download?

**Comment by rboller** [comment]
Fixed in PR #340 and options repo PR [#83](https://github.com/nasa-gibs/worldview-options-eosdis/pull/83).

Should merge and deploy for the next release since data download is broken for all collections - mostly affects SEDAC layers.
