### ISSUE TITLE
Add current date to URL if any other parameters are changed

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3242]
**What existing feature could be improved?**
Currently, the share dialog adds the current date in the shareable input URL, but if a user copies from the browser URL then the date `t=YYYY-MM-DD...` query string parameter will be omitted as a default parameter.

**Describe the improvement you'd like**
Add current date to URL if any other query string parameters are changed. 

**Describe alternatives you've considered**
One potential issue is if users currently copy/paste a URL without the date included from the browser URL with the goal of getting the most recent imagery of a target area. This could potentially be addressed by updating documentation and adding an option within the share dialog to toggle off the date to get the most recent imagery (e.g, 'Always Show Today' in Snapshots).

**Comment by rboller** [comment]
Sounds good - I've added it to our agenda for review next week.  Thanks for the fix and review @edplato @jasontk19 !
