### ISSUE TITLE
Add legend to KM[LZ] output from image snapshot

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#3258]
Perhaps it would be helpful for the KMZ file that is generated by the image snapshot tool to also include the legend as a secondary item of some kind.  See [here](https://www.google.com/earth/outreach/learn/adding-legends-logos-and-banners-to-google-earth-with-screen-overlays/) for some context.

**Comment by edplato** [comment]
Moved to Jira WVS-328.
