### ISSUE TITLE
Replace loader spinner with a React solution

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3260]
**What existing feature could be improved?**
The loader spinner could now be handled from the Redux store using a React based solution. Recent changes in removing jQuery/refactoring data download into smart handoffs present an opportunity to rethink `indicator.js` since its code has been tied closely to both those.

**Describe alternatives you've considered**
https://www.npmjs.com/package/react-spinners  FadeLoader spinner in this module seems like a good option to me

**Comment by jasontk19** [comment]
I would love to see us move to something like Material UI.  They offer a huge variety of customizable React components including various types of [loading indicators](https://material-ui.com/components/progress/).  I think we could completely replace Reactstrap and react-slider with Material UI.

**Comment by jasontk19** [comment]
Also... for the loading indicator to be useful on page load, we really would need to load it separately from our bundled `wv.js` file.  Currently, if you are on a slow connection, you won't see anything the entire time our rather large JS file is being downloaded.  And by the time it finishes and shows the loading indicator, you only see it briefly before the app is up and running.

**Comment by edplato** [comment]
I could definitely see moving to Material UI for overall UI changes. Your page load comment reminds me how cool a proper splash page would look to help with slower connections loading and add to a nice clean mobile look during page load.
