### ISSUE TITLE
Allow flexible categories naming for product picker layers

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3282]
**What existing feature could be improved?**
There are currently some expectations that product picker category names will remain our default names (e.g., 'hazards and disasters') that may cause issues with user custom configurations that add/remove category names or use their own unique category naming. This causes a bug where the product picker won't open when clicking the Add Layers button.

**Potential solution(s)**
There may need to be some parsing of categories from the config files during build stage that are then added to the relevant `web/js` files and/or some `initialState` handling that relies on the config object.

**Comment by jasontk19** [comment]
Hmmm I thought I addressed this recently in this PR: https://github.com/nasa-gibs/worldview/pull/3131. Categories _should_ be entirely config driven now.

**Comment by edplato** [comment]
Wow, looks like it! This was a debug off `master` that the user is having issues with, so that adds up.

Will close.

**Comment by edplato** [comment]
Reopening to determine a way to allow legacy configurations without `categoryGroupOrder.json` to be able to still use application. We may want to update release notes to indicate this can be a breaking change to the configuration.

**Comment by jasontk19** [comment]
If we are going to do anything it will need to happen this release

**Comment by edplato** [comment]
Ok, I will take a look now to see where my particular problem was happening. I didn't end up getting that error - I think it was breaking there or before that point from `categories` or `categoryGroupOrder`  being `undefined`.
