### ISSUE TITLE
Added ISS/LIS FC and RAD QC

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#3285]
Best endpoint for ISS/LIS FC and RAD STD will now point to the QC and not the Non QC products between 2017-03-01 and 2019-09-30.

See [ICD](https://docs.google.com/spreadsheets/d/1Y33ggDjGlpSJfCvuA1arxcCp1A1NPbcA-S5EntaFwFg/edit#gid=1976815606) Lines 9-10

**Comment by minniewong** [comment]
Removed "NRT" from layer names. Will need metadata to point to correct download when available

**Comment by minniewong** [comment]
Updated layer metadata with QC conceptid
