### ISSUE TITLE
Gruntfile.js HTTP/S proxy

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#330]
For UAT, we need a way to pass in an HTTP/s proxy value to the exec:python_packages directive.  I made the following hack, but I'm sure there is a better way to do it, and it needs to be "switchable" via command line flag

command: 'export http_proxy=http://xxx.xxx.xxx.xxx:xxxx && export https_proxy=http://xxx.xxx.xxx.xxx:xxxx && export HTTPS_PROXY=http://xxx.xxx.xxx.xxx:xxxx && export HTTP_PROXY=http://1xxx.xxx.xxx.xxx:xxxx && virtualenv python && bash -c \"PATH=' + pythonPath + ':${PATH} pip install xmltodict isodate\"'

**Comment by minniewong** [comment]
@mcechini and @jejeking - closing this ticket. Reopen if you need it.
