### ISSUE TITLE
#Installation Section on README.md

### ISSUE THREAD

**Issue by ferminjavila** [nasa-gibs/worldview#331]
Please update the Installation section on the README.md file. The prerequisites (versions of them) are not clear. I have spent two days trying to install Worldview  in Debian Jessie x64 using node v4 or v6 or apache.
I always get some warnings trying to make a npm install:

npm WARN package.json @1.4.5 No license field.
npm WARN deprecated grunt-rename@0.1.4: Deprecated
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
grunt Failed!

Thanks in advance for your support!

**Comment by tgunnoe** [comment]
It looks like jessie has an older package of node, 0.10.x, youve installed node v6 using these instructions? https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

I ran through a default jessie installation, and the default node/npm packages weren't sufficient.  But using the instructions from the link above
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
`
