### ISSUE TITLE
Easter Egg - Current TMS / Resolution 

### ISSUE THREAD

**Issue by mcechini** [nasa-gibs/worldview#3313]
It would be really nice if there was a way that I could toggle on the display of the following values. Maybe a special KVP in the URL. Wouldn't have to be bookmarkable. I'm thinking it would show up down near the lat/lon and measurement information.

1. Current Tile Matrix
2. Current Pixel Resolution (either in degree/pixel or meter/pixel... or scale denominator)

**Comment by rboller** [comment]
After discussion in backlog grooming today, we decided that the audience for this would be quite limited and add noise for most users.
