### ISSUE TITLE
Utilize additional visualization metadata fields

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#3314]
**What existing feature could be improved?**
Currently we are pulling `conceptIds` from GIBS visualization metadata.  We should also take advantage of several additional properties such as: `orbitTracks`, `orbitDirection`, `daynight`, `ongoing`, `layerPeriod`

It may also be worth considering taking advantage of the `title` and `subtitle` fields since these are currently just being duplicated between Worldview configs and the vis metadata configs.  But, we would need to determine which take precedence and whether we should remove these properties from our configs.

**Comment by minniewong** [comment]
Some layers have no `layerPeriod` but have an associated data product (e.g. SEDAC layers), it would be nice if we could omit the date in the smart handoffs URL so a user doesn't have to remove it themselves in ED search.

**Comment by jasontk19** [comment]
@minniewong Good catch... I think this would probably be a simple one-line fix so maybe it's worth getting in for this release.  I will investigate.

**Comment by jasontk19** [comment]
I think we can rely on the layer's `dateRanges` property to determine whether or not to include the date range in the handoff URL params.  The SEDAC layers for example have no date ranges.

**Comment by minniewong** [comment]
Moved to WV-1934
