### ISSUE TITLE
"Today" or "Now" button/shortcut

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#3315]
**Is your feature request related to a problem? Please describe.**
As discussed (frequently) in the past, there are times when you'd like to instantly change the date to be "today" rather than having to manually update the year, month, day, etc.

**Describe the solution you'd like**
To test the waters, we can start by adding a keyboard shortcut to avoid allocating the screen real estate and design cycles.  

**Additional context**
Note that there is a distinction between "today" and "now", in that "today" implies just changing the date to today's date... but "now" also changes the time of day to "right now" which could be useful for geostationary layers which are updated every 10 minutes.  TBD which one we want to do.

**Comment by minniewong** [comment]
Come up with a design first :)

**Comment by minniewong** [comment]
FYI - Just happened to find the old "today" button ticket: https://github.com/nasa-gibs/worldview/issues/516
