### ISSUE TITLE
perm.in.layers.3 - URL returns an unexpected error

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3322]
**Describe the bug**
Clicking on the link in perm.in.layers.3 returns "An unexpected error has occurred!"

**Expected behavior**
Layers should be empty. The check is to ensure that the link works without any layers. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 78.6.1esr (64-bit)
 - SIT

**Comment by jasontk19** [comment]
`/?l=&now=2013-07-01T12`
