### ISSUE TITLE
Can't click on zots or settings buttons in layer list in landscape mode on iPad

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3331]
**Describe the bug**
Landscape mode on iPad makes Worldview look like the desktop version but you cannot click on the zots for more info, the layer description, settings, and remove layer buttons in the Layer List. 

**Expected behavior**
Should be able to perform the above actions, or not given the opportunity to see them (which you don't in portrait mode)

**Desktop (please complete the following information):**
 - OS: iPad
 - Browser: safari
 - Version: [e.g. 22]

**Additional context**
Perhaps these things should be considered under the mobile UI enhancements epic

**Comment by jasontk19** [comment]
I am able to click the zot and the tooltip shows.  The info, settings and remove buttons don't show until I tap on a layer row but, when I do they appear and I can tap them and they successfully perform the intended operation.  I tested on an iPad Air 2 with Safari.

**Comment by minniewong** [comment]
Then it's down to my very old ipad - We can close this ticket.
