### ISSUE TITLE
Can't drag to move vector modal (iPad)

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#3338]
**Describe the bug**
The vector modal can't be dragged into different positions on a touch device.  The resize and close interactions work fine.

 - Device: iPad
 - OS: iOS
 - Browser: Safari

**Comment by jasontk19** [comment]
This one has me stumped...

It appears to have something to do with the Reactstrap <Modal> component we are using in `modal.js:170`.  If you replace this with a vanilla `<div>` it works as intended (can be repositioned via touch events). 

This works in production currently so it looks like something must have changed _somewhere_ but I can't find where.  Here's what I've ruled out:

* No obvious related recent changes in `modal.js` since the last release (Reverting the changes in [this commit](https://github.com/nasa-gibs/worldview/commit/d45c0abd9984a252793a57c30920de72076f7b96) did not fix the issue)
* No version change to either `react-draggable` or `reactstrap` since last release
*  The `<Draggable>` component from the `react-draggable` library works perfectly fine for the animation widget so it doesn't seem to be a problem with that.
* Confirmed that `onTouchStart` events are firing on the drag handle target (`.modal-header`)

**Comment by edplato** [comment]
It looks like this (git blame me!) commit broke it: https://github.com/nasa-gibs/worldview/commit/ff3ccddb39a90ed0bf7160f9052102b18bdeb2e0

**Comment by jasontk19** [comment]
Now I'm confused... the `package.json` still points to `^4.1.0` but the `package-lock.json` points to 4.4.3?

**Comment by edplato** [comment]
I guess the dependabot only updates `package.json` if necessary and the `^` should package up to next major release `5.0.0`, which may be risky. I'm checking now to see if a simple revert will fix.
