### ISSUE TITLE
Vector layers with too many points can crash the browser (iPad)

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#3339]
**Describe the bug**
Zooming out to show too many points can easily crash the browser on a touch device.  Some layers switch to WMS tiles at outer zoom levels but the reservoirs layer appears to not do this (there may be others?) and this will crash the browser.

**To Reproduce**
1. Load the Dams layer
2. Load the Reservoirs layer
3. Zoom out until crash

- Device: iPad AIr 2
- OS: iOS
- Browser: Safari

**Comment by Benjaki2** [comment]
HLS grid is another layer that doesn't have the WMS transition but I don't think there are too many features for that layer.
