### ISSUE TITLE
Color Palette not working for orbital tracks

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#334]
![color_palette_issue](https://user-images.githubusercontent.com/17348884/27147883-64f32ed8-510c-11e7-8d9d-e9afebd1d2b9.png)

Orbital tracks not changing color.

**Comment by minniewong** [comment]
Linked to https://bugs.earthdata.nasa.gov/browse/WV-1759 and possibly https://bugs.earthdata.nasa.gov/browse/WV-1772

**Comment by minniewong** [comment]
also doesn't work with any of the Fire layers

**Comment by ZachTRice** [comment]
Also, when you change the color and then hover the color box again the label below the color box disappears.

**Comment by minniewong** [comment]
Waiting for OpenLayers to merge fix

**Comment by minniewong** [comment]
OpenLayers has merged change, but need to release the fix

**Comment by ZachTRice** [comment]
This is no longer relevant since we removed the option to change colors for orbit tracks and we will have support for it in upcoming vector tiles.
