### ISSUE TITLE
Map won't drag after removing/re-adding layers in Compare mode 

### ISSUE THREAD

**Issue by npressley** [nasa-gibs/worldview#3341]
Testing [compare.swipe.1](https://wiki.earthdata.nasa.gov/display/WOR/S-26+%5Bcompare%5D%3A+Comparison)

After I remove the layers then re-add per instructions, I cannot drag the map and the compare line doesn't move the B side with it.

Mac, Chrome Version 88.0.4324.150
<img width="1736" alt="Screen Shot 2021-02-09 at 12 28 31 PM" src="https://user-images.githubusercontent.com/42679804/107402767-59f77c80-6ad2-11eb-829f-d8787c863349.png">

**Comment by minniewong** [comment]
I was able to replicate this a few times, and then it started working again for some odd reason. Another thing I noticed was that if you added an image e.g. Corrected Reflectance Terra/MODIS to the A side and added nothing to the B side, then refreshed the page, the B side will also populate Corrected Reflectance Terra/MODIS for the correct "B" date.

**Comment by jasontk19** [comment]
I was able to reproduce as well... and in my case toggling the AOD layer does nothing, while toggling the Corrected Reflectance layer toggles the AOD layer.  Resizing my browser fixed that particular issue but I was still unable to drag the map.

![Screen Shot 2021-02-09 at 2 12 29 PM](https://user-images.githubusercontent.com/1480000/107415062-e610a080-6ae0-11eb-8b62-87e93a9318ff.png)

I'm guessing something might be happening with events being de-registered but we'll need to investigate more.

**Comment by edplato** [comment]
This appears to be an issue in PROD as well. The fastest way I've found to trigger the issue is to:

2. Load default page and start comparison mode
3. Drag compare swiper so it's not at default middle state
4. Open product picker
5. Add layer and see issue
