### ISSUE TITLE
Trying to Download image with HLS grid active returns an error

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#3343]
**Describe the bug**
Trying to Download image with HLS grid active returns an error

**To Reproduce**
1. Go to '?v=-242.16209711079125,-39.60457890548289,4.255336084090402,79.70252833303897&as=2016-09-21-T00%3A00%3A00Z&ae=2016-09-28-T00%3A00%3A00Z&l=HLS_MGRS_Granule_Grid,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&lg=false&al=true&ab=on&t=2016-09-26-T00%3A00%3A00Z'
2. Try to download image
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OSX
 - Browser: Chrome

**Additional context**
I don't believe there is a WMS layer for the HLS grid. Should we force the user to disable this layer, similarly to graticules?

**Comment by minniewong** [comment]
I had wondered how the image preview was working in the layer description, but then I remembered that I created the image snapshot myself. It might make sense to disable the layer like graticules.
