### ISSUE TITLE
Added AMSR-E SM STD L2/v11 new products.

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#3358]
[GIBS GHRC draft ICD](https://docs.google.com/spreadsheets/d/1Y33ggDjGlpSJfCvuA1arxcCp1A1NPbcA-S5EntaFwFg/edit#gid=70067320).
Lines 92-95.

4 products.

**Comment by minniewong** [comment]
The dates appear to be incorrect in the GC, possibly reversed with end date before start date.

**Comment by jejeking** [comment]
Should be fixed now.
