### ISSUE TITLE
geosearch.permalink.1: Map marker is not on map

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3362]
Map marker does not show on the map when clicking on the link in the test plan. The parameter appears to get stripped out when Worldview loads. maybe just something wrong with the url?

**Comment by edplato** [comment]
Yeah that query string param needs updating. On it.

**Comment by edplato** [comment]
All fixed in the test plan.

**Comment by minniewong** [comment]
And you renamed the test :D
