### ISSUE TITLE
Add VIIRS ClearSky/CYGNSS WS SDR

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#3367]
| Layer Identifier | Title | Subtitle | Source Dataset(s) | Projection |Time Period|
| ------------- |-------------|-------------|------|------|--------|
|CYGNSS_L3_Wind_Speed_SDR_Daily|Wind Speed (Daily)|CYGNSS / DDMI|C1955682144-PODAAC|4326|2018-08-01 to Present|
|VIIRS_NOAA20_Clear_Sky_Confidence_Day|Clear Sky Confidence (Day)|NOAA-20 / VIIRS|CLDMSK_L2_VIIRS_NOAA20<br />CLDMSK_L2_VIIRS_NOAA20_NRT / v1|4326|2018-03-17 to Present|
|VIIRS_NOAA20_Clear_Sky_Confidence_Night|Clear Sky Confidence (Night)|NOAA-20 / VIIRS|CLDMSK_L2_VIIRS_NOAA20<br />CLDMSK_L2_VIIRS_NOAA20_NRT / v1|4326|2018-03-17 to Present|

**Comment by minniewong** [comment]
Awaiting CYGNSS
