### ISSUE TITLE
Update SMAP SSS CAP Products

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#3368]
Both SMAP L3 Sea Surface Salinity CAP Monthly and 8Day-Running-Mean are upgrading from 4.3 to 5.0. The following are their 5.0 concept IDs:
| Layer Identifier | Concept ID |
| ------------- |-------------|
|SMAP_L3_Sea_Surface_Salinity_CAP_8Day_RunningMean|C1972955240-PODAAC|
|SMAP_L3_Sea_Surface_Salinity_CAP_Monthly|C1972950629-PODAAC|

**Comment by minniewong** [comment]
@apdeluca - I noticed we added v4 to the layer-metadata for SSS CAP 8-Day Running Mean. Can you remove it from the layer-metadata and just keep the v5? Remove this conceptID C1650311642-PODAAC. https://cmr.earthdata.nasa.gov/search/concepts/C1650311642-PODAAC.html

**Comment by minniewong** [comment]
i'll fix the above @apdeluca as i'm opening a PR for something else
