### ISSUE TITLE
Investigate and add SI Volcano layer

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#3369]
**Is your feature request related to a problem? Please describe.**
A user has requested that we add a layer containing all volcanoes (or at least non-submarine ones) of the world as provided by the Smithsonian Institution Global Volcanism Program:
https://volcano.si.edu/

**Describe the solution you'd like**
While we could ingest the database and serve it ourselves, the SI also maintains web services which appear to be kept up to date with fields such as "LastEruption":
https://volcano.si.edu/database/webservices.cfm

Their Network KML also provides reference image(s) and links for more information:
https://volcano.si.edu/ge/PlacemarkLinks.cfm

**Describe alternatives you've considered**
We discussed options in a meeting today and decided that it's worth investigating SI offerings and OpenLayers capabilities before confirming a path forward.  Note that this particular user doesn't see a specific need for this layer to be captured by Worldview Snapshots.  It'd be a bonus if it was possible, though.

**Additional context**
Example of what's provided by their WFS as viewed in QGIS:
![image.png](https://images.zenhubusercontent.com/5d55bcb191a5dd02bc6d22d9/532146a4-84c0-4ed4-a3df-ef776c7e4d27)

Example of what's provided by their Network KML:
![image.png](https://images.zenhubusercontent.com/5d55bcb191a5dd02bc6d22d9/814d5648-9424-4eaf-8583-61d9dbf3c2a7)

**Comment by minniewong** [comment]
Awaiting feedback from SI

**Comment by minniewong** [comment]
Possibility to ingest into GIBS/GITC? Give GIBS a geojson file and figure out metadata and style, should do-able. Refresh every now and then.

**Comment by minniewong** [comment]
Moved to WV-1953
