### ISSUE TITLE
Font Awesome icons not loading in IE11

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#338]
In some cases FontAwesome is not loading in IE11. 

I was able to reproduce this on a real machine running Windows 7 as well as Browser stack W7/8.1/10 running IE11. This issue did not happen on a real machine running W10 IE11. 

This only seems to happen after deployment, it does not affect a locally developed version of Worldview.

This seems to be an issue with the current version of Font Awesome (4.7), but we should make sure there is nothing going on on our end.
Ref: [https://github.com/FortAwesome/Font-Awesome/issues/8825](https://github.com/FortAwesome/Font-Awesome/issues/8825)

**Comment by ZachTRice** [comment]
Tried moving `<meta http-equiv="X-UA-Compatible" content="IE=edge">` to first tag in head and removing no-cache / no-store meta tags without any effect.

see: https://stackoverflow.com/a/28490514
see: https://stackoverflow.com/a/39055984
see: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

The next step would be to try number 5 from that last link: "For Internet Explorer: try to get rid of the query strings inside the @font-face definitions. You need a custom css file (Ref: [#3286](https://github.com/FortAwesome/Font-Awesome/issues/3286))".

**Comment by minniewong** [comment]
Wait until FontAwesome 5.0 is released

**Comment by viasors** [comment]
+1 Unfortunately, we see this error as well. The problem occurs when the same font is retrieved from one domain in multiple iframes (but not always).

How it should be solved in version 5?

**Comment by ZachTRice** [comment]
This issue is related to query strings appended to the woff files in FA v4.7. You can see this by inspecting the contents of the font-awesome.min.css file. The developers of FA have stated that v5 has a fix for this issue.
