### ISSUE TITLE
Installation currently breaking on master

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#339]
On OSX, installing a clean version of Worldview master is breaking at the `npm install` stage, looks like something related to react.  See below for details.  @Benjaki2 and @ZachTRice, please take a look when you can.

npm install
npm WARN deprecated grunt-rename@0.1.4: Deprecated
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated fs-watch-tree@0.2.5: This package is outdated and not actively maintained.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.1.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: create-react-class@^15.6.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 15.6.0-rc.0, 15.5.4, 15.5.3, 15.5.2, 15.5.1, 15.5.0, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.1, 1.0.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'react'
npm ERR! notarget

**Comment by rboller** [comment]
Also happening with [latest Travis CI build](https://travis-ci.org/nasa-gibs/worldview/builds/243486273).

**Comment by Benjaki2** [comment]
@rboller @ZachTRice 

I made the package.json versioning stricter and it looks like Travis passed: https://github.com/nasa-gibs/worldview/commit/0f80acc611180cb7bd4afe0d3aac0ab0f2d40db9 . It is weird but maybe the owner of that 'create-react-class' did something funny yesterday. v15.6.0 seems to exist in the npm DB.
