### ISSUE TITLE
Error thrown on changing date on tour step 

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3392]
**Describe the bug**
Error thrown on changing date on tour step. The error appears to happen in `web\js\map\ui.js` `updateDate()`.

**To Reproduce**
1. Go to `?l=VIIRS_SNPP_Thermal_Anomalies_375m_Day(hidden),VIIRS_SNPP_Thermal_Anomalies_375m_Night(hidden),Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor,MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&lg=false&tr=australia_fires_2019_2020&t=2019-09-07-T15%3A25%3A24Z`
2. Click through tour step till STEP 5
3. Click left arrow to change date
4. See error `Uncaught TypeError: Cannot read property 'forEach' of undefined`

Also seeing same error if change date is done after STEP 7 - it should be noted for debug that both steps before STEP 5 and STEP 7 had animations.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by minniewong** [comment]
Also, the map is not zooming to the correct locations for steps 5 and 7

**Comment by jasontk19** [comment]
Hmmm, I am getting a different error: 
```
Uncaught TypeError: Cannot read property 'ol_uid' of undefined
    at getUid (util.js:28)
```

**Comment by edplato** [comment]
I'm seeing that one as well. It looks like the `Uncaught TypeError: Cannot read property 'forEach' of undefined
` error requires a second date change to throw.

**Comment by jasontk19** [comment]
Ah yeah, I see both now.  Guessing the first one is the primary issue.  I also see the zoom issue @minniewong but my first guess would be that this is a separate bug.  @edplato would you mind digging into that one while I look at the date change issue?
