### ISSUE TITLE
Update natural events interface to allow browsing historical events

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#3403]
At present, we are only showing "open" events in our interface but we would like to expand that in order to allow browsing of historical ("closed") events as well.  The current interface should be expanded to allow searching by date range or number of events.  Since the EONET API does not support paging, allowing users to search by arbitrary date range could easily result in huge API responses and an excessive number of events being plotted on the map which would cause UI sluggishness (or worse). 

One possible UI approach to work around this would be to allow the user to pick a limited date range (and also possibly an event category).  Temporal choices could be presented as: last 30 days, then in month blocks going backwards in time.  For example:
* Last 30 days
* February 2021
* January 2021
* etc

Events with "open" and "closed" statuses can be requested simultaneously by using the "all" value for the status parameter (e.g. https://eonet.sci.gsfc.nasa.gov/api/v3/categories/severeStorms?status=all&limit=5)

**Comment by jasontk19** [comment]
test comment

**Comment by edplato** [comment]
In addition to spatial and temporal API requests, we may want to have some sort of internal event collection list to maintain some well known, impactful events. Especially any we may include in a story or EOSDIS link out in an article. I raise this since I'm seeing `https://worldview.earthdata.nasa.gov/?e=EONET_3281` Hurricane Maria come up as a popular URL linked by a search result in metrics and that seems like the kind of storm we may want to always make available.

**Comment by jasontk19** [comment]
Good idea.  I think it's worth some more discussion at a dev meeting to figure out how we would approach this.

**Comment by minniewong** [comment]
Arctic:
- App breaks if you click on North Sea Phytoplankton Bloom, 1 May 2015. Maybe something to do with the box. `?v=-6742016,-7876608,6463488,5705728&p=arctic&e=EONET_13,2015-05-01&efd=2000-01-01,2015-12-11&efc=waterColor,snow&l=VIIRS_SNPP_Thermal_Anomalies_375m_Night(hidden),VIIRS_SNPP_Thermal_Anomalies_375m_Day(hidden),MODIS_Aqua_Thermal_Anomalies_Night(hidden),MODIS_Aqua_Thermal_Anomalies_Day(hidden),VIIRS_NOAA20_Thermal_Anomalies_375m_Night(hidden),VIIRS_NOAA20_Thermal_Anomalies_375m_Day(hidden),MODIS_Terra_Thermal_Anomalies_Night(hidden),MODIS_Terra_Thermal_Anomalies_Day(hidden),MODIS_Terra_Chlorophyll_A(hidden),MODIS_Aqua_Chlorophyll_A(hidden),IMERG_Precipitation_Rate(hidden),VIIRS_SNPP_DayNightBand_ENCC(hidden),VIIRS_SNPP_DayNightBand_At_Sensor_Radiance(hidden),MODIS_Combined_Value_Added_AOD(hidden),MODIS_Terra_Aerosol(hidden),MODIS_Aqua_Aerosol(hidden),OMI_Nitrogen_Dioxide_Tropo_Column(hidden),MOPITT_CO_Daily_Total_Column_L2(hidden),AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Monthly_Night(hidden),AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Daily_Night(hidden),AIRS_L2_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Night(hidden),AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Monthly_Day(hidden),AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Daily_Day(hidden),AIRS_L2_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Day(hidden),AIRS_L2_Dust_Score_Night(hidden),AIRS_L2_Dust_Score_Day(hidden),Reference_Labels_15m,Reference_Features_15m,Coastlines_15m(hidden),VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1(hidden),MODIS_Aqua_CorrectedReflectance_Bands721(hidden),VIIRS_NOAA20_CorrectedReflectance_BandsM11-I2-I1(hidden),MODIS_Terra_CorrectedReflectance_Bands721(hidden),VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2015-05-01-T00%3A00%3A00Z`
- Set to Fire, 1-1-2000 to 12-31-2015, it displays "Showing first 50 events" even though there are only 3 events in list. `?v=-9357170.421775492,-5967323.671163319,8905262.06117803,4619778.79622722&p=arctic&e=EONET_215,2015-10-12&efd=2000-01-01,2015-12-11&efc=wildfires&l=VIIRS_SNPP_Thermal_Anomalies_375m_Night(hidden),VIIRS_SNPP_Thermal_Anomalies_375m_Day(hidden),MODIS_Aqua_Thermal_Anomalies_Night(hidden),MODIS_Aqua_Thermal_Anomalies_Day(hidden),VIIRS_NOAA20_Thermal_Anomalies_375m_Night(hidden),VIIRS_NOAA20_Thermal_Anomalies_375m_Day(hidden),MODIS_Terra_Thermal_Anomalies_Night,MODIS_Terra_Thermal_Anomalies_Day,MODIS_Terra_Chlorophyll_A(hidden),MODIS_Aqua_Chlorophyll_A(hidden),IMERG_Precipitation_Rate(hidden),VIIRS_SNPP_DayNightBand_ENCC(hidden),VIIRS_SNPP_DayNightBand_At_Sensor_Radiance(hidden),MODIS_Combined_Value_Added_AOD(hidden),MODIS_Terra_Aerosol(hidden),MODIS_Aqua_Aerosol(hidden),OMI_Nitrogen_Dioxide_Tropo_Column(hidden),MOPITT_CO_Daily_Total_Column_L2(hidden),AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Monthly_Night(hidden),AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Daily_Night(hidden),AIRS_L2_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Night(hidden),AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Monthly_Day(hidden),AIRS_L3_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Daily_Day(hidden),AIRS_L2_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Day(hidden),AIRS_L2_Dust_Score_Night(hidden),AIRS_L2_Dust_Score_Day(hidden),Reference_Labels_15m,Reference_Features_15m,Coastlines_15m(hidden),VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1(hidden),MODIS_Aqua_CorrectedReflectance_Bands721(hidden),VIIRS_NOAA20_CorrectedReflectance_BandsM11-I2-I1(hidden),MODIS_Terra_CorrectedReflectance_Bands721(hidden),VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2015-10-13-T00%3A00%3A00Z`
-

**Comment by jasontk19** [comment]
Two of these are happening because the API doesn't support projection based filtering... so it says "showing first 50" events because there are 50+ events but few (or none) in the current projection.  I can update the count to be based on the events filtered for projection.

As for the first antarctic issue listed:  The date based filtering considers _all_ dates listed for an event.  So if even one set of coordinates for an iceberg is listed within that date range, it will show.  Even if all the others (and most recent) dates are outside that range.

**Comment by jasontk19** [comment]
Demo instance has been updated with filtering for bounding box based on the current projection which fixes some of the above issues.
