### ISSUE TITLE
New MISR NRT Layers

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#342]
We've added the following layers to GIBS, now ready for Worldview:

| Layer Identifier | Title | Subtitle | CMR Product |
| ------------- |-------------|-------------|------|
|MISR_AM1_Ellipsoid_Radiance_RGB_AA|Color Radiance (AA, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_RGB_AF|Color Radiance (AF, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_RGB_AN|Color Radiance (AN, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_RGB_BA|Color Radiance (BA, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_RGB_BF|Color Radiance (BF, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_RGB_CA|Color Radiance (CA, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_RGB_CF|Color Radiance (CF, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_RGB_DA|Color Radiance (DA, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_RGB_DF|Color Radiance (DF, RGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_AA|Color Radiance (AA, NGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_AF|Color Radiance (AF, NGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_AN|Color Radiance (AN, NGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_BA|Color Radiance (BA, NGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_BF|Color Radiance (BF, NGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_CA|Color Radiance (CA, NGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_CF|Color Radiance (CF, NGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_DA|Color Radiance (DA, NGB)|MISR|C1000000100-LARC|
|MISR_AM1_Ellipsoid_Radiance_NGB_DF|Color Radiance (DF, NGB)|MISR|C1000000100-LARC|

**Comment by minniewong** [comment]
Can't release yet because:
- Some data alignment issues and other upstream data provider fixes that need to be made;
- Data download needs to be updated - we need how to filter by camera, they need to update CMR record for ftp site

**Comment by minniewong** [comment]
- Waiting for data provider to assess alignment issues with imagery
- Data download awaiting review by data providers #352

**Comment by rboller** [comment]
The data provider and GIBS are working to update the alignment issues.

The science team requests that Worldview updates the labels and descriptions accordingly:
1) the second letter is lower case, i.e., Df, Cf, Bf, Af, An, Aa, Ba, Ca, Da
2) there is no "Cg" camera, it should be "Cf"
3) the acquisition order of the cameras should be noted in the description: "Df, Cf, Bf, Af, An, Aa, Ba, Ca, Da"

Will hold off on these updates until there is new imagery available to evaluate.

**Comment by rboller** [comment]
Made all updates suggested above which have been approved by stakeholders.

Ready to merge into master, though deployment will need to wait until GIBS-2479 is complete (updating MISR NRT layers in GIBS GetCapabilities document to start at 2017 Sep 1).
