### ISSUE TITLE
Natural events icons are not visible in mobile when loading a url with an event selected

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3429]
**Describe the bug**
Natural events icons are not visible in mobile when loading a url with an event selected. The icons show fine when switching from desktop to mobile, so it may be something with how the mobile events are initially loaded.

**To Reproduce**
1. Go to 'https://go.nasa.gov/2NR9WPi' in a mobile or simulated responsive mode
2. See no natural event icons

**Expected behavior**
Natural event icons are shown in mobile when navigating to a permalink with an event.

**Additional context**
This has been an ongoing issue since early `v3.x`

**Comment by jasontk19** [comment]
Good find... I will take a look at this and see if it's an easy fix for the existing PR
