### ISSUE TITLE
Activate MERRA2/NLDAS/OMI STD Layers

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#343]
We are now forward process the following the layers, and should be considered active:

|Best Available External Identiifier|
|-------------|
|OMI_Absorbing_Aerosol_Optical_Thickness_MW_388|
|OMI_Ozone_DOAS_Total_Column|
|OMI_Ozone_TOMS_Total_Column|
|OMI_Nitrogen_Dioxide_Tropo_Column|
|NLDAS_Surface_Total_Precipitation_Primary_Monthly|
|NLDAS_Near_Surface_Air_Temperature_Primary_Monthly|
|NLDAS_Surface_Total_Precipitation_Secondary_Monthly|
|NLDAS_Underground_Soil_Moisture_Mosaic_Monthly|
|NLDAS_Underground_Soil_Moisture_Noah_Monthly|
|NLDAS_Underground_Soil_Moisture_VIC_Monthly|
|MERRA2_Surface_Skin_Temperature_Monthly|
|MERRA2_Surface_Pressure_Monthly|

**Comment by minniewong** [comment]
@apdeluca - we do not have the hourly layers in Worldview

**Comment by apdeluca** [comment]
Ok, I remove hourly.

**Comment by minniewong** [comment]
Are these now up to date? OMI layers only go up until 16 June and NLDAS monthlies to April 30. Merra looks good.
