### ISSUE TITLE
Added AERain v13 - version update

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#3444]
GHRC ICD - Lines 56-59

note: AERain_SR is being replaced by AERain_WV. This is a new BEST endpoint.

**Comment by jejeking** [comment]
Also, currently doing the historical processing. We completed 2002 and currently processing 2003. You can see the difference in the color scheme. The previous imagery did not match the colormap at all.

**Comment by minniewong** [comment]
Surface Rain will be replaced with Water Vapor; updated Surface Precipitation

**Comment by minniewong** [comment]
Historical reprocessing has been halted, fixes are being made and will be reprocessed again.

**Comment by minniewong** [comment]
Moved to WV-1935
