### ISSUE TITLE
Clean up/remove unused geostationary modal

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3445]
**What existing feature could be improved?**
Clean up/remove unused geostationary modal `js`, `css`, and `geostationary.gif`. It may be useful to leave a bare bones component in place for future temporary new feature alerts, but the `css` can at the least be commented out and the unused `gif` and related code removed.

**Comment by kberba** [comment]
Hi, I'm new to contributing to open source projects, but would I be able to take on this issue? Thank you!
