### ISSUE TITLE
BEST pointing to C6.1 NRT for all MODIS LAND products for the last 3 days

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#3454]
GIBS is now serving C6.1 NRT for all MODIS LAND products instead of C6.0 NRT.

For all products on lines 270-286, 306-322, 342-343.
This is NOT affecting MAIAC and BRDF products (lines 348-350). Those are still v6.0

For 342-343, those do not have a STD companion. So BEST is serving NRT C6.0 until March 28th and after that it serves C6.1 NRT.

For the rest, BEST points to NRT C6.1 until STD C6.0 replaces it 2~3 days later. 
We are currently working on updating STD LAND products to C6.1

**Comment by minniewong** [comment]
awaiting updated conceptIDs for v6.1 from data provider

**Comment by jejeking** [comment]
it’s all the M[OY]09,10,11,29. Lines 303-319. 335-351. 353-354 in base-lined ICD
