### ISSUE TITLE
Be able to add multiple markers to the map

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3456]
**What existing feature could be improved?**
I see how to add ONE marker to the image via lat/lon, but is it possible to add multiple markers?
"I'd like to put markers on locations in a lake where we took samples aboard the ship during the resuspension event like the one that is there now. "
![image](https://user-images.githubusercontent.com/10747923/114445978-b5abb800-9b9e-11eb-8479-3269d64c5044.png)

**Describe the improvement you'd like**
Be able to add multiple markers

**Comment by minniewong** [comment]
another user: Can more than one marker be placed on an image? I tried to edit URL to add a 2nd lat/lon, and it retains only the last lat/lon set.
Is there a way to use a different, smaller marker?

**Comment by edplato** [comment]
Adding multiple markers is more feasible than changing the marker image. If a user deploys their own instance of Worldview, they can change the interface marker by changing `web/images/map-pin.png` and possibly some related styling positioning code. For Snapshots markers in the images, the marker is added to its MapServer config map file at build time, so there is no current flexibility to change that marker at this time.

**Comment by jasontk19** [comment]
We could also interpret the "smaller marker" request as something to be done on our end. Rather than as an end-user facing feature to change the marker, can we just deploy with a smaller marker.  I don't think it's particularly large as is but maybe some users do?

**Comment by edplato** [comment]
I believe the current interface map marker is appropriately sized but welcome the opportunity to improve it if the team feels it is too large.

**Comment by minniewong** [comment]
Moved to WV-1931
