### ISSUE TITLE
events.trackupdate.2: Date updates but event marker doesn't move to new date

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3472]
The event marker doesn't move to the new date (though the date changes in the sidebar and timeline) when using the URL: v=-48.5388671875,-59.9235546875,-20.361132812500003,-47.6364453125&ics=true&ici=3&icd=7&e=EONET_2934,2021-04-02&l=MODIS_Terra_Sea_Ice(hidden),MODIS_Aqua_Sea_Ice(hidden),VIIRS_SNPP_Brightness_Temp_BandI5_Night(hidden),VIIRS_SNPP_Brightness_Temp_BandI5_Day(hidden),VIIRS_NOAA20_Brightness_Temp_BandI5_Night(hidden),VIIRS_NOAA20_Brightness_Temp_BandI5_Day(hidden),MODIS_Aqua_Brightness_Temp_Band31_Night(hidden),MODIS_Aqua_Brightness_Temp_Band31_Day(hidden),MODIS_Terra_Brightness_Temp_Band31_Night(hidden),MODIS_Terra_Brightness_Temp_Band31_Day(hidden),VIIRS_SNPP_DayNightBand_ENCC(hidden),VIIRS_SNPP_DayNightBand_At_Sensor_Radiance(hidden),Reference_Labels_15m,Reference_Features_15m,Coastlines_15m(hidden),VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2021-04-02-T00%3A00%3A00Z

If I then manually click on the latest point, I can use the advance/back arrow reliably.

**Comment by jasontk19** [comment]
Decided to just remove this from the test suite for now (and remove the related changes from the code) since this was a new piece of functionality that we didn't have before and just seemed like a "nice to have".
