### ISSUE TITLE
Animation Enhancements

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#3473]
**What existing feature could be improved?**
Animation

**Describe the improvement you'd like**
Make animations preload and run smoother than they currently do. Currently animation pauses frequently to preload imagery.

* Requests for map tiles should not be made for dates that a layer is inactive, during preload or otherwise
* Pending requests for tile to cache should be cancelled if animation is stopped
* Certain controls should be disabled while playing (speed, date range, etc)
* The buffer/cache size could be increased in an attempt to prevent stuttering
  * Do some math (based on the time it took to request the first few images and the number of total images) to estimate how many images we need to preload (before starting the animation) in order to animate smoothly. 
* There should be a maximum, or at least a maximum recommended number of frames allowed for an animation.  Trying to play an excessive number of frames is usually the cause of stuttering.  
  *  For example, the [RAMMB SLIDER](https://rammb-slider.cira.colostate.edu/) animation tool allows at most 60 frames, and only allows two layers (1x base layer, 1x overlay)

**Comment by jasontk19** [comment]
Description updated based on discussions so far.

**Comment by minniewong** [comment]
Moved to WV-1942
