### ISSUE TITLE
Location search iPad styling position off

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3476]
**Describe the bug**
CSS related to joyride tour targeting causes a styling issue for iPad (simulated Chrome).
![image](https://user-images.githubusercontent.com/24417194/115901788-a7c42580-a42f-11eb-93a3-65c122709135.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome - simulated iPad

**Comment by jasontk19** [comment]
I don't see this on a real iPad since the resolution is large enough that the app does not enter "mobile" mode.

**Comment by rboller** [comment]
Also tested on landscape and portrait on a real iPad (Pro) and didn't see the issue.
