### ISSUE TITLE
iPad styling issues with various responsive UI elements

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3477]
**Describe the bug**
Styling got weird for iPad Air 2 (simulated Browserstack) around version 3.7.0 and progressively has gotten weirder. 

Some noted issues:
- Date arrows (FlipH related?)
- Sidebar tabs
- Alerts

Fast forward to current PROD and event icon positions seem to be unstyled and stacked in the upper left corner. 

**To Reproduce**
1. Using Browserstack, go to archived v3.7.0 and set to iPad Air 2

**Screenshots**
![image](https://user-images.githubusercontent.com/24417194/115903504-a8f65200-a431-11eb-876e-52dadb6bb6ed.png)

**Desktop (please complete the following information):**

- Device:  iPad Air 2 (simulated Browserstack)
- OS: iOS
- Browser: Chrome

**Comment by jasontk19** [comment]
I'm not seeing any of this on the real device.  Not sure what's going on here but it looks like some Frankenstein between mobile mode and desktop mode.   On the real device, landscape uses desktop move and portrait uses full mobile mode.

**Comment by edplato** [comment]
Weird, it's tough debugging with Browserstack sometimes.
