### ISSUE TITLE
Consider having References measurement group always at the top

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3486]
**What existing feature could be improved?**
References measurement group in Layer List

**Describe the improvement you'd like**
Consider having the References Measurement group always at the top of the layer list. We have received feedback where users were confused as how to move the group up.

**Describe alternatives you've considered**
Possibly this is not necessary once we have a tour that explains the "Group Similar Layers" checkbox. 

**Additional context**

**Comment by jasontk19** [comment]
Consider showing a warning/alert when user tries to drag/drop layer outside of a group or into another group to notify them that layers need to be ungrouped for full control of individual layer order.

**Comment by minniewong** [comment]
Another option is to add new layers under reference layers

**Comment by minniewong** [comment]
Discussed having reference layers always on top if they are grouped.
