### ISSUE TITLE
Set Area of Interest box in dateline wings does not instruct Earthdata Search to download for those dates

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3512]
**Describe the bug**
If you use the set area of interest box and either draw totally on either side of the dateline wings, or half on current day and half on previous/next day, it does not pass that information to Earthdata Search, and Earthdata Search does not show the appropriate dates. 

**To Reproduce**
1. Go to https://go.nasa.gov/3uUMYr1 or https://go.nasa.gov/3wffsMq
2. Set Area of Interest box that is either only on the May 13th side, or one that spans May 14 and 13, Select Standard for AI layer, Click on Download via Earthdata Search
3. See that the Leaving Worldview window shows May 14. Click continue.
4. See error - Earthdata Search only provides data for May 14. If the box spans the two sides of the timeline, it appears to grab the data from either side of the Pacific Ocean for May 14. If the set area of interest box is drawn entirely on the May 13th side, ED Search will give you May 14 for that area. 

**Expected behavior**
I'd expect it to give you the previous/next day. Though I think we should just not allow data download across the date line.

**Screenshots**
Worldview - Set Area of Interest, left side on May 14, right side on May 13
![Screen Shot 2021-05-17 at 1.19.43 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/92f1af0d-7aa3-4bde-84ff-baa0e36ca14a)

Earthdata Search - only returns data for May 14
![Screen Shot 2021-05-17 at 1.20.03 PM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/06255b30-2485-4ba2-a1c3-aba673561eb0)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 90.0.4430.212 (Official Build) (x86_64)

**Comment by jasontk19** [comment]
We should talk through this one at the Thursday meeting

**Comment by minniewong** [comment]
Options
1. Disable data download in wings
2. Throw small warning if entire map view is outside of the current projection extent
3. Detect whether box is crossing dateline and adjust dates accordingly

**Comment by minniewong** [comment]
Moved to WV-1958
