### ISSUE TITLE
CI Changelog Generation using GitHub Action

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3517]
**What existing feature could be improved?**
CI Changelog Generation using a GitHub Action would improve the deployment process by streamlining generating the notes and including within a commit/PR. There are a few Actions options to investigate and find the best for the project's needs.

**Additional context**
The generator appears to work as intended after everything is merged within the target branch; however, the existing changelog generation has some limit request issues due to this repositories large amount of closed issues/PRs.

**Comment by minniewong** [comment]
Moved to WV-1952
