### ISSUE TITLE
Update MISR NRT data download to filter by camera

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#352]
Do more filtering on our request to CMR to get granules for only one camera at a time - possibly separate NGB & RGB downloads, too.

Info on how to filter by sensor:
https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#g-sensor

Example MISR response for DA camera:

Platforms:
    Platform:
      ShortName: AM-1
      Instruments:
        Instrument:
          ShortName: MISR
          Sensors:
            Sensor:
              ShortName: DA
          OperationModes:
            OperationMode: Normal

**Comment by minniewong** [comment]
Need to make sure the NRT data download works as well

**Comment by rboller** [comment]
Linked each camera to its respective data download product.

And after discussion with stakeholders, we decided that it would be best to link directly to MISR Standard products rather than its NRT counterparts.  This was mainly since it could introduce confusion to link to NRT products for "today" while any earlier dates link to Standard products.  Furthermore, the difference in latency between NRT and Standard products is minimal in this case.
