### ISSUE TITLE
Version upgrade - AMSRU-2 SWE (geo/arctic) NRT (v2) and STD (vB02)

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#3530]
GHRC ICD:

Lines 32-39 (STD)
Lines 50-51 (NRT)

Keep in mind that there is 1 daily, 1 5-day and 1 monthly.
Forward processing is set-up in GIBS for all 3 but we currently only the daily one is available from the provider. It will take a week or so for the 5-day and a month for the monthly to be available. There is some older data available for those products. You can see that from the GC temporal values.

In any case, v1 and v2 NRT are linked. Same with vB01 and vB02. Historical is not available yet from the provider.

**Comment by jejeking** [comment]
Looks like May16 came in for the 5-day. GC should get updated soon.

**Comment by minniewong** [comment]
Some imagery missing - 
Daily: missing imagery May 15 - 21 2021
5 Day: March 17 2020 -May 15 2021
Monthly: April 2019 - now (which actually is what the GC says, but seems weird that there’s so much missing)

**Comment by minniewong** [comment]
@jejeking - Presumably these updates should address the fix noted in the descriptions about the artificial, uniform boundary across North America - shall i remove them?

**Comment by jejeking** [comment]
I don't know. How did you know to add the notices in the first place? You may want to check with GHRC or NSIDC and confirm with them?

**Comment by minniewong** [comment]
OK - Must have done it in communication with them, so I'll figure out who to contact.

**Comment by jejeking** [comment]
Historical should be complete for daily and monthly. 5day is 99% done.

**Comment by jejeking** [comment]
All historical for all 3 are now complete for both geo and arctic. let me know if you see anything missing. Thx
