### ISSUE TITLE
Use consistent date formatting throughout the app

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#3539]
**What existing feature could be improved?**
We use too many different date formats throughout the app.  We should compile a list of all the places where dates are displayed and try to bring them into alignment as much as is practical.  To start, some of the known places we show dates are:

* Timeline (including coverage panel)
![Screen Shot 2021-06-01 at 10 44 52 AM](https://user-images.githubusercontent.com/1480000/120343429-b58a8780-c2c6-11eb-8c11-226e71e383ca.png)

* Layer info modal
![Screen Shot 2021-06-01 at 10 44 45 AM](https://user-images.githubusercontent.com/1480000/120343431-b6231e00-c2c6-11eb-884d-5760c8421cc5.png)

* Events (results list, filter dates)
![Screen Shot 2021-06-01 at 10 47 35 AM](https://user-images.githubusercontent.com/1480000/120343524-caffb180-c2c6-11eb-8e03-f362de4ea513.png)

* Layer metadata in category view of product picker (this also needs be pulled from layer metadata derived from GC and not hard-coded in markdown files)
![Screen Shot 2021-06-01 at 10 48 30 AM](https://user-images.githubusercontent.com/1480000/120343711-eff42480-c2c6-11eb-88e4-972521c29b58.png)

**Comment by jasontk19** [comment]
All hail [`toISOStringDateMonthAbbrev`](https://github.com/nasa-gibs/worldview/pull/3544/files#diff-abcf9aeda3c7b9cd676dc30d6b4f543d8eb682c44c2dde65841375faee2555e3R314)!

![hypnotoad](https://user-images.githubusercontent.com/1480000/121687690-a3f86b00-ca90-11eb-92bf-38ef0b195aac.gif)

**Comment by minniewong** [comment]
Moved to WV-1932
