### ISSUE TITLE
Remove all A2RnOcn layers asap

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#3559]
NSIDC and GHRC are asking GIBS/WV to remove the old A2RnOcn layers asap. it doesn't matter that we don't have Ocean STD yet in GIBS to replace them.

**Comment by minniewong** [comment]
Verifying these are the correct layers to be removed (10 layers total): 
- AMSR2_Cloud_Liquid_Water_Day, AMSR2_Cloud_Liquid_Water_Night
- AMSR2_Columnar_Water_Vapor_Day, AMSR2_Columnar_Water_Vapor_Night
- AMSR2_Surface_Precipitation_Rate_Day, AMSR2_Surface_Precipitation_Rate_Night
- AMSR2_Surface_Rain_Rate_Day, AMSR2_Surface_Rain_Rate_Night
- AMSR2_Wind_Speed_Day, AMSR2_Wind_Speed_Night

**Comment by jejeking** [comment]
Correct
