### ISSUE TITLE
date.animation.11: When changing the fps during a playing animation, the does not change speed

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3615]
**Describe the bug**
Start an animation, and change the speed and toggle the loop button - when the animation is playing and you try to change the speed, the speed does not change. 

**To Reproduce**
1. Go to Worldview
2. Click on video camera icon
3. Create a month long animation and press play, change the speed to 10 fps
4. See error - the animation does not speed up

**Expected behavior**
The speed should change right away, but there is an additional issue of the preloading imagery taking a long time to load.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 78.7.0esr (64-bit)

**Comment by jasontk19** [comment]
Will be addressed by #3473
