### ISSUE TITLE
Update tabs to use two spaces (!) instead of four

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#362]
After @Benjaki2's hostile takeover, most of us were convinced to update our tab spaces to be two instead of four.  @ZachTRice says there should be a way to do this in batch.

**Comment by ZachTRice** [comment]
Performing this conversion might cause branches to have merge conflicts. The best time to do this update will be right after a release to minimize the number of checked out / unmerged branches that could be affected. 

I estimate I can have all the files in the js directory beautified and checked over in about an hr. I plan to do this update immediately after 1.4.7 has been released.
