### ISSUE TITLE
Added M[OY]21 C6.1 NRT - Land Surface Temperature TES

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#3621]
ICD lines 40-41 and 58-59.
Only NRT for now. And only 5 days available (July 8th -13th). MODAPS should start forward processing today.

**Comment by minniewong** [comment]
@jejeking The Terra layers are not returning a data download option - were they added to the config?

**Comment by minniewong** [comment]
@jejeking Have they started forward processing? It still ends July 13

**Comment by jejeking** [comment]
From Sudipta yesterday:
"I know Maki was trying to implement the correct code changes on nrt3 last week. I have cc-ed her here for some update on this. but she is tied up with some personal emergency so may not be available much this week. Our CM is also expected back by Thursday of this week. So, things may not progress much at our end over this week."

**Comment by jejeking** [comment]
Answer is no. And may not be starting this week.
