### ISSUE TITLE
Turning on in-browser translation causes timeline to disappear

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#3644]
**Describe the bug**
When in-browser translation (e.g. Google translate in Chrome) is turned on, the timeline disappears and causes an error window to appear. 

**To Reproduce**
1. Go to Worldview using Chrome and install Google Translate
2. Click on "translate this page" and change to another language
3. See error - an Unexpected error message pops up and the timeline disappears. Sometimes if you refresh, it works again and the timeline re-appears, but it will disappear again if you interact with the timeline.

**Expected behavior**
That the app doesn't throw an error. 

**Screenshots**
![Screen Shot 2021-07-23 at 9.38.05 AM.png](https://images.zenhubusercontent.com/5d434327dd8f953c8f021bfa/1a34a37a-f96c-4b62-827c-649c2356019c)

**Desktop (please complete the following information):**
 - OS: OSX and Windows
 - Browser: Chrome
 - Version: Version 92.0.4515.107 (Official Build) (x86_64)

**Comment by jasontk19** [comment]
Any console errors? It works fine for me:
![Uploading Screen Shot 2021-07-23 at 8.27.25 AM.png…]()

**Comment by minniewong** [comment]
![Screen Shot 2021-07-23 at 10 41 48 AM](https://user-images.githubusercontent.com/10747923/126798723-fb0e3123-400f-41e8-8bec-509297ef21f4.png)
