### ISSUE TITLE
Snapshot download filename should show correct date/time for all file types

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#3655]
**Describe the bug**
Snapshot download filename should show correct date/time for all file types. Currently only shows for GeoTIFF

**Comment by edplato** [comment]
This will not be possible client side unless we want to force download and change the current behavior of opening the JPG/PNG in a new tab.

**Comment by jasontk19** [comment]
Right, I assumed this would have to be something we do on the WVS service side?  Should I move this ticket to the WVS Jira?

**Comment by edplato** [comment]
I'll close out - I just made a WVS issue and referenced this original.
