### ISSUE TITLE
Graticule layer not removed, rotate not reset on image download

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#3661]
**Describe the bug**
When downloading a snapshot image, Graticule layer is not being hidden or is and then being made visible too early. This causes an `Invalid name in LAYERS` service exception error. This issue also affects rotation in polar projections as the rotation resets too early before the snapshot is taken.

**To Reproduce**
Steps to reproduce the Graticule behavior:
1. https://worldview.earthdata.nasa.gov/?l=Graticule,Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2021-08-04-T13%3A46%3A29Z
2. Take snapshot, see prompt to clear Graticule, accept, and see Graticule remain
3. Click Download button to request snapshot and see error

Steps to reproduce the Rotate behavior:
1. https://worldview.earthdata.nasa.gov/?v=-6291456,-3088384,6291456,3088384&r=-36.0000&p=arctic&l=Graticule,Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2021-08-04-T13%3A46%3A29Z
2. Take snapshot, see prompt to reset Rotation, accept, see initial reset then revert to original rotation
3. Click Download button to request snapshot. This has the potential to provide an invalid BBOX

**Expected behavior**
Graticule is removed and rotation reset remains until image snapshot is taken.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by edplato** [comment]
May be related to #3343

**Comment by rboller** [comment]
Also may be related to #3665
