### ISSUE TITLE
Possibility to hang the app when adjusting the animation timing

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#3681]
**Describe the bug**
When adjusting the animation start time AND a fine-grained increment is set (e.g. 10 minutes), it's possible to hang the app by setting the time range to be very large.  This can be relatively easily to accidentally do if you're adjusting the start date year and "roll over" to 1948.

**To Reproduce**
1. Load a geostationary layer
2. Open the animation panel
3. Set the increment to 10 minutes
4. Click the "up arrow" on the start date year to roll over to 1948 (or change the start date to be sufficiently large)

[This link](https://worldview.earthdata.nasa.gov/?v=-100.18305158719576,24.808236878773265,-66.97797346219579,44.201516125568126&z=4&ics=true&ici=5&icd=10&as=1948-08-10-T11%3A00%3A00Z&ae=2021-08-10-T15%3A00%3A00Z&l=Reference_Labels_15m,Reference_Features_15m,Coastlines_15m,GOES-East_ABI_GeoColor,GOES-East_ABI_Band13_Clean_Infrared(hidden),GOES-East_ABI_Band2_Red_Visible_1km(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&lg=false&al=true&av=10&ab=on&t=2021-08-10-T11%3A20%3A00Z) will take you straight to the problem.  The app will eventually catch its breath but is quite unhappy about the situation.

**Expected behavior**
Given that it would be impractical (to say the least) of creating an animation with millions of time steps, we should probably prevent the user from trying to do this (and from crashing the app in process).

**Comment by edplato** [comment]
I'll try out different maxframes for animations similar to GIF. The core issue is the `util.snapToIntervalDelta` function gets bogged down traversing through large ranges of 10 minute intervals.

**Comment by jasontk19** [comment]
I was already planning to limit the animation steps in the work on #3473 so we could just roll this ticket into that one essentially? Or if you want to address it in some other way here I'd say go for it.

**Comment by minniewong** [comment]
Moved to WV-1948
