### ISSUE TITLE
Vector tile preloading issues

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#3688]
**Describe the bug**
There is an issue with pre-loading vector tiles where sometimes an individual tile does not finish loading successfully, or overtly fail, which can cause promises further up the chain to hang completely.

Additionally, there is an issue with preloading vector tiles in polar projections where invalid extents are being calculated that cause errors to be thrown.

**To Reproduce**
1. Go to `http://localhost:3000/?v=-5386240,-6936274.417709336,5386240,6936274.417709336&p=arctic&as=2021-08-01-T00%3A00%3A00Z&ae=2021-08-11-T00%3A00%3A00Z&l=VIIRS_NOAA20_Thermal_Anomalies_375m_All,Coastlines_15m,MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&ab=on&t=2021-08-01-T04%3A00%3A00Z`
2. Hit "play"
3. Observe error

**Comment by Benjaki2** [comment]
@jasontk19 Not able to replicate this. The link that loads is in the outermost zoom and appears to request the WMS tiles.

**Comment by jasontk19** [comment]
@Benjaki2 Sorry, the PR that got merged implemented a workaround for this, I need to update the description for a more accurate representation of the remaining bug.

**Comment by jasontk19** [comment]
If this resurfaces during animation enhancements work, we will know about it and can write a clearer ticket in JIRA for it.  Closing for now.
