### ISSUE TITLE
Timeline "data availability bars" are mis-ordered

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#374]
Now that the positions of "base layers" and "overlays" are swapped the layer manager, the timeline "data bars" should also be swapped.  

As it currently stands, when you hover over the layers in the layer manager, the overlays are below the base layers in the timeline even though it's the opposite in the layer manager.
WV-1668

**Comment by minniewong** [comment]
think about it when we overhaul the timeline

**Comment by rboller** [comment]
Closing this ticket as we'll be handing this as part of the broader timeline overhaul:
https://github.com/nasa-gibs/worldview/projects/21
