### ISSUE TITLE
Dual legend layers need custom colormaps options

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#375]
WV-1705
Some layers now have two legends, e,g, MODIS Cloud Optical Thickness, Cloud Effective Radius, Cloud Water Path. It would be beneficial to provide custom colormap options for these layers.

![screen shot 2017-11-16 at 11 24 22 am](https://user-images.githubusercontent.com/10747923/32902577-beb16e2a-cac0-11e7-836d-20e487b898a8.png)

**Comment by Benjaki2** [comment]
<img width="1218" alt="screen shot 2018-11-19 at 10 54 01 am" src="https://user-images.githubusercontent.com/3605988/48718484-7ead6400-ebe9-11e8-869a-46048dfbaf01.png">
I could just append the thresholds/squash/customs like ☝️which would be easy to implement. But tabs might work better. 

@minniewong @rboller Should the opacity continue to adjust both layer's imagery? (I think this would be a lot more work to change)

**Comment by rboller** [comment]
User feedback who is looking forward to adjusting these dual palette products:

> I am sharing it now because I found a cool image but I realize that I cannot share the level 2 layer (Cloudy effective radius) because I cannot adjust the color. If you flip between the RGB and the CER layer you can clearly see bright streaks in the RGB . These streaks are in the CER layer but they have a range of 4 to 15 and the color scale is fixed and it cannnot be adjusted to make those differences apparent. 

> https://go.nasa.gov/2TxRfhG
