### ISSUE TITLE
npm no longer in Debain 9 'Stretch'

### ISSUE THREAD

**Issue by jdm7dv** [nasa-gibs/worldview#383]
For future use npm is no longer in Debian 9 'Stretch' 

https://packages.debian.org/search?keywords=npm

Here's how to install node module's manually:

https://stackoverflow.com/questions/5786433/how-to-install-a-node-js-module-without-using-npm

How do you use: "node-npm-run-path"?

**Comment by tgunnoe** [comment]
Yeah, I didn't try to install it from the repo anyways.  I updated the install instructions to point to node's installation page and recommended >v6, although i think >v4 would work as well...

Here's the specific instructions I followed as I wanted to keep it managed.  https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by jdm7dv** [comment]
@tgunnoe Thank You I will try that.
