### ISSUE TITLE
Bring in start/end dates from GC docs into layer descriptions

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#384]
Ben took an initial look at this: WV-1797

Here is a list of changes discussed on 11/14/17
- [x] Change process_temporal_value to build an array of all dates and add to wv.json.
i.e. this:
  <Value>2011-09-30/2011-11-25/P1D</Value>
  <Value>2011-11-27/2011-11-27/P1D</Value>
  <Value>2011-11-29/2012-01-22/P1D</Value>
Becomes:
  September 30th, 2011 - November 25th, 2011
  November 27th, 2011 - November 27th, 2011
  Novemeber 29th, 2011 - January 22nd, 2012
- [x] Display date range at top
- [x] Format date to be '24 November 2015' style
- [x] Add indicator to top date range to tell user there are gaps in that range.
- [x] Display exact dates at bottom in a list.
- [x] Remove titles from markdown files
- [x] Add date range to the layer list hover state when no data is available:
i.e. this -> "No data on selected date for this layer"
to this -> "Data available between 27 May 2001 - 3 March 2008"

-----------------------------------------------------------------------
Phase 2:
Link the bottom dates to the timeline

**Comment by minniewong** [comment]
Part of #361

**Comment by ZachTRice** [comment]
I can take a look at this @minniewong. Just need some more details on how you want the start / end dates to appear in the layer descriptions.

**Comment by minniewong** [comment]
I think @Benjaki2 has done part of this?

**Comment by Benjaki2** [comment]
@minniewong I have only investigated as to how it should be done, I was waiting for the overhaul. @ZachTRice  Right now we are going straight from markdown to html. You could just append in the temporal value after that header but that seems sloppy. Ideally I would want to go from `.md` to `.json`. Thoughts @ZachTRice ?

**Comment by Benjaki2** [comment]
Follow up to discussion w @minniewong & @ZachTRice :
* `.json` won't work
* Plan is to append in the temporal values into the `<html>`


@ZachTRice The end dates are removed here: The https://github.com/nasa-gibs/worldview/blob/574bb688118c6af3aaa0ef9b7e179439391df044/bin/wv-options-validate#L137-L141 , If the inactive flag is set to `false` from our options

**Comment by localjo** [comment]
Could add some YAML front matter to markdown files. Something like https://www.npmjs.com/package/yaml-front-matter

**Comment by Benjaki2** [comment]
That's a good idea

**Comment by minniewong** [comment]
@ZachTRice I've removed the title and temporal coverage from all the single layer descriptions (i didn't remove it from the measurements descriptions because i wasn't sure how those were being handled). You can test your solution on the branch: https://github.com/nasa-gibs/worldview-options-eosdis/tree/remove-title%26date

**Comment by ZachTRice** [comment]
Thanks! I should be able to get this implemented relatively quickly once we wrap up with module-loaders.

**Comment by minniewong** [comment]
@ZachTRice to push his local branch up

**Comment by minniewong** [comment]
@Benjaki2 - The `remove-title-date2` branch in this PR should be usable with Zach's branch (https://github.com/nasa-gibs/worldview-options-eosdis/pull/187)
