### ISSUE TITLE
You have a bug in the map view

### ISSUE THREAD

**Issue by galitniztad** [nasa-gibs/worldview#3860]
You have a bug in the map view, see attachment, it does not show the surface temperature correctly, also stopped giving measurement comparisons from 2020 backwards.
![nasa2](https://user-images.githubusercontent.com/103301976/162558135-551c0017-def9-451d-9876-9b035f9e44a4.png)
![nasa](https://user-images.githubusercontent.com/103301976/162558138-d053c850-0ef9-4984-aa07-c0fce6cb7d11.png)

**Comment by galitniztad** [comment]
Hi,

When will the Aqua Land Surface Temperature imagery problem be solved?
And regarding the second problem is the link(It's the same map from
1948-2020):  https://worldview.earthdata.nasa.gov/?v=-382.7489568760394,-175.4924630163563,385.6260431239606,194.0700369836437&l=MISR_Directional_Hemispherical_Reflectance_Average_Natural_Color_Monthly,AIRS_Precipitation_Day(hidden),MODIS_Aqua_Land_Surface_Temp_Night,MODIS_Aqua_Land_Surface_Temp_Day,Landsat_Human_Built-up_And_Settlement_Extent(hidden),GRanD_Dams(hidden),NDH_Drought_Hazard_Frequency_Distribution_1980-2000(hidden),Reference_Labels_15m,Reference_Features_15m,Coastlines_15m,MODIS_Terra_SurfaceReflectance_Bands143(hidden),MODIS_Combined_L3_Nadir-BRDF_Daily,MODIS_Combined_MAIAC_L2G_BidirectionalReflectance_Bands143,VIIRS_NOAA20_CorrectedReflectance_TrueColor,VIIRS_SNPP_CorrectedReflectance_TrueColor,MODIS_Aqua_CorrectedReflectance_TrueColor,MODIS_Terra_CorrectedReflectance_TrueColor&lg=false&t=2022-04-11-T02%3A00%3A00Z


Best Regards,

Galit

**Comment by galitniztad** [comment]
Hi,

When will the Aqua Land Surface Temperature imagery problem be solved?
And regarding the second problem is the link(It's the same map from
1948-2020):

https://worldview.earthdata.nasa.gov/?v=-463.7489568760394,-200.2424630163563,304.6260431239606,169.3200369836437&l=MISR_Directional_Hemispherical_Reflectance_Average_Natural_Color_Monthly,AIRS_Precipitation_Day(hidden),MODIS_Aqua_Land_Surface_Temp_Night,MODIS_Aqua_Land_Surface_Temp_Day,Landsat_Human_Built-up_And_Settlement_Extent(hidden),GRanD_Dams(hidden),NDH_Drought_Hazard_Frequency_Distribution_1980-2000(hidden),Reference_Labels_15m,Reference_Features_15m,Coastlines_15m,MODIS_Terra_SurfaceReflectance_Bands143(hidden),MODIS_Combined_L3_Nadir-BRDF_Daily,MODIS_Combined_MAIAC_L2G_BidirectionalReflectance_Bands143,VIIRS_NOAA20_CorrectedReflectance_TrueColor,VIIRS_SNPP_CorrectedReflectance_TrueColor,MODIS_Aqua_CorrectedReflectance_TrueColor,MODIS_Terra_CorrectedReflectance_TrueColor&lg=false&t=2020-04-11-T02%3A00%3A00Z




[image: image.png]

**Comment by minniewong** [comment]
Follow this note for up-to-date information about Aqua: https://landweb.modaps.eosdis.nasa.gov/cgi-bin/QA_WWW/displayCase.cgi?esdt=MYD&caseNum=AS_MYD_22091&caseLocation=cases_data&type=C6

Also, thanks for the link to the map you were referring to (https://go.nasa.gov/3OdxMiK) - I believe you are asking whether the layer "Directional Hemispheric Reflectance (DHR) Average (Monthly, Natural Color)" is still being updated after 2020 August. It currently is on hold, but we hope to receive the imagery again sometime in the near future. Apologies for the inconvenience.
