### ISSUE TITLE
Keep today's and yesterday's map imagery up to date

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#389]
We should periodically check for new imagery if the user is looking at "today" or "yesterday" to ensure that they're up to date with what's available from GIBS.

Will need to determine what that polling rate should be based on how frequently GIBS updates its imagery.

**Comment by rboller** [comment]
On a similar note, we should also allow the user to advance the date if they kept the browser open long enough where it's the next day.  As it currently stands, the app's last date available is fixed at load time.

**Comment by minniewong** [comment]
connects to #409

**Comment by localjo** [comment]
Are there particular times that new imagery becomes available? Is new data published on a once-daily basis? Is it at a certain time for each satellite? Or does it just get published at an arbitrary time whenever it gets added to the system?

**Comment by rboller** [comment]
@localjo each layer gets updated based on whenever it gets added to GIBS.  Some layers are updated as often as every 5 minutes... others less frequently.  Some layers have a fixed end date in the past (e.g., missions which are no longer active) and aren't updated.

So to make things efficient, we'll want to check if the currently-loaded layers are still actively updated by looking at their metadata and then pick some frequency to poll GIBS for new imagery.  We'll have to discuss what that frequency should be but my first take is somewhere between 5-30 minutes.

**Comment by localjo** [comment]
Is there any metadata on the API response that indicates how often the layer might be updated? Actually, it might be helpful if I could inspect the API response to see what I have to work with. Can you help with that?

**Comment by rboller** [comment]
Sure, the GIBS API is [here](https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers) and Worldview uses its [WMTS](https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-OGCWebMapTileService(WMTS)).  It pulls GetCapabilities documents for each of the map projections at build time to discover which products are available and what their date ranges are.  After that, Worldview doesn't ask GIBS anymore what the available date ranges are.  I believe it makes some assumptions about what constitutes an ongoing product and one which is no longer updated.

Otherwise there isn't a specific API which you can query to know if new imagery is available.  A brute force approach would be to query GIBS for the currently-visible tiles and compare to what's already been loaded on the map.

**Comment by minniewong** [comment]
With geostationary imagery coming soon - this will be important.

**Comment by minniewong** [comment]
Look at the "appnow" value to see if that helps

**Comment by jasontk19** [comment]
Plan for this, for now, will be to just make sure you can access the most recent time according to the value in appnow

**Comment by jasontk19** [comment]
Opened #2106 to handle the part of this we are planning on tackling for v3.2.0

**Comment by minniewong** [comment]
Will wait for ONEARTH 2.x

**Comment by jasontk19** [comment]
Going to break this into two new tickets

**Comment by jasontk19** [comment]
Remaining efforts captured in #3645 and #3646
