### ISSUE TITLE
Investigate the possibility of adding normalize.css or another reset file for styles

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#391]
There is no reset file within our CSS. A reset file create cross-browser consistency. One of the more popular resets is [normalize.css](http://necolas.github.io/normalize.css/).

The keyword in this issue is **investigate** the possibility of adding a reset because after a project is started, a reset will usually break a lot of elements. Generally you want to build off of it from the beginning.

Read about it here: http://nicolasgallagher.com/about-normalize-css/

**TL;DR;**
"Normalize.css is a small CSS file that provides better cross-browser consistency in the default styling of HTML elements. It’s a modern, HTML5-ready, alternative to the traditional CSS reset."
The aims of normalize.css are as follows:

- **Preserve useful browser defaults** rather than erasing them.
- **Normalize styles** for a wide range of HTML elements.
- **Correct bugs** and common browser inconsistencies.
- **Improve usability** with subtle improvements.
- **Explain the code** using comments and detailed documentation.
It supports a wide range of browsers (including mobile browsers) and includes CSS that normalizes HTML5 elements, typography, lists, embedded content, forms, and tables.

**Comment by Benjaki2** [comment]
Good call @ZachTRice

**Comment by ZachTRice** [comment]
We are introducing bootstrap 4 in PR #920. BS4 includes normalize.css and a reboot.css built in.
