### ISSUE TITLE
Overzoom indicator is inconsistent across browsers in Antarctic view

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#397]
When looking at [this link](https://worldview.earthdata.nasa.gov/?p=antarctic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden),Land_Water_Map,Coastlines,MODIS_Aqua_Brightness_Temp_Band31_Night(hidden),MODIS_Terra_Brightness_Temp_Band31_Night(hidden),VIIRS_SNPP_DayNightBand_ENCC&t=2017-07-12&z=3&v=-2446014.4753510645,978993.7980686972,-1873958.1576228328,1324799.6987104095&ab=on&as=2017-07-11&ae=2017-07-12&av=3&al=true), the tooltip for the overzoom indicator (i.e., the yellow zot) shows a different overzoom percentage across different browsers.

Might be present in Arctic and geographic projections, too, only tested in Antarctic.

**Comment by Benjaki2** [comment]
It is occuring across all projections...

The reason being: we currently use a bounding box to fit into a browser. If a browser is a different size or proportion it would make sense that It adapts the zoom level to fit that extent in the browser. Should we alter this to be based on a resolution and a center point?

**Comment by rboller** [comment]
@Benjaki2 yes I think that resolution and center point seem like good criteria for this problem.  Is there a resolution value built into OL or will we have to maintain something ourselves?

**Comment by minniewong** [comment]
Confirm that the value is correct and change to multiplier value.
