### ISSUE TITLE
document grunt tasks

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#402]
fetch -> no current documentation
config -> documentation needs more detail

**Comment by localjo** [comment]
There's a CoffeeScript task that can probably be removed, and we can just use the JS source instead of the CoffeeScript source.

**Comment by Benjaki2** [comment]
👍  I've been wanting to out that coffeescript for a while now

**Comment by ZachTRice** [comment]
Possible duplicate of #312

**Comment by ZachTRice** [comment]
These notes have been updated in 2.0
