### ISSUE TITLE
CSS overhaul

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#403]
Notes from talking with @ZachTRice 

* Add CSS Autoprefixer as a dev tool
* Unify Font families & sizes that are cross-system compatible (w/fallbacks)
* Maintain a consistent color scheme
* Create a reset file to normalize elements across multiple browsers
* Implement a elements that adhere to a vertical rythmn. 
* Add SASS as a CSS preprocessor

Missing anything @ZachTRice ?

**Comment by ZachTRice** [comment]
Yea I added creating a reset file and updated your list. I'll keep updating that list as I think of other areas we need to overhaul

**Comment by ZachTRice** [comment]
Since we are tracking these tasks within a [larger project](https://github.com/nasa-gibs/worldview/projects/4), I am going to close this ticket.
