### ISSUE TITLE
Show All Active Event Markers on Map

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#407]
Display all event markers for what's active, need to include labels and event icons

**Comment by localjo** [comment]
I'm thinking about making this a simple text filter;

![screen shot 2017-08-03 at 4 11 52 pm](https://user-images.githubusercontent.com/516388/28941930-8c3ae954-7867-11e7-896b-99c34c090418.png)
![screen shot 2017-08-03 at 4 14 31 pm](https://user-images.githubusercontent.com/516388/28941931-8c3c6086-7867-11e7-9fec-db9a4d43aeab.png)

That way you could filter by event types, just by starting to type something like "Tropical Storm", "Iceberg", "Fire", etc. And you could also filter for specific names of events like "A68B" or "Sandy" or "California", etc.

I could also add a subtle "x" button in the filter input to clear it quickly.

Thoughts?

**Comment by rboller** [comment]
So I believe that one of the original goals of this ticket was to show placemarks on the map for all active events, possibly limited to only the events which are active for the selected day.  Or at least that's what I'm remembering after reading @minniewong 's original comment: 
> Display all event markers for what's active, need to include labels and event icons

In some ways, it would behave like the map on Earth Observatory's [Natural Hazards page](https://earthobservatory.nasa.gov/NaturalHazards/index.php?m=07&y=2017).

That's a bit different than the title of this ticket, though:
> Add a filter to events to toggle by event type or date

@minniewong @Benjaki2 @ZachTRice do you remember if there was something else we were thinking when we wrote the ticket in terms of filtering, e.g., "only show fires"?

**Comment by localjo** [comment]
Ah, interesting. I'm thinking that since events are probably on multiple dates, we might want to consider a timeline "range" feature. That could also be useful for showing event tracks. That could be worth starting a separate discussion about since it's a much larger scope than this issue.

Regarding the filter, filtering the list with text, as I suggested above should be relatively easy to implement. If we add markers, I'm not sure how easy it would be to apply the filter to markers. Doing that in a performant way might be challenging. If we were in a pure React/Redux app, it would be trivial and fast, but I think we're pretty far from that point.

**Comment by localjo** [comment]
Either way, for this issue, should I move forward with implementing a filter for the list, and we can tackle adding markers as a separate issue?

**Comment by rboller** [comment]
Lots of good points in there which tie into larger issues.

Timeline range: in the relatively near future, we'll need something to show a date range of fires or orbit tracks over the course of several days in a single frame (i.e., not an animation).  That's a larger issue, though, and may or may not tie into showing event tracks.

Ability to filter events: we have a larger plan to allow users to browse historical events.  As of now, we're only showing ones marked as active in the [EONET API](https://eonet.sci.gsfc.nasa.gov/). So we'll want to consider filtering in the context of a larger (future) capability to browse historical events. 

Markers: probably makes sense to break this ticket into two pieces: filtering and showing markers.  Let's see what @minniewong has to say next week about what the original intentions of this ticket were.  :)

**Comment by minniewong** [comment]
The original idea for the ticket was what Kevin W suggested here: "Have you thought about having a toggle that turns on all the markers for all the events so that you can see the location of every event on the given day you are looking at? I have had some moments when I was looking at Worldview and I wanted to know what other defined events were in the area I was looking at (e.g., are these other fires also defined events?) Just a thought"
I think we then evolved it into being able to toggle on/off specific event types/categories (e.g. show all fires in event list)

**Comment by Benjaki2** [comment]
I think it would make sense to have:
* hover events on these markers that displays the title or description
* Click events on the markers that zoom into the event

**Comment by localjo** [comment]
Connects to #471
Connects to #472
