### ISSUE TITLE
Remove wv.mobile.css separate stylesheet; convert rules to mobile first

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#426]
We do not not need a separate mobile stylesheet. We should set mobile rules in their respective stylesheet and use @min-width rules not @max-width to prioritize mobile-first and better organize rules. 

It is harder to read when a rule is in a separate location and it is better for mobile devices when the mobile rule is specified first followed by an @min-width rule for desktop.

**Comment by jasontk19** [comment]
This is now captured in #2042
