### ISSUE TITLE
Can't close 'select data' data download dialog box

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#434]
Go to here: https://go.nasa.gov/2tKIA1Z
There is no button visible to close the dialog box.

See also a closely related issue: #63

**Comment by minniewong** [comment]
i actually think it was designed this way.

**Comment by ZachTRice** [comment]
I don't see any reason for keeping it this way. I want to close it. I made a mistake by opening it and now I can't see the map.

**Comment by Benjaki2** [comment]
It does appear to be the intended functionality in that it is consistent with the other forms of data selection (You can't x out of granule data selections).

I agree that a close button would be better. We would just need to deselect the data-selection in the sidebar on close.

**Comment by minniewong** [comment]
Moved issue to user feedback in internal wiki
