### ISSUE TITLE
Convert CSS ID / Element selectors into class selectors

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#438]
Remove the over-specification of css rules. We want to focus on only selecting classes for styling. This will also mean adding classes in the js files where there are currently on ID's.

**Comment by ZachTRice** [comment]
Change stylelint rule: `"selector-max-id": 2` to `"selector-max-id": 0`

**Comment by ZachTRice** [comment]
layers.css: All ID selectors have been converted to class selectors starting in PR #920

**Comment by minniewong** [comment]
@ZachTRice - move to wiki

**Comment by jasontk19** [comment]
This is now captured in #2042
