### ISSUE TITLE
Fix selectors of lower specificity from coming after overriding selectors of higher specificity in CSS

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#440]
There are a lot of rules which are not being specified correctly. Let's use this stylelint rule to find issues, correct them, and then implement the rule so this doesn't occur in the future.
https://stylelint.io/user-guide/rules/no-descending-specificity/

**Comment by minniewong** [comment]
@ZachTRice - move to wiki

**Comment by jasontk19** [comment]
This is now captured in #2042
