### ISSUE TITLE
Prevent use of em units in css. Use px instead.

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#441]
Convert `em`s to `px`

Constrain with stylelint rule: unit-blacklist

Any `em` we are currently using is being based off of a 13px base instead of 16px. 
I would like to remove `em`'s entirely to protect inner element font sizes from being changed by outer elements since `em`'s are relative to each other based on their nested position.  

If we wanted to use `em`'s or `rem`'s in the future it would be better to go with `rem'`s since these are always based off the root element and are predictable. But `px`s never change and don't require math to figure out their size (i.e. 2.5rem = 40px because 16px*2.5=40), and thus are easier to work. Plus, pixels are already used for width/height, margin, padding etc. and so it makes sense to keep units consistent.

**Comment by minniewong** [comment]
@ZachTRice - move to wiki

**Comment by jasontk19** [comment]
This is now captured in #2042
