### ISSUE TITLE
Look into removing overqualified type selectors (type.id / type.class chaining)

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#446]
Ideally, the css should be structured with only type and classes but not with these two selectors chained together because then there is too much specificity to override. This will take quite a bit of reworking and testing to ensure the changed css is cascading correctly.

HTML Example
```
<div class="module">
    <h3 class="title module-title">Title</h3>
    <div class="module-1a">
        <h4 class="title module-1a-title">Sub title</h4>
    </div>
</div>
```
CSS Example: Good
```
h3 {
   font-size: 24px;
}

h4 {
    font-size: 20px;
}

.module .title {
   color: #333;
}
```

CSS Example: Bad
```
.module h3.title,
.module h4.title {
   color: #333;
}
```

Why? Because of reusable components. There may be a point where we want to reuse the `.title` rules on another component which isn't the h3 type. Now, we would have to create another rule for that specific instance. See also [this stackexchange topic](https://stackoverflow.com/questions/14769668/is-it-better-to-chain-css-classes-or-name-them-separately-for-modular-purposes) regarding class chaining. Same idea. Chaining is not preferred because it breaks modularity. 

Add the following stylelint rule
```
"selector-no-qualifying-type": [true, {
    ignore: "attribute"
}],
```

**Comment by minniewong** [comment]
@ZachTRice - move to wiki

**Comment by jasontk19** [comment]
This is now captured in #2042
