### ISSUE TITLE
Auto-highlight product picker's search terms in search results

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#452]
Since we're on the verge of having super-fast search results for the product picker, we can make experience more grok-able by automatically highlighting the user's search terms in the search results.  E.g., if a user searches for "aeros", all of the places where "aeros" is found in the results would be highlighted in some manner.

**Comment by ZachTRice** [comment]
It might be good to implement #428 at the same time as this one since they both relate to highlighting parts of the search bar.
