### ISSUE TITLE
Manual??

### ISSUE THREAD

**Issue by casedup** [nasa-gibs/worldview#4568]
Is there anything I can read to get the most out of the tool? Not that intuitive...

**Comment by minniewong** [comment]
Would you like to install and build your own configuration of Worldview or would you simply like to use Worldview for looking at satellite imagery? 
For installing and building, follow the instructions here: https://github.com/nasa-gibs/worldview#readme
For just viewing satellite imagery and using NASA Worldview, go here: https://worldview.earthdata.nasa.gov, tutorials and related information can be found here: https://www.earthdata.nasa.gov/worldview
