### ISSUE TITLE
Timeline should indicate yearly/season/monthly/weekly/composites layers more clearly

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#461]
Tasks:
~- [ ] Create method to categorize time steps as "Daily", "Weekly", "Monthly", "Yearly", etc. time steps~
~- [ ] Add labels to timeline bars (on hover?)~

**Comment by ZachTRice** [comment]
More information is needed on this ticket.

**Comment by minniewong** [comment]
The timeline availability bars or something else on the timeline should help indicate when a layer is a monthly/yearly/seasonal/composite layer and when a user should expect the layer to change according those temporal resolutions e.g. a seasonal layer will show that the layer doesn't change/it has the same imagery for 3 months and the layer will change/the imagery will change for the next seasonal time interval
