### ISSUE TITLE
Improve Chrome Audit Scores

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#462]
Using Chrome Developer Tools' Audit Tab, we can evaluate some things that need improvement in the app. We should probably open separate issues and/or PRs for each thing that the audit flags, but maybe we could group some together too. Just opening this issue so we can remember to come back to this at some point. Here is our current score;

![screen shot 2017-08-08 at 5 25 17 pm](https://user-images.githubusercontent.com/516388/29095466-ded28280-7c5e-11e7-83d0-6b4ca00cfb1c.png)

**Comment by ZachTRice** [comment]
Some of these are really interesting. Under Progressive Web App "Address bar matches brand colors
" `<meta name="theme-color">`, never would thought this to be something flagged, even in PWA.

Glad to see accessibility is so high and seems like the things missing are relatively easy fixes.

Some of these are out of our control, i.e. related to openlayers "Uses passive listeners to improve scrolling performance" most of the flags are openlayers related.

Agree, these can be broken out into seperate tickets to tackle.

**Comment by edplato** [comment]
To add onto this issue as a general optimization thread, [Google PageSpeed Insights for Worldview](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fworldview.earthdata.nasa.gov%2F&tab=desktop) also has some potentially useful optimizations broken down for desktop and mobile.

**Comment by edplato** [comment]
I don't know if all their recommendations are going to be investigated, but I did create an issue for optimizing static images to get started **Optimize images** #925

**Comment by minniewong** [comment]
Compile a list each service provides and break out into tickets

**Comment by minniewong** [comment]
Closing ticket - more detailed ticket at #1126
