### ISSUE TITLE
Event Track Markers

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#468]
When an event is selected, if it has multiple dates, all of the markers for that event should be shown, with a possible line showing the track of the event.

**Comment by localjo** [comment]
@ZachTRice It's premature to put too much though into this, but something to keep in the back of your mind while working on #610 and changes to the timeline is thinking about how we might want to represent an event's dates on the timeline for events with multiple active dates (like events with a track) and historical events (#467).

**Comment by minniewong** [comment]
Folding this into #283
