### ISSUE TITLE
Add "export to kml" button

### ISSUE THREAD

**Issue by andychase** [nasa-gibs/worldview#47]
One possible enhancement is to add an export to KML option to worldview.

This would assist users who'd like to use the graphical layer add ui to select a bunch of layers and take those layers over to Google Earth and work with the layers in that application.

"The use of Google Earth (GE) to demonstrate geologic principles is becoming more popular in introductory geology courses." [1]

GIBS has a kml export endpoint at:

```
http://map1.vis.earthdata.nasa.gov/twms-geo/kmlgen.cgi?layers=<layername>&time=<time>
```

If this seems like an acceptable idea I might be able to help implement a PR for this.

[1] Greene, T.J ., and Shapiro, R.S . 2008. Student-based learning using Google Earth in sedimentology and stratigraphy courses. In Geological Society of America Rocky Mountain and Cordilleran Sectional Meeting, Las Vegas, (abstracts with programs), vol. 40, p. 90 .

**Comment by IamTechknow** [comment]
Thanks for bringing this up! I worked extensively on Worldview while interning at NASA (see my animation gift pull request) with the image download endpoint but I did not know about the KML endpoint. I am not interning there anymore but I would be interested in working with you on a pull request.

**Comment by jalbertbowden** [comment]
be pretty sweet if this exported to .geojson...i realize that makes this more work, but tying this entirely to google's format and software imho is not the best way to go.

**Comment by rboller** [comment]
Agreed with @IamTechknow - thanks for bringing this up!   And actually Worldview has an option to export to KMZ.  If you go to the image snapshot tool in the upper right, you can change the format to KMZ.  I'll attach a sample output for two time steps.

If you load them in Google Earth, you'll see that the individual layers are separate for each day - reflectance, borders, and sulfur dioxide.  Each KMZ also has a time stamp associated with it so you can change the date in Google Earth and see how things change over time.  In this case, you can see the gas and dust plume from the Calbuco volcano.

One shortcoming of this feature, though, is that all layers are exported as PNGs into the KMZ, even the ones that are natively JPEGs.  So that means that the file size can become unnecessarily huge and also slows down Google Earth.

@jalbertbowden - as for GeoJSON, what kind of information would you want to see exported?

[Worldview-KMZ-example.zip](https://github.com/nasa-gibs/worldview/files/79262/Worldview-KMZ-example.zip)

**Comment by andychase** [comment]
Thanks for the thoughts @rboller. 

The `.kmz` files look cool, and do solve many use cases. However one particular advantage that you hinted at is that the layers linked to using the kml files are interactive. 

If an instructor wants to use Google Earth as a visualization aid showing ecological systems around the world in detail, it's much nicer to use the tiled server rather then pre-download the tiles in `.kmz`. If you wanted the sea surface temperature for the whole world for a day at 250m, for example, that'd use a lot of disk space! Not to mention they might want to add parameters during class without waiting to download all the tiles.

**Comment by rboller** [comment]
Ah, I see!  Agreed that being able to basically transfer Worldview's state to Google Earth via kml would be a useful feature for the reasons you mention.  We'd be happy to add it to Worldview if you're interested in implementing a PR.

**Comment by lewismc** [comment]
@andychase this would be a really cool feature. I'll check out some code as well and see if we can get a PR produced by the end of your Capstone project. FYI folks, @andychase is part of a team from Oregon State University who we are working with on a Senior Capstone project. Some of you will also know Charles Thompson from JPL who is also part of the effort. The project, [ARIA-P](https://aria-p.github.io/) uses GIBS for teaching Labs covering content such as geospatial technology for climate change education and possibly some other areas.
I really think that the export-to-kml feature for Worldview would be a really cool outcome and contribution from the Capstone effort.

**Comment by rboller** [comment]
@lewismc thanks for the background and sounds great.  We on Worldview and GIBS are happy to help however we can.

**Comment by lewismc** [comment]
Having a poke around this for fun today. People will find the [Google Earth KML Access|https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-GoogleEarthKMLAccess] documentation helpful if attempting to use the endpoint provided by @andychase .

**Comment by andychase** [comment]
This ended up not being something we needed for our project, but I really appreciate the feedback you all provided. I will definitely revisit if our needs change.

Hopefully if anyone else comes along with a need like this this conversations will be helpful.

**Comment by lewismc** [comment]
Andy I would keep this open. I might contribute a patch of o get around to
it. I have the cosmically so j might try to cook something up. Can you
please reopen

On Wednesday, April 6, 2016, Andy Chase <notifications@github.com> wrote:

> Closed #47 <https://github.com/nasa-gibs/worldview/issues/47>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nasa-gibs/worldview/issues/47#event-617139572>
>


-- 
*Lewis*

**Comment by andychase** [comment]
Of course- I didn't know you were thinking of working on it. I re-opened the ticket.

**Comment by lewismc** [comment]
Thanks

On Wed, Apr 6, 2016 at 10:12 AM, Andy Chase <notifications@github.com>
wrote:

> Of course- I didn't know you were thinking of working on it. I re-opened
> the ticket.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nasa-gibs/worldview/issues/47#issuecomment-206469258>
>



-- 
*Lewis*

**Comment by mcechini** [comment]
So, if we had network links instead of static images in the image-download response (which is what the GIBS KML access returns), does that solve this?

**Comment by andychase** [comment]
@mcechini I believe so. The KML just needs to point at the tile server using the layers the user has currently selected in WorldView.

**Comment by jalbertbowden** [comment]
What are the pros/cons to using/not using Network Links? I consistently find KML/KMZ data from gov sector that will not convert to other formats because they're using Network Links.
I assume they're pointing locally, which is why they are breaking...are there ways around this?
Do you think Earth developers are not aware the data may not be used in Google Earth?
Am I completely out of left field here and entirely wrong on all accounts?

**Comment by andychase** [comment]
The use case I looked into was teachers using Google earth while they teach class.

The network links seemed like a better fit for this because the teachers wouldn't have to download the full tile sets (very large for some layers) and allowed them to select a lot of different layers and interact with them (looking at different areas, etc) and combining them with other Google Earth layers.

The files can also be distributed to students without any hassle (this is something Pearson does in their geography ecourse materials).

The network links point to GIBS, not local links.

**Comment by mcechini** [comment]
Sounds like we may want to update the GIBS image-download to support both offline (currently supported) and online (new for ID) access.  The latter being somewhat supported in our existing (though not well advertised) KML generation in GIBS.

**Comment by rboller** [comment]
@mcechini updating the GIBS image-download API to include the ability to download network linked KMLs could be one option and make it easier for clients like Worldview to incorporate from an implementation perspective.

That said, I'd think that requests for network KMLs would be different in that they don't seem to be spatially bounded - or at least we wouldn't want them to be for this use case with GIBS.  

So for this proposed Worldview feature, I'd say that we'd want Worldview itself to make a direct request to the [GIBS KML generation script](https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-GoogleEarthKMLAccess) passing the appropriate layers and time step.

**Comment by mcechini** [comment]
well, before you start using the GIBS KML service, we need to discuss what its future is, and whether that capability just gets rolled into Image Download as an option.

**Comment by rboller** [comment]
We decided to close this ticket during a recent backlog grooming session, though the concept of making imagery available to (the new-ish, web-based) Google Earth is still something that we'll consider as we overhaul our image download service.  Thanks to everyone for the discussion!
