### ISSUE TITLE
LocalStorage sometimes causes crash at startup (especially in Safari)

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#474]
It appears that certain browser plugins may cause a crash at startup.  In particular, a user reported a problem which had the following console error which we should handle more gracefully:

`TypeError: null is not an object (evaluating 'localStorage.getItem')`

**Comment by localjo** [comment]
It's not completely clear what causes this, but I found that browser settings that don't allow websites to use `localStorage` could be part of the cause. For example, setting this in Safari;

<img width="408" alt="screen shot 2017-08-18 at 1 38 26 pm" src="https://user-images.githubusercontent.com/516388/29470490-a9a5d2ba-841a-11e7-8d82-6449bee738f1.png">

Causes similar behavior with this error;
<img width="627" alt="screen shot 2017-08-18 at 1 37 42 pm" src="https://user-images.githubusercontent.com/516388/29470551-df37a502-841a-11e7-8200-8f236c1a78a0.png">

I suspect we could solve this issue by improving [our checks for the availability of `localStorage`](https://github.com/nasa-gibs/worldview/blob/master/web/js/util/wv.util.browser.js#L201-L211) and [our utility classes for accessing `localStorage`](https://github.com/nasa-gibs/worldview/blob/master/web/js/util/wv.util.js#L642-L651), and making sure we're using our utility classes and have proper fallbacks [everywhere that `localStorage` is accessed](https://github.com/nasa-gibs/worldview/search?utf8=%E2%9C%93&q=localStorage&type=).
