### ISSUE TITLE
Vagrant not building due to epel-release 

### ISSUE THREAD

**Issue by Loganb3rry** [nasa-gibs/worldview#49]
When running `vagrant up` I got an issue when it was trying to run the following from vm.bootstrap:

```
if ! rpm -q epel-release; then
    yum install -y http://mirrors.kernel.org/fedora-epel/7/x86_64/e/epel-release-7-5.noarch.rpm
fi
```
> ==> default: Cannot open: http://mirrors.kernel.org/fedora-epel/7/x86_64/e/epel-release-7-5.noarch.rpm. Skipping.
> ==> default: Error: Nothing to do
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**Comment by Loganb3rry** [comment]
**I had to do the following to resolve this:**
- vagrant ssh
- sudo yum install epel-release
- exit
- vagrant provision

**Comment by tgunnoe** [comment]
Thanks, we need to automate the fetch of the proper epel package to future-proof errors from the removal of older packages
