### ISSUE TITLE
New MOPITT NRT Layer

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#490]
We've added the following layers to GIBS, now ready for Worldview:

| Layer Identifier | Title | Subtitle | CMR Product |
| ------------- |-------------|-------------|------|
|MOPITT_CO_Daily_Total_Column_L2|Carbon Monoxide (L2, Daily, Total Column)|Terra / MOPITT|TBD|

**Comment by minniewong** [comment]
Will need to add CMR product for data download once available
