### ISSUE TITLE
Add a code of conduct file for GitHub

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#493]
GitHub recommends having a code of conduct page.
https://github.com/nasa-gibs/worldview/community

Read more on why we should have a code of conduct page:
https://opensource.guide/code-of-conduct/

And, adding a code of conduct page to your project:
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by localjo** [comment]
I wonder if NASA has any guidelines for open source projects that may be relevant here. Maybe @rboller or Katie Baynes have some thoughts on that.

**Comment by steadyflux** [comment]
We don't have an broadly applicable Code of Conduct covering NASA work. But we are in a perfect position to establish such a thing through our internal Code Contribution working group. Ping @rboller  or me via slack to get involved and get assigned some homework in helping us get this stuff documented and abided by.

**Comment by localjo** [comment]
This is done in #619
