### ISSUE TITLE
better error logging during fetch and config

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#495]
* to address a recent error: if there is only one layer in the getCapabilities we should log that.

**Comment by localjo** [comment]
What's going on with this? It looks like [there's a commit that fixes it](https://github.com/nasa-gibs/worldview/commit/cf3625e394956283eea74047a0a6f0c8316266db), and this is labeled `testing`, but the commit that fixes it is on an orphan branch with no open PR.

**Comment by ZachTRice** [comment]
Assigning @localjo to this but we can both discuss if any additional logging is still needed / this is still relevant.

**Comment by localjo** [comment]
It looks like `master` and `develop` have diverged since the commit addressing this issue was created and there are now conflicts, but these changes haven't been incorporated into `master` so we should recreate these changes and open a PR.
