### ISSUE TITLE
When animating to events zoom level should account for bounding boxes

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#496]
This issue came up while creating animations for #463 

When an animating to an event, we should take into account the bounding box when setting the final zoom level to make sure that the bounding box fits into the view.

This may be a little more complicated than face value, because bounding boxes don't always represent the area someone might want to visually see, and range in size from entire continents;
<img width="526" alt="screen shot 2017-08-31 at 6 13 02 pm" src="https://user-images.githubusercontent.com/516388/29947556-3cb43fee-8e78-11e7-86d9-00bbddc83862.png">

To areas so small it doesn't make sense to zoom in;
<img width="590" alt="screen shot 2017-08-31 at 6 13 25 pm" src="https://user-images.githubusercontent.com/516388/29947559-40565a74-8e78-11e7-8bfd-03d9bfa6a1d5.png">

An example of a useful situation would be zooming in on a sea bloom;
<img width="562" alt="screen shot 2017-08-17 at 12 14 10 pm" src="https://user-images.githubusercontent.com/516388/29947625-9dd9dfc2-8e78-11e7-9142-446bb6b9cc24.png">

While the bounding boxes *could* be useful in the future, to give an event a custom zoom box, the way that they're defined right now, I'd almost argue that we shouldn't display them at all.

**Comment by minniewong** [comment]
Add testable bounding box to E2E/mock
