### ISSUE TITLE
Vagrant not building the wv-options config correctly

### ISSUE THREAD

**Issue by Loganb3rry** [nasa-gibs/worldview#50]
Once the vagrant box is built, it says it is "Done, without errors" and that the "Worldview is now ready"
However, errors were displayed for the building of the "config" files "wv-options-validate: ERROR".

If I go to the browser, worldview loads but includes errors on the page and fails to load the components.

> Error: An unexpected error occurred. Please reload the page and try again. If you continue to have problems, contact us at "MAIL"

![worldview_config_build_issue](https://cloud.githubusercontent.com/assets/16720682/15390178/bef186fe-1dba-11e6-85be-3b0159fe1fad.png)

**Comment by Loganb3rry** [comment]
I had to update _worldview/etc/dev/vm.bootstrap_ and change grunt to build with --force.

This fixed the issues and builds the config files correctly. Worldview now displays with no errors once vagrant is up again.

**Comment by tgunnoe** [comment]
I believe that you've caught us in a transitional phase to a new backend.  Try it with [this commit](https://github.com/nasa-gibs/worldview-options-eosdis/commit/df2bebee01724c8b40456cd83cb069dab9a9844f)

Also, what is the validation error?
