### ISSUE TITLE
Timeline broken in Edge 15

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#502]
Just noticed this while testing in Browserstack. The timeline is blank in Edge 15 (latest).

<img width="978" alt="screen shot 2017-09-07 at 1 18 08 pm" src="https://user-images.githubusercontent.com/516388/30176146-67362f32-93cf-11e7-8e67-69ccb5fab681.png">

@Benjaki2 Any ideas?

**Comment by Benjaki2** [comment]
I think it has to do with this translated x value being too long
<img width="650" alt="screen shot 2017-09-07 at 2 02 43 pm" src="https://user-images.githubusercontent.com/3605988/30178173-07e0de4a-93d6-11e7-871f-794b07235cd8.png">

**Comment by Benjaki2** [comment]
I think the error is coming from d3 and would likely be solved with an updated version of d3. I started migrating to the newer version but stopped when it proved difficult. Might make sense to address this when we rework the timeline unless user complaints and/or browser stats say otherwise.

**Comment by localjo** [comment]
Is this still an issue? This might be something we should prioritize, since Edge users with an up to date browser will start seeing this issue soon.

**Comment by Benjaki2** [comment]
Looks like it is still broken in Edge 15. Working in Edge 16. I believe our forked version of `d3` is the issue and should be fixed when #610 is implemented.

**Comment by minniewong** [comment]
Users will be recommended to upgrade to Edge 16.
