### ISSUE TITLE
Update to CERES BEDI I

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#509]
We are now forward processing CERES BEDI I. 
You were already serving some historical data though up to 2011. It appears some subtitle are different from what I see in the ICD. Probably got updated.
We probably should make those active if they are not and the latest data available is Dec 2016. Latency is huge for those datasets.

Here is a link to the latest ICD under ASDC:
https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=81795237

Let me know if you need me to add anything to this ticket.

**Comment by minniewong** [comment]
@jejeking - Does the GC indicate the latency of a layer is? If not, how do i know what the latency is?

**Comment by jejeking** [comment]
You can find it in the ICD link I posted in the description.
