### ISSUE TITLE
Degree symbol for Kelvin scale

### ISSUE THREAD

**Issue by oftfrfbf** [nasa-gibs/worldview#51]
This is a very nit-picky thing to point out, but the correct labeling when using the Kelvin scale is to leave out the degree symbol. For layers like "Brightness Temperature," the labels include values such as, "224.9 °K" whereas the correct way to write that value is in the form, "224.9 K" (without the degree symbol). Reference to the "Kelvin" Wikipedia page to verify this <https://en.wikipedia.org/wiki/Kelvin>.

**Comment by tgunnoe** [comment]
Thanks for the report!  The typo comes from GIBS, the system from where we pull out tiles and colormaps.  It turns out that it was recently corrected for our internal build, which should go out to production very soon.

**Comment by oftfrfbf** [comment]
Sounds good! ...p.s. I really enjoy the Worldview code base, it's helped out a lot with a NSF project I've been working on at the Snow and Ice Data Center! Just wanted to say thanks!
