### ISSUE TITLE
Add IMERG Rain and Snow Rate

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#519]
We have added the following layers to GIBS, and are now ready for Worldview:

| Layer Identifier | Title | Subtitle | CMR Product |
| ------------- |-------------|-------------|------|
|IMERG_Rain_Rate|Rain Rate (Early)|IMERG|C1373892275-GES_DISC|
|IMERG_Snow_Rate|Snow Rate (Early)|IMERG|C1373892275-GES_DISC|

**Comment by minniewong** [comment]
Is this updated every 1/2 hour or which time step does the imagery represent?
