### ISSUE TITLE
Deactivate AIRS CO2 IR STD Layer

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#525]
From the AIRS Science Team at JPL. The AIRS-only CO2 V5 product (AIRS3C2M_005_mole_fraction_of_carbon_dioxide_in_free_troposphere) after Feb. 2017 can not be used because a key AIRS channel got noisy. This only affects V5 CO2 product. The generation of this product stopped. Those data after Feb 2017 on our server have been hidden.

Please deactivate AIRS_Carbon_Dioxide_IR_Monthly with an end date of Feb. 2017. GIBS's GC should reflect this.

**Comment by minniewong** [comment]
@apdeluca - We do not have this layer in Worldview.

**Comment by apdeluca** [comment]
Thought you did. I'll add this to #497
