### ISSUE TITLE
Large "+" buttons in Data Download on initial load [dd.sel.1]

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#528]
When zoomed out, the data download buttons do no scale properly. 
[Issue Example](https://worldview.earthdata.nasa.gov/?p=geographic&l=MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,MODIS_Terra_Aerosol,Coastlines&t=2013-09-28&z=3&v=-347.0625,-226.40625,347.0625,226.40625&ab=off&as=2013-09-28&ae=2013-10-05&av=3&al=true&download=MOD04_L2)
Internal Test `dd.sel.1`. 
Affects IE11, Chrome, FF. Edge works as expected.

**Comment by minniewong** [comment]
Appears to be fixed
