### ISSUE TITLE
Palette default color not matching map color & not updating [setting.pal.single.4]

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#529]
The default color in single palettes is not the same as the color shown on the map. Choosing a new color does not change the palette.
Test: `setting.pal.single.4`
See: https://worldview.earthdata.nasa.gov/?p=arctic&l=Land_Water_Map,MODIS_Terra_Sea_Ice(palette=blue_dark)&t=2014-04-18&z=3&v=-5553824,-3667136,4555104,2927424

Additional comments: color does not change to blue UNTIL you change the date to 2017-Mar-07 (Did the color map change on Mar 7, 2017?

**Comment by minniewong** [comment]
I think this error is partially to do with the MODIS_Terra_Sea_Ice and MODIS_Aqua_Sea_Ice layers being a mix of Collection 5 and Collection 6, and having 2 different color maps.

**Comment by minniewong** [comment]
2000 Feb 24/2002 Jul 4 to 2014 Dec 31: GIBS colormap v1.3 - 255,100,100
2015 Jan 1 -2017 Mar 7: 215,114,212 - this color is not represented in any of the GIBS color map files for sea ice.
8 Mar 2017 - present: Magenta color: GIBS colormap v1.3 - 255,100,100

**Comment by mcechini** [comment]
Are you still seeing this problem?  The colormaps were definitely different when we had both v5 and c6 imagery.  But now that we're reprocessed it all, I hope this has gone away.

**Comment by minniewong** [comment]
awesome - looks like the issue has gone away with the reprocessing! I will close this ticket now.
