### ISSUE TITLE
Animation Download not working in Internet Explorer [id.gif.4, date.animation.gif.3-6]

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#530]
Displays message `Do you want to allow this website to open an app on your computer?` Then it is saying it is trying to open a blob.

Tests 
`id.gif.4`
`date.animation.gif.3` - Download button doesn't work in IE11
`date.animation.gif.4-6` - An unexpected error has occurred. No errors in console

**Comment by minniewong** [comment]
Fixed in #891
