### ISSUE TITLE
Image Download fails to download older Arctic projections [id.proj.1]

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#531]
Fails with error: `Unable to complete your download request. Please email support@earthdata.nasa.gov for support.`
Test: `id.proj.1`
Affects IE11& Edge; other browsers not yet tested.

**Comment by minniewong** [comment]
This is still an issue and also occurs in Chrome

**Comment by minniewong** [comment]
Will be fixed when new imagery is in Worldview in a few months
