### ISSUE TITLE
Arctic and Antarctic rotations are not independent [map.rotate.9]

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#532]
When changing the rotation in one view, the rotation changes in the other view. Instead, they should act independently.

Test: `map.rotate.9`

**Comment by localjo** [comment]
I think the rotation of the map is separate. I think it's just the controls that aren't independent. This is what I was seeing;

> When you switch between arctic and antarctic projections, while each projection independently retains it's rotation, the number on the map controls that indicates the degrees of rotation does not change until you rotate the selected projection more.

> Additionally, if you switch to geographic projection in between the polar projections, the value displayed on the rotation control will default to the value for the last polar projection selected instead of the one you select.

**Comment by ZachTRice** [comment]
Closing. This is no longer happening in production.
