### ISSUE TITLE
Add VIIRS Brightness Temp Day/Night

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#533]
We have added the following layers to GIBS, and are now ready for Worldview:

| Layer Identifier | Title | Subtitle | CMR Product |
| ------------- |-------------|-------------|------|
|VIIRS_SNPP_Brightness_Temp_BandI5_Day|Brightness Temperature (Band I5, Day)|Suomi NPP / VIIRS|C1410218515-LANCEMODIS|
|VIIRS_SNPP_Brightness_Temp_BandI5_Day|Brightness Temperature (Band I5, Day)|Suomi NPP / VIIRS|C1410218515-LANCEMODIS|
|VIIRS_SNPP_Brightness_Temp_BandI5_Day|Brightness Temperature (Band I5, Day)|Suomi NPP / VIIRS|C1410218515-LANCEMODIS|
|VIIRS_SNPP_Brightness_Temp_BandI5_Night|Brightness Temperature (Band I5, Night)|Suomi NPP / VIIRS|C1410218515-LANCEMODIS|
|VIIRS_SNPP_Brightness_Temp_BandI5_Night|Brightness Temperature (Band I5, Night)|Suomi NPP / VIIRS|C1410218515-LANCEMODIS|
|VIIRS_SNPP_Brightness_Temp_BandI5_Night|Brightness Temperature (Band I5, Night)|Suomi NPP / VIIRS|C1410218515-LANCEMODIS|

**Comment by minniewong** [comment]
@apdeluca are there only 2 layers to add, not 6?
