### ISSUE TITLE
Map error. Map should be zoomed in to the maximum over ocean [perm.in.map.2]

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#534]
Map should be zoomed in to the maximum over ocean when viewing this link: https://worldview.earthdata.nasa.gov/?v=0,0,0,0&now=2013-05-30T12
Test:  `perm.in.map.2`

**Comment by minniewong** [comment]
@minniewong - remove from test plan

**Comment by minniewong** [comment]
Removed from test suite
