### ISSUE TITLE
dd.curl.6 (OSX)

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#537]
Only retrieves 3 of the six files. Likely the other 3 are being overwritten

**Comment by minniewong** [comment]
The 3 other files that are added are NRT files - there must be an issue when trying to download the NRT files with cURL or Wget.

**Comment by mike-mcgann** [comment]
Now blocked by #952

**Comment by minniewong** [comment]
Closing ticket and adding to data download overhaul project
