### ISSUE TITLE
Test for non-direct links in bulk download does not provide relevant text [dd.nodirect.3]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#539]
No download link present in this test case (tested in firefox)

**Comment by minniewong** [comment]
The cyclone imagery layer does not link to anything and doesn't show the following text- One link appears under "Some items that you have selected do not directly link to a data file.."

**Comment by mike-mcgann** [comment]
Probably related to #871

**Comment by minniewong** [comment]
Closing and adding to data download overhaul project
