### ISSUE TITLE
Orbital tracks that belong to multiple categories aren't properly checked in Add Layers modal

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#542]
Found by @minniewong;

When going through the Test Plan, step `layer.add.10`, when you add/check the box for “Aura/OMI Ascending/Day” orbital track under Aerosol Optical Depth, then go to the Aerosol Albedo measurement, the Aura/OMI Ascending/Day track should be checked since it has already been added to the layer list. If you try to check it, it removes the layer from the layer list, and if you click on the check box again, it adds the layer to the layer list.

**Comment by minniewong** [comment]
This was fixed
