### ISSUE TITLE
Adding CERES L3 BEDI II

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#548]
We are now forward processing and some non-forward processing CERES L3 BEDI II.
17 layers for CERES_CMB_SFC (forward) and 17 layers for CERES_TERRA_SFC (non-forward).
Latency is huge for those datasets and can be found in the ICD along with other relevant info.

Here is a link to the latest ICD:
https://docs.google.com/spreadsheets/d/110zK5ekPpPakL8cABw4gIe0bOZJg-xh5U70Z01_98M8/edit#gid=0

Let Natalie know if you need access to this google doc or if you need me to add anything to this ticket.

**Comment by minniewong** [comment]
@jejeking - is all the imagery now available in GIBS or are you still processing? I'm noticing missing sections in the more recent years.

**Comment by minniewong** [comment]
Can't add data download - need to investigate #581
