### ISSUE TITLE
Timeline: better support for differing temporal ranges (e.g., hourly, monthly, 8-day)

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#555]
To get it to work with sub-daily products (#460, #461)

**Comment by rboller** [comment]
Includes #610, #460, #461

**Comment by ZachTRice** [comment]
#610 is a duplicate of this ticket. Since that ticket has a long thread of information, I am closing this ticket and will use that one instead. @minniewong , @rboller feel free to re-open this ticket if I am misreading this as a duplicate.
