### ISSUE TITLE
Optimize color palettes for rasters

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#557]
WebGL stuff with fallbacks to Canvas

**Comment by ZachTRice** [comment]
Single color palettes, like orbit tracks, could be implemented using a webgl hue filter. 

Then, https://github.com/santilland/plotty would be great for handling the more complex array of colors which use custom palettes. 

For old browsers (mainly IE10, some mobile browsers) we would have a test for webgl support and fallback to canvas if it is not supported. 

Then, possibly try to optimize the canvas functionality further.
