### ISSUE TITLE
Replacement solution for scroll bar

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#558]
Right now, we've got several third party libraries that remove native scrollbars and replace them with JavaScript versions. This was originally done to improve the style of the app, since native scrollbars were ugly and obtrusive. Native scrollbars have recently improved to the point where we don't need to rely on replacements anymore. We should remove all references to and dependencies on Perfect Scrollbar, Mobiscroll, and jScrollPane and use native scrollbars everywhere.

This will require some attention to detail to make sure that the appearance and functionality of all affected scrollbars is acceptable in all browsers; Chrome/Safari/Firefox on Windows and Mac, as well as Chrome on Android and Safari on iOS.

**Comment by gabriellacerda** [comment]
Can I take this?

**Comment by Benjaki2** [comment]
For sure @gabriellacerda !

We want to rip out prefect scrollbar entirely but we are unsure at this moment whether there is a more robust library that we should use or if working with the native scrollbars is the best solution. Feel free to do some research and let us know which approach you plan to take.

Thanks again for your contributions!

**Comment by Benjaki2** [comment]
Fixed by #1084
