### ISSUE TITLE
Create vector metadata modal & tooltips

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#560]
Create an indicator (on hover) for the important attributes contained within a vector point.

- [x] Convert onClick console.log of vector feature object into an OL overlay
- [x] Implement a react-based tooltip
- [x] Style the tooltip
- [x] Create examples for review

**Comment by minniewong** [comment]
Check out: https://firms.modaps.eosdis.nasa.gov/map/
