### ISSUE TITLE
Add debug tools for vector specific data

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#561]
Currently, there is a panel for debugging layers accessed via `debug=layers`. This debug tool should be expanded to include information about a vector layer when it is selected. This should include:
- Static panel showing:
  - Total number of data points (at each zoom)
  - List of attributes / features / tags
  - Default style information
- Hover window showing features / tags for individual vector point

**Comment by mcechini** [comment]
Per our discussion during the OE dev meeting this week, a part of this activity for Zach is to provide GIBS an estimate of the "max feature per tile" we should aim for to avoid client-side performance issues.

**Comment by ZachTRice** [comment]
Stumbled across this tool which could be useful on the server-side for accumulating point counts per tile.
https://github.com/mapbox/tile-count

**Comment by ZachTRice** [comment]
Currently the vector-layers branch has the ability to click a vector point and see it's data in the console. Ideally, this ticket will take this information and put it into a floating panel, along with the other information outlined when a debug parameter is passed into the URL.

**Comment by ZachTRice** [comment]
These new debug tools should be outlined in the manual test plan. Also note, there should be e2e and unit tests added, as needed, for new vector features, before going live.

**Comment by ZachTRice** [comment]
Came across this tool at FOSS4G: https://github.com/jahow/ol-benchmarks

Could be useful to experiment with or use as a guide for developing some e2e Map tests (pan/zoom, etc)
