### ISSUE TITLE
Fix links to issue tags in the contributing docs

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#570]
The [contributing docs](https://github.com/nasa-gibs/worldview/blob/master/CONTRIBUTING.md) have a number of links to issue that are not linked correctly.

**Comment by gabriellacerda** [comment]
Can I take this one?

**Comment by ZachTRice** [comment]
Sure @gabriellacerda that would be great!

**Comment by localjo** [comment]
@gabriellacerda Take a look at the labels we're using here: https://github.com/nasa-gibs/worldview/labels

And let us know if there's any question about what a label is used for. :)

**Comment by gabriellacerda** [comment]
Oh, ok @localjo

**Comment by gabriellacerda** [comment]
I believe they are in an exemplar way

**Comment by ZachTRice** [comment]
Have a look at the links with multiple words. The issue appears to be related to not having quotes around help wanted. 
The current link is formatted:
https://github.com/nasa-gibs/worldview/issues?q=is%3Aopen+is%3Aissue+label%3Ahelp%20wanted

But the desired result would be:
https://github.com/nasa-gibs/worldview/issues?q=is%3Aopen+is%3Aissue+label%3A"help%20wanted"

**Comment by gabriellacerda** [comment]
@ZachTRice ready for test is not being used is it?

**Comment by ZachTRice** [comment]
You're correct. "ready for test" is now "testing", if you'd like to link to that label instead.

**Comment by gabriellacerda** [comment]
Ok, I'll fix it

**Comment by gabriellacerda** [comment]
#571

**Comment by ZachTRice** [comment]
This has been merged.
