### ISSUE TITLE
Optimization of product measurement browsing widget

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#577]
When selecting product measurements (e.g., "Brightness Temperature"), the app can take awhile to respond now that there are 600+ layers available.  This is especially true when clicking the "All" heading or measurements within "All".

This ticket is to improve the response time of the UI.  

See attached image for a basic reference to where this problem resides.

![product-measurements](https://user-images.githubusercontent.com/7243823/31796508-d78f69f8-b4f7-11e7-9aa9-8f5ee0d87af1.png)

**Comment by Benjaki2** [comment]
Major problem is rendering all the sources when we only need to render those when a row is selected.
