### ISSUE TITLE
Permalink window doesn't fit into Android window when in portrait mode

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#60]
See attached screen capture

![android-permalink](https://cloud.githubusercontent.com/assets/7243823/18457881/5849d4f8-792a-11e6-96cf-55ea80046741.png)

**Comment by Dylan-Brown** [comment]
I was able to recreate this issue on my Android Galaxy S2 phone. I can work on this.
What I notice is that on both the android and desktop versions, the box containing the share info seems to  align on the right side of the link icon. My  thought is that if it was reduced in width, say, to 2/3 (or around that value),  that it would fit on the android screen?

![screenshot_2016-10-03-10-53-43-2](https://cloud.githubusercontent.com/assets/10562115/19042013/6057a93e-8958-11e6-8ebe-7c23e0b21c60.png)

**Comment by Benjaki2** [comment]
@Dylan-Brown Sounds good. Could you make it responsive so that it stays the same size on desktop views and is a smaller width on mobile views?

**Comment by Dylan-Brown** [comment]
@Benjaki2 I've looked at / played with the style attribute of this "<div>" element, and through some searching online, I haven't found a way to alter the in-line style of the element in a way that makes it responsive to the screen size. 

I've thought about changing the wv.link.css file to include the style elements and seeing if there was a way to make the width dynamic from there, but that doesn't seem to be the approach with all of the other "major" divs, as they also use in-line style.

I think I lack perspective when it comes to web dev and am struggling to figure out how everything pieces together. Could you possibly point me to a resource that could explain this at a high level?

**Comment by Benjaki2** [comment]
@Dylan-Brown you can find whether the device is under our break point width using this method:

https://github.com/nasa-gibs/worldview/blob/master/web/js/util/wv.util.browser.js#L203

e.g. `var mobile = ui.util.browser.small(); // mobile will be true or false `
