### ISSUE TITLE
Add World Database on Protected Areas layer

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#603]
Add the World Database on Protected Areas (WDPA) layer via the World Conservation Monitoring Centre (WCMC) WMS:

http://gis.unep-wcmc.org:6080/arcgis/services/wdpa/public/MapServer/WMSServer?request=GetCapabilities&service=WMS

The info box should link to the data set terms and conditions:
http://www.protectedplanet.net/terms

and to the download of the data set at:
www.protectedplanet.net

**Comment by minniewong** [comment]
WDPA is going to change the layer names in December - we will wait until the layer names are changed before putting it on Worldview

**Comment by minniewong** [comment]
@rboller - Check with WDPA on progress

**Comment by rboller** [comment]
Checked their layer names today and they're the same as when I contacted them in November.  I'll follow up with them on Monday to see if they still plan to update them.

**Comment by rboller** [comment]
WCMC has decided to keep the layer names as they were to prevent user confusion.  So we're good to move forward using them as currently defined.
