### ISSUE TITLE
Remove layer titles and dates from .md files

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#609]
To prepare for automated adding of titles & subtitles and dates: Connects to #384

**Comment by minniewong** [comment]
Completed in remove-title&dates branch in the options repo.

**Comment by localjo** [comment]
Can we add this to the Module Loaders (v2.0) release?

**Comment by minniewong** [comment]
@localjo -no, we need to test this with Zach's branch first.

**Comment by localjo** [comment]
@ZachTRice Which branch does this need to be tested with?

**Comment by ZachTRice** [comment]
I have a local branch with changes to accommodate this. I didn't push it up because it is not ready. After module loaders is done, I will merge those changes into the codebase and push up a new branch. We discussed this briefly at last week's dev meeting.
