### ISSUE TITLE
iPad: image capture mode can break map

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#61]
On iPad, if
- image download mode is invoked
- then it's closed
- then you rotate the screen a few times

the usable map area becomes greatly reduced.  See attached screen capture - the bottom part of the map is missing.

![ipad-bottom-map-missing](https://cloud.githubusercontent.com/assets/7243823/18457953/e58cb7a4-792a-11e6-94b1-5e80628c1732.PNG)

**Comment by minniewong** [comment]
Cannot replicate issue
