### ISSUE TITLE
Open source projects link is broken on mobile

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#62]
In the "About" window, there is a link to the other open source projects used by Worldview:
- Worldview is built by the NASA/GSFC Earth Science Data and Information System (ESDIS) Project and is grateful for the use of many open source projects.

If on a desktop-sized browser, it links here (and works):
https://worldview.earthdata.nasa.gov/pages/worldview-opensourcelibs.html

If on a mobile-sized browser, it links here (and breaks):
https://worldview.earthdata.nasa.gov/brand/pages/pages/worldview-opensourcelibs.html

This can be reproduced in the desktop if you make the browser small enough to switch into "mobile mode".

**Comment by Dylan-Brown** [comment]
I'd like to work on this issue, and have been thinking about it / looking around the dist for a few days.
brand/pages/pages is not a directory in the dist site-worldview, but brand/pages is. When I create the second page subdirectory (in my local apache2 var/www directory) as follows:
![directory](https://cloud.githubusercontent.com/assets/10562115/18879772/878a75e0-84a3-11e6-9142-9e8e36d145a3.png)
I get the following to show up at the mobile-sized browser:
![webpage](https://cloud.githubusercontent.com/assets/10562115/18879805/a3c206c4-84a3-11e6-8d02-2cbd3736cd22.png)

**Comment by Benjaki2** [comment]
@Dylan-Brown Nice work. I'm glad you are taking on this issue. We have been meaning to get to it for some time now. 

So, I don't think we need to necessarily alter the location of the template. The base of the issue appears to be that in mobile devices the about page opens in a new window and that with higher resolution screens the about page opens as a pop-up/modal.

https://github.com/nasa-gibs/worldview/blob/master/web/js/ui/wv.ui.info.js#L79-L92

You should be able to solve this by just fixing the href in the template file:

https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/brand/pages/about.html#L145

I found another link that is broken in the same template: 

https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/brand/pages/about.html#L170

**Comment by Dylan-Brown** [comment]
So, I rebased my fork after seeing there were two new contributions... and now I can't seem to find about.html anywhere. The folder brand/pages doesn't exist; in brand, there's just .gitignore and .htaccess files?

**Comment by veleiro** [comment]
those files are in our options repo, worldview-options-eosdis

**Comment by tgunnoe** [comment]
That's located in https://github.com/nasa-gibs/worldview-options-eosdis/tree/master/common/brand/pages

**Comment by tgunnoe** [comment]
@Dylan-Brown I think I closed it a bit soon.  It doesn't work on localhost when the URI points to the live instance of Worldview. So keeping this issue open for now

**Comment by Dylan-Brown** [comment]
@tgunnoe so, should I change the links to relative directories? For instance, 
<a href='../../pages/worldview-opensourcelibs.html' target='_blank'>open source projects</a>.
?
Since the 'about.html' file is in the options directory, I wasn't sure how changing it would affect an unpacked dist.

**Comment by tgunnoe** [comment]
you can also open it in a modal under Info -> About in Worldview on the desktop.  The absolute link works in both now on production but you'd want to see local changes of it in your local environment.

So a "../../pages" relative wouldnt work. "@Hostname@/pages" or something similar would be ideal

**Comment by localjo** [comment]
This is no longer relevant after https://github.com/nasa-gibs/worldview-options-eosdis/pull/147

(That update has not been deployed yet, but will automatically be included in the next deployment of Worldview)
