### ISSUE TITLE
Invalid discrete legend display for colormap with more than 10 LegendEntry

### ISSUE THREAD

**Issue by PacoDu** [nasa-gibs/worldview#626]
If you configure a layer with a colormap containing more than 10 discret LegendEntry we have a CSS glitch : 
<img width="350" alt="worldview-legend-issue" src="https://image.noelshack.com/fichiers/2017/48/5/1512138710-worldview-invalid-legend.png">
<img width="350" alt="worldview-legend-issue" src="https://image.noelshack.com/fichiers/2017/48/5/1512138710-worldview-invalid-legend2.png">

IMO discret legend should be displayed on a grid with a limited width and new row if needed, with a static string align on the left for details on mouse hover.

**Comment by ZachTRice** [comment]
A new land cover layer, which should be ready by March, will have 18 categories. We need to come up with a better solution for handling that many category color boxes.

Adding the following to the CSS will help the layout of the boxes.
```
.bank div.wv-palettes-legend { overflow: hidden }
.wv-palettes-class {
    float: left;
    margin-bottom: 8px;
}
```
The actual tooltip label is controlled by javascript and will need to be tweaked.

It might make sense to restructure the html a bit to accommodate this. There are better ways to structure this area.

**Comment by minniewong** [comment]
Fixing this should also close #523
