### ISSUE TITLE
"Loading..." is not removed from sidebar if naturalEvents feature is disabled

### ISSUE THREAD

**Issue by PacoDu** [nasa-gibs/worldview#627]
The loading text in the sidebar is not removed if naturalEvents is disabled https://github.com/nasa-gibs/worldview/blob/a85692d5f20cc227dfefaf0cca7a5e905c0b3de0/web/index.html#L294

The code seems inconsistent as wv-events is dedicated to the Events tab but it's also used for Loading information. So if naturalEvent is disabled the wv-events div is not filled and Loading text is still displayed after rendering.
https://github.com/nasa-gibs/worldview/blob/a85692d5f20cc227dfefaf0cca7a5e905c0b3de0/web/js/layers/wv.layers.sidebar.js#L187-L198

**Comment by ZachTRice** [comment]
This issue was addressed in PR #628
