### ISSUE TITLE
Data download window reappears at unexpected time

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#63]
A relatively obscure bug:
- load a product with daily-only data download (e.g., AMSR2 snow-water equivalent, [http://go.nasa.gov/2c6Mtpf](http://go.nasa.gov/2c6Mtpf))
- go to data download tab
- add a day to the cart
- click "download data"
- go straight back to active layers tab without closing data download window
- click layer settings button - data download window appears in background

**Comment by minniewong** [comment]
Closing ticket as it's more trouble than it's worth - will be resolved by data download v2
