### ISSUE TITLE
Add data download handler for SMAP/Sentinel-1 Soil Moisture

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#636]
SMAP_Sentinel-1_L2_Active_Passive_Soil_Moisture (CMR short name: SPL2SMAP_S) has 30 second granules and a new data download handler has to be created to work with this layer

**Comment by minniewong** [comment]
The layer currently points to the collection level metadata and the data provider would like to see Worldview display the 30 second granules

**Comment by rboller** [comment]
This may be considered in the future with an overhaul of data download.

**Comment by rboller** [comment]
Added to [roadmap](https://github.com/nasa-gibs/worldview/projects/7) if we decide to overhaul data download.

**Comment by minniewong** [comment]
This was a specific request from the data provider - we currently link to the collection information, but we might want this to be at the top of the list for data download overhaul.
