### ISSUE TITLE
Ability to view layer descriptions more easily

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#65]
Worldview currently provides detailed, "human readable" layer descriptions to help users understand how each layer can be used, their limitations, and why they are important.  Here's an example:

https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/config/metadata/amsr2/CloudLiquidWater.md

At present, these descriptions are only available when using the layer selection widget (i.e., the "+ Add Layers" button).  But it would be very helpful if they were more easily available after layers were added to the active layer list.  

So this ticket is to add the capability to view these layer descriptions "on demand", likely invoked from the active layer list.

**Comment by minniewong** [comment]
Connects to #329
