### ISSUE TITLE
Create plan for A|B Comparison

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#652]
Plan out development work/milestones for A|B Comparison, with and without updates to the timeline

**Comment by localjo** [comment]
Let's use a GitHub project for this, and create individual GitHub issues with checklists for each step so we can take advantage of these new GitHub projects features: https://github.com/blog/2487-track-the-progress-of-your-projects

**Comment by minniewong** [comment]
excellent idea @localjo !
