### ISSUE TITLE
Update tests for the layer models

### ISSUE THREAD

**Issue by tgunnoe** [nasa-gibs/worldview#66]
Worldview uses [PhantomJS](http://phantomjs.org/) for executing various unit tests.  The tests havent been updated since the "overlays" were moved to be above "base layers" in the list [here](https://github.com/nasa-gibs/worldview/blob/master/test/layers/wv.layers.model-test.js)

I tried to update [this line](https://github.com/nasa-gibs/worldview/blob/master/web/js/layers/wv.layers.model.js#L59) to
`return overlays.concat(baselayers)`

In order to have the correct sequence of layers returned from `models.layers.get()` and display the order of stacked data in the timeline properly, but PhantomJS returns many errors with 
`$ grunt test`

**Comment by localjo** [comment]
This is a part of #693
