### ISSUE TITLE
Can not animate custom colormaps [perm.in.anim.2]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#667]
When attempting to animate layers with custom colormaps, the loading icon goes forever without logging any errors. (Firefox and Chrome)

links to PR #503

**Comment by ZachTRice** [comment]
Broken in Edge, Chrome, and FireFox (tested on Windows). Works in IE11.

Expected result:
- Page should load with animation widget activated and a custom colormap active
- When you press play the animation should start and loop

**Comment by localjo** [comment]
Also broken in Safari

**Comment by minniewong** [comment]
And Chrome OS X

**Comment by localjo** [comment]
Merged into #503
