### ISSUE TITLE
Update layer legends to use tick marks from colormaps

### ISSUE THREAD

**Issue by tgunnoe** [nasa-gibs/worldview#67]
"As we start to introduce more logarithmic colormaps, it will become more common that the legend images in Worldview may mislead someone into thinking a color ramp is linear (arguably the default interpretation) when in fact it is not.

I think the initial simple solution to this is to honor the "tickMark" attributes in the GIBS colormap legends. WV wouldn't need to label the tick marks, but presumably one would see tick marks that are not evenly spaced, giving a visual indication that the color ramp is not linear."

**Comment by localjo** [comment]
I can explore the option of labeling the tick marks too, and see if I can somehow incorporate that.

**Comment by minniewong** [comment]
@Benjaki2 - where are you on this?

**Comment by Benjaki2** [comment]
Here is where I am at:
<img width="877" alt="screen shot 2019-03-04 at 1 13 27 pm" src="https://user-images.githubusercontent.com/3605988/53753482-5f2c0580-3e7f-11e9-84d3-c19afe9c2bbf.png">

@rboller Does this look right to you? I was expecting to see some layers with ticks that were distributed non-linearly. 

Notes:
* Showing tick marks for all `continuous` legends that have the `showTick` flag in the colormaps

**Comment by rboller** [comment]
@Benjaki2 there aren't many colormaps which have a log scale but try Chlorophyll A on Terra and Aqua.  @mcechini should be able to provide some other examples if needed, too.

Otherwise the styling looks good to me overall and would agree that we could do something to make the ticks stand out when in front of darker colors.  I'd also suggest reducing the tick height by a bit so they don't distract too much from the colorbar itself.

**Comment by mcechini** [comment]
The new TRMM layers have a logarithmic ramp, along with some MEaSUREs products.  I suggest you reach out to Natalie on this, since she's in the middle of creating legends for those products.  It'll be good to work the log colormap issue together.

**Comment by Benjaki2** [comment]
Doesn't look like `Chlorophyll A` layers have `showTick` flags in their colormaps. Should I file a GIBS ticket for this? I will reach out to Natalie about the new `MEaSUREs` products.

**Comment by Benjaki2** [comment]
I tried to do dotted lines and a line with a border but nether looked very good. If you look below, I have a few examples of what thought looked best.

**Tick mark color based on inverse of current color**
<img width="283" alt="Screen Shot 2019-09-04 at 3 24 47 PM" src="https://user-images.githubusercontent.com/3605988/64284887-8e9ff580-cf28-11e9-8f53-7f9ed30e81eb.png">

**Light or dark gray tick marks (based on current color)**
<img width="289" alt="Screen Shot 2019-09-04 at 4 00 56 PM" src="https://user-images.githubusercontent.com/3605988/64287306-4d5e1480-cf2d-11e9-849d-6156193858a4.png">

**Plain black tick marks**
<img width="285" alt="Screen Shot 2019-09-04 at 3 22 44 PM" src="https://user-images.githubusercontent.com/3605988/64284893-93fd4000-cf28-11e9-9264-c2ab63789c6b.png">

**Comment by Benjaki2** [comment]
Notes from Dev meeting:
* Try adding white ticks on the top and black ticks on the bottom
* Try adding ticks outside the `color-bar`
* exclude ticks from certain products (e.g. 12-bin products) and always show them for products with logarithmic scales

**Comment by Benjaki2** [comment]
Updated styling:

Ticks outside of colorbar:
<img width="309" alt="Screen Shot 2019-09-06 at 2 26 49 PM" src="https://user-images.githubusercontent.com/3605988/64451586-85429480-d0b2-11e9-82fd-38826a51026e.png">
White and black ticks:
<img width="299" alt="Screen Shot 2019-09-06 at 12 53 23 PM" src="https://user-images.githubusercontent.com/3605988/64451634-9e4b4580-d0b2-11e9-8d40-b0e777700212.png">

**Comment by Benjaki2** [comment]
Shorter ticks outside the colorbar
<img width="361" alt="Screen Shot 2019-09-09 at 10 24 01 AM" src="https://user-images.githubusercontent.com/3605988/64539312-4861e200-d2ec-11e9-8d89-81b7549877ca.png">

**Comment by Benjaki2** [comment]
Ticks below colorbar
<img width="290" alt="Screen Shot 2019-09-09 at 11 37 24 AM" src="https://user-images.githubusercontent.com/3605988/64546006-cf688780-d2f7-11e9-9a5f-fcbde3388e72.png">
