### ISSUE TITLE
Feedback form not displaying

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#672]
This bug is introduced in #503 

In Safari, when clicking on the info icon, and then send feedback, the feedback form does not appear. The console shows;
```
Refused to display 'https://fbm.earthdata.nasa.gov/tickets/new?app_name=worldview...' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
https://fbm.earthdata.nasa.gov/tickets/new?app_name=worldview...
Failed to load resource: the server responded with a status of 403 (Forbidden) 
```

**Comment by ZachTRice** [comment]
I see this happening in IE, Edge and Chrome on Windows. This is also happening on production, so it was not introduced with module-loader changes.

**Comment by localjo** [comment]
You're seeing it happen on https://worldview.earthdata.nasa.gov ?

I think the problem is related to `X-Frame-Options:SAMEORIGIN`, so I think the form will only display when the app is served from `worldview.earthdata.nasa.gov`.

**Comment by ZachTRice** [comment]
Right, I am just seeing the error on production. The form still displays.

**Comment by localjo** [comment]
It looks like there error you're seeing on production is just a warning, but doesn't prevent the form from being displayed. It looks like this will work fine on production, once this branch is being served from the full domain. Here are the relevant parts of the response header of the iframe;

```
HTTP/1.1 200 OK
...
X-Frame-Options: ALLOW-FROM https://worldview.earthdata.nasa.gov
...
Content-Security-Policy: default-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; frame-src https://www.google.com/recaptcha/; frame-options https://worldview.earthdata.nasa.gov
...
X-Content-Security-Policy: default-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; frame-src https://www.google.com/recaptcha/; frame-options https://worldview.earthdata.nasa.gov
```
