### ISSUE TITLE
Animation widget is not hidden when you select data download [date.animation.15]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#676]
Animation should be hidden when you click on data download

**Comment by minniewong** [comment]
except after refreshing, i couldn't replicate the problem!

**Comment by ZachTRice** [comment]
I am not able to reproduce this in Chrome, Firefox, Edge, or IE. Were you able to reproduce this again @minniewong? If you can't reproduce it then I think this might have just been a glitch and we can close this issue.

**Comment by minniewong** [comment]
no i couldn't replicate it...
