### ISSUE TITLE
Dragging animation end date guitar pick past timeline end causes wonky behavior [date.animation.9]

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#679]
If you drag the animation end date past the right end of the timeline, and then back to the left without releasing, it pushes the animation start date and changes the blue selection highlight in an unpredictable way.

Confirmed in Safari

**Comment by ZachTRice** [comment]
I am seeing this behavior as well in Chrome, IE and Edge on Windows.

**Comment by mike-mcgann** [comment]
Bug still present

**Comment by edplato** [comment]
Addressing in Timeline Overhaul.
