### ISSUE TITLE
Add different icons or colors to denote different types of natural events

### ISSUE THREAD

**Issue by tgunnoe** [nasa-gibs/worldview#68]
In the events tab, change the color of the icon on the left for different events – say blue for hurricanes/cyclones and other water events, and yellow for volcanoes.

Or, have different icons that represent different types of natural events.

**Comment by rboller** [comment]
See a full list of event categories here:
http://eonet.sci.gsfc.nasa.gov/api/v2.1/categories

That said, Worldview is currently ignoring Floods, Earthquakes, Drought, and Landslides since they are often difficult to see with the currently available layers:
https://github.com/nasa-gibs/worldview/blob/e8c796d012ada1f7e9118c27230391dd58042963/web/js/naturalEvents/wv.naturalEvents.ui.js#L186-L192

So those particular event categories wouldn't need to be represented.

**Comment by wrightakencom** [comment]
Zoom lens and a half aperture in icons 
In all of graphics could be done with it  !

**Comment by minniewong** [comment]
Estimated 4 hours

**Comment by rboller** [comment]
Let's check with @CodeMacabre if we can reuse the relevant icons that he designed here:
https://remotepixel.ca/blog/disasterwatch_version1_20161026.html

**Comment by CodeMacabre** [comment]
I'd say it's @vincentsarago's decision, as I designed them specifically for his project. If's he's happy for them to be used, I'm also happy.

Alternatively, I could design a fresh set.

**Comment by vincentsarago** [comment]
👋 Hey I see no problem to re-use the icons in Worldview :-) 
Thanks @CodeMacabre

**Comment by rboller** [comment]
That's great to hear, thanks very much @vincentsarago and @CodeMacabre!   

Also thanks @CodeMacabre for offering to design a new set - our team here really likes what you've already done with @vincentsarago.  The only possible additions would be for the EONET event types which don't currently have icons: Sea and Lake Ice, Snow, Temperature Extremes, and Water Color.  We can just use the "!" icon for those, but if you'd like to create new ones, we'd be happy to incorporate them, too.

**Comment by CodeMacabre** [comment]
More than happy to! I'll get working on them as soon as possible. Are you looking for a similar style (i.e. white icon on circular bkg)?

**Comment by rboller** [comment]
Awesome!  Many thanks, @CodeMacabre!  

And yep, a similar style would work great.  Here are examples of the event types above which still need icons:
http://earthobservatory.nasa.gov/IOTD/view.php?id=83169
http://earthobservatory.nasa.gov/NaturalHazards/view.php?id=89423
http://earthobservatory.nasa.gov/IOTD/view.php?id=87981
http://earthobservatory.nasa.gov/NaturalHazards/view.php?id=85338

**Comment by CodeMacabre** [comment]
Ah great, that's a real help! I have a busy end-of-week, but should be able to get these done this weekend. Will that be ok, @rboller?

**Comment by rboller** [comment]
By all means, please take whatever time you need!  @tgunnoe is planning to work on this ticket over the next week and has been working on the related #117.

**Comment by CodeMacabre** [comment]
A few questions:

+ Do you have a preferred file format for the icons? I'm designing them as vectors (SVG), but can export to any format. If you want them in a bitmap format, what dimensions would you like them?
+ Do you have any preferred naming convention? I was thinking `event-[type].svg` (such as `event-sea-and-lake-ice.svg`, `event-snow.svg`, etc.).
+ Am I right in thinking you'll want them saved in [`./web/images/`](https://github.com/nasa-gibs/worldview/tree/master/web/images)?

**Comment by tgunnoe** [comment]
SVG is great!

event-*.svg also sounds good.  and if you do a pull request /web/images or subdirectory works

**Comment by tgunnoe** [comment]
I added the icons to the [./web/images/natural-events/](https://github.com/nasa-gibs/worldview/tree/master/web/images/natural-events/) directory instead

**Comment by CodeMacabre** [comment]
Sorry, I've had an unexpectedly busy week, but I'll be sure to get the additional four icons done this weekend.

**Comment by tgunnoe** [comment]
No worries! This isn't holding up anything.  Its helped a ton already just having the original icons
![screen shot 2017-02-02 at 12 01 09 pm](https://cloud.githubusercontent.com/assets/7254833/22559388/e83922ce-e93e-11e6-8daa-271c540fc595.png)

**Comment by CodeMacabre** [comment]
Three of the icons are more-or-less finished (provided you're happy with the design), but sea ice is giving me some trouble. Although it's not ideal as a concept, I've resorted to an image of an iceberg. What do you think?

![wv-icons](https://cloud.githubusercontent.com/assets/19981049/22621324/eb3406fc-eb18-11e6-8134-9ce568832799.PNG)

I've also renamed all the icons following the naming convention above, but if you're happy with using the `natural-events` folder to manage them, I can revert the filenames to just `[type].svg`.

**Comment by rboller** [comment]
Looking great, @CodeMacabre !  After discussing with the team, we sympathize with you in how difficult it is to show water color anomalies with a single color.  We also had a comment that the use of a gradient breaks with the style of the other icons.  You could consider something like a halftone but not sure how that would look.  And here are some other examples if it would help:
https://oceancolor.gsfc.nasa.gov/feature/images/A2016322035500.TasmanSea.jpg
http://go.nasa.gov/2kjJEnm
![phytoplanktoninthefalklands_cropped400](https://cloud.githubusercontent.com/assets/7243823/22660206/a86c877a-ec6e-11e6-9a99-e28773c854c1.jpg)

As for the sea ice icon, we really like the look of the iceberg.  Our only hesitation is that, while icebergs exist within sea ice, they're not the most prevalent thing there.  So we think it could still work but a fun alternative could involve sea ice and a penguin or two. :)   E.g.,
http://farm6.staticflickr.com/5048/5229516002_bedc034813_z.jpg

Again, thanks for all of your efforts on this and we're already happy.  If you'd like to update them further, we'll certainly include those updates.  

As for the naming convention, @tgunnoe what is your preference there?

**Comment by tgunnoe** [comment]
I don't have a naming convention.  I went with @CodeMacabre's filenames when i created the branch.  whatever works.

**Comment by CodeMacabre** [comment]
@rboller Ha, yep the water colour has been tricky. I agree that the gradient isn't ideal so I've been experimenting with subtractive [hatching](https://en.wikipedia.org/wiki/Hatching).

I had made a couple of abortive attempts at 'proper' sea ice; I'll persevere in that direction. I like the idea of adding a penguin (although I'm not sure how readable it would be at a small size). I'll hopefully get something to you by the end of the week.

**Comment by CodeMacabre** [comment]
I've made a pull request (#143) with the redesigned the sea ice and water colour icons, plus done some slight colour adjustments to temperature and fire.

![wv-icons2](https://cloud.githubusercontent.com/assets/19981049/22857623/59ad0f16-f0a0-11e6-8a40-50dd1eb59eef.PNG)

I think they're a real improvement (and readable at small sizes), but if you'd like any changes made, just let me know.

**Comment by Benjaki2** [comment]
Thanks for the improvements @CodeMacabre, the adjustments look great! We are doing some testing and will hopefully get those merged over in the next couple weeks.

**Comment by minniewong** [comment]
We're in the process of testing the new icons (and other features) but we've had a new category added in the meantime - icebergs! @CodeMacabre It would be awesome if we could incorporate your previous "sea ice" event icon (the one that looked like an iceberg - see your Feb 4 comment) to the new "iceberg" event category.

**Comment by CodeMacabre** [comment]
@minniewong Excellent! I'm very happy for iceberg to be added to the mix, but my design could use some refinement. I'll work on it this week, but if you'd prefer to use the previous one (at least as a placeholder in the meantime), I can make another PR now?

**Comment by Benjaki2** [comment]
@CodeMacabre That would be awesome. Could you make the PR to the testing-1.4.0 branch? The icon-incorporating code isn't ready to be merged to master yet. Thanks!

**Comment by CodeMacabre** [comment]
@Benjaki2 Will do! I should be able to get the revised icon done today.

Do you need to move #143's base branch from `master` to `testing-1.4.0` or should I resubmit the whole PR again (+ iceberg) to the testing branch?

**Comment by Benjaki2** [comment]
@CodeMacabre I think that switching the base branch of #143 would work.

Thanks again for all the additions!

**Comment by CodeMacabre** [comment]
Base branch switched and new iceberg icon added to the PR! Let me know if you want any changes.

![icon-iceberg-300](https://cloud.githubusercontent.com/assets/19981049/23703775/850f948c-03f9-11e7-870a-d61abd4c947c.png)

**Comment by Benjaki2** [comment]
@CodeMacabre Feel free to reach out to me at benjamin.a.king@nasa.gov if you would like the v1.4.0 testing link to see your icons in action.

**Comment by CodeMacabre** [comment]
@Benjaki2 Thanks! Email sent.
