### ISSUE TITLE
Sometimes drag and drop to change layer order doesn't work on desktop

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#680]
In this view, for example, if you try to drag Brightness Temperature below Cloud Top Pressure, it doesn't work. Dragging Cloud Top Pressure on top of Brightness Temperature does work. https://worldview.earthdata.nasa.gov/?p=geographic&l=MODIS_Terra_Brightness_Temp_Band31_Day,MODIS_Terra_Cloud_Top_Pressure_Day&t=2013-05-15&z=3&v=-116.46886241007195,-46.546875,55.43761241007195,53.015625

Tested in Safari while checking test plan `layer.active.16`.

**Comment by ZachTRice** [comment]
I cannot drag and drop layers at all on Android (Oreo) on Pixel 2 XL.

**Comment by localjo** [comment]
This issue is only for the desktop drag and drop feature. Mobile drag and drop doesn't exist yet. See #684

**Comment by localjo** [comment]
This was merged into #503
