### ISSUE TITLE
Layer Debugger Is Broken [layer.render]

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#681]
In #503, when `debug=layers` is in the URL, the plus and minus buttons to cycle through layers aren't working. Tested in Safari.

**Comment by ZachTRice** [comment]
Chrome on Windows: The layer minus button was not working, the plus button still cycled to the next layer. Additionally, the date minus/plus buttons were working as expected. 

IE & Edge: Works as expected

**Comment by localjo** [comment]
Looks like #668 fixes all of the problems I was seeing.

**Comment by localjo** [comment]
Merged into #503
