### ISSUE TITLE
Granule labels incorrectly positioned [dd.ams.2]

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#683]
In #503 this bug was introduced. Labels on some granules are not correctly positioned when hovering over the granule. Tested in Safari.

<img width="1115" alt="screen shot 2018-01-15 at 12 07 55 pm" src="https://user-images.githubusercontent.com/516388/34954041-f0dd99a4-f9ec-11e7-88e9-4d55da642915.png">

**Comment by Benjaki2** [comment]
Broken in Firefox as well.

**Comment by ZachTRice** [comment]
I am seeing this issue as well on Chrome, Edge and IE. 

Also, when compared to production; production is showing "Large "+" buttons in Data Download on initial load" #528 but the newest version on testing does not have this issue.

**Comment by localjo** [comment]
Looks like this is probably related to [changes in `web/data/map.js`](https://github.com/nasa-gibs/worldview/commit/129035edaa7b935008f543a68501754d8feff226#diff-29ebb84669d5dfc2f0281a7726cc7f6e) but I still haven't tracked it down completely.

**Comment by localjo** [comment]
Thanks @ZachTRice for discovering that reverting to Openlayers v4.3.x fixes the issue. Let's look into what changed in Openlayers 4.4.x and see if we can update something to make this work with 4.4.x.

**Comment by localjo** [comment]
Fix has been merged into `module-loaders` branch.
