### ISSUE TITLE
Drag and drop layer order doesn't work on mobile

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#684]
There is currently no way to adjust layer order on mobile, while you can drag and drop the layers on desktop, on mobile the drag and drop functionality doesn't work. Tested on iOS Safari. `layer.active.13`, `layer.active.16`

**Comment by ZachTRice** [comment]
I cannot drag and drop layers at all on Android (Oreo) on Pixel 2 XL.

**Comment by localjo** [comment]
Merged into #503
