### ISSUE TITLE
Only one granule removed when corresponding layer is remove [dd.sel.19 & dd.sel.21]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#686]
When multiple granules are selected and multiple downloadable projects present, only the first 'gray area' is removed when it's corresponding layer is removed.

![screen shot 2018-01-16 at 9 41 43 am](https://user-images.githubusercontent.com/3605988/34994422-72a36b44-faa1-11e7-8611-28a87f6b502b.png)

**Comment by localjo** [comment]
Steps to reproduce:

    * Go to https://go.nasa.gov/2rktj7v
    * With AOD Aqua/MODIS selected in the data tab, select two granules in the northern hemisphere
    * Select AOD Terra/MODIS and select two granules in the southern hemisphere
    * Four granule outlines should appear on the map
    * Switch to layers tab
    * Remove AOD Aqua/MODIS
    * Switch back to data tab
    * BUG: A selection outline still appears in the north, for the removed layer
    * Deselect the two granules in the south
    * BUG: Download Selected Data button is not disabled

Tested in Chrome on Mac

**Comment by mike-mcgann** [comment]
Verified this is still an issue.
