### ISSUE TITLE
Implement Gitflow approach to feature integration

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#721]
We can use [Atlassian's tutorial about Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) as a guide for our implementation.

Here are the steps to take;

- [x] Rename the `development` branch to `develop`
- [x] Determine how developers will practice “continuous integration” to stay in sync with the `develop` branch while working on features
- [x] Make sure developers have tooling set up for continuous integration
- [x] Determine a workflow for creating and staging release branches to prepare a release
- [x] Determine flexible guidelines for naming feature, release and hotfix branches
- [x] Make sure Gitflow changes are applied to `worldview-options-eosdis` and `worldview-components` repos too.
- [x] Update documentation to reflect the Gitflow approach

**Comment by localjo** [comment]
For developers to keep their work in sync with the `develop` branch, they should run `git rebase develop` ([or an equivalent](https://git-scm.com/docs/git-rebase)) multiple times a day to make sure they have the latest changes from the `develop` branch included in their feature branch.

At a minimum, developers should sync with `develop` each time before they sit down to start or resume work on a feature branch, and immediately every time they realize that their are new changes on the branch.

**Comment by localjo** [comment]
I think feature and hotfix branches should be named using descriptive names like `temporal-resolution`, or `fix-cache-busting`, etc. For release branches, I think we should use this form: `release-2.0.2`. We could also use the prefix `hotfix-` for hotfix branches, but I don't think that's necessary. What do you think @ZachTRice ?

**Comment by ZachTRice** [comment]
I like the naming structure suggested. I would like to start using the `hotfix-` prefix as well but we don't need to be particularly strict about it.

**Comment by ZachTRice** [comment]
Documentation regarding Gitflow and release preparation was added to our internal deployment page.
