### ISSUE TITLE
Install Help - box not found

### ISSUE THREAD

**Issue by jelpatte** [nasa-gibs/worldview#73]
I am working on setting up with your instructions. Full disclosure: I am new to vagrant and virtual box. 

I have installed vagrant and virtualbox and cloned your repos successfully. When I get to the step with the `vagrant up` command I receive the following message:

> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Box 'matyunin/centos7' could not be found. Attempting to find and install...
>     default: Box Provider: virtualbox
>     default: Box Version: >= 0
> The box 'matyunin/centos7' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Atlas, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> 
> URL: ["https://atlas.hashicorp.com/matyunin/centos7"]
> Error: 

I can find the virtual box listed in the box catalog at: https://atlas.hashicorp.com/matyunin/boxes/centos7

I am running on OSX Yosemite, Vagrant 1.8.7, Virtual Box 5.1.

**Comment by Benjaki2** [comment]
Hi @jelpatte ,
It could be the vagrant version causing the issue. Try the installation with v1.8.6.

**Comment by tgunnoe** [comment]
have you tried to run 'vagrant up' again?

**Comment by jelpatte** [comment]
@Benjaki2 and @tgunnoe I installed the previous version of Vagrant and that worked. I still had warnings that the box wasn't found, trying to find... but this time the install software was able to find your box. I have an instance of worldview running on my machine now. Thank you very much for your help.

**Comment by rboller** [comment]
Glad to hear that, @jelpatte !  We'll look for a better long-term fix and update the documentation accordingly.  Thanks for the report!
