### ISSUE TITLE
Re-enable gzip compression

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#731]
At some point, it seems that the Apache configuration for gzip compression stopped working, which means that we're pushing ~80% more data over the wire than we have to and significantly slowing down the app. We need to figure out why gzip compression stopped working and turn it back on again.

**Comment by minniewong** [comment]
Issue appears to be upstream - awaiting fixes from external partners.

**Comment by rboller** [comment]
SA/Networking team reports this being fixed in SIT - @Benjaki2 please verify and they can then promote the changes to the upper environments.

**Comment by Benjaki2** [comment]
@rboller ✅Verified

**Comment by rboller** [comment]
Scheduled for deployment to production this Thursday, 3/22.
