### ISSUE TITLE
Remove warning message and deprecated layers when new 2013 Arctic imagery is available

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#738]
Once GIBS provides updated MODIS imagery for 2013 (Collection 6 in EPSG:3413), we'll need to remove the warning message below and remove the two EPSG:3995 layers (coastlines and graticule).

<img width="396" alt="arctic-warning" src="https://user-images.githubusercontent.com/7243823/35939529-6581de48-0c1a-11e8-8d5e-f067adee297e.png">

**Comment by minniewong** [comment]
also update test plan when this change occurs
