### ISSUE TITLE
Add layer collection/version and type information to all layers

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#742]
Per science team suggestion, it would be helpful to provide information about the version and type of each layer displayed in Worldview.  As it currently stands, Worldview uses the "best available" imagery provided by GIBS (see ["best available" section of the GIBS API docs](https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers) for more info).

Some users may want to know more information, though, such as whether the currently-displayed imagery is based on standard or near real time data and which version of the data was used to generate it. 

A mockup of what this would look like within the app as provided by science team:

![layer-info](https://user-images.githubusercontent.com/7243823/36050429-858ba6d8-0db4-11e8-829d-6871dcd10a41.png)

This information can be extracted from the [GIBS GetCapabilities document for "all" layers](https://gibs.earthdata.nasa.gov/wmts/epsg4326/all/1.0.0/WMTSCapabilities.xml) (as opposed to "[best](https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml)" or "[nrt](https://gibs.earthdata.nasa.gov/wmts/epsg4326/nrt/1.0.0/WMTSCapabilities.xml)").

Example for MODIS Cloud Effective Radius 3.7 um PCL from the "all" endpoint:

> Best:     2000/2/24 - 2018/2/9
v6 NRT:   2017/1/1 - 2017/11/1
v6 STD:   2000/2/24 - 2016/12/31
v6.1 NRT: 2017/10/30 - 2018/2/9

Technical challenges include 
- extracting the appropriate information from the GIBS GetCapabilities documents which are too large to load/parse on application start
- keeping this information up-to-date within Worldview - the GIBS GetCapabilities documents are regenerated every hour
- for each layer, mapping the hierarchy of which specific layers in the "all" endpoint comprise the "best" imagery and showing the appropriate label(s) onscreen when certain dates are selected

**Comment by minniewong** [comment]
Will work on this once all imagery are in GITC

**Comment by minniewong** [comment]
Moved
