### ISSUE TITLE
Re-implement timeline as decoupled component

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#743]
Subtasks:
- [ ] Decide on architecture + choose dependency(s) to support component
- [ ] Implement current timeline features into new timeline
- [ ] Style timeline to look like current timeline

Notes: Would like to see smoother zooming between temporal ranges

**Comment by rboller** [comment]
Closing this ticket as part of reorganizing the work for this effort here:
https://github.com/nasa-gibs/worldview/projects/21
