### ISSUE TITLE
Replace mobiscroll for mobile timewheels

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#757]
We are currently running mobiscroll 2.6.0 and are pulling it in via a browserify-shim. Ideally, we would update this package to include the latest version (3.2.6 / 4.0.0beta-3.1) and pull it in via npm but version 2.7+ have a new license agreement so we can't use the latest version. So, we need to find a replacement solution. 

mobiscroll is only being used in `web/js/date/wheels.js`

**Comment by edplato** [comment]
Console error when interacting with date wheels in desktop simulated mobile device in Chrome:
![image](https://user-images.githubusercontent.com/24417194/45762052-8194d400-bbfb-11e8-870f-59b8ed5cb3a9.png)
I'm not seeing any difference in behavior and this has been around since at least 2.8.0.

**Comment by Benjaki2** [comment]
https://github.com/lanjingling0510/react-mobile-datepicker
