### ISSUE TITLE
Running data optimization

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#77]
https://github.com/openlayers/ol3/pull/6082
Waiting on this merge:
should fix running-data when rotated
Should optimize rendering of layers for data retrieval

**Comment by Benjaki2** [comment]
Appears to be significantly more efficient after merge. Each individual data-value is processing more than twice as quickly.

**Comment by Benjaki2** [comment]
Look into removing colormap loops, and replacing them with a better data mapping solution.
