### ISSUE TITLE
Can't interact with map in collapsed timeline area [map.pan.7]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#782]
Can no longer interact (pan, zoom, click, etc..) with map in area where timeline is collapsed

**Comment by ZachTRice** [comment]
Notes: The timeline wrapper div is absolutely positioned with width 100% & a transparent background. So there is an element there when collapsed. 

Here is how to fix that:
Combine `section#timeline` wrapper, with `.timeline-inner`

`<div id="timeline" class="timeline-inner clearfix" style="display: block;">`

````
#timeline-header {
    width: 320px;
}

.timeline-inner {
    position: absolute;
    border: 1px solid #333;
    background: rgba(40,40,40,.9);
    border-radius: 5px;
    display: inline-block;
    margin-left: 10px;
    margin-right: 10px;
    min-height: 65px;
    bottom: 10px;
}
```
