### ISSUE TITLE
Antarctic Notification fired at wrong time [proj.nav.9 & layer.add.16]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#784]
go to the extension `?now=2013-01-01T12` then change to antarctic projection and then change back to geographic projection and you will see a antarctic notification.

<img width="842" alt="screen shot 2018-03-14 at 5 50 35 pm" src="https://user-images.githubusercontent.com/3605988/37432865-4526fa14-27b0-11e8-9adc-e5dbaffe7f0c.png">

**Comment by ZachTRice** [comment]
This is happening because the time check does not factor (i.e. round) hours, minutes, seconds, as it needs to do to support subdaily. This logic is located in `projection/change.js`.
