### ISSUE TITLE
Clicking on timeline tab brings you to wrong date [date.pick.16 & date.pick.25]

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#786]
When clicking on a timeline tab, you are brought to the tab before the one you clicked. (Found while in year and day zooms)

_Found in chrome_

**Comment by edplato** [comment]
I wanted to check on the status of this issue and if you think I should open up a new one. I encountered a similar issue when clicking on day ticks on the timeline where it displays one day past the one selected.

To reproduce: reload page, with DAYS zoom level on, highlight a tick date on a timeline and it shows, for example, 2018 FEB 28 beneath the tick on the timeline. When clicked, the date displayed to the left of the timeline is 2018 MAR 01.

**Comment by ZachTRice** [comment]
No need to open a new issue. This is still a bug, so nice catch. I'll look into what is causing the problem.
