### ISSUE TITLE
Automate Animation test plan

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#79]

**Comment by Benjaki2** [comment]
Skipping Firefox for the time-being, for lack of selenium compatibility with recent firefox versions  https://github.com/openshift/origin-web-console/issues/945

**Comment by Benjaki2** [comment]
Nightwatch.js testing now works with Firefox, thanks to Marionette. Config changes [here](https://github.com/nasa-gibs/worldview/commit/3669c787947d2829fd7c4e130690b551b8ed3cbe)
