### ISSUE TITLE
Limit animation interval

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#807]
Currently animations can have an indefinite range which can create a large amount of network requests particularly when looping. Pre-cached animations are not able to cache a full animation range because there is no hard-limit set on the upper-bounds of a request. Right now we are chunking pre-cache (in 10 intervals) to create smooth animations and stay within OL's tileCache range but, this means we most consistently re-request layers when looping. 

A hard-limit of 100 intervals will allow us to pre-cache an entire animation range without requiring the user to wait a very long time. When all layers are pre-cached, no layers will need to be re-requested when looping. 100 intervals should allows for 8 years of animation in the monthly range, 3 months in the daily, and 18 hours in the 10-minute interval ranges. If this is not sufficient, a URL parameter will be available (and documented in our testing docs) to override this limit.

Here is what we need to do:

- When the animation play button is pressed, check if there is more than 100 intervals selected between start / end dates.
- If more than 100 intervals are selected, pop up a message describing the 100 interval limit and have a button for the user to choose if they want us to limit them to the max 100 interval.
- When clicked, the end date bound will adjust to be 100 intervals out from the start date.
- If they do not clip the interval, the range markers will stay the same but the user will not be able to animate.
- Set precache limit to a large number (-1/Infinity) so that all layers will always be precached to the 100 interval limit.
- For testing, or when someone absolutely needs a longer range, a URL parameter is available to overrise the limit. i.e. `&ail=[number_here]`. In production, this wouldn't be in the URL, it is only available for testing and documented in our testing docs.

**Comment by minniewong** [comment]
Related to #2435

**Comment by rboller** [comment]
We decided to close this ticket in a recent backlog grooming session and will revisit if we see this issue frequently with upcoming animation-heavy layers (e.g. geostationary).
