### ISSUE TITLE
Gif animation outputs are not contained properly if a large image is selected

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#809]
To reproduce, go to the following link. select the GIF, expand the GIF frame to fully fill the window, change resolution to lowest and create a GIF. The output will create a scrollbar when output.

https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2018-03-21&z=3&v=-78.09641808800518,-7.4834012524068285,-52.48508996300518,9.198239372593171&ab=on&as=2017-06-06&ae=2017-06-10&av=3&al=true

Images of issue:
![screenshot_9](https://user-images.githubusercontent.com/17348884/37738219-b0152658-2d2c-11e8-9e01-fb2178da735a.png)
![screenshot_7](https://user-images.githubusercontent.com/17348884/37738228-b2e48c34-2d2c-11e8-91f8-c2e414c4aa39.png)
![screenshot_8](https://user-images.githubusercontent.com/17348884/37738239-b57d3eaa-2d2c-11e8-810c-b546f673d483.png)

**Comment by Benjaki2** [comment]
Looks to be windows specific.
*  Mac works (tested chrome/firefox)
* Windows breaks (tested chrome with browserstack)
