### ISSUE TITLE
GIF Animation icon color does not look correct

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#810]
The NASA (SVG) icon color looks off when creating an animated GIF. It does not have the proper red color in the slash.

![nasa-worldview-2017-06-06-to-2017-06-10 1](https://user-images.githubusercontent.com/17348884/37738388-332965e0-2d2d-11e8-87e5-5b5d73e53c2d.gif)

**Comment by ZachTRice** [comment]
Also, the date font is rendered differently in Windows (above) than on Mac (below)

![nasa-worldview-2017-06-06-to-2017-06-10 2](https://user-images.githubusercontent.com/17348884/37738833-9f5550a2-2d2e-11e8-9e2f-eb10ca0e4c2e.gif)

**Comment by ZachTRice** [comment]
The icon may be "unfixable" due to the 256 color limitation in GIFs. @Benjaki2 thoughts?

**Comment by Benjaki2** [comment]
@ZachTRice I would say at this point the icon is not fixable. I have looked into it a number of times and it happens during the process of converting from `canvas` images to a`GIF` image. I believe it is either the compression algorithm used by GIFshot or a color-limit of the GIFs themselves

In regards to the text, I think at least in this case the size of the GIFs are different and the `font-size` as well as `stroke-width` is dependent on the dimensions of the requested GIF.

**Comment by ZachTRice** [comment]
Makes sense about the GIF. 

I'm saying that the `font-family` between those two timestamps are different. The Windows font is more of a serif, the Mac more of a sans font.

**Comment by Benjaki2** [comment]
ahh! Good eye
