### ISSUE TITLE
Some products which require Earthdata Login for download don't show warning banner

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#814]
Some products (e.g., AIRS SO2 Prata Night) don't show the Earthdata Login warning banner but may require using it to download data.

Here's an example of the banner for Aura/MLS Water Vapor:
![mls-example](https://user-images.githubusercontent.com/7243823/37802325-63dc3d60-2e00-11e8-9c0b-062b1079e69d.png)

This likely requires adding the URS tag as described here to the relevant products:
https://github.com/nasa-gibs/worldview/blob/master/doc/data_download.md#tagurs

MLS example usage here:
https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/config/wv.json/products/mls/ML2H2O.json

**Comment by minniewong** [comment]
@rboller - I do see the Earthdata Login banner for AIRS SO2 Prata, Night. I am not sure why you do not see it.
![screen shot 2018-03-23 at 10 06 54 am](https://user-images.githubusercontent.com/10747923/37833565-02099e70-2e82-11e8-97ec-69f4f25e8b14.png)

**Comment by rboller** [comment]
Ah, I see what may be happening here for AIRS SO2 Prata, Night - if you try to download non-NRT granules ([example](https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,AIRS_Prata_SO2_Index_Night,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2018-01-23&z=3&v=-101.4609375,-52.92225922131148,57.8671875,59.39100922131148&ab=off&as=2018-03-16&ae=2018-03-23&av=3&al=true&download=AIRIBRAD_NIGHT)), the banner doesn't show up (even though it does now require Earthdata Login).  If you try to download NRT ([example](https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor,AIRS_Prata_SO2_Index_Night,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2018-03-23&z=3&v=-101.4609375,-52.92225922131148,57.8671875,59.39100922131148&ab=off&as=2018-03-16&ae=2018-03-23&av=3&al=true&download=AIRIBRAD_NIGHT)), the banner does show up.

This appears to be predicated on how the URS tag is specified in the product's config file:
https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/config/wv.json/products/airs/AIRIBRAD_NIGHT.json

It appears to be triggering on `(NRT)` in the `dataset_id` field.  For a product like this, assuming that all dates now require Earthdata Login, we'll want to always trigger the banner.  My first guess is to try the `"by": "constant"` in the `urs` part of the config but may take some investigation to determine the proper config.
