### ISSUE TITLE
Increase capacity of animated gif output 

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#816]
Now that we have the ability to create higher-resolution animated gifs and/or lots of frames with sub-daily imagery, it's very easy to hit the current limit of ~40MB uncompressed.  

As it currently stands, if we bump the limit to ~50MB, the app freezes.  This ticket is to investigate and expand this capacity, if possible.

**Comment by Benjaki2** [comment]
@rboller I was able to increase the max-request limit at least 10-fold but I am waiting to see if `gifshot` would accept my contribution here yahoo/gifshot#60 . If not I will implement it on our forked version.

We will need to set a few more limitations for the user now that they are going to be able to download larger files:
* Limit the dimensions. GIFshot's compressor has a firm limit of `65535px` both high && wide but I imagine we will want to limit them to less. What are your thoughts? Maybe we should ask the user what he expects/needs?
*  New max request limit. Currently `40`. Image download is `250`. I think we could potentially set it up to `500` MB

**Comment by rboller** [comment]
@Benjaki2 sounds good about the plan to integrate your new fixes.

And yes to setting some limits!  I suppose we wouldn't necessarily need to set height and width limits if we just set file size limits for the overall GIF?  I.e., if someone asks for a really high resolution set of images, they're going to be over the file size limit very quickly anyway.

And if that's the case, I suppose we can start by setting the total GIF size to `250MB` and see that looks reasonable in terms of resolution and total number of frames.

**Comment by jimmywarting** [comment]
Hi, i made that issue over at yahoo/gifshot#60

yahoo/gifshot#60 might be enough not sure but if you want to take it to the next level then hook me up if you need some streaming capability.

I had some investigation over at gifshot & omggif when i did help a guy in my [StreamSaver](https://github.com/jimmywarting/StreamSaver.js/issues/38) library (we forked part of omggif that gifshot uses) and mad a web streaming functionality out of it.

didn't made a module out of it some part of it was customized 

for references: 
Streaming GifWriter: https://jsfiddle.net/jrftnp13/4/
(final result: https://codepen.io/anon/pen/ObxGZV)

**Comment by Benjaki2** [comment]
Hi @jimmywarting . Thanks for bringing `StreamSaver.js` to our attention. We would probably go with it if cross-browser compatibility (even IE 😢) wasn't a priority for this app (NASA worldview). Your suggestion of going from `base64` -> `blob` solved the primary bottleneck I was running into but gifshot's `processFrame` and omggif's `addFrame` are also really memory consuming. I have played around with throttles for those functions based on pixel dimension which is effective but not a solid solution. Let us know if you have any other suggestions! Thanks!

**Comment by jimmywarting** [comment]
One idea is to never get the base64 string in the first place...

Don't remember exactly how omggif did operate but i think i remember that it was unable to flush the frames that was added once it was done (there was no pipeline) you got the final result when you say it's done

It's still possible to use the streaming gifwriter that i built with a streaming polyfill without the StreamSaver.

You would then also need to change the part where i generate the blob:
```js
	var conf = { headers: { 'content-type': 'image/gif' } };
	new Response(gif, conf).blob().then(function (blob) {
		console.log(blob.url());
	});
```

for a solution that don't require new apis:

```js
var chunks = [];
var reader = gif.getReader();

function pull() {
  reader.read().then(function (result) {
    chunks.push(result.value);
    return result.done ? chunks : pull();
  });
}

pull().then(function (chunks) {
  console.log(new Blob(chunks, {type: "image/gif"}));
});
```


https://github.com/creatorrr/web-streams-polyfill

**Comment by Benjaki2** [comment]
Thanks for the suggestion @jimmywarting . I gave it a go and it appears to be working really well!

**Comment by edplato** [comment]
In SIT 2.5.0, I haven't been able to download a large GIF 240mb+ in IE11 or Edge on a few attempts. It seems to get stuck for 200mb as well, but I haven't tested further than once on each browser.

For both browsers, I can't get past 'Creating GIF'. For IE11, the progress bar just hangs ~15%. For Edge, sometimes it freezes on 'Loading' (with the GIF preview still visible) and other times, it gets to the 'Creating GIF' part but shows a notification 'nasa.gov is not responding' and the progress bar just remains empty.
