### ISSUE TITLE
Rebase nasa-gibs/gifshot on yahoo/gifshot

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#817]
There has been a major `gifshot` release with a complete es6 rewrite since we have forked. 

Adding the features from our forked version to gifshot with PRs
- [x] Add frame text yahoo/gifshot#109
- [x] Add logo
- [ ] Add Text Stroke

**Comment by minniewong** [comment]
Created a PR with `gifshot`; awaiting contributor license approval

**Comment by Benjaki2** [comment]
Removing gifShot and replacing it with custom `gifCreater` class
