### ISSUE TITLE
GIF Animation info box shows wrong image dimensions

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#823]
When the GIF button is clicked, the initial info box always shows the wrong image dimensions.

Example:

![gif - wrong initial image dimensions](https://user-images.githubusercontent.com/17348884/37931399-7d2a7ae6-3113-11e8-8415-2a83e693fafb.gif)

**Comment by edplato** [comment]
I can open a new issue if this is too loosely related, but to add to this, I encountered this issue (IE and Edge) in arctic with a rotated projection [id.rotation.1 - intended for image download, but works for demonstrating this issue]. 
1) load page (make sure its in arctic projection and rotated) and create animated GIF
2) (page still rotated at this point) GIF image dimensions are 117 x 437px
![dimension1](https://user-images.githubusercontent.com/24417194/39582427-ef070100-4ebb-11e8-9165-d4c5161cadf5.png)
3) click Create GIF and get Reset Rotation? alert - click ok
4) (page not rotated at this point) GIF image dimensions are still 117 x 437px

I also noticed that as you rotate the projection and open the create animated GIF dialog, the dimensions will change on each rotation.
