### ISSUE TITLE
Image-download bottom-left selection coordinates do not update

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#833]
the `48.7899,71.0531` in this image do not change when the selection is dragged.
<img width="658" alt="screen shot 2018-04-02 at 3 20 42 pm" src="https://user-images.githubusercontent.com/3605988/38211737-75945998-3689-11e8-981a-d87396b72c5c.png">

**Comment by minniewong** [comment]
It appears the coordinates are flipped. The lower left coordinates are actually the upper right coordinates, and the upper right coordinates are the lower left coordinates.
![Screen Shot 2018-04-03 at 4.02.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5838ab2138f438130034ed03/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f06b7191a37cf112294f5d5d5ecc3c4a4356bcbbd671f3e57862804e0ee5d2650e26c56e14abee821be903b9208b4fd4b4edd91dd2f42f67b6d5db1063474f4dcbed5727a19041c95df449e64550a3163f64e7762431.png)

**Comment by Benjaki2** [comment]
Ahhh That makes sense! Thanks for pointing that @minniewong . I will try to fix this 🐛🐞 ASAP
