### ISSUE TITLE
Date stamps don't show on first creation/download of Animated GIF [date.animation.gif.3]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#839]
Firefox/OS X - Steps to reproduce:
- Clear browser cache
- Open animation widget
- Click on Create GIF icon, use defaults and Create GIF
- Click Download. The first time you create an animated GIF after clearing the browser, there are no date stamps.
- Click create GIF a second time, and then the date stamps appear.

**Comment by ZachTRice** [comment]
Can confirm this happening on FireFox/Windows 10

**Comment by mike-mcgann** [comment]
I cannot reproduce this bug at this time. Reopen this ticket if it shows up again.
