### ISSUE TITLE
Added/checked orbit track is not checked in other relevant measurements section [layer.add.10]

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#841]
When you add/check the box for “Aura/OMI Ascending/Day” orbital track under Aerosol Optical Depth, then go to the Aerosol Albedo measurement, the Aura/OMI Ascending/Day track should be checked since it has already been added to the layer list. If you try to check it, it removes the layer from the layer list, and if you click on the check box again, it adds the layer to the layer list.
(note: this is not a new issue)

**Comment by edplato** [comment]
Fixed.
