### ISSUE TITLE
Add Natural Earth to test plan expected results perm.in.proj.2 and perm.in.prog.4

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#844]
Both test steps show their expected results, except **Natural Earth**, which isn't part of the current expected results, is also listed alongside OpenStreetMap for Place Labels and Coastlines/Borders/Roads in Overlays. So far I've come across this is perm.in.proj.2 and perm.in.prog.4, but will update this issue if more are encountered.

**Comment by minniewong** [comment]
I have fixed these in the test plan
