### ISSUE TITLE
Change source link or expected result for perm.in.vip.4

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#846]
SIT link matches expected result, but the external Earthdata link is requesting a Worldview page with a different map and data (Ash Plumes). Their link loads fine, but may want to revise this test.

**Comment by minniewong** [comment]
Looking at the Earthdata website - we can actually probably remove this test, or update it with the new link/image.

**Comment by minniewong** [comment]
VIP links test removed from the test plant
