### ISSUE TITLE
Map rotate query string displayed in URL is different format or missing

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#848]
For **map.rotate.2** and **map.rotate.3**, address bar is in a different format and missing, respectively. 

- **map.rotate.2** has “&r=18.0000” at the end instead of expected result “&r=18”
- **map.rotate.3** has nothing at the end of its address bar instead of expected result "&r=0"

Rotate functionality and url linking of either versions (“&r=18.0000” or “&r=18” AND "&r=0" or empty) appears to be working fine. Should this just be revised in the testing expected results or does this need to be addressed?

**Comment by mike-mcgann** [comment]
**map.rotate.2**: I'd consider 18 and 18.000 to be the same
**map.rotate.3**: Says "should not have &r=0" at the end. So that one looks good.

**Comment by edplato** [comment]
Ok, thanks. My mistake on the expected results for **map.rotate.3**.

**Comment by minniewong** [comment]
@edplato were the issues in this ticket addressed by Mike? If so, can we close it?

**Comment by edplato** [comment]
I believe so.
