### ISSUE TITLE
Animation play button unresponsive after cancelling Create An Animated GIF dialog [date.animation.14]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#857]
IE11 - after working through the steps associated with **date.animation.14**, animation play button no longer starts the animation. No animation is taking place on the map and the time line pick is stationary.

For clarity, these seem to be the steps that expose this bug:

- create animation (used daily over a one month period)
- click play button (animation starts)
- click on the create-GIF icon while animation is playing (animation stops)
- close the create-GIF animation dialog (click x)
- switch to another projection (used arctic)
- add layer (used Brightness Temperature(Band I5, Day)
- click animation icon (original date range remains)
- click play button (unresponsive)

After trying a few different combinations of steps, it seems the Create An Animated GIF dialog is the culprit.

**Comment by ZachTRice** [comment]
@edplato Could you test if this is happening in production as well. I'm curious if this is only occurring in SIT or if it's an old bug.

**Comment by ZachTRice** [comment]
Thanks! I'll take a look

**Comment by minniewong** [comment]
I can replicate it in firefox

**Comment by edplato** [comment]
Tested and working as expected in IE11.
