### ISSUE TITLE
IE11 Create Animated GIF download button is unresponsive

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#859]
Download button inside the GIF results dialog is unresponsive in IE11. Works fine in Chrome.

- Create Animated GIF
- Click 'Create GIF'
- 'loading...' pops up and disappears
- 'Creating GIF...' pops up and progress bar increases to 90% - hangs sometimes ~10 sec - then 100%
- GIF results dialog pops up and GIF is being shown in motion with file details, but download button is unresponsive

Extra info, but upon cancelling that download dialog (click x) and repeating these steps without reloading page, progress bar freezes at 100% and never gets to GIF results dialog.

**Comment by ZachTRice** [comment]
Verified in IE11 in Prod (v2.2.4) and SIT (v2.3.0-rc.2)

**Comment by Benjaki2** [comment]
'Internet Explorer does not presently support the `Download` attribute on `A` tags.'
https://stackoverflow.com/a/18408028/4589331

**Comment by edplato** [comment]
Works great!
