### ISSUE TITLE
WV not loading in UAT with new Chrome Version

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#86]
I just updated from Chrome 53.0.2785.143 to 54.0.2840.71 and am not getting the following error when I load our UAT WV instance:
Uncaught RangeError: Maximum call stack size exceeded(…)
Ryan was seeing this previously and apparently I was just behind in my Chrome versions.
This is impacting us, but will also impact any of our providers that use UAT.

**Comment by Benjaki2** [comment]
Error is specific to chrome version 54. UAT WV instance works in latest chrome version (55)

**Comment by mcechini** [comment]
Hmm, not so much  I'm running 56.0.2924.87 (64-bit) ... When I build and deploy WV off of master, it doesn't work at all in Chrome.  Not the main endpoint nor the -debug endpoint.  When I checkout 8d9e27b and do a deploy, then only the -debug works.. but that's at least something.

**Comment by mcechini** [comment]
Go ahead and take a look at https://sit.gibs.earthdata.nasa.gov/worldview/gibs/ (on the VPN)

Note that there seem to be a lot of 404 errors trying to load js files.  I see that when I run this:

```
/usr/share/gibs/ecc/worldview-private/wv-newgibs-publish --env sit-ext --force
```

to deploy worldview, that process is deleting the js files that WV is then looking for:

```
	deleted:    web/ext/node_modules/babel-polyfill/dist/polyfill.js
	deleted:    web/ext/node_modules/babel-polyfill/dist/polyfill.min.js
	deleted:    web/ext/node_modules/bluebird/js/browser/bluebird.js
	deleted:    web/ext/node_modules/bluebird/js/browser/bluebird.min.js
	deleted:    web/ext/node_modules/gifshot/build/custom/gifshot.custom.js
	deleted:    web/ext/node_modules/gifshot/build/custom/gifshot.custom.min.js
	deleted:    web/ext/node_modules/lodash/lodash.js
	deleted:    web/ext/node_modules/lodash/lodash.min.js
	deleted:    web/ext/node_modules/openlayers/dist/ol-debug.js
	deleted:    web/ext/node_modules/promise-queue/lib/index.js
	deleted:    web/ext/node_modules/react-dom/dist/react-dom.js
	deleted:    web/ext/node_modules/react-dom/dist/react-dom.min.js
	deleted:    web/ext/node_modules/react/dist/react.js
	deleted:    web/ext/node_modules/react/dist/react.min.js
	deleted:    web/ext/node_modules/worldview-components/browser/wvc.js
	deleted:    web/ext/node_modules/worldview-components/browser/wvc.min.js
```

**Comment by mcechini** [comment]
This seems to be fixed now after getting the updated node_modules and with browser updates.

**Comment by rboller** [comment]
Glad to hear that!   @Benjaki2 please confirm when you get a chance and close this ticket if it's fixed.
