### ISSUE TITLE
Zoom for mousescroll and zoom out button cause different zot flag removals [layer.zots.3]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#862]
Tested in IE11 and Chrome. Zooming out with mousescroll removes zot yellow flag at a certain scale, but using the zoom out button does not at the same scale. Page loads at a scale of 5km/2mi and the layer has zot flag. It takes 2 mousescroll zoom out actions to remove flag, but 3 zoom out button clicks to remove flag, as shown in this table:

| Scale       | Number of Events | Mouse Scroll Out | Click Zoom Out Button| 
| ------------- |:-------------:| :-----:|  :-----:|
| 5km/2mi       | 0 - page load | flag | flag |
| 10km/5mi     | 1 | flag  | flag | 
| 20km/10mi    | 2  | no-flag |   flag | 
| 50km/20 mi    | 3  | no-flag |   no-flag |

**Comment by mike-mcgann** [comment]
This appears to be fine to me. The scale bar indicates how long 20km is at that resolution. Many resolutions will show 20km as the label but with different lengths.

**Comment by edplato** [comment]
Ok, good point. Will close.
