### ISSUE TITLE
IE11 - only opacity available in layer settings [setting.th.3]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#863]
No settings available other than opacity (i.e., no thresholds, no color palette) in layer options dialog box. May be related to [#845](https://github.com/nasa-gibs/worldview/issues/845).

**Comment by minniewong** [comment]
can you include a screenshot? i see this: 
![screen shot 2018-04-06 at 3 27 07 pm](https://user-images.githubusercontent.com/10747923/38440309-07c347f2-39af-11e8-817d-b53bda75c30b.png)

**Comment by edplato** [comment]
Here is what I see in IE11:

![image](https://user-images.githubusercontent.com/24417194/38440489-96cc91d8-39af-11e8-87b6-fb077f8c7bd3.png)

**Comment by ZachTRice** [comment]
That is intended behavior in IE. There is a note about that in the table of contents of the test plan.

**Comment by edplato** [comment]
Ok, I missed that - sorry, will close.

**Comment by ZachTRice** [comment]
👍 No worries! Easy note to miss.
