### ISSUE TITLE
Lose swath grey outline in arctic or antarctic projections from geographic selected swaths [dd.polar.13]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#869]
Selecting a swath in the geographic projection (near the pole so visible in arctic or antarctic) and then switching to arctic or antarctic projections loses the grey outline of the selected swath while viewing in arctic or antarctic. The inverse is fine (i.e., select in arctic project, switch to geographic and grey outline is present). The red '-' button is visible in all projections for selected swaths.

**Comment by minniewong** [comment]
Closing ticket and moving to data download overhaul projct
