### ISSUE TITLE
Selected data in download links has empty link [dd.single.12]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#871]
This may be specific to the selected data (Global Cyclone Hazard Frequency and Distribution). On clicking Download Selected Data, the Selected Data section in the Download Links dialog doesn't have a file link and only contains an 'X' to remove data granule. The expected result of this test is for 'data download page' to be present in the Selected Data area. I see 'data-download' below in the Data Collection Information area, but am not clear if this is the link I'm looking for.

![nolink](https://user-images.githubusercontent.com/24417194/38523391-52b6153e-3c19-11e8-9a57-339b4ea4a3ae.png)

**Comment by mike-mcgann** [comment]
CMR record no longer points directly to a data file. It points to a page where the user is asked to login before downloading. 

http://sedac.ciesin.columbia.edu/data/set/ndh-cyclone-hazard-frequency-distribution/data-download

@rboller: how do you want to handle this?

**Comment by mike-mcgann** [comment]
Data download is doing a collection search instead of a granule search. Probably related to that.

**Comment by mike-mcgann** [comment]
@rboller: Any objections on placing an Earthdata Login notice for all of SEDAC?
