### ISSUE TITLE
Test plan showing 'no data available' notification [dd.nocoord.2, dd.size.1]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#872]
On page load, a 'no data available' alert notification is showing. Data layer is AMSR-E Sea Ice Brightness Temperature (89H GHz, B Scan) for both tests. I scanned around the timeline within the listed data range and couldn't find any data or remove the 'no data available' notification.

I'm not sure if this is something that needs to be revised in the test plan or a greater concern with the requested data layer.

![nodata](https://user-images.githubusercontent.com/24417194/38523967-0d7b9adc-3c1b-11e8-903c-2619b07cb71c.png)

**Comment by minniewong** [comment]
Check what AMSR-E Brightness Temp product it's pointing to as it should be a product with lots of granules

**Comment by minniewong** [comment]
This product does not exist in CMR anymore. Steps to move forward: 1) Change test plan to point to a layer that has data to download; 2) Contact NSIDC to find out which is the most appropriate product to point to from Worldview

**Comment by mike-mcgann** [comment]
I'll change the test plan.

**Comment by minniewong** [comment]
thanks @mike-mcgann . I've just emailed NSIDC as well.

**Comment by mike-mcgann** [comment]
Test suite updated with fixes for dd.nocoord and dd.size. @edplato can you take a look and confirm this has been fixed? Thanks.
