### ISSUE TITLE
Edge style - year, month, and day text is being cut off in timeline when using TAB to navigate

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#874]
Tested in Edge 16 using Browserstack (desktop chrome and IE11 look fine with no cutoff). The year (slightly), month (noticeably), and days (slightly) are being cut off when using TAB to navigate the timeline date field. As you can see from the picture, the left portion of the month in the timeline if being cut off. On load it looks fine and changing the date with up/down and left/right arrows results in no cutoff of dates. 

![edgemonthcutoff](https://user-images.githubusercontent.com/24417194/38574919-177a76ea-3cc8-11e8-9d2b-be4e1dd5f18d.png)

Someone with desktop Edge browser please verify this isn't just a Browserstack issue.

**Comment by ZachTRice** [comment]
I am seeing a very slight overlap on my version of Edge, I'll adjust the input wrapper widths by a few pixels.

**Comment by edplato** [comment]
Your fix definitely reduced the text cutoff, but it's still visible in Edge for me. After interacting with the date inputs a little more I think the issue is limited to occur when the cursor remains at the end of the input. It seems to add just enough space to make the date overflow.

**Comment by ZachTRice** [comment]
Is this present in all version of Edge? I was able to test locally in Edge 14 and checked in Edge 16 on browser-stack. Could you provide another screenshot of what you are seeing now and/or firebug in increased max-widths on the input wrappers to give me an idea of how much additional space I need to account for, that would be helpful.

**Comment by edplato** [comment]
Here is a followup screen shot. Note the left 'DEC' cutoff in the timeline and the comparison between each 'DEC' in the animation timeline (left cutoff, right normal). As discussed, I didn't fully explain how I found this bug originally, because to replicate you have to: 
1) type in date parameters (type in 'DEC'), or 
2) click on date inputs where the cursor is at the end of the input, which causes the text cutoff.

![edge-cutoff](https://user-images.githubusercontent.com/24417194/38635989-ff2f42b4-3d94-11e8-973e-840fbbce1497.png)
