### ISSUE TITLE
EONet categories Sea and Lake Ice and Snow should be mapped to specific layers

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#88]

**Comment by minniewong** [comment]
ask @tgunnoe where these changes are made

**Comment by minniewong** [comment]
Sea Ice Layers: https://eonet.sci.gsfc.nasa.gov/api/v2.1/layers/15
Snow layers: https://eonet.sci.gsfc.nasa.gov/api/v2.1/layers/17

**Comment by minniewong** [comment]
Where do we map specific layers to EONet Categories in Worldview @Benjaki2  and @rboller ? or do we just pull from EONet's layers above?

**Comment by rboller** [comment]
It moved since the last time I looked - it's now over in the options repo:
https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/config/wv.json/naturalEvents.json

**Comment by minniewong** [comment]
https://github.com/nasa-gibs/worldview-options-eosdis/pull/81
