### ISSUE TITLE
Date field in timeline is not updating page data on click and mouse move [date.field.11/perm.out.3]

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#882]
**Description**
Clicking on up/down arrow in date field in timeline doesn't initiate page update when immediately moving mouse off arrow after click. Date doesn't change in page data/URL, but text in date field does change. Affects year, month, and day.

**Steps to Reproduce**
1. Navigate to Worldview page
2. Click up arrow on day in timeline once
3. Move mouse off arrow after click (must be done quickly)
4. Note page update and/or reload and observe if date was changed

**Expected behavior:**
Text date in timeline should change and page/URL should update accordingly with correct date data.

**Actual behavior:**
Text date in timeline changes but no page/URL update.

**Environment**
Version: 2.3.0
Browser: [Chrome Version 65.0.3325.181 ]

**Comment by minniewong** [comment]
seems to be fixed. Closing
