### ISSUE TITLE
Running data should handle colormaps with duplicate entries

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#89]
Matthew Cechini relayed some possible problems that the running data feature may have when dealing with certain colormaps. In particular, there are a few which have the same color mapped to two different data values. There may be some "best guesses" which can help to decide which value to use, though we may also just want to ignore these cases.

**Comment by Benjaki2** [comment]
<img width="290" alt="screen shot 2016-12-22 at 4 38 28 pm" src="https://cloud.githubusercontent.com/assets/3605988/21441262/2254a33e-c865-11e6-84f3-b5f4ad412eb2.png">
