### ISSUE TITLE
IE11 - Download GIF causes blob related invalid address

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#891]
Intermittent issue with IE11 using Windows 10 - tested in UAT and production. After successful create animated GIF, with GIF preview dialog on screen, clicking on the download button results in one of three outcomes: 

**1) no download and a redirect to an invalid blob related address:**
![b1](https://user-images.githubusercontent.com/24417194/38893470-628aeb8e-4258-11e8-814c-12db23769eab.png)

**2) download works, but get these two windows (click allow):**
![c1](https://user-images.githubusercontent.com/24417194/38893612-cb3a96c0-4258-11e8-80af-ec2c87cc2663.png)
![c2](https://user-images.githubusercontent.com/24417194/38893616-ce34af46-4258-11e8-9de1-9618ccf42371.png)

**3) no download, but get the two above windows (click allow OR cancel)**

**Comment by minniewong** [comment]
I am also seeing this on SIT in Chrome OSX
![screen shot 2018-05-02 at 8 57 37 am](https://user-images.githubusercontent.com/10747923/39524524-3fd718ca-4de7-11e8-94fa-2b06759a6709.png)

**Comment by ZachTRice** [comment]
These issues may have started occurring after this commit: https://github.com/nasa-gibs/worldview/commit/37e75e0f915cdd5c47498ece803146ee98f58354

**Comment by edplato** [comment]
This issue is happening on every GIF download in SIT and production for Windows Chrome and Firefox. Instead of downloading the GIF and staying on the map page, it navigates to the blog address where it gives the popup to open/save the file. Then you have to back click to get back to the app.
