### ISSUE TITLE
Data download shows granules that are not available for download

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#898]
MODIS NRT products are now marked as offline in CMR. Worldview ignores this flag and shows them in data download anyway. No links are shown in the download dialog box. 

To reproduce:
- Add the "Aerosol Optical Depth - Terra/MODIS" layer
- Click on the "Data" tab
- Select a granule on the leading edge of the satellite track
- Click on the "Download Selected Data" button 

Expected Results:
Under the selected links heading, one granule should be listed with a link to download if data is available. Otherwise, the granule should not be selectable. 

Actual results:
The granule is listed without a link.

**Comment by edplato** [comment]
I am seeing future data granules available for MODIS/Terra Aerosol 5-Min L2 Swath 10km in the current version:
![image](https://user-images.githubusercontent.com/24417194/48432703-2850a900-e743-11e8-8092-9b23894461f1.png)

Clicking on their hdf download links goes to a LANCE NRT Page not found.

**Comment by mike-mcgann** [comment]
Its not actually the future. Granules are being added to CMR before they have been processed and displayed in GIBS which is okay. And if granules are listed in CMR but not available in the linked repository, that isn't an issue that we can fix. I'm getting 504 errors right now instead of 404s.

**Comment by edplato** [comment]
Ok, thanks for the explanation. I just checked the same granule as earlier and now I'm getting 504 errors too.
