### ISSUE TITLE
Selection pick gets cut off 

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#905]
Bug:
<img width="181" alt="screen shot 2018-04-23 at 1 04 35 pm" src="https://user-images.githubusercontent.com/3605988/39142198-f1197f8e-46f7-11e8-9a54-b17ba03c9ba7.png">
Should look like:
<img width="220" alt="screen shot 2018-04-23 at 1 04 29 pm" src="https://user-images.githubusercontent.com/3605988/39142180-e25ca994-46f7-11e8-9ac9-c0e2c82be6f4.png">

**Comment by minniewong** [comment]
same issue on the right side too
