### ISSUE TITLE
Running data values for GPM Rain Rate overlaps color bar

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#909]
Chrome Version 65.0.3325.181 (Official Build) (64-bit) on OS X
To reproduce:
1. Load [Rain Rate GPM/GMI](https://go.nasa.gov/2F8F7eE)
2. Hover over the very dark red on the map - the running data values overlap the color bar
3. Also hover over the grey areas on the map, the value is "<0.1 mm/hr mm/hr" where mm/hr is repeated

**Comment by edplato** [comment]
I am still getting the 'mm/hr mm/hr' double units when hovering over the grey area.

**Comment by Benjaki2** [comment]
@edplato It looks like that issue is on the GIBS side. @minniewong created them a ticket.
