### ISSUE TITLE
Feedback form has active console.logs

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#913]
### Description

Feedback form has active console.logs

### Steps to Reproduce

1. open dev console
2. open **send feedback** in **information**
3. drag feedback around to see console logs

**Expected behavior:**   
No dev console logs

**Actual behavior:**   
dev console logs

### Environment

Version: 2.3
Browser: [all]

**Comment by minniewong** [comment]
Ticket opened regarding this issue with Feedback Module on January 10, 2018: https://bugs.earthdata.nasa.gov/browse/FBM-224. Pinged them again on 30 April 2018

**Comment by mike-mcgann** [comment]
I say we close this ticket as there is nothing more we can do. If they fix it, great. Otherwise it is okay.
