### ISSUE TITLE
Update references in bulk download from URS to Earthdata Login

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#914]
### Description

URS is now called Earthdata Login. Update all references on the bulk download pages. 

### Steps to Reproduce

1. Go here: https://go.nasa.gov/2JoqgPQ
2. Select a granule on the leading edge of acquisition
3. Click "Download Selected Date"
4. Click on "List of Links" and "List of cURL Commands" at the bottom of the dialog box

**Expected behavior:**   
Page says that an Earthdata Login profile is required

**Actual behavior:**   
Page says that an EOSDIS User Registration System profile is required

### Environment

Version: 2.3.0
Browser: [all]

**Comment by minniewong** [comment]
Will be fixed here: #423

**Comment by mike-mcgann** [comment]
Great! Didn't see that one.
