### ISSUE TITLE
Date entry in timeline allows invalid entries

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#927]
### Description
<img width="319" alt="screen shot 2018-04-27 at 12 49 23 pm" src="https://user-images.githubusercontent.com/10747923/39375117-3f81fa68-4a1b-11e8-9b62-5199b562980e.png">

### Steps to Reproduce

1. Change the month field to "123"
2. Tab to the day field and change to "45"
3. Tab to the year field and change to "1900"

**Expected behavior:**   
I expect to get a red box/error when I change the month to "123", I also expect it to give me a red box/error with I change the day to "45".

**Actual behavior:**   
If I first change the month to "123" it lets me, and then I change the day "45" and it lets me, only when I change the year to "1900" does it give me a red error box. When I click elsewhere on the map, it resets the date to the date that was there previously.

### Environment

Version: 2.3.0  
Browser: Chrome 65.0.3325.181

**Comment by Benjaki2** [comment]
This was fixed with #902
