### ISSUE TITLE
Add Landsat-7 & Sentinel-2A/2B/5P & NOAA-20 Orbit Tracks

### ISSUE THREAD

**Issue by apdeluca** [nasa-gibs/worldview#940]
We have added the following orbit tracks to GIBS, and are now ready for Worldview:

| Layer Identifier | Start Date | Title|
| ------------- |-------------|-------------|
|Landsat_7_Orbit_Asc | 1999-04-15|Landsat 7 Orbital Tracks (Ascending/Night)|
|Landsat_7_Orbit_Dsc|1999-04-15|Landsat 7 Orbital Tracks (Descending/Day)|
|Sentinel_2A_Orbit_Asc|2015-06-24|Sentinel 2A Orbital Tracks (Ascending/Night)|
|Sentinel_2A_Orbit_Dsc|2015-06-24|Sentinel 2A Orbital Tracks (Descending/Day)|
|Sentinel_2B_Orbit_Asc|2017-03-08|Sentinel 2B Orbital Tracks (Ascending/Night)|
|Sentinel_2B_Orbit_Dsc|2017-03-08|Sentinel 2B Orbital Tracks (Descending/Day)|
|Sentinel_5P_Orbit_Asc|2017-10-14|Sentinel 5P Orbital Tracks (Ascending/Day)|
|Sentinel_5P_Orbit_Asc|2017-10-14|Sentinel 5P Orbital Tracks (Descending/Night)|
|NOAA_20_Orbit_Asc|2017-11-19|NOAA 20 Orbital Tracks (Ascending/Day)|
|NOAA_20_Orbit_Dsc|2017-11-19|NOAA 20 Orbital Tracks (Descending/Night)|

**Comment by minniewong** [comment]
@apdeluca - can you provide the day/night designations for the orbit tracks?

**Comment by apdeluca** [comment]
The above table has been updated with titles.
