### ISSUE TITLE
Data download has bullets visible from unordered list

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#945]
### Description

Data download has bullets visible from unordered list.

### Steps to Reproduce

1. Load page and select data tab (with or without additional layers)

**Expected behavior:**   
List bullet style should be 'none'

**Actual behavior:**   
![bullet-list](https://user-images.githubusercontent.com/24417194/39484993-763d9ad0-4d45-11e8-8e2a-53c235b8cf55.png)

### Environment

Version: 2.3.0
Browser: [all]

**Comment by ZachTRice** [comment]
Good eye. I have a fix for this in #920. I'll tag this issue number onto my PR.
