### ISSUE TITLE
WV doesn't support time values in the time dimension

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#95]
WV currently assumes that the start/end/default values for the time dimension in a layer are YYYY-MM-DD. However, as we start adding granule layers, it will need to be able to handle YYYY-MM-DDThh:mm:ssZ values. Even if it isn't serving these layers, the WV config scripts will need to not barf on those values.
I saw this in our epic.gibs branch. It may be fixed in master, but until it is fixed, we would not be able to release AST_L1T in production without breaking your builds.

**Comment by tgunnoe** [comment]
the granule layers are ready to be processed into worldview.

**Comment by tgunnoe** [comment]
@mcechini

**Comment by mcechini** [comment]
ok, cool.  Once this is merged to master and we update our test instances, I should see goodness
