### ISSUE TITLE
Change TIFF filename to include nasa-worldview brand and date

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#950]
### Description

Currently, image snapshot TIFF files download with the filename 'image-download.tiff'. It would be helpful if the downloaded filename was similar to KMZ downloads (e.g. 'nasa-worldview-2018-03-15.kmz').

### Steps to Reproduce

1. Download image with TIFF format selected

### Environment

Version: 2.3.0
Browser: [all]

**Comment by mike-mcgann** [comment]
Image download is going to be replaced soon, and when it is, it won't be saying "Worldview" anywhere. I don't think it is worth changing at this point.

**Comment by edplato** [comment]
Ok, thanks. I will close this.
