### ISSUE TITLE
Date selection pick on timeline is slightly to the left of selected date

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#951]
### Description

Date selection pick is slightly to the left of the actual day dateline.

### Steps to Reproduce

1. Load page with default DAYS timeline zoom level
2. Select a day (first of month helps show the issue as the circle makes the alignment more pronounced) and view what day the date selection pick is within

**Expected behavior:**   
Date selection pick is within actual day.

**Actual behavior:**   
Date selection pick is slightly to the left of actual day.

**March 1 selected:**
![timeline-leftbug-3-1](https://user-images.githubusercontent.com/24417194/39577713-0dec160c-4eb0-11e8-909f-d4e3d1f9e6e2.png)

**March 2 selected:**
![timeline-leftbug-3-2a](https://user-images.githubusercontent.com/24417194/39577718-11a4a494-4eb0-11e8-9104-b8e113ac7f78.png)

![timeline-leftbug-3-2b](https://user-images.githubusercontent.com/24417194/39577723-142f257c-4eb0-11e8-8991-634121116e28.png)

### Environment

Version: 2.3.0
Browser: [Chrome 66 | IE 11]

**Comment by ZachTRice** [comment]
Is the `TIME` parameter in the URL set with a `T00:00:00Z`?

**Comment by edplato** [comment]
yes here is an example: &t=2018-04-01-T00%3A00%3A00Z

**Comment by edplato** [comment]
Addressing in Timeline Overhaul.
