### ISSUE TITLE
KMZ not downloading in ZIP when worldfile is selected

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#954]
### Description

Image download with KMZ format and Worldfile(.zip) selected downloads a single KMZ instead of a ZIP.

### Steps to Reproduce

1. Download image, select KMZ format, select 'yes' for Worldfile(.zip) and click download

**Expected behavior:**   
ZIP file downloads.

**Actual behavior:**   
Single KMZ file downloads.

### Environment

Version: 2.3.0
Browser: [Chrome Windows]

**Comment by minniewong** [comment]
We need to remove that ability to select Worldfile for KMZs: https://github.com/nasa-gibs/worldview/issues/301
