### ISSUE TITLE
Update unit testing framework

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#96]
BusterJS is no longer being maintained and already causes weird errors at times when working with newer versions of node.

The plan is to start writing new tests in another framework (likely Mocha but open for suggestions) and keeping buster to run the old tests while we are in the process migrating.

**Comment by localjo** [comment]
Another suggestion worth checking out is Jest https://facebook.github.io/jest/

**Comment by localjo** [comment]
Another testing framework to consider; https://github.com/avajs/ava
