### ISSUE TITLE
Ability to filter by currently active products

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#962]
From WV-1740: Given the large influx of new products, users may be overwhelmed by many options for the same product (e.g., 15 versions of "Rain Rate"). Many of these new products are historical and no longer being produced.

This ticket is to consider adding the ability for the product picker to filter out those historical products and only show active ones which are currently being produced.

Related to #85

**Comment by jasontk19** [comment]
Will be addressed by #2778
