### ISSUE TITLE
Embedding / Worldview widget

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#964]
From WV-1651: Allow users to embed worldview on their own site

**Comment by ZachTRice** [comment]
So, this would be a button to generate iFrame code with the current state or just WV without any parameters?

We could add either add an "Embed Worldview" input field below the share link input or we could make it a dedicated button (</>) beside the social icons. I'm in favor of adding it as a button.

Another consideration would be do we want options to choose the iFrame height / width, name, etc? I think we could probably default these to common values (such as what's used in the example below).

```
<iframe src="https://worldview.earthdata.nasa.gov" style="border:0px #ffffff none;" name="Worldview" scrolling="no" frameborder="1" marginheight="0px" marginwidth="0px" height="400px" width="600px" allowfullscreen></iframe>
```

**Comment by rboller** [comment]
A few ideas from today's discussion:

- we could start by limiting this feature to only allow embedding of comparison mode
- a user would get a embeddable URL from within Worldview which would potentially link to a separate / lightweight / standalone app which was designed to be embedded (rather than the main Worldview app)

**Comment by rboller** [comment]
We can also consider using functionality from the Juxtapose project:
https://juxtapose.knightlab.com/
https://github.com/NUKnightLab/juxtapose

Here's a sample using two different snapshots from Worldview:
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=fc318e94-4c4a-11e9-8106-0edaf8f81e27
