### ISSUE TITLE
Include ability to add marker/pin by entering specific lat/long coordinates

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#97]
User request: Hi, I'm trying to use the satellite images in NASA Worldview to look at cloud cover over particular places. I know the lat/lon of these places, but I'd like to be able to put a marker where they are, so it can be seen if there's cloud cover over these places at exact times. I was just wondering if there was a way of doing this, because once the image is downloaded, I don't know exactly where my locations are. Thanks.

**Comment by minniewong** [comment]
1. Ability to add marker/pin to Worldview map via lat/long coordinates
2. Ability to export/create snapshot of area with markers and markers are burned into the image

**Comment by localjo** [comment]
I was thinking it might be nice to add a feature to search for specific points on the map, like coordinates or a named place. That could help users find things that they want to look at without necessarily knowing exactly where to zoom into.
