### ISSUE TITLE
Test Suite Documentation Updates

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#971]
- [x] map.init.8: "Map should be centered to include 180W. Hovering over 180W you should see a dotted line with the current date on the right, and tomorrow's date on the left of the dotted line..  However, actual results:180W dotted line is not centered in the browser window, must pan over to the W to see it." The wording could be improved. The map needs to be to the left, and 180W is there somewhere, but it isn't in the "center". 
- [x] Fix map.init.9 too. 
- [x] map.zoom.1 - map.zoom.3: This now varies due to the infinite zoom. Select a better way to test. 
- [x] map.pan.5, Drag the map left as much as possible, 250E should not pass left of the center of the browser window, Actual results: Does go past the center of the page. Reword more along the lines of not being able to "lose" the map. 
- [x] date.init.9 Hover over any part of the label area below the timeline.The label should show a centered date with the format YYYY MON DD.  Actual result Format is YYYY MON DD (DOY).  I think DOY is new since the test plan was written.  This is the same actual result for date.init.14
- [x] and date.init.19
- [x] date.range.1, https://worldview.earthdata.nasa.gov/?time=2013-02-28T12, Select the next day by clicking the up arrow above the day label, Date should change to 2013 Feb 01.  Actual result:  Changes to 2013 Mar 01. Reword to "up arrow button above 28" or something close. 
- [x] One note:  date.mob.resp.2 says "Collapse the Layers list"  However, when you click the link from date.mob.resp.1 with max browser window, the layer list is already collapsed
- [x] date.animation.2, date.animation.21 and possibly other places note the init start/end dates for GIF animation is 10 days apart. It should be only 7 days apart (how Worldview is currently), unless we really want 10 days.
- [ ] dd.nocoord.10, Change the day to August 15, 2013, The granules in the "Select Data" window change., Two granules are selected.  Actual result:  The "OMI/Aura Near UV..." label shows "3 selected" but no granules selected in the Select Data window

**Comment by edplato** [comment]
date.animation.2, date.animation.21 and possibly other places note the init start/end dates for GIF animation is 10 days apart. It should be only 7 days apart (how Worldview is currently), unless we really want 10 days.

**Comment by mike-mcgann** [comment]
I wasn't able to reproduce the issue with dd.nocoord.10.
