### ISSUE TITLE
Migrate Buster Tests to Jest

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#980]
### Description

Our unit testing framework `Buster` is not being maintained and `buster-server` is currently causing the travis build to timeout. It is time to migrate `buster` tests to `AVA`

**Comment by Benjaki2** [comment]
Migrating to AVA was postponed do to problems with dependencies not being correctly transpiled before tests were run. avajs/ava#1798 has been merged and may fix said transpiling issue. This should be tested.

Relates to #96

**Comment by mike-mcgann** [comment]
We went with Jest
