### ISSUE TITLE
Ability to configure a specific version/collection for data download

### ISSUE THREAD

**Issue by rboller** [nasa-gibs/worldview#982]
Our ability to configure data download to select a dataset's collection/version is currently limited.  The [VersionFilter](https://github.com/nasa-gibs/worldview/blob/master/doc/data_download.md#versionfilter) and [VersionFilterExact](https://github.com/nasa-gibs/worldview/blob/master/doc/data_download.md#versionfilterexact) help but are not as flexible as they need to be.

This ticket is to create a way which will support the selection of MODIS Collection 6.1 (rather than 6.0) in a non-hard-coded way.  Our current requests to CMR ([example](https://cmr.earthdata.nasa.gov/search/granules.json?shortName=MOD04_L2&temporal=2016-05-16T21%3A00%3A00.000Z%2C2016-05-18T02%3A59%3A59.000Z&pageSize=1000)) return results for both 6.0 and 6.1 and Worldview primarily [parses/displays granules for 6.0](https://worldview.earthdata.nasa.gov/?p=geographic&l=VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_Aerosol,Reference_Labels(hidden),Reference_Features(hidden),Coastlines&t=2016-05-17-T00%3A00%3A00Z&z=3&v=-145.0546875,-50.09283993027071,14.2734375,56.56158993027071&ab=off&as=2018-05-11T00%3A00%3A00Z&ae=2018-05-18T00%3A00%3A00Z&av=3&al=true&download=MOD04_L2).

**Comment by minniewong** [comment]
Checklist for Atmosphere MODIS products

**Comment by mike-mcgann** [comment]
- [ ] Aerosol 5-Min L2 Swath 3km
- [ ] Aerosol 5-Min L2 Swath 10km
- [ ] Total Precipitable Water Vapor 5-Min L2 Swath 1km and 5km, Day
- [ ] Total Precipitable Water Vapor 5-Min L2 Swath 1km and 5km, Night
- [ ] Clouds 5-Min L2 Swath 1km and 5km
- [ ] Clouds 5-Min L2 Swath 1km and 5km, Day
- [ ] Clouds 5-Min L2 Swath 1km and 5km, Night
