### ISSUE TITLE
A-B: Prototype comparison techniques

### ISSUE THREAD

**Issue by mike-mcgann** [nasa-gibs/worldview#984]
Verify that what we expect to do with OpenLayers is actually viable:

- [x] Swipe comparison
- [x] Opacity comparison
- [x] Spy comparision

**Comment by Benjaki2** [comment]
Swipe: http://jsfiddle.net/m0mtzk1n/13/
Opacity: http://jsfiddle.net/m0mtzk1n/12/
Layer Spy: http://jsfiddle.net/m0mtzk1n/16/
